### ISSUE TITLE
Map creation (with coastlines)

### ISSUE THREAD

**Issue by Advialance** [mapsforge/mapsforge#1010]
If I follow the docs to create a Mapfile containing the coastlines I can't seem to be able to generate Coastlines for Ireland.

I converted the full Coastline ".shp" to an ".osm" file using https://github.com/mapsforge/mapsforge-mapcreator/blob/master/shape2osm.py

I then extracted the Bounding Box of Ireland of of that data the result was an empty File.
When I use the generated world.map to Display the coastlines it seems to work since every country is displayed correctly but the land behind Ireland is missing.

I don't know if it is because Ireland is not included in the Shapefiles or if the data is not converted correctly.
![screenshot](https://user-images.githubusercontent.com/22632241/32271044-87fea736-bef8-11e7-8354-f2d439e3b727.PNG)

**Comment by devemux86** [comment]
For questions please use our [forum](https://groups.google.com/forum/#!forum/mapsforge-dev).
