### ISSUE TITLE
Allow to use OsmAnd map files

### ISSUE THREAD

**Issue by tomikmar** [mapsforge/mapsforge#1011]
Currently I have to download two maps - one for Mapsforge and one for OsmAnd.

It would be great if Mapsforge allowed to reuse OsmAnd map files optionally. 

Or even better, agree common, compatible format between both projects.

**Comment by devemux86** [comment]
They are different map formats and with different license.

Would need a tile decoder for any map format in order to feed the data for rendering in map engine.
