### ISSUE TITLE
Mapsforge maps: Root id for building parts

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/mapsforge#1012]
Hello,
like described in https://mapzen.com/documentation/vector-tiles/layers/#buildings-and-addresses we should add a root id for building parts. So while rendering overlapping buildings can easily be distinguished.

For that id of root elements must be stored. My thoughts:
- only tag buildings with `id`, which inherit parts (preferably OSM-ID)
- give every element its `id` (preferably OSM-ID , more overhead)
- use id inherited order of elements in map-file (_if it is possible_) and add while reading, but seems unsafe
- Id in `---WayStartX---`, but can't be used, only in debug mode

The root id in part elements could be added as follows:
- Use OSM `ref` tag, which normally isn't used otherwise for buildings
- Add an extra `root_id` tag, which does not exist in OSM, but is unique

Correct me, if I interpret something wrong. 
Greets Gustl

**Comment by devemux86** [comment]
Can you explain more the concept for this?
Store extra id for grouping together features?
What are the benefits for the readers, how can be used in rendering?

**Comment by Gustl22** [comment]
Example `height`:
A building with parts can't be distinguished from other buildings, so by default it gets a height or it has the height of highest point of building like described in OSM-conventions ( http://wiki.openstreetmap.org/wiki/Simple_3D_buildings ). Underlaying parts aren't visible and currently there are artefacts when the wall of surrounding building covers its parts.
I tried an implementation which detects the polygons inside a building, but on client side its too cost-intensive. A reference would be much faster and does not take much place.

Features could be adopted from its root element in reader, if necessary.

**Comment by devemux86** [comment]
Could start with the needed elements, like the buildings and use the available `ref` tag to check the implementation and results.
That way map files remain compatible and can see if there is need for special tag in a next step.
Also on client rendering would be interesting to check the results "before" and "after".
Certainly it's best to avoid real time calculations in readers as can hurt performance.

**Comment by devemux86** [comment]
Storing OSM ids in `ref` tag probably could be accomplished with [TagTransform](http://wiki.openstreetmap.org/wiki/Osmosis/TagTransform) Osmosis plugin as a preprocessing step?

**Comment by Gustl22** [comment]
TagTransform may work for already existant relations and tags but i didn't read about calculation out of geo data to create a new relation (reference is predominantly given by the building polygon, which inherits the part).

**Comment by devemux86** [comment]
Fixed via PR #1014 by @Gustl22.
