### ISSUE TITLE
Where put the germany.map on storage ?

### ISSUE THREAD

**Issue by Stangoff** [mapsforge/mapsforge#1016]
I am a beginner and would like to know where to place the .map? i am using an android gsm and emulator and i would like to launch the little application of Getting-Started-Android-App.md. Once launched it closes directly even though the code has compiled well

**Comment by devemux86** [comment]
Need to debug your implementation and see why it closes, if there are any exceptions in log.
The map can be put in internal storage folder. e.g. `/storage/emulated/0/`

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by Stangoff** [comment]
what does it mean ? where can i find /storage/emulated/0 ?
