### ISSUE TITLE
Sample in java desktop to draw a marker / circles / load images 

### ISSUE THREAD

**Issue by red0bear** [mapsforge/mapsforge#1017]
hi people ,

i would like to know if there a place with more examples to java desktop how i put in title. i see examples using android but i didn't find a good example using java desktop.

**Comment by devemux86** [comment]
The overlays API is platform agnostic, so the Android examples are valid for Desktop too..

For questions please use our [forum](https://groups.google.com/forum/#!forum/mapsforge-dev).

**Comment by red0bear** [comment]
you could at least showed me the class import org.mapsforge.map.awt.graphics.AwtBitmap;

it works well to load Bitmap to Desktop. Well this kind of info could me added in java sample too ?

**Comment by devemux86** [comment]
You can check [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md) which mentions the dependencies required for each platform.

**Comment by red0bear** [comment]
I'm not trying to annoying you. I see this project very good in future but you could think and make examples or at least make citations for equivalent class to desktop. I figure out when you say same way to process in mapsforge map ... but the way from desktop and smartphones are different.

Thank you to respond my question.

**Comment by devemux86** [comment]
Don't really understand what's the issue about, need to provide exact details in [forum](https://groups.google.com/forum/#!forum/mapsforge-dev) for what you have tried and where is the problem.

e.g. Marker needs a Mapsforge `Bitmap`, so can create a `AwtBitmap` using one of its constructors, like with a `BufferedImage` (simple to read on Java).

**Comment by devemux86** [comment]
BTW Mapsforge main focus was Android, that's why most samples are on that platform.
Desktop came later and duplicating samples with each new feature is not very manageable with available resources.
Pull requests for extra [Desktop samples](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-awt) in new separate classes are always welcome. :slightly_smiling_face:

**Comment by red0bear** [comment]
hahaha ..... hummmm here we go

fragment 

    private TileRendererLayer createTileRendererLayer(TileCache tileCache, MapDataStore mapDataStore, MapViewPosition mapViewPosition, HillsRenderConfig hillsRenderConfig) {
        TileRendererLayer tileRendererLayer = new TileRendererLayer(tileCache, mapDataStore, mapViewPosition, false, true, false, GRAPHIC_FACTORY, hillsRenderConfig) {
            @Override
            public boolean onTap(LatLong tapLatLong, Point layerXY, Point tapXY) {
                System.out.println("Tap on: " + tapLatLong);
                
                Layers layers = mapView.getLayerManager().getLayers(); 
                
                while (layers.size() > 1) 
                { 
                    layers.remove(1); 
                }
                
                Marker marker = createMarker( tapLatLong, 0 );
                if (marker != null) 
                { 
                    layers.add(marker); 
                }
                
                return true;
            }
        };
        tileRendererLayer.setXmlRenderTheme(InternalRenderTheme.OSMARENDER);
        return tileRendererLayer;
    }

    private Marker createMarker( LatLong p, int resource ) 
    {         

        Bitmap icon = null;
        
        try {        
            InputStream is = new FileInputStream(new File(put_here_the_path_to_your_image_icon));
           AwtBitmap teste = new AwtBitmap(is);
           
           icon = teste;
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(map_class_work.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(map_class_work.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        icon.scaleTo(50, 50);
        return new Marker(p, icon , 0, -icon.getHeight() / 2); 
    }
