### ISSUE TITLE
provide a medium detail world map between 100-150mb

### ISSUE THREAD

**Issue by nutpantz** [mapsforge/mapsforge#1018]
there really needs to be a world map with cities with population over 5000 and major waterways and highways. it would be nice to have provincial, state and country boundaries. 

something similar to the osmand world basemap (which is 188mb)

(i would do it myself but my internet access is very limited (hence my need for such a map)

**Comment by devemux86** [comment]
That would be a nice addition in maps server with a base world.map with more details in it.

Though 100-150MB seems large, if we keep current land polygons simplification and work with apk <100MB for Google Play.

**Comment by nutpantz** [comment]
If it could still be used as a general map to travel with. Ie could still follow major roads to towns of reasonable size in most countries.
As long as it shows highways and freeways and city's of reasonable size ( pop+5000)then it will be worth it. I would prefer it be as little bigger and more useful than smaller and not enough city's in most countries

**Comment by ludwigb** [comment]
While I think that a more detailed world map has some use, you also need to
understand what make the current world map pretty small:

   1. limited zoom level range. Mapsforge maps unfortunately grow in size
   when increasing the zoom level range even if there is no content in the map
   (apart from land/sea).
   2. no-data.

So, increasing the zoom level range to something that would be useful for
more than just a backdrop I fear will create a map that is already quite
large.

According to some websites, there are over 4000 cities with a population
over 100000. I think including all places with a population over 5000 will
include most settlements.

I think maybe we should try producing a world map with a larger zoom range
first, seeing how big a file we will be getting.
A next step would be including national boundaries and maybe capital
cities.

I this proves useful, I think continent by continent maps with a bit more
detail (such as major cities) might be more useful then providing a world
map with ever increasing detail.

Opinions?

Ludwig

**Comment by devemux86** [comment]
Those are valid thoughts Ludwig.
After all a world map is not intended for work at large scales, only for overview purposes, until a more detailed region map is loaded.
Avoiding many polygons (besides lands) and playing only with points and lines could keep the size manageable.

Also as demonstrated in [world map creation guide](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md#world-map-creation), we currently use the 1st `zoom-interval-conf=5,0,7` which has the largest simplification.

**Comment by hgoebl** [comment]
Continent maps sound good. Who needs a world-map?

**Comment by boldtrn** [comment]
> Who needs a world-map?

Every app that is available world-wide :). If you only have continents the "world view" might look weird, because of missing sea areas.

**Comment by nutpantz** [comment]
A world map with major highways and one or two of the largest cities would be the minimum.
If you look at the osm base map it's detailed enough to use for travel I the major roads or education about counties, provinces and capital cities.
I could see a real use for a good world map for education and yes continents with more detail and even counties with more.maybe even a ocean only detail map(which much be good for education or budding sailors or refugees)
There are a huge number of low end devices that such maps would be very useful.
All over 100 mb and under 150 mb or wherever provides the best detail for the size.
But that is just my thought.

**Comment by ludwigb** [comment]
My approach to making a world map with some data in it (out current world
map relies entirely on the coastlines) would be to take the planet file and
first extract some data from it (with osmfilter), then feed the resulting
data file into our mapcreator.

So, the question is what should be included in this map? Nation boundaries?
Rivers/lakes? cities (if so, base on what criteria?)

Suggestions?

This does not mean there could only be one other world map, this is more
for a first try if this is feasible at all.

Ludwig

**Comment by nutpantz** [comment]
personally i would like to see 
national and state/provincial boundaries ( really who is not interested when they switch counties)
major rivers and lakes (now deciding what the natives think is major for their part of the world is another topic)   
major highways, freeways or transportation routes (in the US 4 lanes is a major road but other places the major roads may be two lanes) maybe just direct routes between capital or major cities?
major cities for each state/province (maybe top 5 cities by population)


but then i do not  know how much data each feature would require.
for me this would make it a map i would have to have
