### ISSUE TITLE
Remove mapsforge-map-android-extras

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1021]
`mapsforge-map-android-extras` purpose seems being solely the Android 6.0 (API 23) runtime permissions.
As noted in #1020, runtime permissions are not any library's responsibility, but should be handled in the app.
And actually there are many ways to handle them, even helper libraries with a little online search.

So the idea is to remove the `mapsforge-map-android-extras` from Mapsforge modules.
It's not maintained, causes issues and anyone can use its code directly. Opinions?

**Comment by kyawko41493** [comment]
I Like this

**Comment by ludwigb** [comment]
Yes, I support this.

The module was written when there was little support for the new permission
system, now there are plenty of libraries out there that facilitate this,
such as Google's own EasyPermissions
https://github.com/googlesamples/easypermissions.
