### ISSUE TITLE
PausableThread does not stop – leads to memory leak

### ISSUE THREAD

**Issue by MarcelHeckel** [mapsforge/mapsforge#1023]
Hi,

Our Android application create MapView instances and destroy them when they are not needed anymore, and creates them if needed again.

Now we have a memory leak in the application and we think PausableThread is the cause:
Let’s look at org.mapsforge.map.android.view.MapView. It calls interrupt on the layer manager and them sets it to null.

```
public void destroy() {
        …
        this.layerManager.interrupt();
        this.layerManager = null;
        …
}
```

When we look at LayerManager, we see that it is a org.mapsforge.map.util.PausableThread. The interrupt method causes the PausableThread to stop waiting, but in many cases it will not terminate. Look at the run() method.
```
   @Override
    public final void run() {
        setName(getClass().getSimpleName());
        setPriority(getThreadPriority().priority);

        while (!isInterrupted()) {
            synchronized (this) {
                while (!isInterrupted() && (this.shouldPause || !hasWork())) {
                    try {
                        if (this.shouldPause) {
                            this.pausing = true;
                        }
                        wait();
                    } catch (InterruptedException e) {
                        // restore the interrupted status
                        interrupt();
                    }
                }
            }

            if (isInterrupted()) {
                break;
            }

            try {
                doWork();
            } catch (InterruptedException e) {
                // restore the interrupted status
                interrupt();
            }
        }

        afterRun();
    }
```
The main loop will stop if the interrupt status is true. Both catch block reset the interrupt status to false. So when an InterruptedException is thrown while working or waiting, it will not terminate. 
So the layerManager.interrupt(); method will have no effect in many cases. The thread will run forever and causes a memory leak.

A solution would be to add a Boolean to flag to terminate the loop, e.g.:
```
    private boolean finished;

    public void finish() {
        finished = true;
        interrupt();

    }
    @Override
    public final void run() {
        setName(getClass().getSimpleName());
        setPriority(getThreadPriority().priority);

        while (!finished && !isInterrupted()) {
            synchronized (this) {
                while (!finished && !isInterrupted() && (this.shouldPause || !hasWork())) {
                    try {
                        if (this.shouldPause) {
                            this.pausing = true;
                        }
                        wait();
                    } catch (InterruptedException e) {
                        // restore the interrupted status
                        interrupt();
                    }
                }
            }

            if (finished || isInterrupted()) {
                break;
            }

            try {
                doWork();
            } catch (InterruptedException e) {
                // restore the interrupted status
                interrupt();
            }
        }

        afterRun();
    }
```
All usages of the PausableThread should then use finish() instead of interrupt().

**Comment by devemux86** [comment]
Thanks for the detailed report, will check it!

**Comment by devemux86** [comment]
Tested the proposal and implementation seems more robust.
@MarcelHeckel do you want to post a pull request with the change?

BTW can also check VTM [PausableThread](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/utils/PausableThread.java), which is an improved implementation of Mapsforge, using similar approach.

**Comment by devemux86** [comment]
I pushed the mentioned changes.
@MarcelHeckel can you check the result?

**Comment by MarcelHeckel** [comment]
Hi, the commit looks OK. Thank you!
