### ISSUE TITLE
How to modify the library file?

### ISSUE THREAD

**Issue by vivekebics** [mapsforge/mapsforge#1024]
I would like to download all the lib source file and modify and import in to my project. could please help me ?

**Comment by devemux86** [comment]
You can clone Mapsforge and open it with Android Studio.
Then can install it to local Maven repository with IDE or:
```bash
./gradlew clean install
```
To [include](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md) it in your project, you need to declare the `master-SNAPSHOT` version and add the repository:
```groovy
repositories {
    mavenLocal()
}
```

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
