### ISSUE TITLE
Render theme exclude rule

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1030]
Implement an exclude rule, similar to "-" in [VTM](https://github.com/mapsforge/vtm).
i.e. matches if the map element has tag without the specified values.
```xml
<!-- match tunnel-tag that are not 'no' or 'false' -->
<m k="tunnel" v="-|no|false">
```

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.

**Comment by mohanrajs19** [comment]
Web page not available
    
      body { margin-top: 0px; padding-top: 0px;  } /* Used for additional styles, e.g. direction */
      h2   { margin-top: 5px; padding-top: 0px; }
    

    
      
      
      Web page not available
      
      The web page at data:text/html; charset=utf-8;charset=utf-8;base64, could not be loaded because:
      
      net::ERR_INVALID_RESPONSE
