### ISSUE TITLE
"Parse error for XML rendertheme" after building with Proguard

### ISSUE THREAD

**Issue by secaw** [mapsforge/mapsforge#1031]
After upgrading mapsforge from 0.8.0 to 0.9.1 and building an app with Proguard, maps don't show and I get

> org.mapsforge.map.layer.renderer.DatabaseRenderer: java.lang.IllegalArgumentException: Parse error for XML rendertheme

Without Proguard everything is ok.
I guess, it might be related to _androidsvg_, but the thing is, all is working just fine with 0.8.0 and the same version of _androidsvg_ (1.2.2-beta-1) AND Proguard.

Does anybody have the same issue, or even a solution?
Thanks!

**Comment by devemux86** [comment]
Always use ProGuard and never seen that. But usually no need to obfuscate the third-party libraries. So can use in `proguard-rules.pro`:
```
-keep class com.** { *; }
-dontwarn com.**
-keep class jsqlite.** { *; }
-dontwarn jsqlite.**
-keep class org.** { *; }
-dontwarn org.**
```

**Comment by devemux86** [comment]
Can you provide your build.gradle and the full log of the exception?

**Comment by secaw** [comment]
@devemux86 Unfortunately there's no more log info than the above, maybe because it's only happening in release version. Also nothing special in build.gradle. I thought somebody may have had something similar going on. I will investigate further and report back when I found something. Btw. I'm using mapsforge through osmdroid, but it's pretty straight forward implemented, no extended classes etc.

**Comment by devemux86** [comment]
> I'm using mapsforge through osmdroid, but it's pretty straight forward implemented, no extended classes etc.

Better test all these via creating a simple Android project with [Getting started guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) and try also ProGuard. If it works correctly then can check what differences the custom implementation has.

**Comment by secaw** [comment]
Good idea, thanks.

**Comment by secaw** [comment]
Ok, I think, I found it - I need this new line in addition to the other proguard rules:

`-keep class org.xmlpull.v1.** { *; }`

Didn't need this in 0.8.0, maybe got to do with change in #974?
Thanks for the support!

For future reference, mapsforge currently seems to need those rules:
```
-dontwarn org.xmlpull.v1.**
-keep class org.xmlpull.v1.** { *; }
-dontwarn com.caverock.androidsvg.R
-dontwarn com.caverock.androidsvg.R$styleable
```

**Comment by devemux86** [comment]
Probably, as mentioned above there is no need to obfuscate any third-party open source libraries.
Can use those [ProGuard rules](https://github.com/mapsforge/mapsforge/issues/1031#issuecomment-359485907) anytime.
