### ISSUE TITLE
Indoor offline map

### ISSUE THREAD

**Issue by Awordes** [mapsforge/mapsforge#1032]
Can I use this library for indoor mapping in the android application? And if I can, then how?

**Comment by devemux86** [comment]
Depends also on map source, if it has enough precision for indoor mapping, for your needs.
For example the [Mapsforge map file format](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md) has microdegrees coordinates precision.

You can check also [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library where in vtm-android-sample there is an indoor sample using GeoJSON map source.

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
