### ISSUE TITLE
wms/wmts map providers

### ISSUE THREAD

**Issue by am2222** [mapsforge/mapsforge#1033]
Hi,
Is there any providers to add these kind of layers?I was looking for a data provider api for rasters and vectors but could not fine any. is there any example and etc to develop data providers?
thanks

**Comment by devemux86** [comment]
There is support for raster tiles via any quadtree-scheme tiles provider, e.g. [DownloadCustomLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadCustomLayerViewer.java).

**Comment by devemux86** [comment]
Online vector tiles are supported in [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, via specific decoders & themes per provider.

**Comment by am2222** [comment]
Thanks very much I'll look at the provided lines thanks
