### ISSUE TITLE
POI file writer

### ISSUE THREAD

**Issue by Yerme** [mapsforge/mapsforge#1034]
I'm trying to export a .osm.pbf file to a .poi file.
I downloaded the file: central-america.osh.pbf
I have osmosis set up and it works well for other tasks.
if I execute the following instruction:
osmosis --rb file = new.osm.pbf --poi-writer file = cr-sj.poi

a cr-sj file is generated perfectly, however the file is very large.

what I want is to generate a poi file for a more specific area, for this I execute the following instruction:
osmosis --rb file = new.osm.pbf --poi-writer file = cr-sj.poi bbox = 9,636, -84,594,10,086, -83,736

the file is generated with a size of 60 kb

if I check the file I see that it only contains the categories of the map, but it does not contain the nodes, it does not contain anything other than the categories, I do not see any errors.

I dont understand what's the problem, I have tried several bboxes that I use to generate other .map files and I know they are correct, but I can not generate the poi files with that bbox.
Does anyone know what's the problem?

**Comment by devemux86** [comment]
Please see carefully POI [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/POI.md):
_"Bounding box definition as comma-separated list of coordinates in the form: minLat,minLon,maxLat,maxLon (be aware that osmosis does not allow white space in its command line parameters)."_

So avoid white spaces in Osmosis command line and better use dot "." for decimal separator in coordinates.

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by Yerme** [comment]
yes, I understand, the spaces in the example above were copy / paste error, but, when I do it in my local I do not leave blank spaces but still it is not generated.
here's the real instruction that is not working:

osmosis --rb file=new.osm.pbf --poi-writer file=cr-sj.poi bbox=9.636,-84.594,10.086,-83.736

anyway if I dont put it right osmosis gives me an error, however when I execute it there are no errors and the file is generated but with no other information than the categories.

**Comment by devemux86** [comment]
See answer in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/OGhTDH034UU).
