### ISSUE TITLE
MyLocationOverlay implementation in library

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1035]
`MyLocationOverlay` implementation in library with coordinates / accuracy setters.

**Comment by djnotes** [comment]
How to use this in version 0.9.0 of Mapsforge? It does not seem to be available in the latest version.

**Comment by Gustl22** [comment]
If you use e.g. `implementation 'org.mapsforge:mapsforge:master-SNAPSHOT'`, you always get the latest updates.

**Comment by devemux86** [comment]
It will be included in next library release.
But can always use the latest snapshot version, see [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#snapshots) for details.

**Comment by djnotes** [comment]
I replaced all mapsforge-related version numbers in build.gradle to master-SNAPSHOT, and it failed to resolve, though I added the Sonatype repository.

**Comment by devemux86** [comment]
Let's move the dependencies discussion in the [forum](https://groups.google.com/group/mapsforge-dev). :slightly_smiling_face:
