### ISSUE TITLE
supported data providers

### ISSUE THREAD

**Issue by am2222** [mapsforge/mapsforge#1040]
Hi,
I have a set of geometry data which are saved in sqlite database, Is there any input plugins to use this source to feed mapsforge of create a map file?
thanks

**Comment by devemux86** [comment]
Mapsforge vector maps can be created with [map-writer](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md) plugin for [Osmosis](https://wiki.openstreetmap.org/wiki/Osmosis) tool.
So it depends on what input formats Osmosis supports (better search that).
And can always convert any formats to osm files for easier result.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
