### ISSUE TITLE
Wiki for rendering map file to BufferedImage

### ISSUE THREAD

**Issue by hkcorac** [mapsforge/mapsforge#1048]
Hello,

I searched in issue list and `docs` directory, but couldn't find useful information for rendering map file into `BufferedImage`. I tried to read the code, but it seems Javadocs is lacking a lot. Currently I can't connect all the components to read a map file, then render partial area to a `BufferedImage`.

I have a work around - mostly copying/pasting from sub project `mapsforge-samples-awt`:

- Make new `JFrame`.
- Make new `MapView` and put it on the frame.
- For the `MapView`, override `public void paint(Graphics graphics)` then:
  + Wait for the first call.
  + For subsequent calls, measure delay between them.
  + Wait until a delay time is too large, which might seem that the `MapView` is not going to paint again. For example if average time between paints is 30 ms, then I can wait for 5 seconds, to see if there are no other calls.
  + Now make new `BufferedImage`, build a `Graphics` from the image, and call `MapView#paint()` on that graphics. Finally I can use `ImageIO` to export `BufferedImage` to an image file.

I wish I can learn more than that. But as I mentioned, it seem Javadocs is not sufficient.

May I ask if you could provide some hints for better approach?

Thank you very much.

**Comment by devemux86** [comment]
Vector map libraries are not meant to be raster tiles producers.
Anyway can check [SaveTiles](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-awt/src/main/java/org/mapsforge/samples/awt/SaveTiles.java) for how to retrieve tile bitmaps.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by hkcorac** [comment]
Thank you very much for your help.
