### ISSUE TITLE
DatabaseRenderer crash while printing exception

### ISSUE THREAD

**Issue by drakkan** [mapsforge/mapsforge#1049]
I got an null pointer at this line

https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/renderer/DatabaseRenderer.java#L133

the exception message is null and so I get "java.lang.NullPointerException: println needs a message"

this crash happen randomically

can you please change that log to something like this:

`LOGGER.warning("exception: "+e.getMessage());`

that should not crash? thanks

**Comment by devemux86** [comment]
Thanks for the report, I pushed the change.
