### ISSUE TITLE
Routes and plot them on the map

### ISSUE THREAD

**Issue by powellbird** [mapsforge/mapsforge#1050]
Good afternoon.
There is some way to implement routes and draw them in this excellent library.

please help

**Comment by hgoebl** [comment]
https://github.com/graphhopper/graphhopper

**Comment by devemux86** [comment]
Mapsforge is a vector map library, cannot do routing with the map files.

If you mean routing, then like @hgoebl mentioned, can use [GraphHopper](https://www.graphhopper.com/) routing library.

If you mean how to draw paths on map, then can see [OverlayMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/OverlayMapViewer.java) example in samples.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
