### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by henksplace** [mapsforge/mapsforge#1052]
![2018-04-16_22-27-54 1](https://user-images.githubusercontent.com/18657661/38833414-be5b401e-41c5-11e8-8c4a-dfc282bd3a88.png)

When migrating from Mapsforge version 0.3.0 to 0.8.0 I ran into this rendering issue (see screenshot) on a HTC One S running Android 4.1.1.

The issue occurs only in Portrait mode. First rendering is ok. After slightly moving the map via the touchscreen the rendering issue occurs. Recovery after changing to Landscape mode and back to Portrait mode.

The same code runs fine on Sony Compact X with Android 8.0.0

Map used for testing: http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v4/europe/germany/bayern.map

**Comment by devemux86** [comment]
That could happen in old Android, can be tested in emulator old versions too.
You can try disabling hardware acceleration for the `MapView` depending the Android min/max versions:
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB
        && Build.VERSION.SDK_INT <= ...)
    mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```

**Comment by devemux86** [comment]
Testing in older Android the mapsforge-samples-android does seem having such behavior.
But depending the app implementation and `MapView` layout, can see it in Android emulator 4.1 (Jelly Bean) API 16.
Disabling hardware acceleration like above usually fixes the situation.

**Comment by henksplace** [comment]
Problem does not occur with proposed solution. Thanks!
