### ISSUE TITLE
map not rendered after really quick zoom in/out

### ISSUE THREAD

**Issue by drakkan** [mapsforge/mapsforge#1054]
If I zoom in/out quickly using gesture on android then the map is not rendered, please take a look at the following screenshot

![screenshot_2018-04-18-00-20-11](https://user-images.githubusercontent.com/553263/38902983-22dce046-42a3-11e8-9dae-d4ba31f138fb.png)

I see this suspicious log when this happens

W/MapWorkerPool: Shutdown workers executor failed

**Comment by devemux86** [comment]
Don't know your implementation and have not seen something like that.
Try the [mapsforge-samples-android](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) app to check if see similar behavior.

That (harmless) warning could happen when adding or removing layers on map, which normally doesn't happen when zoom in a ready map.

For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev) first. If an actual problem arises, then can create issues for improve or fix.
