### ISSUE TITLE
deadlock on mapView destroyAll

### ISSUE THREAD

**Issue by drakkan** [mapsforge/mapsforge#1058]
here is the trace

```
DALVIK THREADS (71):
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x740fd000 self=0xb8c776d0
  | sysTid=18402 nice=-4 cgrp=apps sched=0/0 handle=0xb6fefbec
  | state=S schedstat=( 0 0 0 ) utm=1294 stm=174 core=0 HZ=100
  | stack=0xbe28d000-0xbe28f000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x2ef35f24> (a org.mapsforge.map.view.FrameBufferBitmap$Lock)
  at org.mapsforge.map.view.FrameBufferBitmap$Lock.waitDisabled(FrameBufferBitmap.java:67)
  - locked <0x2ef35f24> (a org.mapsforge.map.view.FrameBufferBitmap$Lock)
  at org.mapsforge.map.view.FrameBufferBitmap.destroy(FrameBufferBitmap.java:101)
  - locked <0x2ef35f24> (a org.mapsforge.map.view.FrameBufferBitmap$Lock)
  at org.mapsforge.map.view.FrameBufferHA2.destroy(FrameBufferHA2.java:70)
  - locked <@addr=0x13d3a4c0> (a org.mapsforge.map.view.FrameBufferHA2)
  at org.mapsforge.map.android.view.MapView.destroy(MapView.java:191)
  at org.mapsforge.map.android.view.MapView.destroyAll(MapView.java:218)
```

Please find attached the modified sample ItemDetailFragment that shows the issue
[ItemDetailFragment.zip](https://github.com/mapsforge/mapsforge/files/1971940/ItemDetailFragment.zip)

it seems that you cannot create a mapview and then destroy it before it is rendered.

In my app I add a map fragment after a database query and the user can exit the activity and so destroy the fragment (that triggers mapView.destroyAll) after the map is created and before it is rendered.

I think that this deadlock can happen in any app even if is not so easy to trigger

**Comment by drakkan** [comment]
please find attached a better example to reproduce the issue
[ItemDetailDeadlock.zip](https://github.com/mapsforge/mapsforge/files/1977542/ItemDetailDeadlock.zip)

replace ItemDetailFragment.java and ItemDetailActivity.java with the ones attached,

In ItemDetailFragment.java I simply added a log before and after mapView.destroyAll().

In ItemDetailActivity.java I added an handler that 10 milliseconds after onResume remove the map fragment from the activity.

From a phone launch the samples, tap on "ItemListActivity" then tap on an item for example "Savigny Platz", go back and tap again, after few times you'll get the deadlock, on my device happen always the second time, here are the logs:

```
05-06 12:48:30.891 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailActivity: resume detail activity
05-06 12:48:30.900 20531-20531/org.mapsforge.samples.android I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
05-06 12:48:30.945 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailActivity: remove map fragment
05-06 12:48:31.039 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailFragment: destroy mapview started
05-06 12:48:31.057 20531-20546/org.mapsforge.samples.android I/art: Background sticky concurrent mark sweep GC freed 19989(1379KB) AllocSpace objects, 10(186KB) LOS objects, 0% free, 16MB/16MB, paused 5.742ms total 104.627ms
05-06 12:48:31.153 20531-20636/org.mapsforge.samples.android W/DatabaseRenderer: Exception: null
05-06 12:48:31.154 20531-20626/org.mapsforge.samples.android W/FrameBufferBitmap: Frame buffer interrupted
05-06 12:48:31.154 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailFragment: destroy mapview finished
05-06 12:48:58.491 20531-20531/org.mapsforge.samples.android I/AndroidUtil: TILECACHE INMEMORY SIZE: 25
05-06 12:48:58.492 20531-20531/org.mapsforge.samples.android I/AndroidUtil: TILECACHE FILE SIZE: 556
05-06 12:48:58.511 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailActivity: resume detail activity
05-06 12:48:58.559 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailActivity: remove map fragment
05-06 12:48:58.595 20531-20531/org.mapsforge.samples.android D/org.mapsforge.samples.android.ItemDetailFragment: destroy mapview started
05-06 12:48:58.697 20531-20694/org.mapsforge.samples.android W/DatabaseRenderer: Exception: null
```

are you able to reproduce? thanks

**Comment by drakkan** [comment]
the deadlock seems solved removing the if here:

https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/LayerManager.java#L99

and so executing frameBuffer.frameFinished (that release the lock) even if there is an animation is in progress (a flickering is better than a deadlock ...)

I would like to receive a feedback before continuing to debug the library code, thanks

**Comment by devemux86** [comment]
> a flickering is better than a deadlock

That depends on if users have seen actually the deadlock so far.
They certainly won't like to start seeing suddenly any flickering. :slightly_smiling_face: 

BTW writing tests with extreme conditions, like start / stop an initialization instantly, does not mean that would need to change the whole workflow.
Could mean that some synchronization or some "if" is needed somewhere.
i.e. debugging and testing..

**Comment by drakkan** [comment]
understood, I have to solve this myself :disappointed:

**Comment by devemux86** [comment]
Not meant that, just that core changes need good search and tests by all, since they affect the whole library and all users. :slightly_smiling_face:

**Comment by drakkan** [comment]
please tell me what do you think about https://github.com/mapsforge/mapsforge/pull/1059 thanks

**Comment by devemux86** [comment]
Fixed via #1059.

**Comment by drakkan** [comment]
well, there is another deadlock

```
DALVIK THREADS (67):
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x73e0e000 self=0xb77a96d0
  | sysTid=11028 nice=-4 cgrp=apps sched=0/0 handle=0xb6f19bec
  | state=S schedstat=( 0 0 0 ) utm=1974 stm=272 core=2 HZ=100
  | stack=0xbe48a000-0xbe48c000 stackSize=8MB
  | held mutexes=
  at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:77)
  - waiting to lock <0x365ce6d4> (a java.nio.FileChannelImpl) held by thread 69
  at java.nio.channels.spi.AbstractInterruptibleChannel$1.run(AbstractInterruptibleChannel.java:46)
  at java.lang.Thread.interrupt(Thread.java:657)
  - locked <0x0fdb107d> (a java.util.ArrayList)
  at java.util.concurrent.ThreadPoolExecutor$Worker.interruptIfStarted(ThreadPoolExecutor.java:622)
  at java.util.concurrent.ThreadPoolExecutor.interruptWorkers(ThreadPoolExecutor.java:726)
  at java.util.concurrent.ThreadPoolExecutor.shutdownNow(ThreadPoolExecutor.java:1387)
  at org.mapsforge.map.layer.renderer.MapWorkerPool.stop(MapWorkerPool.java:117)
  - locked <@addr=0x145a0300> (a org.mapsforge.map.layer.renderer.MapWorkerPool)
  at org.mapsforge.map.layer.renderer.TileRendererLayer.onRemove(TileRendererLayer.java:209)
  at org.mapsforge.map.layer.Layer.unassign(Layer.java:170)
  - locked <@addr=0x13aa8ab0> (a org.mapsforge.map.layer.renderer.TileRendererLayer)
  at org.mapsforge.map.layer.Layers.remove(Layers.java:308)
  - locked <0x3cfa4b72> (a org.mapsforge.map.layer.Layers)
  at org.mapsforge.map.layer.Layers.remove(Layers.java:295)
  - locked <0x3cfa4b72> (a org.mapsforge.map.layer.Layers)
  at org.mapsforge.map.android.view.MapView.destroyAll(MapView.java:206)
```

I'll try to investigate this weekend, is something obvious to you?

**Comment by devemux86** [comment]
Hmm strange is that never seen any of all these, so it's clearly connected on how use or misuse the library. :slightly_smiling_face:

**Comment by drakkan** [comment]
My usage is quite simple, no threads ecc... i think this is related to how android manage fragments, probably I'm the first one to seriously use the library inside a fragment ...

**Comment by drakkan** [comment]
my usage is similar to the one you suggest, what happens is that the fragment is destroyed and MapWorkerPool.stop is called while MapWorker run method is blocked in MapFile.processBlocks and so deadlocks

here is the blocked thread when the fragment is destroyed (match with thread 67 in the previous comment)

```
"pool-70-thread-1" prio=5 tid=69 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x14256280 self=0xb862bb10
  | sysTid=17280 nice=0 cgrp=apps sched=0/0 handle=0xb863c480
  | state=S schedstat=( 0 0 0 ) utm=2 stm=0 core=0 HZ=100
  | stack=0x9509d000-0x9509f000 stackSize=1036KB
  | held mutexes=
  at java.lang.Thread.popInterruptAction$(Thread.java:894)
  - waiting to lock <0x0fdb107d> (a java.util.ArrayList) held by thread 1
  at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:110)
  at java.nio.FileChannelImpl.readImpl(FileChannelImpl.java:324)
  at java.nio.FileChannelImpl.read(FileChannelImpl.java:291)
  at org.mapsforge.map.reader.ReadBuffer.readFromFile(ReadBuffer.java:126)
  - locked <0x365ce6d4> (a java.nio.FileChannelImpl)
  at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:581)
  at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:903)
  at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:864)
  at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:94)
  at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:149)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
```

this deadlock seems in AbstractInterruptibleChannel (end and close methods) and so it is probably related to this upstream bug:

https://bugs.java.com/view_bug.do?bug_id=JDK-8198562

the fix is quite recent and probably it will never reach my test android device (android 5.1), what do you think about? Do you agree with my analysis? Do we should to try to workaround the deadlock in mapsforge even if it seems an upstream bug? thanks

**Comment by cl90** [comment]
I still get the same problem with mapsforge 0.11.0 when quickly initializing/destroying a map view.

```
"main@10640" prio=5 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks main@10640
	  at java.lang.Object.wait(Object.java:-1)
	  at org.mapsforge.map.view.FrameBufferBitmap$Lock.waitDisabled(FrameBufferBitmap.java:67)
	  - locked <0x3e81> (a org.mapsforge.map.view.FrameBufferBitmap$Lock)
	  at org.mapsforge.map.view.FrameBufferBitmap.destroy(FrameBufferBitmap.java:101)
	  at org.mapsforge.map.view.FrameBufferHA2.destroy(FrameBufferHA2.java:70)
	  - locked <0x3e82> (a org.mapsforge.map.view.FrameBufferHA2)
	  at org.mapsforge.map.android.view.MapView.destroy(MapView.java:191)
	  at org.mapsforge.map.android.view.MapView.destroyAll(MapView.java:218)
```

**Comment by drakkan** [comment]
The workaroud is to switch to vtm that does not have this bug

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.
