### ISSUE TITLE
Caption text get strange when I pan the map

### ISSUE THREAD

**Issue by WongSpark** [mapsforge/mapsforge#1060]
My English is not very good,I don't know if I could describe this problem clearly.

![1](https://user-images.githubusercontent.com/16441272/39794981-d1c3f080-537f-11e8-8b7b-de29f844de68.png)

It is ok when I first run my code.But when I pan the map,the layout of caption text is in a mess.Like the follow picture.

![2](https://user-images.githubusercontent.com/16441272/39795080-5f2f7804-5380-11e8-8041-60c5ec8d6493.png)

Do you have any suggestion?Thanks a lot.

**Comment by devemux86** [comment]
Sorry it's difficult to understand from the images where the text appears strange on map?

Does the [GettingStarted](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/GettingStarted.java) example works on your device? Don't test only in emulators.
See also my answer in #1052 if need to play with hardware acceleration.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
