### ISSUE TITLE
view scale is wrong when used in layout

### ISSUE THREAD

**Issue by foofel** [mapsforge/mapsforge#1074]
When I use the mapview directly as content view (as shown in the tutorial) everything works correctly. when I integrate the view into an layout via xml (as in the smaples example) some "scaling" seems to happen. The distance scale is drawn way to small and the map drags only at half the speed as it should (drag for 500px, the map moves 250px). I am not sure whats going on but it looks like some size/bounds calculations are wrong. this is on oreo 8.0.

**Comment by devemux86** [comment]
We test the samples in all Android versions and have not seen any issues, so could be some implementation problem?

For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
