### ISSUE TITLE
SVG Salamander (JitPack)

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1078]
[SVG Salamander](https://github.com/blackears/svgSalamander) on Desktop does not provide artifacts in Maven Central.

We can get it at least via [JitPack](https://jitpack.io/#blackears/svgSalamander) in order to use a more updated version.

**Comment by JackPGreen** [comment]
Have you considered adding the JitPack repository to the pom.xml?

Currently if anyone tries to use mapsforge-map-awt without doing this they will not be able to build as the repository for the library is not specified.

**Comment by devemux86** [comment]
What do you mean?

There are instructions in [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md) for how to include Mapsforge in the projects.

**Comment by JackPGreen** [comment]
I've created a sample simple project to illustrate the problem.

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.me</groupId>
	<artifactId>application</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.mapsforge</groupId>
			<artifactId>mapsforge-map-awt</artifactId>
			<version>0.11.0</version>
		</dependency>
	</dependencies>
</project>
```

When you do a Maven install, you get the following error:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.me:application >-------------------------
[INFO] Building application 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.blackears:svgSalamander:jar:v1.1.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.236 s
[INFO] Finished at: 2019-03-27T09:50:56Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project application: Could not resolve dependencies for project org.me:application:jar:0.0.1-SNAPSHOT: Failure to find com.github.blackears:svgSalamander:jar:v1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

This is because you need to add the jitpack Maven repository to the POM file - if you do this it builds fine.

I think it would be better if this was included in the `mapsforge-map-awt` POM instead.

This isn't covered in the integration guide.

**Comment by devemux86** [comment]
> I think it would be better if this was included in the mapsforge-map-awt POM instead.

Mapsforge used Gradle as build system, not Maven.

> This isn't covered in the integration guide.

It is covered clearly in [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#desktop).

**Comment by JackPGreen** [comment]
> > I think it would be better if this was included in the mapsforge-map-awt POM instead.
> 
> Mapsforge uses Gradle as build system, not Maven.
> 
> > This isn't covered in the integration guide.
> 
> It is covered clearly in [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#desktop).

My apologies - I skipped the Gradle section as I was using Maven.
