### ISSUE TITLE
Upgrading from 0.8.0 to 0.10.0 DatabaseRenderer NPE

### ISSUE THREAD

**Issue by spyhunter99** [mapsforge/mapsforge#1084]
I'm attempting to update our forge adapter for osmdroid from .8 to .10. I'm getting all yellow tiles and the following error in the logs. What am i missing?

DatabaseRenderer: Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.app.Application.getAssets()' on a null object reference

**Comment by devemux86** [comment]
For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

A complete stack trace could help or can check the implementation, like if read properly the map file.
