### ISSUE TITLE
Render themes: PNG scaling

### ISSUE THREAD

**Issue by b3nn0** [mapsforge/mapsforge#1090]
Hi,
while SVG scaling works well, the rendertheme specification also allows setting of symbol-width/height/percent for PNG symbols, see https://github.com/mapsforge/mapsforge/blob/master/resources/renderTheme.xsd.
When specifying these parameters, they are correctly parsed by the Symbol class.
The RenderInstruction class will correctly forward these parameters to  XmlUtils.createBitmap.
However, the codepath that loads a PNG image will completely ignore these parameters, so scaling does not work at all.

**Comment by devemux86** [comment]
Symbol scaling was created and meant for SVG resources, where works perfectly.

PNG images cannot be enlarged without producing bad blurry rendering results.

**Comment by b3nn0** [comment]
Well yes, you are right. But: this also means, that dpi scaling doesn't work for PNG.
Therefore, on a low-DPI screen, you will get very huge images.

**Comment by devemux86** [comment]
There isn't any scaling on PNG resources anywhere, they're always rendered in their native size, small or large.

**Comment by devemux86** [comment]
Implemented via #1091.
