### ISSUE TITLE
Does it have MapMatching feature for Android?

### ISSUE THREAD

**Issue by anonym24** [mapsforge/mapsforge#1092]
https://en.wikipedia.org/wiki/Map_matching

Example: https://farm1.staticflickr.com/530/18518221448_5752e8ab30_o.gif

**Comment by devemux86** [comment]
Mapsforge is a map library.
Map matching needs routing libs like [GraphHopper](https://www.graphhopper.com/).

_For questions please use the [forum](https://groups.google.com/group/mapsforge-dev)._

**Comment by anonym24** [comment]
Do you mean I need to use a different library/framework?
But at least Mapsforge supports routing feature?
