### ISSUE TITLE
Suggest users to download countries

### ISSUE THREAD

**Issue by anonym24** [mapsforge/mapsforge#1093]
Can Mapsforge suggest users to download maps? E.g. there is some world map and when you zoom to some country it tries to find it on SDCard if it's missing then suggest user to download it

(20 km vs 200 km)

![z1](https://user-images.githubusercontent.com/8851301/49853324-71058b80-fdef-11e8-8688-64e37be51baf.jpg) ![z2](https://user-images.githubusercontent.com/8851301/49853332-7531a900-fdef-11e8-8ae1-5e73a517e788.jpg)

There is MultiLingualMapViewer in Mapsforge Android samples but it only shows world.map

**Comment by devemux86** [comment]
That's more an app's feature, not inside a map library which handles the rendering.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
