### ISSUE TITLE
Two maps issues (one country covers another with white background)

### ISSUE THREAD

**Issue by anonym24** [mapsforge/mapsforge#1094]
I'm testing TwoMaps sample and I see that it doesn't look very good for neighbor countries (they covering each other with white background)

![screenshot_2018-12-12-12-45-40-664_org mapsforge samples android](https://user-images.githubusercontent.com/8851301/49864984-60174300-fe0c-11e8-8061-8ada30ab9b00.png)

**Comment by devemux86** [comment]
Please use the [forum](https://groups.google.com/group/mapsforge-dev) for questions and discussion.
If there is a verified problem, we can create an issue in repository.
