### ISSUE TITLE
Labels disappear when using proguard rules

### ISSUE THREAD

**Issue by vidsag** [mapsforge/mapsforge#1104]
I am currently using mapsforge ver 0.10.0 and I am using `LabelLayer` to display the label. When proguard is enabled the labels disappear. These are the proguard rules that I am using

```
-dontwarn com.caverock.androidsvg.**
-keep class com.caverock.** { *; }
-dontwarn org.xmlpull.v1.**
-keep class org.xmlpull.v1.** { *; }
-dontwarn com.caverock.androidsvg.R
-dontwarn com.caverock.androidsvg.R$styleable
```

Anyone have any idea on what I might be missing?

Thanks!

**Comment by devemux86** [comment]
Try using `-keep` directives also with Mapsforge classes.

For questions / discussion about the library please use the [forum](https://groups.google.com/group/mapsforge-dev).
