### ISSUE TITLE
Update Mapsforge Applications

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/mapsforge#1106]
Some mapsforge [app links](https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md) are outdated, beginning with Android Speedometer.

**Comment by devemux86** [comment]
Won't be nice to remove apps that don't exist any more, can leave them for history purposes.

**Comment by Gustl22** [comment]
Yes of course, may only remove the broken links.

**Comment by devemux86** [comment]
If any app has a new website can update it, otherwise there is no reason for changes.

Also the [forum](https://groups.google.com/group/mapsforge-dev) is more appropriate place to inform about new applications or updates.

**Comment by Gustl22** [comment]
Why there's a reason to keep broken links? For me it's a sign for bad maintenance (at least on websites). If there's a working link again, can add it of course.

**Comment by devemux86** [comment]
Already mentioned above, a non maintained anymore app does not give us the reason to remove it from applications list.

We're not responsible for the apps / websites state and it's not a dictionary of live apps, only write down the apps which ever used the library.

**Comment by Gustl22** [comment]
Never said to remove them from list. Only to remove the broken link markdown at first row.
We are not responsible for any websites, but for maintenance of "ours".

**Comment by devemux86** [comment]
A non working link today (for whatever reason), can work tomorrow (e.g. republished), can never be certain for the internet or apps condition.

And don't really want to keep checking app links all the time, there are far more important features / bugs needing attention in the libraries. :slightly_smiling_face:

**Comment by Gustl22** [comment]
Ok, so lets keep them.
