### ISSUE TITLE
Map animates to wrong position when previous movement is still active

### ISSUE THREAD

**Issue by Dustin1358** [mapsforge/mapsforge#1115]
Hello,

I found an issue in the android library. In our project we have a map and a "move back to center" button on top of the map. When the user swipes the map and presses the "move back to center" button (which calls the animateTo method (mapView.getModel().mapViewPosition.animateTo(initCenter);)) while the map still moves, the map animates to the initCenter but at the same time continues with the swipe animation which leads to a wrong final position.
I traced the error back to the startAnimationMove method in MapViewPosition.java and there is a TODO which asks if this is probably synchronized so I would say no it is not.
Happens at least on mapsforge 0.11.0 and 0.10.0.

Greetings,
Dustin

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
