### ISSUE TITLE
Spatialite native support for x64 architecture

### ISSUE THREAD

**Issue by luis901101** [mapsforge/mapsforge#1117]
Google has announced that starting August 1, 2019, every apps published on Google Play will need to support 64-bit architectures... Currently I have an app which is already published in GooglePlay, and I have been notified by Google that my app doesn't support x64 bit architecture... In my dependencies the only native dependency that doesn't support x64 architecture is spatialite-android...
This is why I'm using in my build.gradle:

   ```
api 'org.mapsforge:spatialite-android:0.9.1'
api 'org.mapsforge:spatialite-android:0.9.1:natives-armeabi'
api 'org.mapsforge:spatialite-android:0.9.1:natives-armeabi-v7a'
api 'org.mapsforge:spatialite-android:0.9.1:natives-x86'
```

How can I do to get the natives for x64 bit... like:

```
api 'org.mapsforge:spatialite-android:0.9.1:natives-arm64-v8a'
api 'org.mapsforge:spatialite-android:0.9.1:natives-x86_64'
```

Thanks in advance

**Comment by devemux86** [comment]
Mapsforge POI now use SQLite Android Bindings which have all natives.
See [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/POI.md) and [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#poi) for more details.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by luis901101** [comment]
Ok thanks
