### ISSUE TITLE
Ability to disable antialiasing on android

### ISSUE THREAD

**Issue by wentam** [mapsforge/mapsforge#1121]
I am attempting use use the Mapsforge renderer on an android device that is black & white only (hardware is a bike computer). Pixels are either on or off, no in-between. Antialiasing works very poorly in this situation.

Antialiasing is enabled hard-on here: https://github.com/mapsforge/mapsforge/blob/eccfea2aabf9efc035c84c0ce312be573fa15b54/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidPaint.java#L132

I don't think there's a need for this to be configurable per-element, but a global on/off switch for antialiasing would be incredibly helpful.

**Comment by devemux86** [comment]
Can you show some images with how the rendering appears on that device with the option on and off, so can better understand and verify the case?

**Comment by wentam** [comment]
This is surprisingly difficult to capture on camera, especially given inconsistent focus and AA changing the location of rendered text, but I think I managed to capture a sufficient example:

![AAexample](https://user-images.githubusercontent.com/901583/60241113-866c6f80-9880-11e9-99fa-8d5549f7daeb.jpg)

Left is non-AA, right is AA. Look at the shape of the "a" and note which pixels are on. AA causes it to meld into a blob once displayed on a display that doesn't show pixels between on or off. In general, with AA, text especially will look odd, wobbly and melded together.

The pixels on the display have two modes: black or white. It can not display gray or anything else.

AA works by creating pixels of less intensity around the object being rendered. On a display that can't display those dimmer/more transparent pixels, AA simply serves no function and produces unpredictable results.

It's not a fault in the AA implementation or mapsforge -- it's simply that AA fundamentally does a thing that the hardware is incapable of displaying. Thus, it should be possible to disable AA to be able to render output fully compatible with that type of display.

Even if it did render perfectly well with AA by coincidence, it would not make sense to use AA on such a display, as the display is simply incapable of displaying what AA is intended to do. It would simply be wasted resources.

**Comment by devemux86** [comment]
We could add a new flag in [Parameters](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/Parameters.java) to handle antialiasing.

**Comment by wentam** [comment]
That would work. However, I just noticed that [GraphicContext](https://github.com/mapsforge/mapsforge/blob/e684a4b07504a16794db29ee516e20b0673a4334/mapsforge-core/src/main/java/org/mapsforge/core/graphics/GraphicContext.java#L61) has a setAntiAlias call that looks like is implemented all the way up to [AndroidCanvas.](https://github.com/mapsforge/mapsforge/blob/eccfea2aabf9efc035c84c0ce312be573fa15b54/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidCanvas.java#L277) . If this is setting the value on the same Paint object, then all that would need to be done at least in android's case is provide a call on MapView to set AA.

**Comment by devemux86** [comment]
These don't seem to be connected, it was introduced in #1102.

**Comment by wentam** [comment]
[Ah yup, looks like it's just created right here (line 49)](https://github.com/mapsforge/mapsforge/blob/eccfea2aabf9efc035c84c0ce312be573fa15b54/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidCanvas.java#L49)

**Comment by devemux86** [comment]
Implemented via #1122.
