### ISSUE TITLE
Too restrictive max aspect ratio in frame buffer controller

### ISSUE THREAD

**Issue by cpt1gl0** [mapsforge/mapsforge#1124]
For devices with a screen aspect ratio > 2 (e.g. Huawei P30) the max aspect ratio of 2 in frame buffer controller is too restrictive. This leads to wrong results when calculating frame buffer dimensions with Parameters.SQUARE_FRAME_BUFFER set to true.

**Comment by devemux86** [comment]
Seems the `maxAspectRatio` check is not much needed, we can remove it, if want `SQUARE_FRAME_BUFFER` then better have square frame buffer.

**Comment by cpt1gl0** [comment]
# #1125

**Comment by devemux86** [comment]
Fixed via #1125.
