### ISSUE TITLE
Part of the map disappears when using %f in tagmapping

### ISSUE THREAD

**Issue by SMinin** [mapsforge/mapsforge#1127]
When I generate a europe / germany / bremen map with tagmaping: 

```
<pois>
        <osm-tag key="seamark:bridge:clearance_height" value="%f" zoom-appear="6" />
</pois>
```

one part of the city map of the Bremen disappears. The probable cause may be one of the values of "seamark:bridge:clearance_height=7.02". Other sections of the map where this tag is used are displayed normally.

**Comment by devemux86** [comment]
For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
Then for verified problems or new features we can create issues.
