### ISSUE TITLE
POI search not working in androidx

### ISSUE THREAD

**Issue by farhad-kargaran** [mapsforge/mapsforge#1128]
I migrated my app to androidx, and poi search stop working.
I debug my app, in this line:
`persistenceManager = AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(POI_FILE.getAbsolutePath());`
I faced this error: 
java.lang.UnsatisfiedLinkError: No implementation found for long org.sqlite.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_org_sqlite_database_sqlite_SQLiteConnection_nativeOpen and Java_org_sqlite_database_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)

**Comment by devemux86** [comment]
> I migrated my app to androidx

What does that mean exactly, how that migration is done?
See the [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md), are all POI dependencies included (also the native)?

There is use of POI on projects with AndroidX without issues.

For questions and until an error is verified please use the [forum](https://groups.google.com/group/mapsforge-dev).
