### ISSUE TITLE
Gradle Build Error

### ISSUE THREAD

**Issue by tomstewart99** [mapsforge/mapsforge#1130]
I am trying to build the project using gradle on windows 10. When I run clean build it fails initially with this error:

> Task :mapsforge-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-core:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-map:compileJava FAILED
warning: [options] bootstrap class path not set in conjunction with -source 1.7
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:49: error: unclosed character literal
        sb.append('┬░');
                  ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:49: error: illegal character: '\u00b0'
        sb.append('┬░');
                    ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:49: error: unclosed character literal
        sb.append('┬░');
                     ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:54: error: unclosed character literal
        sb.append('ÔÇ▓');
                  ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:54: error: ';' expected
        sb.append('ÔÇ▓');
                    ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:54: error: illegal character: '\u00b2'
        sb.append('ÔÇ▓');
                     ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:54: error: unclosed character literal
        sb.append('ÔÇ▓');
                      ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:58: error: unclosed character literal
        sb.append('ÔÇ│');
                  ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:58: error: ';' expected
        sb.append('ÔÇ│');
                    ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:58: error: illegal character: '\u00b3'
        sb.append('ÔÇ│');
                     ^
C:\Users\Thomas.Stewart\Downloads\mapsforge-master\mapsforge-map\src\main\java\org\mapsforge\map\layer\overlay\Grid.java:58: error: unclosed character literal
        sb.append('ÔÇ│');
                      ^
11 errors
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mapsforge-map:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
19 actionable tasks: 5 executed, 14 up-to-date

After cahnging the grid.java file and removing some quotation marks and replaceing from ' to " I have got past this issue but it then gives a different error:

> Task :mapsforge-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-core:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-map:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-map:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

> Task :mapsforge-map-android:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':mapsforge-map-android:lint'.
> No value has been specified for property 'lintClassPath'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
24 actionable tasks: 12 executed, 12 up-to-date

If i run gradlew clean assemble the build is successful but no apk is actually created. Therefore I have been trying to perform the full build and it gives this 'no specified lintClassPath error'. I posted the first error just to see if changing that may have been the cause for the second error. Any help is appreciated.

**Comment by devemux86** [comment]
Can make a clean clone of the repository and then try to build again.

For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
With the latest code / build changes now should work more correctly on Windows.
