### ISSUE TITLE
Can MapForge Shows Statelight View of Maps?

### ISSUE THREAD

**Issue by AKMANSoft** [mapsforge/mapsforge#1133]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

Can MapForge Shows Statelight View of Maps?

**Comment by devemux86** [comment]
Satellite maps are usually online bitmap tile sources.

Can show them if create a custom time source, as seen in [DownloadCustomLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadCustomLayerViewer.java) sample.

For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).
