### ISSUE TITLE
Integer overflow in logging when converting huge .pbf to .map

### ISSUE THREAD

**Issue by NorbertSandor** [mapsforge/mapsforge#1137]
When converting the whole `europe-latest.osm.pbf` to `.map` format, the logged node count displayed in the console overflows, like (note the negative sign):
```
INFO: start reading data...
Add nodes: -2,114,000,000
```
where the node count begins to decrease...

**Comment by devemux86** [comment]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
Thanks for the report.
I changed progress logs to use longs instead of integers, that should fix the overflow.
