### ISSUE TITLE
Android mapsforge marker displaced

### ISSUE THREAD

**Issue by MDKPredator** [mapsforge/mapsforge#1138]
I was having problems with my application because I saw that the markers were displaced as I zoomed in and out, so I decided to install the mapsforge examples.

When I tested them on my Android 9, I discovered that the problem was still there. In the screenshots you can see how the coordinates shown are different as I zoom.

In the screenshots you can see how the position of the marker changes and the coordinates returned by the example are different from the original protected LatLong latLong1 = new LatLong(52.5, 13.4);

This doesn't happen to me in Android version 6 and earlier.

![Photo 1](https://user-images.githubusercontent.com/2007504/69885176-389ade00-12dc-11ea-8e08-96c9dcd33aa0.jpg)
![Photo 2](https://user-images.githubusercontent.com/2007504/69885192-49e3ea80-12dc-11ea-9203-b71278729f1f.jpg)
![Photo 3](https://user-images.githubusercontent.com/2007504/69885200-4e100800-12dc-11ea-9ea7-2785fe67d627.jpg)
![Photo 4](https://user-images.githubusercontent.com/2007504/69885201-4e100800-12dc-11ea-81e3-fd38dfca7c32.jpg)

**Comment by devemux86** [comment]
Seems a problem at drawables to bitmaps conversion on newer Android.
We could use a simpler bitmap read and avoid all that code workarounds.

![Mapsforge](https://user-images.githubusercontent.com/3484020/69899376-cd015100-136d-11ea-95d2-9e04e1ddde09.png)

**Comment by devemux86** [comment]
> In the screenshots you can see how the position of the marker changes and the coordinates returned by the example are different from the original protected LatLong latLong1 = new LatLong(52.5, 13.4);

By the way the displayed coordinates in OverlayMapViewer is the [geographic position of the tap](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/Layer.java#L104),
not the position of the marker.

**Comment by MDKPredator** [comment]
> Seems a problem at drawables to bitmaps conversion on newer Android (BitmapDrawable.getBitmap). We could use a simpler bitmap read and avoid all that code workarounds.

Perfect, thank you very much.

> By the way the displayed coordinates in OverlayMapViewer is the geographic position of the tap,
not the position of the marker.

And thank you again for the clarification.
