### ISSUE TITLE
Possible detect when posiotion is outside the map area?

### ISSUE THREAD

**Issue by grais** [mapsforge/mapsforge#1147]
Hi.
I'm using mapforge verion 0.11.0 and a want these folloving things:
**Possible detect when position is outside the loaded map area?**
Possible automatic load new map when the position outside the loaded map?

Thanks for your answare.

**Comment by devemux86** [comment]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).
