### ISSUE TITLE
Kml support for Mapsforge

### ISSUE THREAD

**Issue by puneethreddy-3186** [mapsforge/mapsforge#1150]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by puneethreddy-3186** [comment]
Is there way to show KML data on the map view of Mapsforge?

**Comment by devemux86** [comment]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).
