### ISSUE TITLE
Expose some properties public

### ISSUE THREAD

**Issue by DrMarkEy** [mapsforge/mapsforge#1154]
Hi,

In my project I am successfully using 
`boolean busy = tileRendererLayer.mapWorkerPool.jobQueue.size() > 0;`
to show a loading indicator for my map when tile rendering is in progress. However I currently have to compile the library myself as TileRendererLayer.mapWorkerPool is a private property in the original source code as well as MapWorkerPool.jobQueue. However I would much rather use the packaged version of the library, as right now updating is a hassle. Would you consider adding getters for these properties?

Furthermore I would like to use org.mapsforge.map.android.graphics.AndroidMatrix to draw scaled Bitmap Layers using `canvas.drawBitmap(bitmap, scaleMatrix);` which is also package private at the moment.

**Comment by devemux86** [comment]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
