### ISSUE TITLE
Layer onScroll event (#1132) introduces speed bug

### ISSUE THREAD

**Issue by bailuk** [mapsforge/mapsforge#1162]
_Commit 79c0af8 Layer onScroll event (#1132)_ introduces speed bug. 

The code added to `TouchGestureHandler` uses synchronized access to all layers. The same is done from` LayerManager` when drawing layers. Drawing and scrolling usually happens at the same time and drawing is in a different thread. Therefore this **has** to slow things down.

**Comment by devemux86** [comment]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

_If a report can be verified with a solution, then can see it in an issue / pull request._

**Comment by bailuk** [comment]
> If a report can be verified with a solution, then can see it in an issue / pull request.

Sorry I don't understand this sentence.

My point is that commit 79c0af8 clearly introduces a bug that makes maps forge unusable. The solution is to revert this commit.

**Comment by devemux86** [comment]
> My point is that commit 79c0af8 clearly introduces a bug that makes maps forge unusable.

Android + Desktop samples seem to work without problems.

> The solution is to revert this commit.

You didn't write in the report that you want to remove that user code.

That PR code seems to be used similarly with all other events, i.e. tap, long press.

Anyway let's discuss the report first in the forum,
with more details for how can reproduce the report.

**Comment by devemux86** [comment]
Being a public API, can make it optional via a boolean flag in the [Parameters](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/Parameters.java) class.

(users wanting to use that function can set the flag 'true' before initialize the library)

**Comment by bailuk** [comment]
> Android + Desktop samples seem to work without problems.

Because it's a multi threading issue it's a mater of timing and of how heavy the redrawing is.
In my app the slowness really gets annoying when there are lots of POIs to draw.

> That PR code seems to be used similarly with all other events, i.e. tap, long press.

Yes but only when the user scrolls continuous redrawing starts in LayerManager

> Being a public API, can make it optional via a boolean flag in the Parameters class.

I would consider removing this feature for two reasons: First it clearly introduces a speed bug. Second getting scroll events can also be achieved outside of mapsforge with a overlay widget.

But of course i can perfectly live with this feature if it is optional.

**Comment by devemux86** [comment]
Option in `Parameters` implemented in #1163.

**Comment by bailuk** [comment]
Thanks a lot for fixing this!
