### ISSUE TITLE
Cannot create MapFile from public file on Android 11(+)

### ISSUE THREAD

**Issue by wharnisch** [mapsforge/mapsforge#1164]
To create a MapFile object an object of type File or FileInputStream or FileChannel is needed. On Android 11 because of 'scoped storage' it is no longer possible to read a File on a folder for example on the sd card that is accessible by multiple apps. Reading via a File object or a FileInputStream object or a FileChannel object is only possible for files that only can be accessed by the own app. So every app that uses Mapsforge has to hold its own copy of the (big) map files - this is very inconvenient. So I think further constructors for MapFiles are needed that can handle objects like InputStreams or DocumentFiles or Uris or other objects that are returned by 'Storage Access Framework' (SAF) or by the MediaStore API.

**Comment by devemux86** [comment]
See the related [forum discussion](https://groups.google.com/forum/#!topic/mapsforge-dev/2tkZjOx8tdQ).

For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
See #1170.
