### ISSUE TITLE
Memory Leak In Layout Builder

### ISSUE THREAD

**Issue by jjonesdesign** [mapsforge/mapsforge#1166]
Hello,

I don't have the experience needed to help locate the issue, but it seems there is some kind of memory leak related to the layout builder screen rendering a live view of the map layout.

Running the latest version of Android Studios, Latest build of MapsForge.

Randomly (it seems to happen more often when trying to code complete), Android Studio will hijack 100% CPU and memory usage will spike. This doesn't happen if I remove the MapView from the layout builder.

System specs are plenty high enough to run Android Studio and I don't have this issue with any other project, even much much larger ones.

Confirmed this issue happens even when the library is installed in a fresh project, with 1 view.

No non-default IDE plugins running.

Hope this helps.

**Comment by devemux86** [comment]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

Need details in forum & if community can verify / reproduce the report,
then could create an issue along with the the solution in a pull request.

In any case better examine [VTM](https://github.com/mapsforge/vtm), as Mapsforge engine has its limits.
