### ISSUE TITLE
JavaFX implementation from 2013

### ISSUE THREAD

**Issue by kellerkindt** [mapsforge/mapsforge#1171]
Back in 2013 I did a port of the - at that time - current version of mapsforge to JavaFX:

https://github.com/kellerkindt/mapsforgefx
https://github.com/kellerkindt/mapsforgefx_demo

In 2017 I was able to open source the code. Feel free to link/refer to it, but at the moment I have no intentions to update the repo.

**Comment by devemux86** [comment]
Thanks, you can inform the community also in the [forum](https://groups.google.com/group/mapsforge-dev).
