### ISSUE TITLE
Mapsforge theme resources with Android SAF

### ISSUE THREAD

**Issue by ryust** [mapsforge/mapsforge#1184]
I've noticed release 0.15.0 has the new ContentRenderTheme for SAF. When will resources for the themes also be supported with SAF?

**Comment by devemux86** [comment]
This is currently not supported.
You can copy the theme to the app's internal storage and open it from there.

For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by ryust** [comment]
I had been doing this, but when a user has a large number of themes the copy process slows down considerably to become unusable. Plus, the effort to sync between user stored themes and internal storage is difficult to determine when the user themes have been changed to recopy again.

I'm willing to try to come up with a solution myself if I knew which modules to look at. I started with ContentRenderTheme, but got lost knowing where to find the code that loads the resources.
