### ISSUE TITLE
It may make sense to rewrite Specification-Binary-Map-File.md into Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [mapsforge/mapsforge#1193]
KS is a declarative DSL for both human- and machine-readable specifications of file formats. Machine-readability allows to generate parsers for multiple programming languages automatically. Human-readability and declarativeness allows to replace free-form text docs with KS specs.

It may make sense to rewrite https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md into Kaitai Struct.

Here is the kind of getting started guide: https://doc.kaitai.io/user_guide.html

**Comment by devemux86** [comment]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by KOLANICH** [comment]
I'm sorry, but Google Groups usage is completely inacceptable for me.
