### ISSUE TITLE
Rolling of Map

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#128]
_From [daisy.g....@gmail.com](https://code.google.com/u/118370791756141671289/) on June 09, 2011 10:41:44_

What steps will reproduce the problem? 1. Drag / Fling the map it will reaches the end of map 2. 3. What is the expected output? What do you see instead? Once i reach the end of map i'm expecting to see the starting position of world map again. Instead of that i'm just seeing the white space. What version of the product are you using? On what operating system? Android OS, 2.2 Please provide any additional information below.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=128_

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.
