### ISSUE TITLE
Include POI without name

### ISSUE THREAD

**Issue by mfbehrens99** [mapsforge/mapsforge#1381]
Hello,
I am not sure if this issue is really appropriate here.

I use the mapsforge POIs in QMapShack, and they really help me out while planning tours. Afaik, POIs without a name get not included in the `.poi`-file. This probably sense in most situations (like `place`). However, when I am looking for a place to park my car I would like to see all `amenity=parking` neither if they have a name or not.

I know that this would significantly increase the amount of POIs.

Looking forward to your comments

**Comment by devemux86** [comment]
Thanks for the suggestion.
We certainly need to think about it.

Have you tested to see the size of both implementations? (with `names` `true` or `false`)
Do you know if the poi files from [OpenAndroMaps](https://www.openandromaps.org/en/) include unnamed poi?
