### ISSUE TITLE
Search much slower in Mapsforge POI v3 compared to v2

### ISSUE THREAD

**Issue by Juanjo-MC** [mapsforge/mapsforge#1443]
Hi,

Latest Oruxmaps beta ships with support to both Mapsforge POI v2 and v3 databases.
It appears that search speed using bbox bounded queries is much slower on v3 databases than on v2 databases with the exact same content.

Creating the two indexes below in v3 database dramatically increases search speed:

`CREATE INDEX "idx_poi_index_lat" ON "poi_index" ("lat")`
`CREATE INDEX "idx_poi_index_lon" ON "poi_index" ("lon")`

**Comment by devemux86** [comment]
@Juanjo-MC thanks for the suggestion.

When I wrote the POI v3 format, I compared their performance, but I didn't see any significant difference.
(even with huge databases like germany.poi)

I tested berlin.poi without and with the above indexes using the PoiSearchViewer sample:
Indexes seem to perform similarly or worse?
<table>
<tr>
<th>No indexes</th><th>With indexes</th>
</tr>
<td><img src="https://github.com/mapsforge/mapsforge/assets/3484020/f79777a4-21a7-4b82-9093-692af970a3ce"/></td><td><img src="https://github.com/mapsforge/mapsforge/assets/3484020/13d77b42-7e87-487d-bded-1e1d951c6433"/></td>
<tr>
</tr>
</table>

**Comment by Juanjo-MC** [comment]
Hi,

when the first POI V3 databases started to appear on Mapsforge server I tested them as well. I performed the tests on my laptop, with and without the indexes, and it turned out that there were little to no difference at all, so I arrived to the same conclusion than you.

When testing on Oruxmaps, on my android phone, it quickly appeared that searches were way slower in V3 than in V2. After adding the indexes, performance was back to normal, queries were orders of magnitude faster. 

As an example, in Oruxmaps, you can display POI info by touching the screen at the place (or near) where the POI is located. This is supposed to be a very fast query because the search is bounded to a small radius around the point. In V2 databases the result was there instantaneously while in V3 it was taking several seconds for it to appear on the screen.

**Comment by devemux86** [comment]
Tests need to be done with [Mapsforge samples](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) where the code is open source and available to all users.
We can't know what each app is doing in its code and how it uses the library.

Can you see any difference using the [PoiSearchViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/PoiSearchViewer.java) sample with existing or a different query?

**Comment by devemux86** [comment]
Also, searching for a word like "restaurant" without categories, the above indexes seem to perform worse:
<table>
<tr>
<th>No indexes</th><th>With indexes</th>
</tr>
<td><img src="https://github.com/mapsforge/mapsforge/assets/3484020/8675d144-6c97-411b-aae0-9f46ca6ab701"/></td><td><img src="https://github.com/mapsforge/mapsforge/assets/3484020/3d479695-0d62-4380-a88e-7be100fc5fe9"/></td>
<tr>
</tr>
</table>

**Comment by Juanjo-MC** [comment]
I see that, in both cases, you are using a bbox as big as the whole
dataset. In such case the index is not going to help as the whole dataset
must be visited anyway.

I do not think that this would be the typical use case, nobody is going to
search for restaurants city or country wide.
A more typical use case  would be: I want to eat something, let's search
for restaurants 1 km around me.

In such a case the index would be helpful as as the db engine can then look
for POIs one km around and discard those that are not restaurants. Without
it, again, the whole dataset must be scanned.

May I ask you to repeat your tests with a very small bbox, just a couple of
kilometers wide?

**Comment by devemux86** [comment]
@Juanjo-MC

I will do more tests, also with the large germany.poi so that the results are more visible.

**Comment by oruxman** [comment]
Hello!

I can confirm that, using version v.0.20 of the libraries (Pixel 6 device, using Android 15 beta), the call to https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi/src/main/java/org/mapsforge/poi/storage/PoiPersistenceManager.java#L77

     Collection<PointOfInterest> findNearPosition(LatLong point, int distance,
                                                         PoiCategoryFilter filter, List<Tag> patterns,
                                                         LatLong orderBy, int limit, boolean findCategories)

1.-Using the Spanish pois database: http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/pois/europe/spain.poi

I get an average of 650 ms on different map queries.

Once I enter to the database the indexes suggested by Juanjo, the average time drops to 19 ms.

2.-In different queries to https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi/src/main/java/org/mapsforge/poi/storage/PoiPersistenceManager.java#L58

     Collection<PointOfInterest> findInRect(BoundingBox bb, PoiCategoryFilter filter, List<Tag> patterns,
                                            LatLong orderBy, int limit, boolean findCategories);
                                           
The results are not so spectacular, the time is only reduced by half. The query that takes 8000 ms is resolved by the database that has indexes in about 4000 ms.
                                           

The unwanted side effect is an increase in the size of the database. Goes from 263 mb to 314 mb...

**Comment by devemux86** [comment]
Thanks everyone for the report and the tests.

Testing also with the large germany.poi the results indeed improve with the indexes.
I pushed the change in the repository.

The poi on Mapsforge server will be updated soon.
