### ISSUE TITLE
Rotation of the map on Android 13 shows white screen

### ISSUE THREAD

**Issue by karel-zabloudil-3pg** [mapsforge/mapsforge#1454]
When rotating the map on Android v13 the maps shows white screen.
Please see the images from the official example application on Android v10 and Android v13

![Animation](https://github.com/mapsforge/mapsforge/assets/99957071/f3f8c3e8-966c-4396-bda4-3da7f54842c3)
![Animation2](https://github.com/mapsforge/mapsforge/assets/99957071/2fdef11d-c0d5-425a-a99b-f1e2e77b45db)

**Comment by devemux86** [comment]
See the VTM (OpenGL) map library, compatible with Mapsforge maps: https://github.com/mapsforge/vtm
It has map rotation / tilt, continuous zoom and many other features.

**Comment by devemux86** [comment]
Next Mapsforge will have native map rotation.

**Comment by devemux86** [comment]
@karel-zabloudil-3pg I do not know that yet, as I am still optimizing the code.

You can test it with the [rotation](https://github.com/mapsforge/mapsforge/tree/rotation) branch, see the [RotationMapViewer](https://github.com/mapsforge/mapsforge/blob/rotation/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotationMapViewer.java) sample.

**Comment by devemux86** [comment]
I merged the map rotation in Mapsforge, see the [RotationMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotationMapViewer.java) example.
