### ISSUE TITLE
POI: not all ways defined in the poi mapping are included

### ISSUE THREAD

**Issue by slwmr** [mapsforge/mapsforge#1456]
## Description

I tried to create a version 3 POI file with street names (apart from other objects included by default).
If a way contains nodes with tags that do not match selection criteria for nodes, that way is not included in the POI database (although the tags for the way itself match the criteria).
PoiWriter.java  
```
for (WayNode wayNode : way.getWayNodes()) {  
	wayNodes[i] = findNodeByID(wayNode.getNodeId());  
	if (wayNodes[i] == null) { ... }  
```

## Test Case
The file Widok.osm attached as
[Widok.txt](https://github.com/mapsforge/mapsforge/files/13905549/Widok.txt)
contains just one way.
I have commented out the tags of the nodes exept one (in the line 16).

If you create a POI database based on this file - it will not contain any POI entry.

If you comment out line 16 (`<tag k="crossing" v="traffic_signals"/>`) in the file Widok.osm the POI file will contain the POI entry for this way.

The command line:
`osmosis --read-xml Widok.osm  --poi-writer  names=false ways=true filter-categories=false progress-logs=true tag-conf-file=my-poi-mapping.xml  file=Widok.poi`

my-poi-mapping.xml is a standard mapping with a few uncommented categories. For our case the important part is:
```
        <category title="Tertiary way">
            <mapping tag="highway=tertiary" />
        </category>
```

**Comment by devemux86** [comment]
Elements in osm are usually processed in the order: nodes > ways > relations.
POI writer first stores temporarily the nodes and then check the ways for POI.

But very large databases like Germany cannot be created with all nodes stored.
There is a filter [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi-writer/src/main/java/org/mapsforge/poi/writer/PoiWriter.java#L390) about what nodes to store that may be way nodes or not.

Probably not the best solution, but at least all nodes in poi-mapping
and most matching ways should be stored.

If you are interested for your case to not use this filter,
we can make it optional via a parameter.

**Comment by slwmr** [comment]
Thank you for a quick answer. 
Yes, I would be interested. Especially that I make the POI for one city/region.
Another option could be not to exclude ways because one / a few of their nodes were filtered out in the previous step? After all later just one point is calculated for the way (so even if only one node is left after filtering - it still could be used to calculate the coordinates of the POI)

**Comment by devemux86** [comment]
> Another option could be not to exclude ways because one / a few of their nodes were filtered out in the previous step? After all later just one point is calculated for the way (so even if only one node is left after filtering - it still could be used to calculate the coordinates of the POI)

This may produce invalid geometries for JTS.

**Comment by devemux86** [comment]
You can use the `way-filtering` option to turn off the filtering of the tagged nodes in ways.

https://github.com/mapsforge/mapsforge/blob/master/docs/POI.md

**Comment by slwmr** [comment]
Thank you very much!
