### ISSUE TITLE
renderTheme.xsd is not deterministic

### ISSUE THREAD

**Issue by tumic0** [mapsforge/mapsforge#1461]
The render theme XSD is not deterministic and can thus not be used for style XML validation:

```
[tumic@tumic mapsforge]$ xmllint --schema ~/Downloads/renderTheme.xsd default.xml > /dev/null
/home/tumic/Downloads/renderTheme.xsd:337: element complexType: Schemas parser error : complex type 'rendertheme': The content model is not determinist.
WXS schema /home/tumic/Downloads/renderTheme.xsd failed to compile
```

**Comment by devemux86** [comment]
We have not seen any problem validating the render themes with supported editors or IDEA.

**Comment by devemux86** [comment]
We have not seen any problem validating the render themes with supported editors or IDEA.

If you see something that could be improved, please post it so we can review it.
