### ISSUE TITLE
Suggestion to eliminate the old package split 

### ISSUE THREAD

**Issue by Asquator** [mapsforge/mapsforge#1464]
There is an old problem with the package org.mapsforge.map.rendertheme [exposed by two modules](https://github.com/mapsforge/mapsforge/issues/1135) mapsforge.map, mapsforge.themes.

The two modules are frequently used together, so it becomes a very challenging situation in modular projects, and the best solution seems to just rename the package manually in one of the modules.

Maybe it is worth doing it on library level?

P.S:
I think the suggestion should be motivated, after reading responses to previous discussions of the topic.
The main motivation isn't really the necessity to conform to weird implications of the module system, but user experience. Existing solutions for eliminating package splits aren't as easy as one might think. The best option I found after hours of research is merging the two jars corresponding to mapsforge.map and mapsforge.themes to a single jar module. This isn't straightforward at all, and requires importing the library as a bunch jars instead of using build systems.
The merge could really be done on the library level, and the two modules could become one. If the merge goes against mapsforge's design goals, renaming is an option.

If we talk about integration with JavaFX, all JFX apps are modular by default (there is an option for non-modular approach there, but it's awkward). Even now there exists an approach to integrate AWT map into Javafx, and doing so in current setup is just difficult.

**Comment by Asquator** [comment]
Any ideas?

**Comment by devemux86** [comment]
Changing public packages will break user apps that already use them.
And the vast majority is on Android that has no such strange problems.

Mapsforge modules are separate as they are not needed by all apps.
So we will see what can be done...

**Comment by devemux86** [comment]
Fixed by #1486
