### ISSUE TITLE
fire_station are invisible

### ISSUE THREAD

**Issue by Mahabarata** [mapsforge/mapsforge#1465]
I'm using your maps in Locus Map and in Cruiser softwares.

The ways with the tags building=fire_station (according to https://wiki.openstreetmap.org/wiki/Tag:building%3Dfire_station) are currently not visible on your maps.

An example : this fire station = https://www.openstreetmap.org/way/71491025/history, in osm database for 13 years but with the tags building=fire_station for more than 2 years , is not visible on the map guyane.map (2024-01-19 version), file from this folder https://download.mapsforge.org/maps/v5/europe/france/

A screenshot of Locus map = ![Screenshot_2024-02-06-14-20-19-782_menion android locus](https://github.com/mapsforge/mapsforge/assets/3121119/092bc70a-5f62-4116-b8e9-e1494e193693)

Same problem in Cruiser software with the same map file.

**Comment by devemux86** [comment]
Thanks, I added it in map-writer's tag-mapping.

**Comment by devemux86** [comment]
@Mahabarata Thanks, I added it in map-writer's tag-mapping.

**Comment by applantation** [comment]
I will in the next few days update the server.

Emux ***@***.***> schrieb am Fr. 9. Feb. 2024 um 15:54:

**Comment by Mahabarata** [comment]
Great ! Thanks !

**Comment by Mahabarata** [comment]
i just downloaded the last version of guyane.map from your server (2024-03-14 version).
Again the fire_station is invisible on Locus Map and Cruiser

**Comment by devemux86** [comment]
@Mahabarata

If we build the map locally, the fire station is there, so the server probably hasn't used the latest map-writer.

cc @applantation

**Comment by applantation** [comment]
I was kind of waiting for a release before installing a new version, so
firestations are still not in the server generated maps

Emux ***@***.***> schrieb am Di. 26. März 2024 um 23:40:
