### ISSUE TITLE
`docs/Mapsforge-Applications.md` contains a link to osmaptuner.salzburgresearch.at, which does not exist.

### ISSUE THREAD

**Issue by dreirund** [mapsforge/mapsforge#1470]
The file [`docs/Mapsforge-Applications.md`](https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md) contains a link to [`osmaptuner.salzburgresearch.at`](http://osmaptuner.salzburgresearch.at/), which does not DNS-resolve:

`host osmaptuner.salzburgresearch.at`:  
```
Host osmaptuner.salzburgresearch.at not found: 3(NXDOMAIN)
```

Regards!

**Comment by devemux86** [comment]
The application list contains applications that used or are using Mapsforge.

**Comment by dreirund** [comment]
On Tue, 05 Mar 2024 06:10:44 -0800, Emux ***@***.***>
wrote:

> The application list contains applications that used or are using
> Mapsforge.

So it contains  also applications that do no longer exist or that may
have moved to another domain?

**Comment by devemux86** [comment]
We don't remove apps that may have stopped existing, it's a historical list.

If an app has a new website, we can update the list.
