### ISSUE TITLE
Rotation gesture

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#1495]
Mapsforge now has native map rotation via the API, see https://github.com/mapsforge/mapsforge/issues/7#issuecomment-2147721066.
We can also implement a rotation gesture.

It can be enabled with `TouchGestureHandler.setRotationEnabled`, see [LabelLayerUsingLabelCacheMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LabelLayerUsingLabelCacheMapViewer.java).

**Comment by krzysztofwycislo** [comment]
When can we expect release of rotation feature? Do you have any predictions on that?

**Comment by devemux86** [comment]
New Mapsforge with map rotation can be released the next weeks.
You can already use the snapshot version, see the [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md).

_Next releases will be on JitPack, as Maven has various issues._

---

I will first release a beta of [Cruiser 5](https://github.com/devemux86/cruiser) with the new Mapsforge.

So users can test it in navigation and real conditions and see if any improvements are needed.

**Comment by devemux86** [comment]
Cruiser 5 (Beta) with the new Mapsforge engine and map rotation is available for testing:

- https://github.com/devemux86/cruiser/discussions/610

**Comment by moving-bits** [comment]
Mapsforge with rotation gesture enabled is also available as hidden feature in c:geo's UnifiedMap (see https://github.com/cgeo/cgeo/pull/15984). One thing I regularly stumble upon while using it, is that rotation gesture nearly always changes both rotation and zoom level, which in 99% of the cases is not what I want. Can the gesture handler be enhanced to distinguish between the two gestures?

**Comment by devemux86** [comment]
@moving-bits thanks!

There is an improved rotation gesture implementation in the `rotation` branch.
I will merge it soon.

Rotation and zoom gestures now work independently,
because there were many user complaints in other apps like OsmAnd when they are mixed together.

---

You can already test it in the latest Cruiser 5 (Beta):
- https://github.com/devemux86/cruiser/discussions/610

**Comment by vetoketju** [comment]
Couple things I noticed:
- `MapViewProjection.toPixels` does not seem to yet take rotation into account
- ~~`MapViewPosition.setRotation` does not call notifyObservers~~ -> I see this is already fixed in rotation branch

**Comment by devemux86** [comment]
> MapViewProjection.toPixels does not seem to yet take rotation into account

See how it is used in `TouchGestureHandler` `onSingleTapConfirmed` and `onLongPress`.
Conversions for map rotation or map view center can be made afterwards.

**Comment by devemux86** [comment]
@vetoketju 

> MapViewProjection.toPixels does not seem to yet take rotation into account

See how it is used in `TouchGestureHandler` `onSingleTapConfirmed` and `onLongPress`.
Conversions for map rotation or map view center can be made afterwards.

This is a public API, so we have to be careful with changes.
We could add extra methods to handle rotation, pivot, etc.

**Comment by devemux86** [comment]
@vetoketju 

I added a new `toPixels` method in `MapViewProjection`.
