### ISSUE TITLE
Library for using 2 vector maps in border areas

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#150]
_From [Matthias...@gmail.com](https://code.google.com/u/113150559930951145896/) on July 12, 2011 06:30:40_

Hi there, 

I am an advanced user of the Android mapping application "Locus". Some days ago the developer of this application started working in using your libraries (afaik with your knowledge and cooperation) to get vector maps into the application. The Betas are looking very promising. 
But there is some problem with users living in border areas. It seems that it is not possible to show two vector maps next to each other (for example 'France <-> Germany'). These users would have to switch these maps very often. 
On request of this feature, the developer redirected me to the providers of the library. So I came here to post this issue after I did a fine research if it hadn't been posted before. 

To come to an end... ;)
I would be very happy, if you could make it possible, that developers, which are using your libraries, can implement the feature to show two or even more vector maps next to each other without switching them manually. 

Cheers, berkley

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=150_

**Comment by ludwigb** [comment]
This has been added in 0.5.1.
