### ISSUE TITLE
No Road Numbers on Locus maps created with mapsforge

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#154]
_From [theski...@googlemail.com](https://code.google.com/u/118021930424978106892/) on July 14, 2011 22:04:01_

What steps will reproduce the problem? 1. Open Locus (for Android)
2. Select vector maps for any of UK or France
3. View maps at any zoom level What is the expected output? What do you see instead? Roads should be numbered (e.g. A66, N12) but no numbers are visible What version of the product are you using? On what operating system? I have been told that the maps used by Locus are created using mapsforge.  Locus running on Android 2.2 Please provide any additional information below. I understand that the data included in the vector maps used by locus is defined by mapsforge.  If this is the case, then could I request that road numbers are included in the data.  Otherwise the use of these maps for navigation is severely limited.  I wondered if this is just a locus problem, but I also do not see any road numbers on the sample map images on your home page).  Sorry if my request does not really make sense, but I understand very little about mapping - I am just an ignorant end user!

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=154_

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.
