### ISSUE TITLE
Urban Biker - H10 Cardio Band

### ISSUE THREAD

**Issue by Viaggiatore-Solitario67** [mapsforge/mapsforge#1547]
Yesterday I wanted to pair the Polar H10 heart rate monitor with the Urban biker app... There was no way to pair it. It appears in the list of detected, but nothing appears. Does anyone know how to solve the problem?.

**Comment by devemux86** [comment]
This is the repository of the Mapsforge map library.

For questions about the apps, please write in their forums.
