### ISSUE TITLE
AndroidCanvas constructor not enabling antialiasing/bitmap filtering

### ISSUE THREAD

**Issue by Sublimis** [mapsforge/mapsforge#1572]
EDIT: AwtCanvas is not affected after all, as it enables the filtering in its `setBitmap()`.

Like the title says, those two classes have two constructors each, and while one of those enables antialiasing/bitmap filtering properly, the other does not (constructors are not chained). Is there any reason for such behavior?

On Android, the constructor which skips enabling the filtering is called from the `MapView.onDraw()`. This made it manifest a bug: Running HillshadingMapViewer sample on an actual Android 9 device, the display was very pixelated, both labels and paths. Chaining the constructors so that both enable the filtering made the pixelation bug go away. Curiously enough, pixelation wasn't noticed (maybe the effect was just too small? maybe the system enables filtering by default?) on some other devices, including Android 14.

It seems that such a constructor asymmetry has existed since 2013. Not documented in any way. It's also interesting how on AWT the parameter-less constructor misses to enable the bitmap filtering, while on Android it's the other way around.

Code in question:

https://github.com/mapsforge/mapsforge/blob/45eb484d62cff97d7f6761874261a5ad929cce66/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidCanvas.java#L45-L58

https://github.com/mapsforge/mapsforge/blob/45eb484d62cff97d7f6761874261a5ad929cce66/mapsforge-map-awt/src/main/java/org/mapsforge/map/awt/graphics/AwtCanvas.java#L86-L93

**Comment by devemux86** [comment]
The deprecated `Filter` class was removed for performance reasons and to simplify the graphics API.
Its functions are already available in the much more powerful `ThemeCallback`.

**Comment by devemux86** [comment]
@Sublimis Thanks for the report.

This looks a bit strange and it seems to be so from the beginning.
Android and desktop are expected to work differently in graphics.

Desktop empty constructor does not have graphics object to apply filtering.

So we could chain the Android constructors?
Move the filtering to the other constructor and call it from the empty one?

By the way I have not seen any pixels on Android 5 emulator.
(except my last [hillshading report](https://github.com/mapsforge/mapsforge/pull/1561#issuecomment-2451490677) which was fixed)

Also we have not seen any visible issue with existing Android API in vector maps.
Wondering what is the reason for the current implementation.

**Comment by Sublimis** [comment]
Here are the screenshots before/after:

![screen_filter_incorrect](https://github.com/user-attachments/assets/9ef9b611-5f6d-4818-964d-6b53c3c800f3)![screen_filter_correct](https://github.com/user-attachments/assets/170fdf0c-70ae-4001-b58a-9765f1903b1a)

**Comment by devemux86** [comment]
> Here are the screenshots before/after:

Is it also because of hillshading processing?
Because we have never seem this with normal map rendering.

> Should we create a PR?

With the Android chain? Please, do it.

**Comment by Sublimis** [comment]
> Is it also because of hillshading processing? Because we have never seem this with normal map rendering.

Most definitely not, as no DEM file was used. If you don't believe:

![screen_filter_incorrect2](https://github.com/user-attachments/assets/a5fc3251-2453-46b8-a0cb-86c4896fedcd)

**Comment by devemux86** [comment]
Fixed by #1574.
