### ISSUE TITLE
Minor zoom/pan bugs - pan threshold; zoom centering; multi-touch panning.

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#183]
_From [tdh...@gmail.com](https://code.google.com/u/109865181815441425951/) on October 11, 2011 16:35:34_

Hi, you're doing a great job with mapsforge. I just thought I would document a few of the interface bugs related to zooming and panning I've noticed. They're relatively minor but some are a bit subtle.

1. You have a threshold for panning the map. This is usually considered a bad idea (e.g. Google Maps doesn't do it). I guess the reason is so you can detect taps, but a better way would be to start panning anyway, even if the touch turns out to be a tap.

2. The threshold isn't really a problem, however a big problem is that when you reach the threshold, the map suddenly jumps several mm. I.e. it goes "ah you are panning, and you have moved 5 mm; I will now instantly pan 5 mm". This looks horrible; instead it should ignore the first 5 mm of movement (or whatever it is) and just start panning from the point at which the move threshold was reached.

3. When doing pinch-to-zoom you can't also pan. Lots of implementations of pinch-to-zoom seem to behave like this (e.g. I think even the stock android browser), but it doesn't really feel right, especially on tablets. The Google Maps app behaves correctly in this regard.

4. When you double tap to zoom, it instantly re-centres the map on your tap location and then zooms at the centre, rather than zooming with the tap point as the centre of the zoom... I didn't explain that very well. Do a double tap on the corner of the screen and you will see what I mean.

Anyway, as I said, relatively minor bugs. Keep up the good work!

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=183_

**Comment by devemux86** [comment]
The only remaining issue here is (3) "avoid panning during pinch zoom".
I will look it as part of #616.

**Comment by devemux86** [comment]
Closed via 82a101c5f38d5200afcdab43a19aa870f47bd7a8.
