### ISSUE TITLE
Improve tile scheduling and pre-rendering algorithm

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#189]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on October 16, 2011 22:28:52_

The pre-rendering of tiles should take the movement of the map into consideration. Also tiles on higher and lower zoom levels should be pre-rendered, currently only tiles on the same zoom level are put into the queue.

The weighting function for the tile scheduling also needs to be improved as it does not yet take into consideration whether a tile is visible or not.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=189_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
