### ISSUE TITLE
Handle recursive relations 

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#195]
_From [SakirS...@gmail.com](https://code.google.com/u/105542850597277139642/) on October 23, 2011 19:35:03_

This issue is related with issue190 . Here i will describe how to solve this issue.

In OSM you can define nested/recursive relations. Each relation has several outer and inner ways, which can form a multi polygon. Now each inner way of a relation can be also a outer way of another relation. And each outer way could be possible an inner way of another relation. 

We have to hierarchically merge those nested relation to draw the resulting multi polygon in the right order.

When it is done right we do not need to drill any holes in to multi polygons anymore. Only if the outer way tag and the inner way tag are the same we need to drill holes in our multi polygon. Otherwise we just render the multi polygon in respect of its hierarchy. First the outer way then the inner way. And for each inner way which is an outer way for another multi polygon we do the same.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=195_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
