### ISSUE TITLE
multipolygon inner polygon isn't subtracted properly if not tagged as outer

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#229]
_From [mirarki...@gmail.com](https://code.google.com/u/114693895068332180105/) on January 14, 2012 23:02:11_

Allegedly, you should be able to have multipolygons where the inner polygon does not share the same tagging as the outer polygon, and the inner polygons are still subtracted.

for instance:

relation: multipolygon
outer polygon: building=yes
inner polygon: -

should still be rendered as a building with holes. 

relation: multipolygon building=yes
outer polygon: -
inner polygon: -

should also be rendered as a building with holes. (But isn't in potlach 2.)

relation: multipolygon
outer polygon: building=yes
inner polygon: landuse=forest

should be rendered as a building with a forest inside.

When testing, only

relation: multipolygon
outer polygon: building=yes
inner polygon: building=yes

rendered correctly.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=229_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
