### ISSUE TITLE
overlaping rules when using zoom-min and zoom-max

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#234]
_From [dido...@gmail.com](https://code.google.com/u/110035260582331699103/) on January 18, 2012 20:21:04_

...theme snippet: 
<rule e="node" k="natural" v="peak" zoom-min="12" zoom-max="14">
  <caption k="ele" dy="20" font-style="italic" font-size="10" fill="#FF0000" stroke="#ffffff" stroke-width="2.0" />
</rule>
<rule e="node" k="natural" v="peak" zoom-min="14" zoom-max="16">
  <caption k="ele" dy="20" font-style="italic" font-size="15" fill="#00FF00" stroke="#ffffff" stroke-width="2.0" />
</rule>
<rule e="node" k="natural" v="peak" zoom-min="16">
  <caption k="ele" dy="20" font-style="italic" font-size="20" fill="#0000FF" stroke="#ffffff" stroke-width="2.0" />
</rule>

in this case the color and the size of the elevation label is unpredictable at zoom 14 and zoom 16 and causing random colored labels on the map

3.0.0-SNAPSHOT

in PositiveRule.java and NegativeRule.java lines with (2 matches in both files)

this.zoomMax >= zoomLevel    should be replaced with    this.zoomMax > zoomLevel

...also this allow non integer zoomlevels for vector maps in future

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=234_

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.
