### ISSUE TITLE
Do not filter way points on high zoom levels

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#235]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 22, 2012 16:37:26_

The map-writer filters out way points by using the Douglas-Peucker algorithm. This can lead to bad geometries in particular when viewing the map on high zoom levels (> 16). The attached screenshot demonstrates an example, where the filtering of way points was done too aggressively. The original map can be seen here: http://www.openstreetmap.org/?lat=52.5144&lon=13.35019&zoom=17&layers=O

**Attachment:** [way_point_filtering_bug.png](http://code.google.com/p/mapsforge/issues/detail?id=235)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=235_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
