### ISSUE TITLE
Add support of other relation types than multipolygon

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#245]
_From [m.zd...@gmail.com](https://code.google.com/u/105693236104289924215/) on February 02, 2012 21:23:55_

This feature is necessary to display maps with eg. public transportation or bicycle / hiking routes.

My personal ideas:

Fast and simpler solution could be to copy all properties from the relation to all its members. If some member is in multiple relations with the same key but different value, then values should be joined with semicolon, sorted alphabetically.

Also then rules in rendertheme should support filtering just be one element in the semicolon separated list (maybe this is possible already).

Relation tags should be also added to its members as key:value=yes to support different way of filtering. Roles could be set as for example relation_role=role1;role2 and also as relation_role:role1=yes and relation_role:role2=yes.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=245_

**Comment by kolesar-andras** [comment]
I also miss this feature.

**Comment by devemux86** [comment]
Currently only [multipolygon](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/model/TDRelation.java#L90-L98) relations are recognized.

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
