### ISSUE TITLE
MapController zoomToSpan missing

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#250]
_From [bennob...@gmail.com](https://code.google.com/u/113641033745186309278/) on February 16, 2012 12:57:17_

I am missing the function 
MapController.zoomToSpan(int LatSpan, int LonSpan ) 

What version of the product are you using? 
0.2.4

Is there any intension to implement this in the next release?

Thanks Benno

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=250_

**Comment by schildbach** [comment]
@mapsforge Wouldn't this be a candidate for the MapViewPosition class? Just because there is not MapController any more doesn't mean this useful method couldn't be implemented elsewhere.

**Comment by ludwigb** [comment]
Pull requests welcome.

**Comment by devemux86** [comment]
The functionality is already there, see [ZoomToBounds](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/ZoomToBounds.java) in Samples.
But we can simplify the API more.

**Comment by schildbach** [comment]
@devemux86 This works nicely, thanks.

**Comment by devemux86** [comment]
@schildbach if you like you can post a PR with a simplified API, ```MapViewPosition``` is a nice candidate to host it.
