### ISSUE TITLE
Make the tag configuration file of the map-writer more flexible

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#257]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on February 22, 2012 19:23:16_

Say for example one wants to write all ways with a building tag into the map file. With the current implementation that is almost impossible as each tag (key=value) has to be added separately.

A much better approach would be to allow for wildcard characters, such as "*" which matches any value (this can already be done in render-theme files). I also propose to add a syntax for multiple values, like demonstrated in the following example:

<tag key="building" value="*" />
<tag key="foo" value="bar|bao|baz" />

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=257_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.

And can always use [TagTransform](https://wiki.openstreetmap.org/wiki/Osmosis/TagTransform) Osmosis plugin before map-writer.
