### ISSUE TITLE
Make the file parameter of the map-writer mandatory

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#262]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on March 04, 2012 13:07:25_

If no file name is specified, the map-writer will use "mapsforge.map" as default for the newly created output file - which is not a very meaningful name. Therefore it would be better to make the parameter mandatory so that the user must always specify a name.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=262_

**Comment by ludwigb** [comment]
I do not think this is worth fixing. Having this optional makes the command line a bit easier for beginners.

**Comment by devemux86** [comment]
Additionally I followed the same mechanism in POI writer too.
