### ISSUE TITLE
Filter map objects on lower zoom levels based on their size

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#268]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on March 11, 2012 15:54:58_

Currently the map-writer assigns objects to zoom levels purely based on their tags. Very often this leads to large visual differences when zooming in or out by only one zoom level. Of course some objects have to be filtered out so that the map renderer can still handle the amount of data. But defining a trade-off between performance and visual quality is difficult.

In order to improve this situation, we should filter objects not only based on their tags but also on their geographical size and/or complexity. On lower zoom levels, small polygons and ways can easily be removed as they do hardly contribute to the visual quality of the rendered map. This would allow us to reduce the amount of data while still rendering all visually important objects.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=268_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
