### ISSUE TITLE
Add an offline POI search component

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#270]
_From [Oleg.Baidalka](https://code.google.com/u/Oleg.Baidalka/) on March 13, 2012 17:03:05_

Provide Geocoding feature:
- Search for POI info (lat, lon, name tags)
- Search for Address (lat, lon, full-name)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=270_

**Comment by devemux86** [comment]
We revived the POI Search component, see #728.
