### ISSUE TITLE
Allow for custom tags with arbitrary values in the map file

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#276]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on March 24, 2012 20:25:06_

The current version 3 of the binary map file format allows only for a fixed set of tags with an arbitrary value. Such tags are name, ele (for POIs), addr:housenumber. Custom tags with arbitrary values (for example "wikipedia=...", see http://wiki.openstreetmap.org/wiki/Key:wikipedia for more details) cannot yet be stored in the map file. The next version of the file format should support this.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=276_

**Comment by devemux86** [comment]
Should be possible now via #1006.
