### ISSUE TITLE
Add a metadata file to the download server

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#316]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on May 20, 2012 11:24:09_

The download server should include an auto-generated XML file containing metadata about all available map files. Applications could then fetch and parse this file in order to check for updates, display a tree with the available regions and files to the end user, etc. Right now the only way to achieve this is parsing the directories via HTTP, which is a PITA. The metadata file could also include the bounding box for each map file, the map start position, an MD5/SHA1 checksum, etc.

Just for the record: this issue was triggered by a recent discussion on our mailing list ( https://groups.google.com/group/mapsforge-dev/browse_thread/thread/880aeb45868c5c85 ).

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=316_

**Comment by devemux86** [comment]
Mapsforge server is not meant to be used directly by third-party apps, but only from users to download maps.
