### ISSUE TITLE
Provide a low detail world map

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#319]
_From [h...@flashlight.de](https://code.google.com/u/105864613744213469970/) on May 27, 2012 22:20:10_

How about providing a low detail world map with small size?

It should contain all country borders plus their major cities.

If you do not want to provide that kind of map could you 
give some hint how to produce something like this in a
efficient way?

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=319_

**Comment by andreynovikov** [comment]
Can you explain briefly how you managed to create such a map? I've tried to create my own one using only sea and land polygons and got 18MB file but yours is only 3MB.

**Comment by devemux86** [comment]
@andreynovikov see also here:
https://groups.google.com/d/msg/mapsforge-dev/uaZM4NIydus/q4kOH7ibJtwJ

**Comment by devemux86** [comment]
By the way, since we have now a low detail world map, I'm closing this issue.

**Comment by devemux86** [comment]
The process for creating a low detail world map is explained here:
https://groups.google.com/forum/#!topic/mapsforge-dev/1PzOYvFs8sE

**Comment by DrMarkEy** [comment]
I would like to use the world.map file with the major highways and borders. Unfortunately the attachments seem to be broken due to the migration from google code to github. Could someone provide me a link to this file?

**Comment by devemux86** [comment]
The `world.map` containing land polygons is provided in our [server](http://download.mapsforge.org/maps/world/) with creation instructions [here](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md#world-map).

**Comment by gcPhil** [comment]
> The `world.map` containing land polygons is provided in our [server](http://download.mapsforge.org/maps/world/) with creation instructions [here](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md#world-map).

What [DrMarkEy](https://github.com/DrMarkEy) was searching is the `world.map` with land polygons, borders and major Highways from [this post](http://code.google.com/p/mapsforge/issues/detail?id=319#hc6). Unfortunately the attachment seem to be broken due to the migration from google code to github.
