### ISSUE TITLE
Missing country map files on FTP server

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#320]
_From [f3lisca...@gmail.com](https://code.google.com/u/107917587901380425054/) on June 01, 2012 19:10:24_

Related: Issue 127 ( https://code.google.com/p/mapsforge/issues/detail?id=127 )

There are still version 0.3.0 map files for some European countries missing on the ftp server. On first glance I found Denmark and Belgium missing. There might be more. I guess this is not high priority, but as developers are starting to transition away from 0.2.4 it would be nice to have them all.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=320_

**Comment by TofLaBeuze** [comment]
Hi,
Corsica is still missing on http://download.mapsforge.org/maps/europe/france/ , though the polygon file exists in folder ?

**Comment by devemux86** [comment]
Actually we have far less built France regions than their poly and declarations in the config file.

Also I see both ```centre-val-de-loire.map``` and ```centre.map```.

Ludwig can you have a look at it?

**Comment by ludwigb** [comment]
Removed the centre.map (it was an old map, our scripts just create new
ones, but do not eliminate old ones).

Added Corsica, will be made at next iteration.

The other French regions in the example config actually lie outside the
Europe polygon, so this would never work. If someone is really interested
in them, please supply a config file that extracts from planet.osm....

Ludwig

**Comment by devemux86** [comment]
You mean their poly are wrong?

**Comment by devemux86** [comment]
I pushed some changes on map-creator repository:

- Rename back France centre to its OSM default.
- Move France 'outside Europe regions' to inherit from planet osm. I tried to make them build inside the ```europe/france``` folder. Ludwig will this work?
- Update the related polygons in case we had errors.

**Comment by ludwigb** [comment]
Building the territories from the planet.osm should work. I put that on the
server and we will see.

Thanks

**Comment by devemux86** [comment]
Only thing that worries me is that playing directly with planet osm can have speed impacts.
We could improve it using the related continent pbf, though then not sure about the target folders.
