### ISSUE TITLE
Right to left texts on map displayed in left to right

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#328]
_From [ali.behz...@gmail.com](https://code.google.com/u/108835889714080735635/) on June 23, 2012 06:06:39_

In right to left languages(Persian, Arabic, hebrew and some other languages), right to left texts (names of the map elements) displayed in wrong direction (LTR). The other problem is that in this languages, the characters join together to create a word. What steps will reproduce the problem? 1. This problem is already exists in Iran map in ftp.mapsforge.org What is the expected output? What do you see instead? I attached a photo to explain the issue. What version of the product are you using? On what operating system? Please provide any additional information below. Take a look at these: http://en.wikipedia.org/wiki/Bi-directional_text http://www.fribidi.org/

**Attachment:** [mapsForge_RTL_issue.png](http://code.google.com/p/mapsforge/issues/detail?id=328)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=328_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
