### ISSUE TITLE
Platte Carree Projection Support

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#333]
_From [kendrick...@gmail.com](https://code.google.com/u/106474584108262476089/) on July 16, 2012 17:33:16_

Is is possible to work in how to modify the library to support Platte Carree? Or if not, any points in the right direction? Or anything on how hard it might be?

I found the MercatorProjection file, so I know I should write one for Platte Carree..

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=333_

**Comment by ludwigb** [comment]
To be honest, this is very unlikely to happen unless anyone volunteers to do this and supplies a full patch.
