### ISSUE TITLE
Map doesn't display country borders after conversion

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#339]
_From [adamno...@gmail.com](https://code.google.com/u/105564336150475199748/) on July 24, 2012 09:15:16_

Converting any administrative.osm to .map results in a file that doesn't display borders properly. For example, converting germany.administrative.osm to .map resulted in the following file. I am not sure, what I am doing wrong.

**Attachment:** [germany.png](http://code.google.com/p/mapsforge/issues/detail?id=339)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=339_

**Comment by kivsiak** [comment]
I have some problem. But a looks like markdown in this thread broken. Could you repost your solution?

**Comment by devemux86** [comment]
With cc838d7c0115ca81b3c0ce5d8d2f913cf14f7345 I pushed on dev a fix enabling in ```tag-mapping``` the use of [Tag:boundary=administrative](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative).

We can use this tag-mapping in server.

**Comment by devemux86** [comment]
For reference there is relative discussion in forum:
https://groups.google.com/forum/#!topic/mapsforge-dev/kPhwdaRpv7g
