### ISSUE TITLE
MapFileWriter-SNAPSHOT: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#362]
_From [starous6...@gmail.com](https://code.google.com/u/100862657324016620498/) on October 18, 2012 23:33:16_

What steps will reproduce the problem? 1. Start command:
env JAVACMD_OPTIONS="-server -Xmx2500M" ~/bin/osmosis/bin/osmosis --read-pbf file=~/MKGMAP/osm/NOR-OSM-SRTM.osm.pbf --mw file=./NOR-SRTM.map type=hd tag-conf-file=./tag-mapping-srtm.xml

where:
NOR-OSM-SRTM.osm.pbf is Norwegian OSM map merged with map with elevation contour generated from SRTM
tag-mapping-srtm.xml is attached file

2. After lot of hours this command finishes with this error message:
...
java.lang.OutOfMemoryError: GC overhead limit exceeded
...

3. If I suppress this type of error by -XX:-UseGCOverheadLimit option, I get another error:
...
INFO: written 70.0&#37; of sub file for zoom interval index 2
18.10.2012 10:13:55 org.mapsforge.map.writer.MapFileWriter processTile
WARNING: error in parallel preprocessing of ways
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
...
The full log of this latest MapFileWriter run is attached (NOR.log file) What is the expected output? What do you see instead? I expect correct MAP file, but I got only some partial result and some error messages... What version of the product are you using? On what operating system? I am using Osmosis Version 0.40.1-101-g6dd9f48 and SNAPSHOT from SVN (downloaded and compiled at 10/12/2012).
I am using SVN version because I was probably affected by issue 354 (352) - at least I got the same error messages when I started "official release" MapFileWriter with my version of osmosis.
All is running on more or less standard Debian Squeeze Linux. Please provide any additional information below. This problem looks to appear only on Norwegian map - I have successfully converted another countries with the same command style and merged OSM-SRM maps, some are bigger than Norwegian, e.g. Germany, Austria.
But also on these countries I had some small troubles - with previous version of osmosis and "official release" MapFileWriter there was sufficient to allocate 512MB for heap. With newest versions I need to allocate approx. 1024MB even if type=hd option is specified.

**Attachment:** [tag-mapping-srtm.xml NOR.log](http://code.google.com/p/mapsforge/issues/detail?id=362)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=362_

**Comment by devemux86** [comment]
If you use ```type=ram``` then you need a lot of memory for large regions (specially with complex coastline):
```-XX:PermSize=256m -XX:MaxPermSize=256m -Xms8g -Xmx8g -server```

Or else you can try ```type=hd``` for slower but more safe results.

I'm closing this to continue such questions on mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
