### ISSUE TITLE
 Android 4.2: java.lang.RuntimeException: Buffer not large enough 

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#370]
_From [sashi...@gmail.com](https://code.google.com/u/113042979075099975442/) on November 13, 2012 18:50:14_

What steps will reproduce the problem? 1. Install advanced map viewer on android 4.2
2. Run App and open a map. 
3. See exception What is the expected output? What do you see instead? should work, but see exception:
E/AndroidRuntime( 3178): FATAL EXCEPTION: MapWorker
E/AndroidRuntime( 3178): java.lang.RuntimeException: Buffer not large enough for pixels
E/AndroidRuntime( 3178):        at android.graphics.Bitmap.copyPixelsToBuffer(Bi tmap.java:381)
E/AndroidRuntime( 3178):        at org.mapsforge.android.maps.mapgenerator.InMemoryTileCache.put(InMemoryTileCache.java:142)E/AndroidRuntime( 3178):        at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.jaa:77)
E/AndroidRuntime( 3178):        at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
W/ActivityManager(  390):   Force finishing activity org.mapsforge.applications.android.advancedmapviewer/.AdvancedMapViewer What version of the product are you using? On what operating system? 0.3.0 Please provide any additional information below. running on a galaxy nexus with 4.2

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=370_

**Comment by zebenyeste** [comment]
Hello weidig.m...@gmail.com, i have the same problem on a real device. When i try to open the map throws the error. Could you send to me the .jar file? (zeben@crokis.com) Because i can't see your email, i really appreciate it, thanks.
