### ISSUE TITLE
Closed outer ways of multipolygons are reported as invalid and skipped

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#431]
_From [morav...@gmail.com](https://code.google.com/u/115730355087327916966/) on May 15, 2013 23:04:02_

What steps will reproduce the problem? run osmosis with attached file (it contains just the two problematic multipolygons - ways 38321616 and 38321623): 
osmosis --rx missing.osm --mw file=test.map bbox=47.726460,16.828400,49.618600,22.570510 What is the expected output? What do you see instead? The multipolygons (protected area boundaries) should be included, but they are dropped. Previous comments in project's google group concerning this issue indicated that the ways are not closed and thus not forming the boundary, but as far as I can tell from the data is not true in this case. What version of the product are you using? On what operating system? mapsforge-map-writer-0.3.1-SNAPSHOT-jar-with-dependencies.jar
in current git snapshot (rewrite), 20130515.201043

Linux, x86, both Java 1.7 (OpenJDK) and Java 1.6 (Sun) Please provide any additional information below. The messages generated during the map file creation look as follows:

ODP. org.mapsforge.map.writer.util.GeoUtils toJtsGeometry
WARNING: outer way of multi polygon is not a polygon, skipping it: WAY_ID

e.g.

V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 10.0&#37; of sub file for zoom interval index 2
V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 20.0&#37; of sub file for zoom interval index 2
V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.util.GeoUtils toJtsGeometry
WARNING: outer way of multi polygon is not a polygon, skipping it: 38321616
V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 30.0&#37; of sub file for zoom interval index 2
V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.util.GeoUtils toJtsGeometry
WARNING: outer way of multi polygon is not a polygon, skipping it: 38321623
V 15, 2013 10:53:01 ODP. org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 40.0&#37; of sub file for zoom interval index 2

**Attachment:** [missing.osm](http://code.google.com/p/mapsforge/issues/detail?id=431)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=431_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
