### ISSUE TITLE
Map Tiles completely distorted after panning/zooming on Sony Xperia

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#440]
_From [c.step...@wwu.de](https://code.google.com/u/106226714321690839280/) on July 06, 2013 18:27:35_

I am using mapsforge 0.3.0 to show a map together with a way overlay. I am facing the problem that the map is completely distorted as soon as I start zooming or panning (see attachments). Initially the map is being displayed correctly. This issue seems only to show up with the device Sony Xperia (4.1.2). The map (the same source code) runs perfectly on Samsung Galaxy Nexus (4.2.2), HTC Nexus One (2.3.3), HTC Desire S (2.3.5) and Samsung Nexus S (4.1.2).

The source code of my map is online at: https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.app/src/org/envirocar/app/activity/Map.java

**Attachment:** [Screenshot_2013-07-06-18-14-20.png Screenshot_2013-07-06-18-14-44.png](http://code.google.com/p/mapsforge/issues/detail?id=440)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=440_

**Comment by ludwigb** [comment]
The mentioned distortion appears when hardware acceleration is set in the manifest, but apparently only on 4.1 devices. 
It can also be triggered on 4.1 devices regardless of the hardware acceleration setting in the manifest by selecting Force GPU Rendering in the Developer Settings menu.

**Comment by devemux86** [comment]
Could be the [unsupported drawing operations](http://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported) with hardware acceleration in our calls.
(Android 4.1 is API level 16)
