### ISSUE TITLE
closed oneways wrong direction

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#458]
_From [hla...@gmail.com](https://code.google.com/u/116260628383584123943/) on October 18, 2013 14:38:39_

Hello

It seems there is some problem with closed oneways. Closed oneway is always on clockwise direction, no matter what is the direction in original data. In the attchements there is source xml file and output .map file.
I used osmosis 0.40.1 and current mapsforge-map-writer-0.3.1-SNAPSHOT-jar-with-dependencies.jar from git.

And here are examples of such closed oneways (these should be counter clokwise): http://www.openstreetmap.org/browse/way/98568793 http://www.openstreetmap.org/browse/way/8095639 Regards

Hlad

**Attachment:** [oneway.osm oneway.map](http://code.google.com/p/mapsforge/issues/detail?id=458)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=458_

**Comment by ludwigb** [comment]
The latest writer build has this change, 
http://ci.mapsforge.org/job/dev/lastSuccessfulBuild/artifact/mapsforge-map-writer/build/libs/mapsforge-map-writer-dev-SNAPSHOT.jar

This fixes the issue, but might have side effects that I have not thought about or seen. Please test and report.

**Comment by ludwigb** [comment]
Since there has been no feedback, I assume that the issue has been fixed (in reality, no one has really tested it of course).
