### ISSUE TITLE
blue titles of POI

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#460]
_From [d...@csform.com](https://code.google.com/u/114437759336977969381/) on November 01, 2013 14:11:35_

I'm making new style to use in my application. 
For testing i use AdvancedMapViewer.

But there is problem, in some zoom levels map render some POI's titles which i can't remove with .xml style.

The sceenshot in attachment is taken with empty xml theme.

Please help

**Attachment:** [Screenshot_2013-11-01-14-02-23.png](http://code.google.com/p/mapsforge/issues/detail?id=460)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=460_

**Comment by devemux86** [comment]
I'm closing this, if you still have any questions please report them in mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
