### ISSUE TITLE
wrong rendering of waterway=canal, tunnel=yes, layer=*

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#465]
_From [rdzid...@gmail.com](https://code.google.com/u/108270143277378192865/) on December 04, 2013 23:16:28_

Consider http://www.openstreetmap.org/way/37712897 It is rendered like waterway=canal in areas without landuse=*, and not at all in areas with some landcover.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=465_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
