### ISSUE TITLE
Setting an origin for symbols

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#472]
_From [tartami...@gmail.com](https://code.google.com/u/115560783500310858875/) on December 26, 2013 16:31:21_

I'd like to be able to set an arbitrary origin for symbols. Ideally it could be expressed as percentage from a given corner of the surrounding box, but even a crude system that refers to 9 points would be probably enough (I mean TL for top-left, TM for top-middle and so on).

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=472_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
