### ISSUE TITLE
SwingMapViewer with multiple maps 

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#513]
_From [th.rit...@gmx.at](https://code.google.com/u/108458371057877793761/) on August 14, 2014 21:15:29_

What steps will reproduce the problem? 1. Use more than one map-file as arguments
2. Start program 
3. Only some tiles are displayed 

-> using dev-branch (Works with master branch) bd9f9b564d788357a9ba0790ffe2573fa4f37692 If only using 1 map file - all things work as expected.

Also some Messages are printed:

Aug 14, 2014 9:11:09 PM org.mapsforge.map.layer.cache.InMemoryTileCache put
WARNING: overwriting cached entry: org.mapsforge.map.layer.renderer.RendererJob@afe4348f
Aug 14, 2014 9:11:10 PM org.mapsforge.map.layer.cache.FileSystemTileCache put
WARNING: overwriting cached entry: 9/275/167

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=513_

**Comment by devemux86** [comment]
It was a matter of using separate cache per map.

With ef8d70bcf4fa176ce59972a6f34c0067e66d26d1 I pushed on dev the fix.
