### ISSUE TITLE
Train stations and roundabouts are dropped by mapsforge-map-writer

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#526]
_From [yst...@gmail.com](https://code.google.com/u/106774087836489148242/) on September 23, 2014 10:33:07_

What steps will reproduce the problem? 1. Obtain an OSM with train stations (building=train_station, railway=station) or roundabouts (junction=roundabout, highway=*).
2. Convert the OSM to MAP using mapsforge-map-writer. What is the expected output? What do you see instead? The train stations and roundabouts should be in the output MAP file, but they are dropped by the writer. What version of the product are you using? On what operating system? Latest master revision - 25b5f2d0d6d8, on Linux. Please provide any additional information below. The problem should be due to the OSMUtils.isArea(way) checking in TDWay.java. Removing the checking can solve the issue.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=526_

**Comment by benchuk** [comment]
Hi, on last version I still do not see roundabouts. I have tried several render styles (original one and a few others) and still could not see roundabouts - is this a know issue?

**Comment by devemux86** [comment]
Can you mention an area coordinates & zoom level and the specific elements that don't appear ?

**Comment by benchuk** [comment]
Any zoom level or location.
Attached is the rendering xml.
[customrender.xml.zip](https://github.com/mapsforge/mapsforge/files/90695/customrender.xml.zip)

Thanks.

**Comment by devemux86** [comment]
Is this the `Elevate` render theme from OpenAndroMaps?
Are you trying with OpenAndroMaps maps?

**Comment by benchuk** [comment]
No, just mapsforge control on a custom android app, downloaded a map file, and tried with custom and original xml renders, except for roundabout - everything is ok, render file affects the actual rendering -(colors visibility of object and etc.)....

**Comment by devemux86** [comment]
To identify the problem we need specific instructions.
Map file + render theme, exact coordinates + zoom level and which elements having the issue.

It's important to mention that not all map files are the same.
They're often built based on different `tag-mapping`, contain probably transformed tags and usually play well with their accompanied render themes.

e.g. the above render theme is OpenAndroMaps specific, destined for those maps.
So you may need to ask the same question in its [forum](http://www.openandromaps.org/en/oam-forums) too, so that Christian and Tobias can answer for their maps / render themes construction better.

**Comment by devemux86** [comment]
Checking our default `tag-mapping`, the only roundabout rule I see is [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml#L11) (poi from zoom 17).

And in our two render themes ([Osmarender](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/resources/osmarender/osmarender.xml) & [RenderThemeV4](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml)) there aren't any render rules for that.

**Comment by ludwigb** [comment]
I believe this issue was fixed a long time ago (see the history of this
issue). Are you sure the mapsforge version being used is up-to-date?

**Comment by benchuk** [comment]
This is the map file: http://download.mapsforge.org/maps/asia/israel_and_palestine.map
Location: 32.784908, 34.999621 for example.
Render theme is the original one from the repository.
