### ISSUE TITLE
Unexpected zoom out while using multi-touch to zoom in

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#527]
_From [yst...@gmail.com](https://code.google.com/u/106774087836489148242/) on September 23, 2014 11:07:53_

What steps will reproduce the problem? Use two fingers to zoom in, but just touch the screen for a short time. What is the expected output? What do you see instead? Expect the map to zoom in, or keep the existing zoom level if the gesture is not complete, but the map will zoom out sometimes. What version of the product are you using? On what operating system? Latest master revision - 25b5f2d0d6d8. Please provide any additional information below. Issue 60 added a feature "multi-touch tap to zoom out". https://code.google.com/p/mapsforge/issues/detail?id=60 Suggest to provide a method to disable this behaviour, as this behaviour can be annoying sometimes.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=527_

**Comment by devemux86** [comment]
This issue is fixed with latest commits in #616.
