### ISSUE TITLE
Difficult to avoid NPE if setOnTouchListener on MapView

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#529]
_From [yst...@gmail.com](https://code.google.com/u/106774087836489148242/) on September 23, 2014 11:57:00_

What steps will reproduce the problem? 1. setOnTouchListener on MapView to handle some custom gestures involving two fingers.
2. Use more than two fingers. Events for the 3rd/4th/... fingers will be passed to mapsforge. What is the expected output? What do you see instead? Expect that the custom gesture works properly without issue, but NPE may occur sometimes. What version of the product are you using? On what operating system? Latest master revision - 25b5f2d0d6d8. Please provide any additional information below. The NPE occurs as an invalid pointerIndex is passed to motionEvent.getX() in TouchEventHandler.
Attached a version which will check whether the pointerIndex is valid or not first.

**Attachment:** [TouchEventHandler.java](http://code.google.com/p/mapsforge/issues/detail?id=529)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=529_

**Comment by ludwigb** [comment]
Is this still an issue?

**Comment by devemux86** [comment]
Indeed Mapsforge gesture system was rewritten in dev branch, so any related issue has to be examined again if it's valid.

**Comment by ystsoi** [comment]
NPE cannot be reproduced using three fingers for the new gesture system in dev branch, even if setOnTouchListener on MapView. Although there will be a minor issue (with setOnTouchListener) if I use three fingers in a special way, this is not significant.

**Comment by ludwigb** [comment]
>
> if I use three fingers in a special way, this is not significant.


like what special way? Maybe it is something that can be easily fixed.

**Comment by ystsoi** [comment]
The issue does not exist if setOnTouchListener is not used.

Steps:
1) Touch the map with the first finger, my listener returns FALSE for the down event.
2) Touch the map with the second finger, my listener returns TRUE for the down event.
3) Touch the map with the third finger, my listener returns TRUE for the down event.
4) Lift the first and second fingers, my listener returns TRUE for the up events.
5) Move the third finger, my listener returns FALSE for the move event.
And then the map will shift, such that the third finger seems moved to the center of the three fingers.

**Comment by devemux86** [comment]
Thanks for the feedback.

It's worth mentioning that we don't use anymore multiple pointer [tracking](http://developer.android.com/training/gestures/multi.html), but relying on Android less complex gesture recognition for handling the various events.

**Comment by ludwigb** [comment]
So, I guess the answer is that this is not an issue anymore?

**Comment by devemux86** [comment]
(I didn't checked) but I understand that the issue arises if an external touch listener is attached.

**Comment by ystsoi** [comment]
Yes, "Difficult to avoid NPE if setOnTouchListener on MapView" is not an issue anymore. In fact, the 5 steps above will produce NPE in master branch, but they just cause minor issue in dev branch.

**Comment by ludwigb** [comment]
I guess we can close this. I suggest that if the minor issue reported needs fixing to open a new issue as with the rewrite this has nothing to do anymore with this one.
