### ISSUE TITLE
Wrong map positioning just after zoom

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#537]
_From [art.v.se...@gmail.com](https://code.google.com/u/102762708964646108759/) on October 30, 2014 12:49:14_

What steps will reproduce the problem? 1. Zoom a map.
2. Drag it to some new position quickly (before the first frame for the new zoom level will be finished). What is the expected output? What do you see instead? The map is drawn in the wrong place, not in the place it should be. After a while it becomes normal. What version of the product are you using? On what operating system? It takes place in 5.0.0_rc1 both under PC (Windows 7 x64) and Android. Please provide any additional information below. It looks like in FrameBufferController.adjustFrameBufferMatrix(...) should be 

long mapSize = MercatorProjection.getMapSize(mapViewPosition.zoomLevel, model.displayModel.getTileSize());

instead of 

long mapSize = MercatorProjection.getMapSize(mapPositionFrameBuffer.zoomLevel, model.displayModel.getTileSize());

At least in my case it removes the problem.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=537_

**Comment by devemux86** [comment]
I think this situation is resolved in latest dev with the touch gestures refactoring.
See #616 and #626.
