### ISSUE TITLE
MyLocationOverlay not showing in mapview

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#538]
_From [safeer....@gmail.com](https://code.google.com/u/103651151910810952787/) on October 31, 2014 04:49:17_

What steps will reproduce the problem? I have added my location overlay as,

Drawable myLocationMarker = this.getResources().getDrawable(R.drawable.person);
        Bitmap bitmap = AndroidGraphicFactory.convertToBitmap(myLocationMarker);
        myLocationOverlay = new MyLocationOverlay(this.getApplicationContext() ,mapView.getModel().mapViewPosition, bitmap);
        myLocationOverlay.setSnapToLocationEnabled(true);
        myLocationOverlay.enableMyLocation(true);
        mapView.getLayerManager().getLayers().add(myLocationOverlay);

map loaded with no issues but there is no view of my location, so i send the location coordinates through DDMS then the app crashes with the below stack trace,

10-31 03:41:17.893: E/AndroidRuntime(3007): FATAL EXCEPTION: LayerManager
10-31 03:41:17.893: E/AndroidRuntime(3007): java.lang.NullPointerException
10-31 03:41:17.893: E/AndroidRuntime(3007): 	at org.mapsforge.map.layer.overlay.Circle.draw(Circle.java:69)
10-31 03:41:17.893: E/AndroidRuntime(3007): 	at org.mapsforge.map.android.layer.MyLocationOverlay.draw(MyLocationOverlay.java:141)
10-31 03:41:17.893: E/AndroidRuntime(3007): 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:94)
10-31 03:41:17.893: E/AndroidRuntime(3007): 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

Any help is much appreciated.

Thanks,

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=538_

**Comment by yihong-lco** [comment]
Hi, I also faces exactly the same bug for the NullPointerException on MyLocationOverlay. Did you manage to solve it?

**Comment by devemux86** [comment]
Let's continue that discussion in mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
