### ISSUE TITLE
maven build with java 8

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#540]
_From [syt...@gmail.com](https://code.google.com/u/100793062571381824928/) on November 04, 2014 18:44:41_

Its need to add <additionalparam>-Xdoclint:none</additionalparam> in maven-javadoc-plugin to build maven project with java 8. http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-javadoc</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
                        <configuration>
                            <additionalparam>-Xdoclint:none</additionalparam>
                        </configuration>
					</execution>
				</executions>
			</plugin>

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=540_

**Comment by devemux86** [comment]
I'm closing this as the recommended Java version for building Mapsforge is Java 7, because of Android max Java 7 compliance level.
