### ISSUE TITLE
Introduce map zoom factor for devices with xhdpi displays

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#543]
_From [christia...@gmx.at](https://code.google.com/u/102625142710619456857/) on November 10, 2014 07:41:00_

Relates to:
mapsforge 0.3 used in c:geo to display pre-rendered map tiles

Problem:
Some Android devices have a very high pixel density. For example my Xperia Z has 443ppi.
Mapnik-rendered maps have a constant pixel height for all labels. For example a street name is ~6pixels in height.
As a result, labels are often so small they are not readable any more. For example a street name on my Xperia Z is smaller than 0.4mm

Proposal:
Introduce a customizable zoom factor. All map tiles are magnified by that factor. (A similar feature can be tried out in Locus under Map Options/Advanced Settings)

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=543_

**Comment by jonas-koeritz** [comment]
> _From [devemu...@gmail.com](https://code.google.com/u/109528871084914010993/) on November 09, 2014 23:35:17_
> 
> If you are referring to the online raster tile sources that Mapsforge supports, then at latest version you can again play with the tile size so that the pre-rendered bitmap tiles that come from servers appear larger (and blurry).
> 
> Emux

How is this done? I am not able to find any documentation on this? I'm currently struggling with a tiny unreadable map on a Pixel 2 XL using Mapsforge 0.11.

**Comment by devemux86** [comment]
See [DownloadLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadLayerViewer.java#L52) sample, can set fixed tile size or use the default scaled one.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
