### ISSUE TITLE
Rendertheme V4 stylemenu changes and persistent cache

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#560]
It would be good to find a way to identify when changes have been applied to the style menus with Rendertheme V4 to purge a persistent cache (otherwise of course stale tiles will be served). 

In https://github.com/mapsforge/mapsforge/commit/30e26508cd7076f6d6b1e07fed4c0d4130dc430c the tile caches of the Samples app are always purged whenever the settings change, but this is unspecific to the keys that changed. 

Changing keys could be identified by prefixes or by storing them in a separate preference file.

**Comment by devemux86** [comment]
Seems more app related, instead of library's job.
