### ISSUE TITLE
MapsForge's tutorial

### ISSUE THREAD

**Issue by ehclima** [mapsforge/mapsforge#565]
Hello, 

I developed an app months ago and as far as I remember there was a tutorial for beginners and etc. So, in these days I was looking for it and I could not find this tutorial, the question is: Where's the tutorial (to generate binary maps from osmosis, to add some overlays, etc)?

note: My hope is that the tutorial have some information about bounding box or how I can set the zoom level and position of the map. Google maps has LatLngBounds that makes easy to fit the polyline on the map. So another question is: Is there anything which can help me in this situation? To help me when I have a polyline and I want to see this totally, not to see it in partial because the map was not positioned accordantly and I have several polylines in different places of the map, so I don't want to store latitute, longitude and zoom level for each polyline?

**Comment by devemux86** [comment]
Please use the mailing list for such questions.

There is the [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) tutorial and of course the Samples app with many examples.

Also now you can use the new [MapViewerTemplate](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/util/MapViewerTemplate.java).

You can find all tutorials in main [Wiki](https://github.com/mapsforge/mapsforge/blob/master/README.md) page.

To find the zoom for a ```BoundigBox``` you can use the ```LatLongUtils.zoomForBounds```, see its usage in [ZoomToBounds](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/ZoomToBounds.java).
