### ISSUE TITLE
NPE in rendertheme

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#567]
With current dev branch I got an NPE probably rendering the first tile (some others came from persistent cache). Reasons unknown.

E/AndroidRuntime(12485): FATAL EXCEPTION: MapWorker
E/AndroidRuntime(12485): java.lang.NullPointerException
E/AndroidRuntime(12485):    at java.util.LinkedHashMap.makeTail(LinkedHashMap.java:275)
E/AndroidRuntime(12485):    at java.util.LinkedHashMap.get(LinkedHashMap.java:261)
E/AndroidRuntime(12485):    at org.mapsforge.map.rendertheme.rule.RenderTheme.matchWay(RenderTheme.java:207)
E/AndroidRuntime(12485):    at org.mapsforge.map.rendertheme.rule.RenderTheme.matchClosedWay(RenderTheme.java:113)
E/AndroidRuntime(12485):    at org.mapsforge.map.layer.renderer.DatabaseRenderer.renderWay(DatabaseRenderer.java:439)
E/AndroidRuntime(12485):    at org.mapsforge.map.layer.renderer.DatabaseRenderer.processReadMapData(DatabaseRenderer.java:415)
E/AndroidRuntime(12485):    at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:182)
E/AndroidRuntime(12485):    at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:88)
E/AndroidRuntime(12485):    at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:65)
E/AndroidRuntime(12485):    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

**Comment by devemux86** [comment]
I have not seen something like this.

Ludwig does it happen with a Samples example,
any specific map / render theme or in your apps?

**Comment by ludwigb** [comment]
That was actually with one of my apps, upgraded to the latest dev, but
there is nothing special in it regarding the loading of renderthemes. The
rendertheme is also ok, as after a restart the app just started without
error.
I have not been able to reproduce this and it was the first time it
happened.

The only hunch I had was that somehow the rendertheme was not yet fully
loaded despite the future having been returned.

**Comment by atasoyh** [comment]
You need to check usage of you LinkedHashMap. Is it thread-safe?

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
