### ISSUE TITLE
 "LayerManager" IllegalArgumentException with marker.

### ISSUE THREAD

**Issue by necati-cevik** [mapsforge/mapsforge#571]
I am creating a marker like this :

```
posMarker = new Marker(new LatLong(currentLat, currentLon), bitmap, 0, -bitmap.getHeight()/2);
```

When I maximum zoom in, I get the exception :

```
Exception in thread "LayerManager" java.lang.IllegalArgumentException: left: 2.147483647E9, right: -2.147483625E9
    at org.mapsforge.core.model.Rectangle.<init>(Rectangle.java:32)
    at org.mapsforge.map.layer.overlay.Marker.draw(Marker.java:80)
    at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:90)
    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

Am I doing something wrong ?

**Comment by devemux86** [comment]
Can you provide more information, like the actual Marker coordinates and at what zoom the issue happens?

**Comment by necati-cevik** [comment]
Exception occurs at zoom level 24
```
currentLat = 39.90008; 
currentLon = 32.77370;
```

**Comment by devemux86** [comment]
Ok I can reproduce it.
The numbers in the exception are actually Integer limits.
So apparently something is to be checked with overlays at those large zoom levels.

**Comment by necati-cevik** [comment]
I am limiting the amount of zoom in the user can do as a temporary solution.

**Comment by ttirupathi** [comment]
I am also trying to add marker to map, but I am not able to do it. Can you please tell me/send me how bitmap, is created?

Thank you

**Comment by devemux86** [comment]
This is for the specific issue.
For using the Mapsforge overlay API check the [OverlayMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/OverlayMapViewer.java) in Samples.

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
