### ISSUE TITLE
Java SVG support

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#575]
Add support in Java for SVG resources.

**Comment by devemux86** [comment]
I pushed on dev 509fce764adfe228417be6876a0f70f80549eb95 an implementation for Java SVG support via [SVG Salamander](https://svgsalamander.java.net/) (LGPL and BSD).

It's small and seems to handle the SVG spec well.

**Comment by devemux86** [comment]
SVG Salamander keeps the rendered SVG documents loaded in memory, so we have a memory cache of them for the lifetime of the application.

**Comment by applantation** [comment]
No way to clear the cache?

**Comment by devemux86** [comment]
On the contrary we can clear it with:
```Java
SVGCache.getSVGUniverse().clear();
```
but it's a useful memory cache, so I have not changed anything in Mapsforge.

It can be handled in application level.
Do you mean something different?

**Comment by applantation** [comment]
I cannot quite remember how we clear the SVG cache on Android, but if we
provide a wrapper then maybe the same wrapper should clear the cache for
Java too.

**Comment by devemux86** [comment]
In Android we have a file cache too, so it's somewhat different:
[AndroidSvgBitmapStore.clear()](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidSvgBitmapStore.java#L75)
But I could tie them together if it would be useful.

**Comment by ludwigb** [comment]
I would be in favour of that, if only to make Android and Java development
as much the same as possible. But if you feel the calls are essentially
different, leave it, I am equally not in favour of forcing things if it
does not feel natural.

Ludwig

**Comment by devemux86** [comment]
Well we have two different caches (memory vs file).
We could clear memory cache in both platforms via an interface.

Android memory cache is cleared via:
[AndroidResourceBitmap.clearResourceBitmaps()](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidResourceBitmap.java#L53)

I was wondering if it's needed to implement a file cache in Java too, the pc speed probably doesn't justify the effort.

But mixing the file and memory cache calls together requires more thought for the possible cases.
I think we could implement it for memory only for start.

**Comment by devemux86** [comment]
I pushed on dev with ea192bfd013803320ca49a134843571d4c019f61 common clear methods for resource memory / file cache in Android and Java.
