### ISSUE TITLE
Contact mail is not accessible

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#576]
On your maps server there is a line: "For any issues and questions contact mapsforge-dev@googlegroups.com."

Trying to contact you via this email I got: "We're writing to let you know that the group you tried to contact (mapsforge-dev) may not exist, or you may not have permission to post messages to the group."

**Comment by devemux86** [comment]
You need to join the mailing list
http://groups.google.com/group/mapsforge-dev
as its members can post messages in it.

**Comment by kcwu** [comment]
I feel the better way to fix it is revising the message on maps server.

**Comment by applantation** [comment]
Changed that.
