### ISSUE TITLE
Split Russia map into regions

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#577]
It would be nice if Russia map will be split in separate regions like this is done for France, Germany and UK. Existing file is too big, and 98% of users do not need all Russia at once.

If you need some assistance in implementing this I am eager to help!

**Comment by ludwigb** [comment]
The map creation is handled from a companion project at https://github.com/mapsforge/mapsforge-mapcreator/tree/master/xml.

I am in favour of creating smaller files for Russia, we will need both a polygon and a start location for this.

You can see examples for the polygons in the /poly/ directory and the definition of start points is in the xml/example_config.xml file.

Please create a pull request, I have little time to attend to this.

**Comment by andreynovikov** [comment]
Thank you, I will look into that.

**Comment by devemux86** [comment]
I'm closing this as the split has been implemented.
Any new issues about the maps could be posted at map-creator project.
