### ISSUE TITLE
Some countries are missing on your server

### ISSUE THREAD

**Issue by laurascc** [mapsforge/mapsforge#581]
I'm trying to develop using South America maps from your server but I can't find some countries as Venezuela, Paraguay, Guyana,... 
Could you tell me where I can find them? Are they going to be uploaded?

Thanks in advanced,
Laura

**Comment by ludwigb** [comment]
The map creation is handled from a companion project at https://github.com/mapsforge/mapsforge-mapcreator.

I am in favour of creating additional country files for South America, we will need both a polygon and a start location for this.

You can see examples for the polygons in the /poly/ directory and the definition of start points is in the xml/example_config.xml file.

Please create a pull request, I have little time to attend to this.

**Comment by devemux86** [comment]
Let's continue the addition of more countries on server at MapCreator issues list.

I opened a relevant issue:
https://github.com/mapsforge/mapsforge-mapcreator/issues/2
