### ISSUE TITLE
Can not style power lines in rendertheme

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#582]
As I understand map data is not filtered when maps are generated, but I can not make rendertheme draw power lines. I've tried:
```
<rule cat="roads" e="way" k="power" v="*">
    <rule e="way" k="power" v="line" zoom-min="14">
        <line stroke="#888888" stroke-width="1.0" stroke-linecap="butt" />
    </rule>
    <rule e="way" k="power" v="minor_line" zoom-min="16">
        <line stroke="#888888" stroke-width="0.6" stroke-linecap="butt" />
    </rule>
</rule>
```
(I use roads category to be sure it will be drawn during testing.) Then I tried to simplify things:
```
<rule cat="roads" e="way" k="power" v="*">
   <line stroke="#888888" stroke-width="2.0" stroke-linecap="butt" />
</rule>
```
But also with no success. I am sure that my amendments to rendertheme are applied because I've successfully changed visual styles for some roads and other ways.

**Comment by devemux86** [comment]
Actually tag-mapping.xml defines what's included in the map files.

At the default one (see [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml#L131-L132)) I see only 2 POI rules related to power.

**Comment by andreynovikov** [comment]
So it's actually filtered... Can it be changed? As I see forest cut lines are also filtered. But these objects are essential for orienting on topographical map (when e.g. hiking).

**Comment by ludwigb** [comment]
Yes, all you have to change is the tag-mapping.xml file, you can supply a
changed one with the elements you need on the command line, see
https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md

**Comment by andreynovikov** [comment]
Thanks, but I'm talking about default file, used to generate provided maps. Mapsforge rendertheme has topo style, but is not very different from city style. I wanted to correct this.

**Comment by ludwigb** [comment]
Well, the question really is if we want to include that data in the map
files on our server. I am not as such totally against it, but it is a size
question (which might not be much). Opinions of others are welcome.

The way to get this changed is to change
https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-writer/src/main/config/tag-mapping.xml


and create a pull request for it.

**Comment by andreynovikov** [comment]
I can create a pull request but I need to know if it will be accepted.

**Comment by devemux86** [comment]
I'm fine with it too.
The map size is a critical factor of course and we need to have it always in mind.

Another important thing is the type of the maps we're hosting.
We wouldn't want it to be of a specific type (e.g. only for outdoor activities), but as far as possible generic type maps.

**Comment by ludwigb** [comment]
Can I suggest that you first try to apply the changes locally to your build
process to see if the maps will then actually come out as expected and no
further features are missing.

Then it should be easy to produce a pull request quite easily.

As long as the changes do not introduce anything too special and do not
increase the map size disproportionately, I am in favour of adding more
features to the map files. Power-lines are perhaps useful (it is something
we see and in remoter areas use for orientation), something like sewer
systems probably not (just to give an idea what I would be willing to
accept).

Ludwig

**Comment by andreynovikov** [comment]
Of course

**Comment by devemux86** [comment]
Any news on this?

**Comment by andreynovikov** [comment]
A little bit busy at the moment, plan to return to this in September.

**Comment by ludwigb** [comment]
Since there seems otherwise little interest in power lines and this is not bug, but something that can easily be changed by modifying the tag-mapping.xml, I am closing this issue without further action.
