### ISSUE TITLE
NPE when rotating device several times within short time

### ISSUE THREAD

**Issue by wish7code** [mapsforge/mapsforge#584]
One of our users reported a strange bug: when rotating the device several times in a very short times, mapsforge crashes with a null pointer exception. (for reference https://code.google.com/p/openbmap/issues/detail?id=72)

Version is mapsforge-0.5.0.
I can reproduce the NPE on my Nexus 4 device (although I need to shake for several seconds and it doesn't happen in every case)

Relevant log cat from my Nexus 4:
02-28 20:43:26.710 E/AndroidRuntime(15442): Caused by: java.lang.NullPointerException
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.mapsforge.map.layer.cache.FileSystemTileCache.deleteDirectory(FileSystemTileCache.java:99)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.mapsforge.map.layer.cache.FileSystemTileCache.destroy(FileSystemTileCache.java:198)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.mapsforge.map.layer.cache.TwoLevelTileCache.destroy(TwoLevelTileCache.java:49)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.openbmap.activities.MapViewActivity.releaseMap(MapViewActivity.java:1006)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.openbmap.activities.MapViewActivity.onDestroy(MapViewActivity.java:380)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2006)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1076)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1954)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:313)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at com.actionbarsherlock.app.SherlockFragmentActivity.onDestroy(SherlockFragmentActivity.java:87)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at org.openbmap.activities.HostActivity.onDestroy(HostActivity.java:306)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.app.Activity.performDestroy(Activity.java:5491)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
02-28 20:43:26.710 E/AndroidRuntime(15442): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3491)

**Comment by devemux86** [comment]
Thanks for the report. Are you using threaded cache?

By the way you don't need to restart the activity at each device orientation change (if you don't want).

**Comment by wish7code** [comment]
Hey emux!

>  Are you using threaded cache?

Well, I can't say exactly. I think I used some code snippet from the mailing list or the sample app.
Here's the cache initialization:

`
public static TileCache createExternalStorageTileCache(final Context c, final String id) {
		TileCache firstLevelTileCache = new InMemoryTileCache(32);
		String cacheDirectoryName = c.getExternalCacheDir().getAbsolutePath() + File.separator + id;
		File cacheDirectory = new File(cacheDirectoryName);
		if (!cacheDirectory.exists()) {
			cacheDirectory.mkdir();
		}
		TileCache secondLevelTileCache = new FileSystemTileCache(1024, cacheDirectory, AndroidGraphicFactory.INSTANCE);
		return new TwoLevelTileCache(firstLevelTileCache, secondLevelTileCache);
	}
`

Can you determine from the code, whether this is a threaded cache?

> By the way you don't need to restart the activity at each device orientation change (if you don't want).

I remember there were some issues when not recreating the app. Anyways this screen rotation thing is sort of a personal nightmare for me :-)

**Comment by devemux86** [comment]
The constructor you're using doesn't create a threaded cache.
But you're using fixed values for memory and file cache sizes (probably from AWT code).

I recommend to use one of ```AndroidUtil.createTileCache``` methods which perform the needed calculations for cache size based on device characteristics.

You can check [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) wiki for a complete implementation.

About activity restart you can read also [here](https://groups.google.com/d/msg/mapsforge-dev/7Mem4S1Aotw/ryJJqB2Li4MJ).

**Comment by wish7code** [comment]
I changed the code as you suggested and now I sitting here shaking and spinning my phone (quite funny picture):
The NPE seems gone so far, but I wondering: does the suggested fix just circumvent the problem or was the NPE a real bug?

**Comment by devemux86** [comment]
>I changed the code as you suggested

What code do you mean, for the cache creation or the activity restart?

**Comment by wish7code** [comment]
Sorry, meant the cache creation (activity restart remained unchanged)..
Now cache creation reads

`AndroidUtil.createTileCache(this.getActivity(), "mapcache", mMapView.getModel().displayModel.getTileSize(), 1f, this.mMapView.getModel().frameBufferModel.getOverdrawFactor());`

**Comment by devemux86** [comment]
The suggested code is for creating a properly calculated cache for mobile use.

I checked the 0.5.0 src, the NPE is at the point of [deleting](https://github.com/mapsforge/mapsforge/blob/0.5.0/mapsforge-map/src/main/java/org/mapsforge/map/layer/cache/FileSystemTileCache.java#L99) the cache folder at activity end.

Apparently during consecutive restarts, the cache folder does not have enough time to be created and we try to delete a non existed directory.

I pushed a fix with 7d7dd3c3954673cd47850f3955eb34b61c139d0b at dev.

**Comment by applantation** [comment]
Thanks, that fix should probably soon be integrated into master, that way
it would make it into the 0.5.1 release.

Ludwig

**Comment by devemux86** [comment]
+1

**Comment by wish7code** [comment]
Let me say thanks to both of you!!!!!!!
Your joint efforts to make mapsforge better and better are so incredible :-)
Thanks a lot!

**Comment by applantation** [comment]
I have pushed this fix to master.
