### ISSUE TITLE
Samples: changing tile size example is broken

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#585]
At least on dev the changing tile size sample is broken. It seems that the persistent tile cache is getting in the way of properly drawing the screen with the right tiles.

**Comment by ludwigb** [comment]
Just playing with it and turning the persistent cache off in the settings for samples makes the issue go away.

**Comment by devemux86** [comment]
So a clear cache has to take place (as with any other map model changes) ?

**Comment by devemux86** [comment]
With 7c67dcf92a9d0987ef957f420762bbec7fe1b597 I pushed a fix on dev adding ```MapViewerTemplate.purgeTileCaches``` method for better handling persistent tile cache.
