### ISSUE TITLE
Offline TileStore continuously ask for missing tile

### ISSUE THREAD

**Issue by xamix** [mapsforge/mapsforge#587]
Use the library v5 RC4.

If in the tile store there are some missing tile, the library always carry it continuously, 
It generate an active and infinite CPU consumption. 
See the bellow log for example:

	Mar 04, 2015 11:31:54 PM org.mapsforge.map.layer.cache.TileStore findFile
	INFO: Failed to find directory C:\Users\Max\Documents\Work\Soft\Viewer\data\tilestores\TestTileSToreDir\16
	Mar 04, 2015 11:31:54 PM org.mapsforge.map.layer.cache.TileStore findFile
	INFO: Failed to find directory C:\Users\Max\Documents\Work\Soft\Viewer\data\tilestores\TestTileSToreDir\15
	Mar 04, 2015 11:31:54 PM org.mapsforge.map.layer.cache.TileStore findFile
	INFO: Failed to find directory C:\Users\Max\Documents\Work\Soft\Viewer\data\tilestores\TestTileSToreDir\14\8312
	Mar 04, 2015 11:31:54 PM org.mapsforge.map.layer.cache.TileStore findFile
	INFO: Failed to find directory C:\Users\Max\Documents\Work\Soft\Viewer\data\tilestores\TestTileSToreDir\17
	Mar 04, 2015 11:31:54 PM org.mapsforge.map.layer.cache.TileStore findFile
	INFO: Failed to find directory 

In the file "TileLayer.java", and more precisely in the "draw" method, 
it seem that the condition below recursively ask for redraw and so until bitmap is found
it always fire a file not found exception: 

	if (waitingForCachedTiles) 
	{
		this.requestRedraw();
	}

See the following thread for discussion: https://groups.google.com/forum/#!topic/mapsforge-dev/uD1Pgigu9pw

**Comment by ludwigb** [comment]
At the reported point, we probably cannot wait on a condition variable as
that is the draw method on the UI thread, so we would halt everything. But
if the TileStore interface would implement the Observable interface the
tile store could trigger a redraw on the TileLayers that depend on it if
the state of the TileStore changes (i.e. a tile is added).

Ludwig

**Comment by devemux86** [comment]
That seems a nice way to go.

**Comment by ludwigb** [comment]
I have pushed a fix to dev for this.

**Comment by ludwigb** [comment]
The change removes the busy wait for all TileLayers and makes the TileLayer only redraw when a change happens in the TileCache (i.e. a new tile is added). That should reduce CPU time for all TileLayers. 
(Drawback at the moment is that there might be changes happening to the tile cache that are not visible.)

**Comment by applantation** [comment]
Missing file added

**Comment by devemux86** [comment]
Only the ```TileRendererLayer``` needs the change?

**Comment by ludwigb** [comment]
I guess download layer will need the same, will change a bit later today.

**Comment by xamix** [comment]
Tested a bit the patch you provided and it seem to do the job :)

Thanks.

**Comment by applantation** [comment]
I just pushed the change that also the TileDownloadLayer will react to
tilecache changes

**Comment by devemux86** [comment]
Doesn't ```TileStoreLayer``` need also the same?

**Comment by applantation** [comment]
I thought the assumption is that the TileStoreLayer never changes, so we
should never be waiting for tiles. Or I am mistaken here with something?

**Comment by devemux86** [comment]
Yes usually a TileStore is created with a fixed tiles pyramid.
I'm thinking of cases where we want to be flexible with that, e.g. apps where the tile store is being updated.

**Comment by applantation** [comment]
Could do, but it could also be done in easily derived class....
