### ISSUE TITLE
Pausing MapWorker can freeze calling thread

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#588]
I am pausing `MapWorker` with the following code:

    mapWorker.pause();
    mapWorker.awaitPausing();

But if `MapWorker` is doing nothing it's put in `WAITING` state by `JobQueue` and `awaitPausing()` never returns because run loop is not executing and `pausing` flag is not set. I've made a workaround for that case: 

    mapWorker.pause();
    if (mapWorker.getState() != Thread.State.WAITING)
        mapWorker.awaitPausing();

But I think the source of the problem should be fixed in some way.

**Comment by devemux86** [comment]
Do you use the ```PausableThread``` outside of Mapsforge context?

AFAIK ```awaitPausing``` is not used currently in the code.

**Comment by andreynovikov** [comment]
In some way. Why not?

**Comment by devemux86** [comment]
I mean we have not seen any issues inside the library where just the ```pause()``` is used.
Have you tried only that?

**Comment by andreynovikov** [comment]
Yes, does not work for me. I'm playing with `MultiMapDataStore`. I have extended it to be able to dynamically add and remove individual map files. If I do not pause `MapWorker` before data store manipulation I get `ConcurrentModificationException`. If I do not use `awaitPausing` I still get this exception.

**Comment by devemux86** [comment]
I think the processing of a map file is not supposed to be done without proper synchronization.
i.e. the map database read can get corrupted by multiple threads reading the file at once.
Or by not following the map file life cycle, cleanup / close operations at switching.

Is it something relevant to your case ?

(I use ```MultiMapDataStore``` playing with multiple maps without any problems)

**Comment by devemux86** [comment]
Any news on this?

**Comment by andreynovikov** [comment]
I've just went another way. You can close it if you wish.
