### ISSUE TITLE
Problem on rendered maps available on the website.

### ISSUE THREAD

**Issue by vinceo** [mapsforge/mapsforge#590]
Hello,
I noticed recently that the maps available on this website : http://download.mapsforge.org/maps/ are now experiencing some problems. The maps are nearly empty and their file size have dropped dramatically. For example, France size used to be more than 1 GB and is now 81 MB !
I couldn't find a topic on this issue and I hope my message is in the right place.
Regards,

Vinceo

**Comment by devemux86** [comment]
Yes we're aware of the issue.
Thanks for the report.

**Comment by ludwigb** [comment]
Maybe we had a problem with the planet.pbf download.

The current file is 28GB, the last one where we produced the smaller files
was smaller (22GB) and that was already after restarting the process.

We are currently remaking the Russia files and it will be a while until we
get to Europe again.

No, we do not have backups of the old files. It is a size question as we
cannot keep all the files around. But I will see that if the current
process works, that we keep something like a 'last known good' set.

Ludwig

**Comment by applantation** [comment]
I have killed off the process that made the
russia/far-eastern-federal-district. The extraction from the planet.pbf had
been going on for several days and did not seem to stop.

The processing is continuing with the next elements.

Ludwig

**Comment by devemux86** [comment]
I'm closing this as the process restarted.

Feel free to report any other map problems at MapCreator issues list:
https://github.com/mapsforge/mapsforge-mapcreator/issues
