### ISSUE TITLE
Code optimization (i.e. Android Lint)

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#592]
Ongoing task of reducing number of code warnings.

**Comment by devemux86** [comment]
We have also the deprecated [Resources.getDrawable](https://developer.android.com/reference/android/content/res/Resources.html#getDrawable%28int%29) with Android 5.1.

**Comment by devemux86** [comment]
Lint does not always reports [unnecessary object creation](http://developer.android.com/training/articles/perf-tips.html#ObjectCreation), we should keep an eye on them too.

**Comment by devemux86** [comment]
With f5a6c21b6fc534c7e01751677af2842cc5b024c1 I cleaned up some Lint warnings taking also care of the deprecated [Resources.getDrawable](https://developer.android.com/reference/android/content/res/Resources.html#getDrawable%28int%29) with Android 5.1.

**Comment by devemux86** [comment]
@ludwigb
Are the following suppress warnings:
```java
@SuppressWarnings("PMD.SignatureDeclareThrowsException")
```
in [HttpServerTest](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/test/java/org/mapsforge/map/HttpServerTest.java) useful anywhere?

**Comment by ludwigb** [comment]
IIRC, I added this as the PMD checker complained about too general exceptions. I think the PMD checking module is still run, but no-one ever looks at the output. 
I think the warnings can just go .... and probably also the whole PMD stuff. Thilo added it, but we have an overkill of different lint systems.

**Comment by devemux86** [comment]
Ok I removed the PMD (leaved its ruleset for now).
I see it was only configured in Gradle build.

**Comment by devemux86** [comment]
Closing this, ongoing work.
