### ISSUE TITLE
Build failed - bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by hurzl** [mapsforge/mapsforge#593]
```
* What went wrong:
Execution failed for task ':Applications:Android:Samples:preDexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /.../android/sdk/build-tools/22/dx --dex --output /.../mapsforge/Applications/Android/Samples/build/intermediates/pre-dexed/debug/mapsforge-map-0.5.1-c28fbb330a20f2bd2caceff3ecff8ca602a1543f.jar /.../mapsforge/mapsforge-map/build/libs/mapsforge-map-0.5.1.jar
  Error Code:
        1
  Output:
  
        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
                at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
                at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
                at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
                at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
                at com.android.dx.command.dexer.Main.processClass(Main.java:704)
                at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
                at com.android.dx.command.dexer.Main.access$300(Main.java:83)
                at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
                at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
                at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
                at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
                at com.android.dx.command.dexer.Main.processOne(Main.java:632)
                at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)
        ...while parsing org/mapsforge/map/view/MapView.class
  
        1 error; aborting
```
Somewhere I read it had to do with using java 1.8, I don't have 1.7, so I changed in build.gradle to 
```
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
    }
```
but that didn't change anything. Ideas?

**Comment by ludwigb** [comment]
As you said, you will need java 1.7.

**Comment by hurzl** [comment]
Also for running the binary downloads? 
And why does the apk not install?

**Comment by applantation** [comment]
The apk from the download site should install and run.

**Comment by hurzl** [comment]
I get "Parsing Error"

**Comment by devemux86** [comment]
You're trying to run Samples with an IDE (e.g. Android Studio) ?

As Ludwig mentioned you'll need Java 7 SDK for Android development.
Android does not yet support Java 8 compiler compliance.

-- 
Emux
Cruiser <http://wiki.openstreetmap.org/wiki/Cruiser> - Atlas 
<http://wiki.openstreetmap.org/wiki/Atlas_%28navigation_application%29>

**Comment by devemux86** [comment]
You're trying to run Samples with an IDE (e.g. Android Studio) ?

As Ludwig mentioned you'll need Java 7 SDK for Android development.
Android does not yet support Java 8 compiler compliance.

**Comment by hurzl** [comment]
No on an android phone, 5.0.2
I compiled apps with jdk 1.8, I don't know why 1.8 shouldn't (or doesn't) compile 1.7 compliant code?

**Comment by ludwigb** [comment]
Try the debug version,
http://ci.mapsforge.org/job/0.5.1/lastSuccessfulBuild/artifact/Applications/Android/Samples/build/outputs/apk/Samples-release-unsigned.apk


http://ci.mapsforge.org/job/0.5.1/

I think we are linking to the release version, which might need to get
signed first before using.

Ludwig

**Comment by devemux86** [comment]
Actually we're linking the above apk but we have actually two now (in 0.4 we had only one).

We should again provide only one and it shouldn't necessarily be signed / aligned since we don't put it in store.

**Comment by applantation** [comment]
I have removed the unsigned release Samples app from the builds (and also
from the 0.5.1 release, as it will not work, keeping it will only create
problems), and updated the Downloads doc.

Building the release versions of the Samples app had already been removed
from the dev and rotation builds, but not from master (from which the 0.5.1
releases had been copied).

Ludwig

**Comment by ludwigb** [comment]
The advice is to use JAVA 1.7 as 1.8 is not supported by Android.

The second issue has been cleared with a change to the build procedures on the ci.mapsforge.org server and an update to the documentation (see 5e3b20633b3461144)

**Comment by devemux86** [comment]
I think that's the best way to handle this.

>Building the release versions of the Samples app had already been removed from the dev and rotation builds, but not from master (from which the 0.5.1 releases had been copied).

In [master](http://ci.mapsforge.org/job/master/) too I see only the debug apk.

**Comment by ludwigb** [comment]
I had changed that at the same time and rebuild.
The unsigned release version makes no sense and if we left it there, I am
pretty sure the problem would crop up again.

**Comment by devemux86** [comment]
+1

**Comment by schildbach** [comment]
I wonder if we can make gradle to pick the right JDK automatically. I have both java-1.7.0-openjdk-amd64 and java-1.8.0-openjdk-amd64 installed in parallel, but it picked 1.8. I need to switch using update-java-alternatives. But then again other projects that require 1.8 don't work, so I need to switch back and forth manually all the time.

btw. Mapsforge claims to support Android versions down to 2.3, so we should build against Java 1.5!

**Comment by devemux86** [comment]
>btw. Mapsforge claims to support Android versions down to 2.3, so we should build against Java 1.5!

Never seen any problem with Android 2.3 (test all the time).
I think Android build tools are backwards compatible.

**Comment by dfeng99** [comment]
This used to be happened due to java idk version inconsistent with the android studio, you'd better to specify the JAVA_HOME to the version which same as android studio.
