### ISSUE TITLE
Task type mapfile-writer doesn't exist.

### ISSUE THREAD

**Issue by manish-dev-28** [mapsforge/mapsforge#594]

**Comment by devemux86** [comment]
More info about the problem could help us better.

Check if your Osmosis has properly in its classpath the map-writer jar.

**Comment by ludwigb** [comment]
Your map writer plug-in is not correctly installed in a location where osmosis expects it.

Read https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md

This has also been discussed a few times on the mailing list and is, most likely, not an issue.
