### ISSUE TITLE
LabelLayer: cache overwriting

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#595]
Testing ```LabelLayer``` with multiple adjacent maps via ```MapDataStore```, I see continuous overwriting warnings where the maps are connected.
(If I disable the ```LabelLayer``` the warnings dissappear)

```java
org.mapsforge.map.layer.cache.FileSystemTileCache storeData
WARNING: overwriting cached entry: 7/64/41
org.mapsforge.map.layer.cache.FileSystemTileCache storeData
WARNING: overwriting cached entry: 7/65/44
org.mapsforge.map.layer.cache.FileSystemTileCache storeData
WARNING: overwriting cached entry: 7/65/41
org.mapsforge.map.layer.cache.FileSystemTileCache storeData
WARNING: overwriting cached entry: 7/64/44
```

**Comment by devemux86** [comment]
Further tests show that the above behavior appears also with a single map at map borders.

**Comment by devemux86** [comment]
Ludwig can you explain why in [TwoLevelTileCache.put](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/cache/TwoLevelTileCache.java#L88-L93) the ```secondLevelTileCache.put``` is not inside the ```if (this.workingSet.contains(key))``` statement as the ```firstLevelTileCache.put```?

**Comment by ludwigb** [comment]
The workingSet is IIRC the set of tiles that is currently displayed (more
or less, I cannot remember the exact rules), and the first level cache
should contain those tiles.
The second level cache should contain all rendered tiles, regardless of
them being displayed or not.

HTH, is this causing problems?

**Comment by devemux86** [comment]
With ```LabelLayer``` and current implementation we have the current issue of overwriting tiles in file cache at map borders.
This goes away with the above change, so I'm wondering what's going on.

**Comment by ludwigb** [comment]
Is that somehow because the LabelLayer, which has nothing to do with the cache, nevertheless changes the label cache, causing those tiles to be rewritten (even if they do not contain any labels, so the tiles do not actually change)?

**Comment by devemux86** [comment]
Probably, the tile overwriting happens continuously at map borders, although the map is not moving (no panning).

**Comment by ludwigb** [comment]
I think the question is why do we keep regenerating these tiles, the cache
overwrite is a consequence of this, but not the core problem.

Is it a question of tiles being considered out of date?

**Comment by devemux86** [comment]
Further searching it, reveals that the tiles which keep regenerating and overwriting in cache, are actually adjacent and completely outside the map bounding box.
So somehow the ```LabelLayer``` bounds cause this behavior.

**Comment by devemux86** [comment]
I pushed fixes in both dev / master branches because of the different implementation.

**Comment by devemux86** [comment]
Essentially like #642 with ```LabelLayer``` we need to perform some actions independently of the ```TileRendererLayer```.
In this case the cache writing should happen only for non label renderer jobs.
