### ISSUE TITLE
MultiMapDataStore NPE at tile read

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#596]
The relevant discussion is at [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/tJFXt7hUOiU).

At ```MultiMapDataStore``` we may see the case of NPE while reading tile data and being in multiple maps loop, see [here](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MultiMapDataStore.java#L177).

**Comment by ludwigb** [comment]
Pushed fix to dev, 4e9335cf6977cf

**Comment by devemux86** [comment]
:+1:
