### ISSUE TITLE
Model.MapViewPosition.getMapLimit() may return null?

### ISSUE THREAD

**Issue by hurzl** [mapsforge/mapsforge#600]
In fact for me it does return null. Is there a way to get the current lat/long span of the map?

**Comment by devemux86** [comment]
As its docs declare, it can return null, if it was not set.
By setting map limit you can restrict map view bounds.

Please try using the forum for questions.
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by devemux86** [comment]
For getting current map bounds you can try:
```java
MapPositionUtil.getBoundingBox(mapView.getModel().mapViewPosition.getMapPosition(), mapView.getDimension(), mapView.getModel().displayModel.getTileSize());
```

**Comment by hurzl** [comment]
I misunderstood limits. Your complicated lines works though, thank you very much.

**Comment by devemux86** [comment]
With 1ac94e1e78203234db098b64993693a5efd61861 on dev I added a simplified ```MapView.getBoundingBox()``` method.

**Comment by hurzl** [comment]
very nice :+1:

**Comment by hurzl** [comment]
Somehow I have the impression that I always get the BoundingBox of my previous call to this function ... But calling twice doesn't help either ;)  When is the position being updated?

**Comment by devemux86** [comment]
The algorithm uses map position's coordinates and zoom level, so it should change.

What method are you using, the simplified?

**Comment by hurzl** [comment]
No I use master with your above code

**Comment by devemux86** [comment]
Are you sure you're not using a cached ```MapPosition``` ?
Try printing its coords / zoom prior using it.

**Comment by hurzl** [comment]
The problem was that a layer which depends on this data was redrawn only at the next update ;-/ - sorry
