### ISSUE TITLE
All Russia map

### ISSUE THREAD

**Issue by AntonLunegovPerm** [mapsforge/mapsforge#601]
Hello. 
I'm an android developer and i need all Russia.map file. I'm using osmosis, and trying create .map file, used Russia.osm.pbf file. But i can't do this. Russia.osm.pbf weighs 1.5 Gb, and my JVM with 5 Gb random access memory can't do this. As I know, you have European part of Russia :: http://download.mapsforge.org/maps/     russia.map    17-Nov-2014 03:10    1.0G.
Could you create all Russia.map file with my data osm.pbf ?
P.s. I am use this file http://gis-lab.info/projects/osm_dump/ : In table "Данные", file Ru,"Российская Федерация",13 Apr (1507 MB)

**Comment by devemux86** [comment]
We have recently split it into regions, see #577.

Have you tried with parameter ```type=hd``` in the map-writer?
It switches from memory to hd mode, slower but eventually could finish the job.

Please use the forum for questions.
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by devemux86** [comment]
For map issues please use the map-creator issues:
https://github.com/mapsforge/mapsforge-mapcreator/issues

And for questions the forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
