### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by kobymolcho** [mapsforge/mapsforge#603]
Hello!

in maps-forge 0.3.1 we had the "updated" BoundingBox of the current map relative to the current zoom, 
i cant really find this functionality in the 0.5.1,

what im trying to do is to validate if a current LatLong point is in front of the user,
and if not - just animate the map to center on a new position.

i tried to use 
tileRendererLayer.getMapDataStore().boundingBox()
or
mapView.getModel().mapViewPosition.getMapLimit()

but the first gives me the overall of the all map - so for sure any point on the map will be there regardless  to the current zoom.

and the second gives me a limit (which i can define easily) only then the user cant move the map any more... so its not the right solution.

anyone can help here?

**Comment by devemux86** [comment]
Try ```MapView.getBoundingBox()```.

Please use our forum for questions.
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by kobymolcho** [comment]
i would like... but there is no function named MapView.getBoundingBox() 

0.3.1  use to have... but where and why is it gone?

**Comment by devemux86** [comment]
We added that simplified method recently.

In release version you can try:
```MapPositionUtil.getBoundingBox(mapView.getModel().mapViewPosition.getMapPosition(), mapView.getDimension(), mapView.getModel().displayModel.getTileSize());```

**Comment by kobymolcho** [comment]
You are the best man!!!! :)

i missed this util ... 

thanks!
