### ISSUE TITLE
org.mapsforge.core.graphics.FontFamily has incorrect error message

### ISSUE THREAD

**Issue by CvR42** [mapsforge/mapsforge#604]
The method fromString() has an incorrect message in its throw:

throw new IllegalArgumentException("Invalid value for Align: " + value);

'Align' should of course be 'FontFamily'.

Also, personally I have the habit to always surround the offensive string with quotes, so that even for weird strings that are empty or whitespace I get a reasonable error message. Thus:

throw new IllegalArgumentException("Invalid value for FontFamily: \"" + value + '\"');

**Comment by devemux86** [comment]
Thanks for the report.
With 2a2c35f0fcfb9e7f42c0d518cdfe3ed34f41d3c6 I pushed the fix on dev.
