### ISSUE TITLE
NPE in MapWorker and RenderTheme

### ISSUE THREAD

**Issue by CvR42** [mapsforge/mapsforge#605]
Apologies if this is a duplicate, but as far as I can tell the other NPEs reported right now are not related.

I get this NPE occasionally. Unfortunately I don't know how to reproduce it.

```
F/libc    (17167): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb4f46010 in tid 17178 (Binder_1)
E/AndroidRuntime( 1262): FATAL EXCEPTION: MapWorker
E/AndroidRuntime( 1262): Process: nl.cvr.columbus.walkabout, PID: 1262
E/AndroidRuntime( 1262): java.lang.NullPointerException: Attempt to invoke virtual method 'int org.mapsforge.map.rendertheme.rule.RenderTheme.getLevels()' on a null object reference
E/AndroidRuntime( 1262):        at org.mapsforge.map.layer.renderer.DatabaseRenderer.createWayLists(DatabaseRenderer.java:395)
E/AndroidRuntime( 1262):        at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:173)
E/AndroidRuntime( 1262):        at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:88)
E/AndroidRuntime( 1262):        at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:65)
E/AndroidRuntime( 1262):        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

**Comment by ludwigb** [comment]
Obviously this should not happen.

Anything special about your setup? Anything special about the device?

**Comment by devemux86** [comment]
Can you tell us the Mapsforge version, which map file and at what coordinates / zoom level it appeared?

**Comment by devemux86** [comment]
Looking at 0.5.1 code I suspect if it is a case of mixed app life cycle regarding Mapsforge handling.

**Comment by CvR42** [comment]
Ah yes, I forgot to mention the details. Standard mapsforge 0.5.1 jars running on a Moto G (2nd generation) with the Motorola factory Android 5.0.2.

Coordinates come from the GPS, so they are difficult to reproduce, but unless the GPS was very confused the coordinates should be somewhere in the area of Rotterdam and Amsterdam in the Netherlands. Zoom level I don't know.

**Comment by CvR42** [comment]
@devemux86: I'm not reporting app life cycle events to Mapsforge in any way. Should I do something?

Something that may be relevant is that I allow the render theme to be changed, and during startup I set the render theme from a stored preference. I do that with the following code:

```
tileRendererLayer.setXmlRenderTheme(xRenderTheme);
tileRendererLayer.requestRedraw();
activity.fileCache.purge();
```

The `purge()` call is there because in the Swing version of the code I noted that changing the render theme does not invalidate the current tiles in the cache.

**Comment by devemux86** [comment]
You can find a simple implementation of Mapsforge life cycle in [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) wiki.

And an example of changing render themes at [RenderThemeChanger](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/RenderThemeChanger.java) in Samples.

**Comment by CvR42** [comment]
@devemux86  As far as I can tell I do everything that is necessary to get mapsforge started as specified in the wiki. Keep in mind that most of the time the whole setup works, so it looks more like a race condition.

Regarding that example code: when I change the three lines I showed above to the switching code in RenderThemeChanger, I get a crash:

```
E/MapFile ( 9217): null
E/MapFile ( 9217): java.io.IOException: lseek failed: EBADF (Bad file number)
E/MapFile ( 9217):      at java.io.RandomAccessFile.seek(RandomAccessFile.java:602)
E/MapFile ( 9217):      at org.mapsforge.map.reader.IndexCache.getIndexEntry(IndexCache.java:95)
E/MapFile ( 9217):      at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:512)
E/MapFile ( 9217):      at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:341)
E/MapFile ( 9217):      at org.mapsforge.map.reader.MultiMapDataStore.readMapData(MultiMapDataStore.java:177)
E/MapFile ( 9217):      at org.mapsforge.map.reader.MultiMapDataStore.readMapData(MultiMapDataStore.java:131)
E/MapFile ( 9217):      at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:183)
E/MapFile ( 9217):      at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:88)
E/MapFile ( 9217):      at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:65)
E/MapFile ( 9217):      at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
E/MapFile ( 9217): Caused by: android.system.ErrnoException: lseek failed: EBADF (Bad file number)
E/MapFile ( 9217):      at libcore.io.Posix.lseek(Native Method)
E/MapFile ( 9217):      at libcore.io.BlockGuardOs.lseek(BlockGuardOs.java:163)
E/MapFile ( 9217):      at java.io.RandomAccessFile.seek(RandomAccessFile.java:600)
E/MapFile ( 9217):      ... 9 more
E/AndroidRuntime( 9217): FATAL EXCEPTION: MapWorker
E/AndroidRuntime( 9217): Process: nl.cvr.columbus.walkabout, PID: 9217
E/AndroidRuntime( 9217): java.lang.NullPointerException: Attempt to read from field 'boolean org.mapsforge.map.reader.MapReadResult.isWater' on a null object reference
E/AndroidRuntime( 9217):        at org.mapsforge.map.reader.MultiMapDataStore.readMapData(MultiMapDataStore.java:178)
E/AndroidRuntime( 9217):        at org.mapsforge.map.reader.MultiMapDataStore.readMapData(MultiMapDataStore.java:131)
E/AndroidRuntime( 9217):        at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:183)
E/AndroidRuntime( 9217):        at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:88)
E/AndroidRuntime( 9217):        at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:65)
E/AndroidRuntime( 9217):        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

**Comment by devemux86** [comment]
Have you tried to change the render theme by creating a new tile renderer layer as shown in Samples?

**Comment by CvR42** [comment]
@devemux86 That's what `RenderThemeChanger` does, no? I copied the code from `RenderThemeChanger`, and that causes this crash.

**Comment by applantation** [comment]
The second one is clearly something totally different, it has nothing to do
with the Rendertheme change, but is an non-readable map file.

**Comment by devemux86** [comment]
I didn't quite understand what you do when you change render themes.

The Sample ""Changing render themes" works for you?
(you need to put some render themes in external storage directory)
I just retested and it works.

The above exceptions seem to be from trying to read a closed input stream.
(And I suppose you have the right permissions in manifest)

**Comment by devemux86** [comment]
Any news on this?
