### ISSUE TITLE
Strange bbox Map Writer Bug

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#606]
I've bound a strange bug in the map writer. It sometimes has issues when there is too much precision in the bbox passed in to it. I'm not sure if the bug is in the map writer or osmosis, but this is the result:
![image1](https://cloud.githubusercontent.com/assets/1422186/7597229/f9682c64-f8a6-11e4-9be8-343c13eb8a93.jpg)
The left map was created with:

osmosis --rx 3-0-2-mf.osm --mw file=3-0-2.nmap bbox=40.97990,-180.0,66.51326,-135.0

and the right one with

osmosis --rx 3-0-2-mf.osm --mw file=3-0-2.map bbox=40.9798980696201270,-180.0000000000000000,66.51326
04431118610,-135.0000000000000000

As you can see, the only difference is the number of significant digits in the bbox. I debugged MapFileWriterTask.java, and found that the bbox was being parsed correctly in both cases.

**Comment by devemux86** [comment]
Thanks for the report.
You say that during debugging the ```double``` values after the parsing have the whole precision as in the input ?

Out of curiosity can you try the same test in another region where the coordinates are all positive?

**Comment by lincomatic** [comment]
I put a logging statement in MapFileWriterTask.java, and this is the output:
INFO: bbox=minLatitude=40.97989806962013, 
minLongitude=-180.0, maxLatitude=66.51326044311186, maxLongitude=-135.0 ... basically same precision as input.

Unfortunately, my machine is currently generating a world map, so I can't do more testing for you for at least a week or two. The problem does not happen with all regions. It also happened with

INFO: bbox=minLatitude=-66.51326044311186, minLongitude=-180.0, maxLatitude=-40.
97989806962013, maxLongitude=-135.

Which is basically the same, except that the latitudes are negative.

My current workaround is I modified a copy of osmosis to output the bbox to the OSM file after it merges land and sea OSM files, so the mapwriter doesn't need me to specify the bbox on the command line.

If you like, I have a small pbf file.. only 1.4MB which exhibits the problem, that I can send you

**Comment by lincomatic** [comment]
BTW, there is another bug, where the water can be seen in land masses sometimes. You can see very fine blue vertical lines in the map on the left. These lines also show up in the us-pacific map I downloaded from your server.

**Comment by devemux86** [comment]
>My current workaround is I modified a copy of osmosis to output the bbox to the OSM file after it merges land and sea OSM files, so the mapwriter doesn't need me to specify the bbox on the command line.

Note that if you use input data that has a bounding box defined in it, then you normally won't need to specify one in map-writer.

Another test you could try is to use coordinates without making them hit the world limits (180 or 90).

**Comment by devemux86** [comment]
>BTW, there is another bug, where the water can be seen in land masses sometimes. You can see very fine blue vertical lines in the map on the left. These lines also show up in the us-pacific map I downloaded from your server.

We put the sea in its own layer occupying the map bounds under the land vector data.

If it is what I have already saw at map edges (e.g. Antarctica on world.map), I think it may be a rounding issue or slightly different values regarding the sea rectangle and land polygons bounds.

Can you open a different issue about this?

**Comment by lincomatic** [comment]
>Note that if you use input data that has a bounding box defined in it, then you normally won't need to specify one in map-writer.

Yes, I am aware of that. That's why I had to modify osmosis. The bbox parameter was needed for the mapwriter only because osmosis wasn't outputting the bbox to the osm file that was merged with the land and sea. This is because the land and sea osm files don't have bounding boxes... osmosis will always throw away the bounding box if one of the files being merged doesn't have a bounding box. Please refer to : http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.44#Bound_entity_processing

>Another test you could try is to use coordinates without making them hit the world limits (180 or 90).

I just tested this by changing -180 to -179.99 and it doesn't fix the problem. Actually, the one with lower precision that worked OK (image on left) was hitting the world limit at -180.

**Comment by lincomatic** [comment]
>We put the sea in its own layer occupying the map bounds under the land vector data.
>
>If it is what I have already saw at map edges (e.g. Antarctica on world.map), I think it may be a rounding issue or slightly different values regarding the sea rectangle and land polygons bounds.
>
>Can you open a different issue about this?

Since it is happening in the middle of large land masses, I think it might be different from what you are seeing at the bounds. But I agree, it is probably something due to rounding errors, since the sea is bleeding through from below. I will open a new issue for this. Thank you.

**Comment by andreynovikov** [comment]
@lincomatic Have you fixed this? It appears that I've hit the same issue.

**Comment by lincomatic** [comment]
Only the workaround (modified osmosis to output bbox) that I mentioned above

**Comment by lincomatic** [comment]
My osmosis modification is here: https://github.com/lincomatic/osmosis/commit/9b15ec4db95d2bf65fa4610726eeb9e3aac17154

**Comment by devemux86** [comment]
>Only the workaround (modified osmosis to output bbox) that I mentioned above

Couldn't include bounding box in the input osm or pbf files to avoid Osmosis modification?

BTW @lincomatic have you reported the issue in Osmosis, what did they say?

**Comment by lincomatic** [comment]
> BTW @lincomatic have you reported the issue in Osmosis, what did they say?

I did not report it to Osmosis

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
