### ISSUE TITLE
MapViewPosition.animateTo wobbling

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#607]
Trying consecutive calls of ```MapViewPosition.animateTo```, e.g. quick follow my location via a mock provider or outside in a fast vehicle, we see that the map animation is performed around the actual position, back and forth alternatively.

**Comment by ludwigb** [comment]
This is because while the animation is running, the MapViewPosition is not actually correct, so any subsequent changes are effected on a wrong position.
