### ISSUE TITLE
Map Writer: Sea sometimes bleeds though from under land masses

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#608]
Sometimes, vertical or horizontal strips of sea bleed through when creating a map by merging OSM data with land polygon and underlying sea rectangle. Here is a detail from us-pacific.map downloaded from mapsforge server:
![image1](https://cloud.githubusercontent.com/assets/1422186/7627726/2a9adcea-f9cf-11e4-9d5c-d3775b225a76.jpg)

**Comment by devemux86** [comment]
Ok now that I see the screenshot, what land polygons are you using?

I have seen such artifacts with split land polygons (e.g. from OpenStreetMap Data).

**Comment by devemux86** [comment]
BTW the land polygons used at mapsforge server are the split ones from there.

**Comment by lincomatic** [comment]
Yes, those are the exact set that I am using: land-polygons-split-4326. Is there a better set to use?

**Comment by devemux86** [comment]
You can try the non-split edition provided from the same source.
But the map build time will rise significantly for large complex lands.

Alternatively you can change in render theme the land rendering, e.g. put larger stroke at split polygons in order to hide the seams.

**Comment by lincomatic** [comment]
OK, I will try those ideas, thanks. I was avoiding the unsplit polygons because of the comment in the mapcreator's landextraction.py:

 "# self.landfiles = "land-polygons-complete-4326"  # there seems to be a bug in that data"

**Comment by devemux86** [comment]
That comment is from Ludwig, so he could answer better for that.

**Comment by lincomatic** [comment]
OK your stroke idea works great! For the benefit of anyone else trying to fix this problem, I empirically found 0.6 to work:
	<rule e="way" k="natural" v="nosea">
		<area fill="#F4F3F2" stroke="#F4F3F2" stroke-width="0.6"/>
	</rule>
Next I will try using the unsplit polygons to see how that affects map size & rendering speed.

**Comment by lincomatic** [comment]
What is the best way to bring the question about land-polygons-complete to Ludwig's attention? Should I post to the mailing list?

**Comment by devemux86** [comment]
>What is the best way to bring the question about land-polygons-complete to Ludwig's attention? Should I post to the mailing list?

Ludwig is watching both issues and mailing list.
But I agree it's better any discussion to take place primarily in forum.

**Comment by devemux86** [comment]
I'm wondering if we should add at ```nosea``` in default render themes (Osmarender / RenderThemeV4) a stroke directive for better handling the seams at split land polygons.

A counter argument could be that the stroke will expand slightly the land.

BTW I see the use of ```stroke-width="1.0"``` at ```nosea``` in OpenAndroMaps themes.

**Comment by applantation** [comment]
Re this issue with the unsplit polygons, the problem was that some
geometries were invalid, reason unclear, maybe lines crossing the dateline
or unclosed polygons.
This might be resolved in newer versions of the coastline files, it is
worth a try.

The coastlines do not change that much, but I advise to update to newer
versions once in a while just to keep OSM data for beaches etc in line with
the coastline.

Ludwig

**Comment by devemux86** [comment]
With 93df27f9b2e86c785e47c87b61de7a54c2f8cd6f I pushed on dev a fix adding ```stroke-width="1.0"``` at ```natural=nosea``` in Osmarender and RenderThemeV4 themes.

More fine tuning can be done, based also on zoom levels.
