### ISSUE TITLE
relation type=multipolygon reverses direction of oneway=yes

### ISSUE THREAD

**Issue by Piskvor** [mapsforge/mapsforge#611]
When a one-way street is added into a multipolygon relation, it is rendered as going the opposite way.
Steps to reproduce:
1. have multiple ways forming a closed loop, some of them one-way (oneway=yes)
2. make a relation type=multipolygon
3. add the ways to relation as type=outer
4. render and display map:
   $ osmosis --read-xml file=./praha-centrum-bugOnewayRelationOnly.osm --mw file=./praha-centrum.map && java -jar ~/prog/osm/Atlas-Beta-1.2.13/Atlas-Beta.jar ./praha-centrum.map
   (
   INFO: Osmosis Version 0.43.1-39-gcd86c44-SNAPSHOT
   May 18, 2015 12:16:28 AM org.openstreetmap.osmosis.core.Osmosis run
   INFO: Preparing pipeline.
   May 18, 2015 12:16:28 AM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
   INFO: mapfile-writer version: mapsforge-map-writer-0.5.1
   )

Expected result: one-way arrows displayed along the ways, in the ways' direction (similarly as in bitmap renderings, e.g. Mapnik - note the red route: IRL arrives from east, continues south)
![mapnik_177633](https://cloud.githubusercontent.com/assets/917239/7672472/7af167a4-fcf4-11e4-9b79-827ed39687c5.png)

Actual result: one-way arrows displayed _in opposite direction_ than mapped - note that only the ways in relation are affected (note that the southern part of the red route is now incorrectly shown as leading _to_ the intersection, not _away_ from it)
![reversed1](https://cloud.githubusercontent.com/assets/917239/7672475/8461dc06-fcf4-11e4-984f-869724c5e005.png)

Here's a minimal case manifesting the symptoms: http://i.piskvor.org/osm/mapsforge/praha-centrum-bugOnewayRelationOnly.osm , here's the same relation in OSM: http://www.openstreetmap.org/relation/2052491

Removing the way from relation restores expected behavior (one-way arrows point in the correct direction), but that's very much mapping for a renderer, and cripples the relation's data.

This issue appears both in the mapsforge Java viewer and in Android (Locus); I have also downloaded a map generated by someone else (from OSM via osmosis, probably similarly to me), and it exhibits the same symptoms: http://osm.paws.cz/czech_republic_ee.map

**Comment by applantation** [comment]
I have not double checked this, but this is quite possible: we had a
similar issue with circular ways. The reason this happened was that there
was an underlying assumption that a circular way was an area and areas
should have their ways run a specific direction.

I assume this here happens for very much the same reasons (plus to be able
to combine the ways into the multipolygon).

It is obviously wrong, thanks for reporting.

**Comment by devemux86** [comment]
I assume the aforementioned issue is #458.

**Comment by Piskvor** [comment]
The difference here is that there are multiple ways, not all are oneway, but the relation is closed. Note that the order of the ways in the relation is the same as with the oneway direction - not sure if this has any effect.
But yes, this looks very similar to the issue I am seeing - and the wrong direction is indeed clockwise.

**Comment by Piskvor** [comment]
Interesting. For 0.6.0 writer+reader, still present in the minimal case, and present when generated from a current countrywide extract - but not present when merged with contours and a current citywide extract. Will look how these differ.

**Comment by Piskvor** [comment]
Hm. The bug seems to fluctuate on and off - apparently it's somehow dependent on the surrounding features. Currently manifesting: http://maps.piskvor.org/praha-elevated_20160615.osm.map

**Comment by voldapet** [comment]
Hi,
is there any progress with this issue, please? This one-way highway https://www.openstreetmap.org/way/44741126 (and several others) has wrong orientation for one-way symbol in generated map. I used the map writer 0.10.0 and tested map in cruiser - see attached screenshot
![image](https://user-images.githubusercontent.com/29754122/53558558-849bd500-3b48-11e9-91bc-c3c0037c1607.png)

It seems that the way is reversed during conversion into JTS Geometry at https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/util/JTSUtils.java#L55  I only mention that the way is also member of several relations

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue with a small map sample if still valid.
