### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#613]
Right now in order for Mapsforge to function properly we disable hardware acceleration in manifest:

``` java
android:hardwareAccelerated="false"
```

Or disable hardware acceleration only for the map view:

``` java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)
    mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```

We need to investigate this issue.

**Comment by devemux86** [comment]
For reference, previous 0.3.X versions do not have this problem.

It can be easily triggered with consecutive ```LayerManager.redrawLayers()``` calls.

**Comment by devemux86** [comment]
It turns out to be mostly a thing of how we paint / erase the background of the canvas buffers.

With bf5fc6d99960753b87eaf390a4e1c91cf7227807 I pushed a fix on dev, moving the call to another less obtrusive point with remarkable results.

I enabled also hardware acceleration in Samples to test it.

More search is to follow for better results.

The related discussion at the forum is:
https://groups.google.com/forum/#!topic/mapsforge-dev/clHgWBfXErw

**Comment by ludwigb** [comment]
Whow, that would be an easy fix. I will test this soon.

**Comment by devemux86** [comment]
Essentially we have in different places fill with the background color. That gets in the way of consecutive redraws, which is apparent with hardware acceleration.

We certainly need to review it, it's significant also for the general performance.

I'm testing various implementations and was able to make it more stable, but it needs more refinement.

**Comment by devemux86** [comment]
A little more research and the issue is mainly from the calls [here](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map/src/main/java/org/mapsforge/map/view/FrameBuffer.java#L94-L96) and [here](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map/src/main/java/org/mapsforge/map/layer/TileLayer.java#L80-L82).

With hardware acceleration there is already have double buffering in Android level (besides our own), so any erase could trigger the buffers switch with the clear canvas / bitmap, aka flickering.

**Comment by devemux86** [comment]
Eventually I don't think moving to hardware accelerated drawing is so simple.
Another thing we have to see is the [unsupported drawing operations](http://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported) in our calls.

**Comment by applantation** [comment]
I am seeing a problem with hardware acceleration turned on with 4.1.1
devices and it can be reproduced with the genymotion emulator and the
Samples app.

The effect is that after the first draw, which is fine, everything then
appears slanted.

The problem is not there with 4.2 and further on (as far as I have tested
it).

Ludwig

**Comment by devemux86** [comment]
You mean like distorted?
I remember an old distortion issue #440.

That may be due to HA drawing operations got supported after that Android version.

**Comment by applantation** [comment]
Yes, that seems to be the same issue. Only on 4.1.

**Comment by devemux86** [comment]
Closing in favor of #919.
