### ISSUE TITLE
Village/Hamlet labels are not shown on zoom levels < 13

### ISSUE THREAD

**Issue by romanshuvalov** [mapsforge/mapsforge#614]
Greetings, I'm trying to get rendered village and hamlet labels on low zoom levels. I've got existing rendertheme XML file and modifying it:
```
<rule e="node" k="place" v="city|town|island|village|hamlet|isolated_dwelling" 
	zoom-min="10"> <!-- <===== 13 was here  -->
	<caption k="ele" dy="20" font-size="12" font-style="bold" 
		fill="#333380" stroke="#FFFFFF" stroke-width="2.0" />
</rule>
``` 
But these labels still appear only after zooming to 13 or even 14 level. 

I'm using OruxMaps (which is use mapsforge library to render vector maps) and use .map file that I've converted using osmosis with --mapfile-writer parameter. 

So, how to force mapsforge to render this labels on defined zoom levels? Same question about track roads, they are also rendered only after 14th zoom level and I need them to be rendered on smaller (10) zoom levels.

Thank you.

**Comment by ludwigb** [comment]
There are two distinct elements that govern what will be displayed, one of
them is the render theme.

But the render theme can only display what is included in the map file.This
is defined by the tag mapping in the tag-mapping.xml file. There is a
default tag mapping file for the map file writer which only includes tracks
and hamlets from level 13 and does not include isolated_dwellings at all.
You will need to change the tag-mapping.xml file from the default and pass
it on as a parameter to your map-building process.

Ludwig

**Comment by romanshuvalov** [comment]
Thank you for your explaination, I've created custom tag-mapping file, re-converted map and it worked. By the way, I'm creating specific type of map (for mountain biking) and there is a lot of map objects that are useless for this purpose, so in order to increase rendering performance I can hide them during exporting stage and actually remove them from the map. It was very useful to know about tag-mapping.xml. Thank you.

**Comment by devemux86** [comment]
I suggest also to study the [RenderTheme](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md) wiki where you can find more directives to aid you visualizing better your elements (like ```priority``` and ```display``` for overlap etc).

BTW for questions please try using our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
