### ISSUE TITLE
Missing islands / coastline

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#615]
Playing with latest maps and Osmarender, I see we have again the issue with islands under water and missing coastline.

The problem arises from ```natural=coastline``` declaration [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/resources/osmarender/osmarender.xml#L198-L205), which fills the islands on top of the ```nosea``` fill.

How about removing the aforementioned block or use as fill the ```nosea``` color?
Since it causes issues and now the land / sea elements are defined at different [location](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/resources/osmarender/osmarender.xml#L5-L11) in the theme.

![islands](https://cloud.githubusercontent.com/assets/3484020/7784246/876496f6-0167-11e5-8365-02ae5734fe42.png)

**Comment by devemux86** [comment]
And I see we have similar ```natural=coastline``` declaration (though with different fill) in [RenderThemeV4](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml#L151-L158) too.

**Comment by devemux86** [comment]
With 0dcd3d224fd6d2c867454c8b4ca4f38e3865ef8d I removed on dev the old coastline rules from the render themes which cause rendering issues.

**Comment by lincomatic** [comment]
I like the way it looks. I noticed that the coastlines were inconsistent, anyway. Does this mean we're ignoring coastlines? If so, shouldn't we disable coastlines in tag-mapping.xml as well?

**Comment by devemux86** [comment]
We used to paint the coastline with separate rules for ```closed``` or not and a fixed width for all zoom levels, which didn't look very good.

Now appearance is more clear, but some may still like to have coastline in their maps.
That's why I didn't remove it from ```tag-mapping```, to let them paint it if they want.
The land polygons, if they are split, cannot be used for that.
