### ISSUE TITLE
Square frame buffer

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#617]
Right now we are not using actually a square frame buffer, even if it is defined in the library for better handling device orientation changes.

**Comment by devemux86** [comment]
Fixed with 8293cf585733cb88cd97706410546112b6a591db.

**Comment by devemux86** [comment]
I see that the above change (which ensures that frame buffer is square), causes issues with tile cache.

Our automatic calculations are not sufficient anymore and we have random empty tiles.

**Comment by devemux86** [comment]
I'm reopening the issue to better handling it.

**Comment by devemux86** [comment]
Ludwig what's your opinion here?

In ```AndroidUtil``` we calculate the memory cache size based on screen sides, but in ```FrameBufferController``` we set the frame buffer as square.

**Comment by devemux86** [comment]
I see the ```useSquareFrameBuffer``` was introduced in the Rescue era, but do we really need it?
I can understand its usefulness in map rotation.

It's worth mentioning that until 8293cf585733cb88cd97706410546112b6a591db, we were not using square frame buffers and because of the ```useSquareFrameBuffer = true``` we never [changed](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map/src/main/java/org/mapsforge/map/controller/FrameBufferController.java#L88-L94) frame buffer's dimension.

**Comment by ludwigb** [comment]
IIRC, the reason for the square buffer was to avoid reallocating the frame buffer in case of an orientation change. It seemed to improved the memory situation despite actually being larger (the clue we now see is that we did not actually have a square buffer). With the bug that Emux discovered and fixed we now actually allocate a square frame buffer, so the frame buffer now needs more tiles than before meaning that the cache calculations are wrong. 

We now have the following options: 
-- do not use a square frame buffer unless set (for people who do their own rotation). This would bring it in some ways back to the previous situation, but with reallocation of the frame buffer when changing orientation. Could require too much memory on some devices.
-- change cache calculation: could technically also require too much memory on some devices. 

Other options?

**Comment by devemux86** [comment]
I see the same two options too.

BTW the device orientation change is something happening very often in app life cycle, we should somehow cover it.

But I'm thinking also that eventually all increments we do at frame buffer (also the ```overdrawFactor```) could be integrated into just using a square frame buffer with side the ```Math.hypot``` of the screen sides.

That way we have it all into one (actually we cover future map rotation - but that's another subject).

**Comment by devemux86** [comment]
With c73d655709096ac881eae1204e05321bb6f9f8be I made square frame buffer selectable for the user.

With ef1b3de1ca6832fdf5c7d81cab8bb66ed009a37b I changed the minimum cache size calculation to be based on frame buffer's dimension.

We now have larger cache (e.g. on a 1280x800 160dpi tablet from 44 to 64 tiles).
We'll see how it goes regarding memory consumption.

**Comment by devemux86** [comment]
>do not use a square frame buffer unless set (for people who do their own rotation). This would bring it in some ways back to the previous situation, but with reallocation of the frame buffer when changing orientation. Could require too much memory on some devices.

So far we hadn't a square frame buffer, so at every device orientation change, a reallocation happened.
At least users now can select if they want it or not.

>change cache calculation: could technically also require too much memory on some devices.

I changed cache calculation and with square frame buffer by default, we have now a larger cache, regarding memory and tiles production.

I'm still wondering which is the preferred way..

**Comment by devemux86** [comment]
I'm closing this as the situation has been fixed.

We still need to watch the memory consumption of the new implementation.
