### ISSUE TITLE
ReadBuffer Limit Too Small

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#619]
In ReadBuffer.java, 

    static final int MAXIMUM_BUFFER_SIZE = 2500000;

is too small for the Japan map, causing blank tiles.

![image](https://cloud.githubusercontent.com/assets/1422186/7866136/3dca73da-0522-11e5-9250-7dedd906320d.png)

**Comment by lincomatic** [comment]
The blocks in screencap above cause these warnings:

WARNING: current block size too large: 5752875
WARNING: current block size too large: 4813204

**Comment by devemux86** [comment]
Looking at the history I see that value hasn't changed, have you changed it and it worked?

BTW are you playing with Java or Android and at what resolution?

There can be empty tiles from improper memory cache size.
In Java I had increased the memory cache to 128.
In Android it's calculated automatically.

**Comment by devemux86** [comment]
Also with what map file (from where) is that test?

**Comment by ludwigb** [comment]
I think the problem might be the complex coastline or some complex
polygons.

We could increase the size in mapsforge, but the problem is that we need to
process all these points on the device, which is likely to result in OOM
errors.

Ludwig

**Comment by devemux86** [comment]
I remember a topic in forum about grey tiles where eventually there were changes in the map-writer regarding multi-polygons.

**Comment by lincomatic** [comment]
Map is from your server: http://download.mapsforge.org/maps/asia/japan.map
It happens w/ SwingMapViewer, Atlas Beta, anything that uses ReadBuffer.java. The data block is just too big to swallow. A lot of memory could be saved by streaming the data instead of buffering such a big chunk.

**Comment by lincomatic** [comment]
Warning message I posted above is from MapFile.java

				} else if (currentBlockSize > ReadBuffer.MAXIMUM_BUFFER_SIZE) {
					// the current block is too large, continue with the next block
					LOGGER.warning("current block size too large: " + currentBlockSize);
					continue;

**Comment by devemux86** [comment]
I pushed a change on dev making ```ReadBuffer``` limit adjustable.

Also I increased it at ```SwingMapViewer``` to test it (on Android we're more memory limited).
