### ISSUE TITLE
Simplify cleanup operations

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#620]
Developers often have difficulties to perform proper clean up and our [instructions](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#cleanup) contain many steps.
We should examine the option of providing a more simplified way for handling this.
Less grouped methods could suffice (with the needed internal checks).

**Comment by devemux86** [comment]
I pushed on dev a simplified ```MapView.destroyAll``` method, which groups all the appropriate calls (with the needed internal checks).

**Comment by devemux86** [comment]
Also I updated our Android ```SimplestMapViewer``` and Java ```SwingMapViewer``` samples to demonstrate its use.

**Comment by ludwigb** [comment]
I stumbled over the problem that using the destroyAll() method requires overriding the destroyMapViews() method in the MapViewerTemplate, as otherwise a double destroy of the FramebufferController will cause a crash. 

I think this is somewhat undesirable.

**Comment by devemux86** [comment]
Thanks for the feedback Ludwig.
The method is actually useful, specially for newcomers.

Its use is supposed to be outside strict directives, e.g. like in our [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/dev/docs/Getting-Started-Android-App.md) guide.

I had made a simple implementation in [SimplestMapViewer](https://github.com/mapsforge/mapsforge/blob/dev/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/SimplestMapViewer.java) where indeed we have to override some partial destroy methods just for the sake of it.

Or else we need to alter the base class (i.e. ```MapViewerTemplate```) and its derivatives. I can look at it.

**Comment by ludwigb** [comment]
I wonder if it should just be integrated into the MVT?
Am 04.08.2015 14:09 schrieb "Emux" <notifications@github.com>:

**Comment by devemux86** [comment]
You mean along with the partial destroy methods?

I had tried replacing them all and stopped for not breaking Samples modularity.
e.g. some examples need specific destroy.

**Comment by ludwigb** [comment]
>
> e.g. some examples need specific destroy.


True, at the end the last thing we want to do is introduce yet more
confusion.

**Comment by devemux86** [comment]
I changed ```MapViewerTemplate``` to use the ```destroyAll``` call and modified accordingly all Samples examples.
