### ISSUE TITLE
Map encryption

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#621]
We could handle maps built from proprietary data. Their providers may worry about how their data are used and exposed.

We can implement an Android / Java compatible encryption / decryption mechanism. This should be included in both map writer and reader.
It could possibly hurt performance but it'll be optional.

**Comment by ludwigb** [comment]
If we ever moved to sqlite we would get this for free:
https://www.sqlite.org/see/doc/trunk/www/readme.wiki

**Comment by RicoZ-OSM** [comment]
@ludwigb: SEE is not free and probably incompatible with mapsforge license.

Imho, don't worry about implementing anything like this. Anything that can be decrypted by mapsforge can be "stolen" by a rogue app with root privileges.
