### ISSUE TITLE
Avoid creating unnecessary objects

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#622]
Ongoing task of reducing number of unnecessary created objects.

http://developer.android.com/training/articles/perf-tips.html#ObjectCreation

**Comment by ludwigb** [comment]
Android lint is pretty good for this.

**Comment by devemux86** [comment]
Indeed though e.g. if doesn't catch the ```Rect``` creation in [AndroidPaint](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidPaint.java#L135-L147).

Should I close it in favor of #592 ?

**Comment by devemux86** [comment]
I'm closing this in favor of #592.
