### ISSUE TITLE
Sample - map file

### ISSUE THREAD

**Issue by mj10777** [mapsforge/mapsforge#629]
I would be nice if your sample application would use a small map for as a demo
- germany.map 1.6 GB

maybe berlin.map (25 MB) might be better

**Comment by devemux86** [comment]
We wouldn't want to push users to a specific map or storage method.

You can any map you want, provided you rename it as ```germany.map```.

**Comment by mj10777** [comment]
Then maybe the text should be rephrased using: 'called germany.map (any map file will do)'

For geopaparazzi, we would like to know if the classes 
* `MapGeneratorJob, TileDownloader,GeoPoint, Tile` from mapsforge-map-0.3.1-SNAPSHOT

still exist. I saw that there is now a ' Point'  class  instead of GeoPoint.

But if they still work in the same way
* we would like to get back to your latest version.

**Comment by devemux86** [comment]
>Then maybe the text should be rephrased using: 'called germany.map (any map file will do)'

Yes you are right here.

About the rest we could continue the conversation in mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev

0.3.X versions are really old, a lot has been refactored since then, API changes etc.
e.g. ```GeoPoint``` class is now ```LatLong```

**Comment by mj10777** [comment]
Yes, we know that, was very worrying. but we were told that the Tile-based support was going to be removed
* without that nothing, for us, would have worked any more

If this is not the case, I would try to get the latest version working with geopaparazzi at

https://github.com/geopaparazzi

**Comment by devemux86** [comment]
Actually raster tiles support is back again (there are examples in Samples).
