### ISSUE TITLE
could not find setRenderTheme

### ISSUE THREAD

**Issue by emdete** [mapsforge/mapsforge#630]
this doc https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md mentiones setRenderTheme() but i can't find it. i use 0.5.+ for testing.

**Comment by devemux86** [comment]
The proper syntax is ```tileRendererLayer.setXmlRenderTheme(new ExternalRenderTheme(File));```
(I corrected our docs)

Please use the mailing list for such questions:
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by emdete** [comment]
i think it's an issue because the doc states otherwise and should be fixed to make it easier for the next developer ;)

**Comment by devemux86** [comment]
@emdete I suppose you are right here :)
