### ISSUE TITLE
mix maps

### ISSUE THREAD

**Issue by emdete** [mapsforge/mapsforge#631]
can i mix maps in the view, for example switch to a satellite view and back to vector or even overlay a satellite one with transparent vector tiles with roads? if so can you provide a sample?

**Comment by devemux86** [comment]
Mapsforge supports several modes of operation, e.g.:
* Offline vector maps
* Online raster tile servers
* Offline tile stores

All these work via layers, so eventually you can handle their visibility or even stack them.
I suggest to take a look at the Samples app, it has many examples of the API.

Please use the mailing list for such questions:
https://groups.google.com/forum/#!forum/mapsforge-dev
