### ISSUE TITLE
RotateView

### ISSUE THREAD

**Issue by muganda** [mapsforge/mapsforge#632]
Greetings team...
I am using RotateView but i have a strange problem. If i do not use it, then the map loads just fine. If i use it, then the map displays okay and after a second or two displays a blank tile on part of the map. This keeps on happening when you change the zoom or move the map. 
Just wondering what the problem could be.

**Comment by devemux86** [comment]
Is the Samples Rotate example working for you?

It's important to follow its instructions for properly creating the tile cache.

Also do you have hardware acceleration on or off ?

Please use the mailing list for questions:
https://groups.google.com/forum/#!forum/mapsforge-dev
