### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#634]
Improve Mapsforge logging (e.g. with proper use of tags).

**Comment by ludwigb** [comment]
I am all in favour of this.

For me the main question is: what is actually the most efficient way of
logging where we can have a debug build (with lots of debug logging
enabled) and a release build (with most logging disabled).

If we can agree on a scheme, I would suggest a bulk change.

**Comment by devemux86** [comment]
We use 2 different logging frameworks (```java.util.logging``` and Android) because Mapsforge core modules are not platform specific (and avoiding external libs).
Using only ```java.util.logging``` would be convenient.

I'd suggest using the full class name as tag (including the ```org.mapsforge``` package).
That way we can watch closely e.g. specific class development.

If we want global ```org.mapsforge``` filtering at command line, this can be achieved via wildcards / regular expressions.

According to Android official [docs](http://developer.android.com/reference/android/util/Log.html): Debug logs are compiled in but stripped at runtime.

**Comment by devemux86** [comment]
Controlling the logging via a global flag in Android could be done via provided ```BuildConfig.DEBUG```.

**Comment by emdete** [comment]
i suggest to implement a logging wrapper that for android uses Log and for JVM uses java.util.logging. it's the only way to avoid libraries (which i like much). 

the wrapper should be efficient in the do-not-log decision (for example by consulting BuildConfig.DEBUG) and do the message formatting after. there is a message formatting class in java which has issues but it's the direction i would go.

**Comment by devemux86** [comment]
With f529cbac11e7bfc80bd424f09b06fdb5994d0d75 I scanned the whole Mapsforge code improving the logging and using proper tagging.

The situation right now is:
- In library modules we use Java Logging
- In Samples we use Android Logging

**Comment by devemux86** [comment]
I'd avoid filling Mapsforge with external dependencies (for many reasons).
We need to be very strict with this rule, to not lose control in the process.

Logging frameworks or facades are probably useful in applications.
But users usually find very annoying libraries that force them to use external loggers (or mix them with their own).
