### ISSUE TITLE
read buffer limit handling

### ISSUE THREAD

**Issue by emdete** [mapsforge/mapsforge#635]
if the limit is reached, the tiles are empty, the user doesn't see why & the app has no chance to get this information to inform the user of the fact. the only information is given in logcat:

```
W/MapFile ( 5338): current block size too large: 4871934
```

to improve the situation i would suggest to:
- mark the tiles somehow as broken (let the app provide an img for that case?) to make this visible to the user
- send an event to the app to make the app aware of what happened

**Comment by devemux86** [comment]
Thanks for the suggestions.

For reference it's related to #619.

**Comment by devemux86** [comment]
ReadBuffer is now adjustable.
