### ISSUE TITLE
Error after adding markers

### ISSUE THREAD

**Issue by Euphrates-Media** [mapsforge/mapsforge#636]
When I add markers to map and run app I receive these errors :

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
&
java.lang.ClassNotFoundException: Didn't find class "java.awt.Color" on path: DexPathList

**Comment by ludwigb** [comment]
it looks like you are somehow mixing libraries/platforms. The complaint is
about an AWT class (which is Java only, not available on Android), but you
are running on Android.
You will need to check where your call to color comes from.

**Comment by devemux86** [comment]
Check the [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md#components) for the proper libraries for each platform.

Please use our mailing list for questions:
https://groups.google.com/forum/#!forum/mapsforge-dev
