### ISSUE TITLE
LabelLayer: redraw

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#642]
Using ```LabelLayer``` with a map filled with grid based symbols, if we zoom in / out then only some map tiles are filled again with the symbols.

Often after pan / zoom we have empty areas and we need to move slightly the map in order to trigger a redraw.

**Comment by devemux86** [comment]
This behavior seems to appear when we return to already cached areas.
We see the cached map tiles but often not the symbols.

**Comment by devemux86** [comment]
And it occurs on Android, ```LabelLayer``` seems working fine on Java.

**Comment by devemux86** [comment]
@ludwigb any hint on this?

It's easy reproducible with Samples too (just zoom in / out at same area).

**Comment by ludwigb** [comment]
I do not see the tiles constantly reproducing, but the few tiles that I
have seen being recreated were outside of the map area. Just an observation.

**Comment by devemux86** [comment]
You mean we have wrong calculations about the visible tiles?

**Comment by devemux86** [comment]
I see we scan map view's all visible tiles but many come up empty in [TileBasedLabelStore.getVisibleItems](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/labels/TileBasedLabelStore.java#L69) (though they shouldn't), probably in a racing condition as this is totally random.

I associate it with ```MapWorkerPool``` job, where only the ```TileRendererLayer``` is triggered to redraw and not the ```LabelLayer```.

**Comment by devemux86** [comment]
I pushed fixes in both dev / master branches because of the different implementation.

**Comment by devemux86** [comment]
Essentially like #595 with ```LabelLayer``` we need to perform some actions independently of the normal ```TileRendererLayer```, in this case the redraw.
