### ISSUE TITLE
Invalid Number of Way Nodes

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#645]
It is a common occurrence to get a warning message from this block in MapFile.java:

			if (numberOfWayNodes < 2 || numberOfWayNodes > Short.MAX_VALUE) {
				LOGGER.warning("invalid number of way nodes: " + numberOfWayNodes);
				// returning null here will actually leave the tile blank as the
				// position on the ReadBuffer will not be advanced correctly. However,
				// it will not crash the app.
				return null;
			}
with numberOfWayNodes == 0. I'm guessing it's a bug in the map writer. An example is in japan.map, in the block where z=4,x=13,y=6

**Comment by devemux86** [comment]
I'm aware of this and see it often, specially on custom maps with a lot of complex lines / polygons.
I intend to check what actually happens under the hood.

**Comment by ludwigb** [comment]
We should check why the map writer writes 0 length ways into the file and probably remove them. But I suggest for stability that this is something past the next release (we do not crash at the moment, even though this is undesirable).

**Comment by devemux86** [comment]
+1

**Comment by lincomatic** [comment]
It's very strange... there is code in TDWay.java that specifically checks for a valid number of nodes before creating a TDWay:

		// only ways with at least 2 way nodes are valid ways
		if (way.getWayNodes().size() >= 2) {
			boolean validWay = true;

I don't understand how the 0 node ways are getting written out.

**Comment by ludwigb** [comment]
Are we maybe having an overflow in the reader?
Am 30.10.2015 08:00 schrieb "lincomatic" <notifications@github.com>:

**Comment by devemux86** [comment]
I haven't check out yet, but I'm able to quite easily reproduce the issue on maps with complex polygons, like isopleths.

**Comment by ludwigb** [comment]
Would be good to identify this.

**Comment by lincomatic** [comment]
I don’t think so. Code:

 

int numberOfWayNodes = this.readBuffer.readUnsignedInt();
if (numberOfWayNodes < 2 || numberOfWayNodes > Short.MAX_VALUE) {
   LOGGER.warning("invalid number of way nodes: " + numberOfWayNodes);

**Comment by ludwigb** [comment]
Emux,
can you share one of the polygons that trigger the problem?

**Comment by devemux86** [comment]
@ludwigb I sent a sample.

**Comment by ludwigb** [comment]
Playing around with this. First funny result: changing the names of objects
in the map (my objective was to identify the culpable geometries), results
in different elements to be reported invalid.

Can someone confirm this behaviour?

This would suggest to me that there is maybe nothing wrong with the
geometries, but somehow with either the encoding by the writer or the
reading of the encoding by the reader.

Ludwig

**Comment by devemux86** [comment]
>changing the names of objects in the map

What exactly do you mean?

BTW this shouldn't be something regarding our latest multilingual changes, it's an older issue.

**Comment by applantation** [comment]
I simply changed the value of the name attribute in the osm file.

My intention was to isolate a way that exhibits the problem, but changing
the name resulted in then different elements being reported as having a
0-element way.....

(I added a bit more debugging to output the name of 0-element ways first).

Ludwig

**Comment by lincomatic** [comment]
I think you're kn the right track that it might be an encoding/decoding bug. Could you share your OSM file?

**Comment by devemux86** [comment]
@lincomatic I PM you.

**Comment by lincomatic** [comment]
@devemux86,
Thanks. I've traced the bug to the writer. It's writing out ways with zero node count. I should have a fix soon.

**Comment by devemux86** [comment]
Interesting, will wait for the feedback.

**Comment by lincomatic** [comment]
The problem was that after clipping, some of the ways become degenerate and need to be filtered out. I have fixed it, but am having trouble getting my editor to match your indenting style. Can you recommend a tool to fix the indentation?

**Comment by ludwigb** [comment]
Fixing this would be good news, even better if the bug is in the writer and
does not need any changes in the client.

**Comment by lincomatic** [comment]
Yes, the bug was in the writer. The fix is in my PR: https://github.com/mapsforge/mapsforge/pull/719

**Comment by devemux86** [comment]
So far my writer tests with various map types did not show any side effects.

**Comment by applantation** [comment]
I have not seen any issues either, so I support promoting to master.
Let's just see if we get some other issues before making rc3.

I will merge later today, unless Emux beats me to it.

Ludwig
