### ISSUE TITLE
Zoom level global handling

### ISSUE THREAD

**Issue by emdete** [mapsforge/mapsforge#646]
please consider to put the zoom level limitation into the library. currently there are 3 places where zoom levels can be set:

 - at the online tile class

 - at the tile layer

 - at the zoom controls

none of these talk to each other automatically (for example if a online tile may have smaller limits than set in the controls).

**Comment by devemux86** [comment]
For reference we have modelled the core ```MapViewPosition``` class which handles centrally the map position and its limits.

The related discussion in the forum is [here](https://groups.google.com/forum/#!topic/mapsforge-dev/fxWqtnITmhA).

**Comment by devemux86** [comment]
Related to #662.

**Comment by devemux86** [comment]
I added `setZoomLevelMin` and `setZoomLevelMax` methods to `MapView` handling also the zoom controls.
