### ISSUE TITLE
Map buffer size not adjustable with mapsforge-map-reader-0.5.1.jar

### ISSUE THREAD

**Issue by schmidju** [mapsforge/mapsforge#654]
The default buffer size of 2500000 at the 'ReadBuffer' is to small for the current germany.map.
As it is mentioned in the changelog, the buffer size should be adjustable with version 0.5.1.

Unfortunately the current mapsforge-map-reader-0.5.1.jar from Jenkins does not containes these changes. I had to include the snapshot from the current master build to get a proper version.

**Comment by devemux86** [comment]
In changelog we mention the changes 'since' 0.5.1 version.
These are to be included in next 0.5.2 version.

These changes exist in dev branch and lately in master.

**Comment by schmidju** [comment]
Thanks for the explanation and please apology the false alarm.
