### ISSUE TITLE
Possible to add elements (nodes, ways, ...) to an existing map and to retrieve elements in a BBOX ?

### ISSUE THREAD

**Issue by geolives** [mapsforge/mapsforge#655]
Hello.

Is it possible in any way with the mapsforge library (reader - writer - ...) :

- to open an existing map (.MAP file already generated) and to add nodes or ways (coming from external sources) to that map file via addNode() / addWay() method (or equivalent)?

In mapsforge-maps-writer library, instanciating a new HDTileBasedDataProcessor using HDTileBasedDataProcessor.newInstance(configuration); only seems to work to create a brand-new file.

- to retrieve ways and nodes from a .MAP file in a BBOX in order, for example, to display a list of all nodes of some type in the BBOX of the map?

In mapsforge-map-reader library, I only find methods to retrieve elements based on a tile.

If you have codes example for these two cases, it would help me a lot :-)

Sorry if these questions have already been answered but I have not seen the answer to these questions on this github project or on the Web.

If it is not the appropriate place to post these questions, please tell me where I can post them.

Thanks in advance for your answers.

Best regards.

**Comment by devemux86** [comment]
- Map file is a ready binary format, not suitable for later updating (like a DB).

- Map reading is based on tile requests because of the map view structure, which shows map tiles for a specific region.

Please for questions use the mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
