### ISSUE TITLE
Marker.draw NPE at cleanup

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#659]
Playing with many markers on the map, occasionally at Android app exit (i.e. resources cleanup), I have seen NPE inside ```Marker.draw``` method, specifically for its ```bitmap```.

Though we check ```bitmap``` state at ```draw``` start, possible race conditions with ```Marker.onDestroy``` manage to nullify it prior ```draw``` exit.

It's worth investigating also if ```Bitmap```'s enclosing ```android.graphics.Bitmap``` is null or recycled at ```draw``` start. Probably we need to place checks for that too.

**Comment by virus-warnning** [comment]
Call stack
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth(AndroidBitmap.java:114)
at org.mapsforge.map.layer.overlay.Marker.draw(Marker.java:72)
at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:90)
at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

**Comment by devemux86** [comment]
I added a method to Mapsforge `Bitmap` for checking its internal (platform) bitmap validity.
Then this check is used centrally in `Marker.draw` method.

Let's see if we have any issues with that or we need to put the check in other places too.

**Comment by wish7code** [comment]
Looking forward to test this! I'll get a similar exception, although not directly related to markers:

    E/AndroidRuntime: FATAL EXCEPTION: main java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object
    at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth(AndroidBitmap.java:114)
    at org.mapsforge.map.scalebar.MapScaleBar.draw(MapScaleBar.java:264)
    at org.mapsforge.map.android.view.MapView.onDraw(MapView.java:291)
    at android.view.View.draw(View.java:15231)
    at android.view.View.draw(View.java:15140)
    ...

(Version org.mapsforge:mapsforge:0.6.0)

**Comment by devemux86** [comment]
That could happen if the `MapScaleBar.destroy` was called directly or indirectly from `MapView` destroy methods and the scale bar (i.e. the map view) is still in use.

**Comment by wish7code** [comment]
Thanks emux! Is this intended behaviour or shall I open a new issue?

I was trying to cleanup ressources, when my map frament becomes invisible:
    @Override 
    public void setUserVisibleHint(boolean isVisibleToUser) {
       if (mMapView != null) {
            // save map settings
            mMapView.getModel().save(mPreferencesFacade);
            mPreferencesFacade.save();
            mMapView.getModel().mapViewPosition.destroy();
            mMapView.destroyAll();
            mMapView = null;
        }
    }

**Comment by devemux86** [comment]
@wish7code the exception you mentioned should happen normally, maybe something in your app life cycle?

Calling `MapView.destroyAll` clears the resources and after that the map host (view / activity / fragment) should not be used again.

So in `onDestroy` is a good location as seen in our [docs](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#cleanup).
