### ISSUE TITLE
Writer language improved parsing

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#663]
The language matcher in OSMUtils.java only handles the alpha-2 code of ISO 639-1:

	private static final Pattern NAME_LANGUAGE_PATTERN = Pattern.compile("(name)(:)([a-z]{2})");

However, I've found language specifiers in OSM data which contain more than two characters...
e.g. 

		<tag k="name:zh-py" v="Gāoxióng Shì"/>

In the OpenStreetMaps wiki, there is also an example

name:ko_rm=Mweonga    (the name in Romanised Korean)

which is later corrected to

name:ko_Latn=Mweonga

The pattern matcher should just allow arbitrary characters. I would rewrite it myself, but I am not very good with regular expressions.

**Comment by lincomatic** [comment]
This appears to work OK:

	private static final Pattern NAME_LANGUAGE_PATTERN = Pattern.compile("(name)(:)(.{2,})");

or maybe should we should just use:

	private static final Pattern NAME_LANGUAGE_PATTERN = Pattern.compile("(name)(:)(.++)");

**Comment by devemux86** [comment]
That's a valid proposal.
Thanks @lincomatic for the regular expression examples.

**Comment by ludwigb** [comment]
+1

The proposed implementation is easy and should be done separately.

But when I read it I thought this should support something a bit more
complicated like falling back onto the main language if the sub-set is not
there, e.g. use es_ar if argentinian name is provided, else use es. There
must be some official algorithm for this, so we should not reinvent the
wheel.

Ludwig.

**Comment by devemux86** [comment]
Based on http://www.w3.org/TR/xmlschema11-2/#language we could use something like:
```
[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*
```

@ludwigb fall back with regular expression or by code?

**Comment by devemux86** [comment]
Online regex debugger: https://www.regex101.com/

**Comment by lincomatic** [comment]
This regular express is for the client (reader) side to handle potential fallback, correct?

NAME_LANGUAGE_PATTERN which I specified above is for the writer, which receives tags of the form:

 

name:language

 

unless we want to throw an exception where “language” isn’t specified in a specific way, using a more specific regex will just result in localized names to be thrown out.

**Comment by lincomatic** [comment]
Also, based on the example I extracted from the wiki above, the "_" may appear in a language specification as well.

**Comment by devemux86** [comment]
I wrote strictly a language regular expression (without the ```name:``` prefix).

This issue is about the writer, correct? What language we put in map file.
The reader will show what it'll find.

**Comment by devemux86** [comment]
>Also, based on the example I extracted from the wiki above, the "_" may appear in a language specification as well.

(Following the rules in tagging is an old story)
We can always make regex more versatile.

**Comment by ludwigb** [comment]
>
> Based on http://www.w3.org/TR/xmlschema11-2/#language we could use
> something like:
> [a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*
> @ludwigb <https://github.com/ludwigb> fall back with regular expression
> or by code?


I think we should stick with the official regular expression. There will be
cases in OSM data where yet more, but wrong codes are used. We cannot cater
to every OSM data bug and probably using a few names is not the end of the
world (if it is important, this should be fixed in OSM data).

I think the fallback mechanism is difficult and not a regex problem.
Android must have an implementation of some sort as it falls back onto a
more general language when the specific one is not there. Maybe we should
just provide a simple implementation (e.g. fall back to 2-letter code if
longer code is not available, with a hook option it a user wanted a more
complicated mechanism).

Ludwig

**Comment by devemux86** [comment]
>I think we should stick with the official regular expression.

@ludwigb which are you referring to?

About fallback +1.

**Comment by applantation** [comment]
[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*

**Comment by devemux86** [comment]
I pushed on dev the use of W3C XSD language pattern as defined [here](http://www.w3.org/TR/xmlschema11-2/#language).

I'm moving the fall back case in #664 to see it there.

**Comment by devemux86** [comment]
See also #624.

**Comment by lincomatic** [comment]
I tested your regex: "(name)(:)([a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*)" it returns 4 groups instead of 3.. the last group is ignored by the code. Is it for future use?

Also the regex is too stringent to allow certain languages present in current OSM data such as prc and zh_py.

Please also reference:
http://wiki.openstreetmap.org/wiki/Talk:Multilingual_names

it is safer to just pass the unfiltered language string through the regex, and let the user decide whether or not he wants to use the non-conformant ones.

I am also working on a function to rewrite certain inconsistent language tags that occur, such as zh_py & zh_pinyin, which are equivalent to zh-Latn-pinyin

**Comment by devemux86** [comment]
1st group in Java matching is the whole string, so actually we went from 4 to 5 groups now, last one coming from the greedy interpretation.
e.g. ```name:en-US``` gives (indexes 0-4): [name:en-US] [name] [:] [en-US] [-US]

I followed @ludwigb 's above suggestion to go with an official recommendation.
If we want really to cover all cases in OSM, then we don't need a RE.
Just splitting the string ```name:X``` and getting the ```X``` would do the job.
Opinions?

**Comment by devemux86** [comment]
I pushed an improved language pattern, for parsing also '_'.

**Comment by lincomatic** [comment]
OK, I've run the code the whole planet. After analyzing the output, I see that we need to make some changes. There are lots of tags with "name:qualifier" that are not really "name:language."

For instance, in Paris, There are many streets with "name:left" and "name:right" tags. (another issue.. there is no "name" tag at all ... prior code couldn't handle this, and resulted in no name for this particular road). With our current implementation, we end up with two "languages," "left" and "right."

An example: 
	<way id="25100898" version="7" timestamp="2014-12-18T21:54:04Z" changeset="27559644" uid="1830549" user="poivronvertbleu">
		<nd ref="245935906"/>
		<nd ref="3241774734"/>
		<nd ref="271026763"/>
		<tag k="ref" v="D 75"/>
		<tag k="name" v="Avenue Georges Clemenceau - Rue Pierre Brossolette"/>
		<tag k="highway" v="secondary"/>
		<tag k="name:left" v="Rue Pierre Brossolette"/>
		<tag k="name:right" v="Avenue Georges Clemenceau"/>
	</way>

There are also lots of other "name:qualifier" which do not pertain to languages. For instance:

name:alternative
name:backward

Also, there are lots of 3-letter languages, and a few that begin with 1 letter.  e.g 

s-latin
alb
prs

 Therefore, I advise that we change the regex to require the first field to be between 1-3 characters, rather than 1-8. I tried to modify your regex by:

(name)(:)([a-zA-Z]{1,3}([-_][a-zA-Z0-9]{1,8})*)

But this doesn't work because it results in a match for "name:left"

as "name" + "::" + "lef". I'm not good enough with regex, but what we really need is to have an expression that only allows 1-3 letters before a '-' or '_' character.

I would also like to propose that all "_" characters be rewritten as "-"
This way, "pt-br" will get merged with "pt_br," for instance.

**Comment by devemux86** [comment]
@lincomatic thanks for checking that.
I'm reopening the issue to review the regular expression.

>I would also like to propose that all "_" characters be rewritten as "-"
This way, "pt-br" will get merged with "pt_br," for instance.

You mean by code to make that conversion, the reason (and why not the reverse) ?

**Comment by devemux86** [comment]
@lincomatic see also @ludwigb 's https://github.com/mapsforge/mapsforge/issues/624#issuecomment-139202864.

**Comment by devemux86** [comment]
With 94b0557b109aeeb3ffa4ea24fbedadbcfacd856e I pushed merging of '_' to '-' in writer.

**Comment by lincomatic** [comment]
Yes, because the data contains both “pt_br” and “pt-br,” which are obviously equivalent.

I propose that “-“ be used rather than “_” because “-“ is more common.

**Comment by ludwigb** [comment]
As usual, there is a data quality issue in OSM. Is there really a point to
have a preferred_languages=* option? Without additional folding this does
not seem to be useful to anyone. I just cannot imagine a use case where
this makes sense.

As lincomatic's planet scan has shown, all these tags exist, but in the
whole scheme of things they are few, many of them errors, many (probably
well-) meant to mean something else, but the data such tagged is just not
useful.

To make this useful, additional folding would be needed, which would be
better spent on fixing the data in OSM.

Ludwig

**Comment by devemux86** [comment]
>Is there really a point to have a preferred_languages=* option?

I'd vote removing both * and - options.
1st leads to maps with practically unknown language content and 2nd is covered by not setting the option.
Not confusing the users, they should see a minimal command line API, i.e. setting only the needed languages or none.

**Comment by applantation** [comment]
+1

**Comment by devemux86** [comment]
>But this doesn't work because it results in a match for "name:left" as "name" + ":" + "lef".

I cannot confirm that in Java, "name:left" fails matching with 1-3.
(online regex testers may behave differently)

**Comment by devemux86** [comment]
I pushed an improved regex pattern, setting the 1st field to 1-3 characters and using non-capturing group for the rest.

**Comment by lincomatic** [comment]
That’s fine with me. I put * because it’s quite useful for testing/debugging the quality of the data, and mainly to see what languages are actually present.

**Comment by devemux86** [comment]
@ludwigb @lincomatic 
Have you tested latest language regex pattern, is it ok?

**Comment by lincomatic** [comment]
Looks good

**Comment by devemux86** [comment]
Ok, as I have not seen either any problems, I'm closing this issue.
