### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#669]
Implement clustering in adjacent markers.

**Comment by devemux86** [comment]
We have now a clustering example in Samples (thanks  @vennekamp for PR #707).

If we include the clustering in the library, the code needs proper refactoring (e.g. eliminating activity leaks).

**Comment by Ehsan-Naghipour** [comment]
I'm experiencing horrible flicker with marker clustering in Samples App which gets worse by adding more geopoints. This only happens when moving the map. I guess it's due to the resetting the viewport in ClusterManager class on every move event, but is't that all happening in a separate thread? or maybe because of redraw happening in the same thread it is usual?

**Comment by devemux86** [comment]
Have you [hardware acceleration](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#hardware-acceleration) enabled?

**Comment by Ehsan-Naghipour** [comment]
I think it is disabled because I'm using the pre-compiled apk of Samples App. By flickering I mean delayed/slow redrawing of markers only. I can post a video of issue if that helps. Also it's worth mentioning that I'm on Samsung Galaxy Grand 2 with android 5.1.1 custom rom (based on CM12).

**Comment by devemux86** [comment]
We have disabled HA in `master` branch (it's enabled in `dev`).

**Comment by Ehsan-Naghipour** [comment]
I'm referring to the official release here:
http://ci.mapsforge.org/job/0.6.0/

**Comment by devemux86** [comment]
(Releases also have HA disabled)

In `ClusterMapActivity` there is `Observer` addition to map view, which in [ClusterManager.onChange](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/cluster/ClusterManager.java#L338) each position change produces continuous re-clustering.

*As mentioned previously, we have not optimized the example.*

**Comment by vennekamp** [comment]
A delayed redraw of the markers was a normal behaviour in my commit. And
personally, I did not experienced it as a big issue. (With approx. 1000
objects clustered)

But as EMUX: Any improvements to the code would be helpful.....

Regards, Martin
Am 15.12.2015 15:38 schrieb "Ehsan-Naghipour" <notifications@github.com>:

**Comment by borbasl** [comment]
I use the sample code to cluster more than 4000 objects. In this case, the flickering was very annoying. So I enabled cluster drawing during clustering and also increased the bounding box of the viewport to prevent the flickering near the borders. It seems to be the solution for me.

ClusterMarker.java:
```
    @Override
    public synchronized void draw(BoundingBox boundingBox, byte zoomLevel
            , org.mapsforge.core.graphics.Canvas canvas, Point topLeftPoint) {
        Boolean isSelected = isSelected();
        if (cluster.getClusterManager() == null ||
                /*cluster.getClusterManager().isClustering ||*/
                this.getLatLong() == null) {
            return;
        }
        setMarkerBitmap();

```

ClusterManager.java:

```

   protected synchronized BoundingBox getCurBounds() {
                                        .
                                        .
                                        .
            /** North-West geo point of the bound */
            LatLong nw_ = projection.fromPixels(-mapView.getWidth()*0.5, -mapView.getHeight()*0.5);
//			Log.e(TAG, " nw_.latitude => " + nw_.latitude + " nw_.longitude => " + nw_.longitude );
            /** South-East geo point of the bound */
            LatLong se_ = projection.fromPixels(mapView.getWidth()+mapView.getWidth()*0.5,
                    mapView.getHeight()+mapView.getHeight()*0.5);

```

**Comment by pstorch** [comment]
Thanks @borbasl for this fix. Wouldn't it be good to integrate it into the example Cluster code?

**Comment by devemux86** [comment]
See example in samples.
