### ISSUE TITLE
FpsCounter lazy initialization

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#670]
Move ```FpsCounter``` initialization outside of ```MapView``` constructor.

It's an overlay rarely used and shouldn't be created always, but only on user's request.

**Comment by devemux86** [comment]
I tried converting ```FpsCounter``` to a ```Layer```.
It works but we have the same problem (like ```Grid```) with draw position shaking during pan due to not steady canvas position / size.

**Comment by lincomatic** [comment]
Does the FpsCounter actually work as it's supposed to? I see the value fluctuating up and down all over the place in the middle of drawing a screen that takes several seconds to draw. Isn't it supposed to update just once per frame?

**Comment by devemux86** [comment]
Well it's old code, we haven't touched its algorithm for a long time considering all the library changes, so it may require a review.

@ludwigb 
The question is if we still need to support it, which are its actual uses now?

**Comment by applantation** [comment]
A frame in this context is the hardware frame rate, so you would expect the
counter to go up and down as a the tiles on a screen are shown. It is an
indicator of how much we are blocking the main thread.

**Comment by devemux86** [comment]
We can close this, as the implementation is not actually heavy on resources.
