### ISSUE TITLE
MapView as a layout for native Android views?

### ISSUE THREAD

**Issue by schildbach** [mapsforge/mapsforge#680]
The old Google Maps v1 library had this wonderful feature where MapView would act as a geo-coordinate-aware layout. You would add views to the layout and they would follow all map panning and zooming.

```
mapView.addView(view, new MapView.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT,
	point, 
MapView.LayoutParams.BOTTOM_CENTER));
```

Here is how the view could look. Other than markers etc. it contains native Android buttons.

![device-2015-09-16-234321](https://cloud.githubusercontent.com/assets/743306/9919378/bd50f29e-5ccc-11e5-9c26-1ed50aaa01f4.png)

Is something like this planned for mapsforge?

**Comment by devemux86** [comment]
Agreed that it would be a useful feature to have in Mapsforge.
I have tried it in the past, not without issues at pan / zoom and neglected it.

Experiments could start as always in Samples app.

**Comment by schildbach** [comment]
This is the next feature I will work on shortly, if no one else beats me at it.

**Comment by devemux86** [comment]
Since we're dealing with a vector library, on top of my list would be allowing steplessly variable zoom levels (old issue #75). :smile:

**Comment by devemux86** [comment]
Thanks, merged with some improvements. Some remarks:
* View overlays are not handled properly during zoom scale animation
* Osmdroid similar implementation has also additional x/y offsets for the alignment locations (might be unnecessary)

**Comment by schildbach** [comment]
Thanks for merging.
Zoom scale animations: this will be fixed once we do proper zoom animations. Currently zoom animations are very local to MapViewPosition. Also see my comment about that on #688.
Offsets: if there is a usecase, we can easily add that. I never had one, as I was always anchoring to one of the 9 standard alignment points.
