### ISSUE TITLE
Jitpack

### ISSUE THREAD

**Issue by matteozajac** [mapsforge/mapsforge#691]
Hi, working on Android cannot download lib from Jitpack, could You add latest version, please

**Comment by devemux86** [comment]
How do you include Mapsforge in your project?

We support the usual methods ([jars](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md), Maven, Gradle).

About questions please use our mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
