### ISSUE TITLE
Overlay/Controls enhancements

### ISSUE THREAD

**Issue by schildbach** [mapsforge/mapsforge#696]
I will work on a few enhancements of the various controls and overlays, mostly look & feel.

First step is PR #695.

Next up: scale overlay, copyright overlay.

**Comment by devemux86** [comment]
Same recommendation applies with scale bar, as I did with zoom controls at https://github.com/mapsforge/mapsforge/pull/695#issuecomment-141816438.

Keep current scale bar intact and have a new one with the proposed functionality (specially on heavy modifications).

After all we should support (and we are) multiple expressions of a map control.
That way new custom controls could have their own life and evolution.

**Comment by devemux86** [comment]
Created #700 for customizable zoom controls, for having its own space.

**Comment by devemux86** [comment]
I'm closing this, scale bar can be tracked in its own issue.
