### ISSUE TITLE
how to achieve google animateCamera like functionality.

### ISSUE THREAD

**Issue by GitPiyush** [mapsforge/mapsforge#702]
Hello,

i want to move the cursor on the map which i am able to do animateTo function but i also want to keep my path north up just like we can do using google animateCamera. is it possible with Graphhopper android which uses Mapsforge mapview. Do you have any method that takes the current location and rotate the map in that direction.

**Comment by devemux86** [comment]
We don't have currently *native* map rotation in Mapsforge.
You can find an *external* map rotation example in [Samples](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/RotateMapViewer.java).

Please use out mailing list for questions:
https://groups.google.com/forum/#!forum/mapsforge-dev
