### ISSUE TITLE
Android 6/SDK 23/ Runtime Permission Support

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#704]
Android 6 introduces the new runtime permission system. This affects mapsforge at two points: storage and location. Setting the target SDK to 22 avoids the runtime permissions and, unless storage permission is revoked, mapsforge then runs on Android 6. 

However, to move forward mapsforge needs to support Android 6 and deal with runtime permissions, particularly if apps want to use new features introduced with SDK 23 (and up).

**Comment by devemux86** [comment]
How do you think we should connect Mapsforge with this?
(as permissions handling seems more a task for an application than its libraries)

**Comment by ludwigb** [comment]
9f657f1afaa introduces product flavors into our gradle build to build both a oldpermissions and runtimepermissions variant of the Samples app. oldpermissions is build with SDK 22, runtimepermissions with SDK 23 (or whatever will come next).

cc5ebead3dc clarifies permissons a bit: we only need read permission in the Samples app to read the external germany.map file, not for the cache (which writes to non-protected storage). If you have an app that has a map file somewhere in non-protected storage, you will not need to ask for the storage permission for SDK > 18.

**Comment by ludwigb** [comment]
dca8d897491 is first cut of solving the runtime permission problem for our Samples app. It is actually pretty tricky as the request process is asynchronous, so I needed to find something that can be restarted when the permission is granted and on which nothing else relies. 
For this I had to refactor a little bit the onCreate method, so that anything that accesses data on protected storage will have asked for permission first. I think this is technically safe as removing the storage permission seems to result in an activity recreation, so asking for permission in onCreate should be enough. 
If someone has a better solution, welcome.

**Comment by devemux86** [comment]
First thought: it bothers me having now also ```support``` dependencies in Mapsforge libraries.
There are many who don't use```MapViewerTemplate``` or could prefer their own permissions implementation.
I'm wondering if we could host the relevant code somewhere else (e.g. only in Samples).

**Comment by devemux86** [comment]
BTW I added ```extra-android-support``` in Travis, for passing the tests.

**Comment by ludwigb** [comment]
@devemux86 First thought: it bothers having now also support dependencies in Mapsforge libraries.

Probably a point. I guess another level of indirection could solve this.

**Comment by ludwigb** [comment]
I made the MyLocationOverview in Samples work with runtime permissions. I had considered extending the class, but some interface changes would have been required anyway to allow for the asynchronous nature of the permission request. 
If the permission is denied, the app keeps on asking until the user ticks the 'do not ask again' box. While this is not ideal, the main intent was just to have a working version. 

I think with this we have at least something that works on Android 6/SDK 23.

**Comment by devemux86** [comment]
:+1:

**Comment by devemux86** [comment]
Is there something else to check here?

**Comment by ludwigb** [comment]
I think this is done.
