### ISSUE TITLE
Android gestures options

### ISSUE THREAD

**Issue by babobka** [mapsforge/mapsforge#705]
Is there a way to disable pinch zoom? I've found this:https://groups.google.com/forum/#!topic/mapsforge-dev/3_FQZ97B4-Q
It says mapsforge has no API for this kind of operation, but it was in 2014. What do?

**Comment by devemux86** [comment]
There are some ways to accomplish that:
- Use ```MapView.setGestureDetector``` consuming the proper events in it
- Or even override ```MapView.dispatchTouchEvent```

If there is indeed need for such a functionality we could provide an appropriate API.

Please for questions use our mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by babobka** [comment]
Can you please provide some code?

**Comment by devemux86** [comment]
Try:
```java
mapView.setClickable(false);
```
Of override ```MapView.dispatchTouchEvent```, that would disable all touch functionality:
```java
@Override
public boolean dispatchTouchEvent(MotionEvent event) {
	return true;
}
```

**Comment by babobka** [comment]
But I still want all touch functionality to be able. With setClickable(false) I can not even move the map

**Comment by devemux86** [comment]
Sorry there is not such functionality, to selectively disable some touch gestures.

I'm reopening the issue to handle it in the future.

**Comment by devemux86** [comment]
I made the scale gestures optional at `TouchGestureHandler`:
```java
mapView.getTouchGestureHandler().setScaleEnabled(false);
```

In the future we could introduce even more options.

**Comment by devemux86** [comment]
I added also option for double tap gestures.
