### ISSUE TITLE
graphhopper zoom to current location 

### ISSUE THREAD

**Issue by spring1370** [mapsforge/mapsforge#708]
I'm using graphhopper for offline routing in android , How does my program show current location with mobile GPS
and after that zoom to that point (point of my current location ) ?

**Comment by devemux86** [comment]
You can check our Samples application, it has [examples](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/LocationOverlayMapViewer.java) for Mapsforge API.

For questions please use our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
