### ISSUE TITLE
Denying runtime permission disables zoom buttons

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#717]
In the LocationOverlayMapViewer in the Samples app: denying the location permission somehow disables the zoom buttons. 

To reproduce simply run the that example on an Android 6 device, deny the location permission. The zoom buttons will stop working. 

The connection is unclear.

**Comment by ludwigb** [comment]
It also disables the menu and the back button....

**Comment by devemux86** [comment]
And nothing strange in the log?

**Comment by ludwigb** [comment]
Seems to go into some sort of spin, repeating the following messages

11-09 22:03:10.386  1911 12237 W InputMethodManagerService: Window already
focused, ignoring focus gain of:
com.android.internal.view.IInputMethodClient$Stub$Proxy@bbb912b
attribute=null, token = android.os.BinderProxy@e09afee

11-09 22:03:10.399  1911  2656 I ActivityManager: START u0
{act=android.content.pm.action.REQUEST_PERMISSIONS
pkg=com.android.packageinstaller
cmp=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity
(has extras)} from uid 10746 on display 0

**Comment by devemux86** [comment]
The problem seems being in the consecutive calls we now have on ```LocationOverlayMapViewer.onResume``` which overflows the application.

So I moved the location handling at start / stop and added the ```onRequestPermissionsResult``` in target activity.

Though I think we need more checking of the whole situation.

**Comment by ludwigb** [comment]
That seems to have solved the problem (even though I do not quite understand why the activity permanently cycled through resume/pause).
