### ISSUE TITLE
How can I set listener for long click?

### ISSUE THREAD

**Issue by babobka** [mapsforge/mapsforge#718]
Is there any method for map view to set long click listener? mapView.setOnLongClickListener has no effect for some reason.

**Comment by devemux86** [comment]
See our [LongPressAction](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/LongPressAction.java) example in Samples.

For questions please use the mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
