### ISSUE TITLE
Ending your app

### ISSUE THREAD

**Issue by NamakeHU** [mapsforge/mapsforge#722]
What is the correct way to finishing an app?
I usually got this error when closing the app:

11-15 20:08:00.683: E/MapFile(1061): null
11-15 20:08:00.683: E/MapFile(1061): java.io.IOException
11-15 20:08:00.683: E/MapFile(1061): 	at java.io.RandomAccessFile.openCheck(RandomAccessFile.java:259)
11-15 20:08:00.683: E/MapFile(1061): 	at java.io.RandomAccessFile.seek(RandomAccessFile.java:704)
11-15 20:08:00.683: E/MapFile(1061): 	at org.mapsforge.map.reader.IndexCache.getIndexEntry(IndexCache.java:95)
11-15 20:08:00.683: E/MapFile(1061): 	at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:460)
11-15 20:08:00.683: E/MapFile(1061): 	at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:805)
11-15 20:08:00.683: E/MapFile(1061): 	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:138)
11-15 20:08:00.683: E/MapFile(1061): 	at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:121)
11-15 20:08:00.683: E/MapFile(1061): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
11-15 20:08:00.683: E/MapFile(1061): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
11-15 20:08:00.683: E/MapFile(1061): 	at java.lang.Thread.run(Thread.java:1019)

my closing code:

if ( locationManager != null )
{
	if ( NmeaL != null )
	{
		locationManager.removeNmeaListener(NmeaL);
		NmeaL = null;
	}

	locationManager.removeUpdates( main );
	locationManager = null;
}
						
if ( tileRendererLayer != null )
	tileRendererLayer.getMapDataStore().close();

if ( mapData != null )
	mapData.close();

finish();

**Comment by devemux86** [comment]
See our simple [guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md).

For questions please use the mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by NamakeHU** [comment]
Hi,

I just want to tell you about my app using mapsforge. Thank you for your
work, it is very cool.
http://mapet.nspace.hu

Cheers,
Laszlo

P.S.
Sadly on some devices still freezing, I can't figured out why.

Xperia Mini - ok (2.3.4) - my phone
Xperia E4g - freeze (4.4.4)
Samsung Galaxy S2 - freeze (4.1)
Samsung Galaxy A3 - ok (5.0.2)
Samsung Galaxy S5 - ok (5.0.2)
Navon Explorer 3g - ok (4.1)


2015-11-15 20:25 GMT+01:00 Emux <notifications@github.com>:

**Comment by devemux86** [comment]
Have you tried our [Samples](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md) application in those devices and see it plays correctly?

**Comment by NamakeHU** [comment]
I can not. Not my devices, just reports.

2015-11-22 11:32 GMT+01:00 Emux <notifications@github.com>:

**Comment by ludwigb** [comment]
I do not think that your app crashes with that exception. While this
exception can happen when the reader thread in mapsforge still runs after
the map file has been closed, we catch this exception and do not crash the
app. The exception gets logged, so you see it, but it is ignored and does
not affect the closing of the app.

Your app crashes because of something else, which might not have anything
to do with mapsforge.

Ludwig

**Comment by NamakeHU** [comment]
No, this is an other problem. This is what only I saw occasionaly, when my
phone connected to my computer and eclipse is running and I closing the
app. Not a big problem, not freezing, just error messages.

The freezing occurs on other devices when they scrolling and zooming fast.

2015-11-22 14:20 GMT+01:00 ludwigb <notifications@github.com>:

> I do not think that your app crashes with that exception. While this
> exception can happen when the reader thread in mapsforge still runs after
> the map file has been closed, we catch this exception and do not crash the
> app. The exception gets logged, so you see it, but it is ignored and does
> not affect the closing of the app.
>
> Your app crashes because of something else, which might not have anything
> to do with mapsforge.
>
> Ludwig
>
>

**Comment by devemux86** [comment]
I tried your app (as we do with all submitted apps) in an Android 4.4.4 emulator and I saw the map occasionally disappearing with scrolling. Have you modified Mapsforge functionality?

**Comment by NamakeHU** [comment]
yes, but only when pinch zoom is disabled.


2015-11-22 14:28 GMT+01:00 Emux <notifications@github.com>:
