### ISSUE TITLE
Samples: DownloadManager does not work with implicit WRITE_EXTERNAL_STORAGE permission in version 19 and above

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#723]
Samples 'Low Res World Background' example does not work with the implicit ```WRITE_EXTERNAL_STORAGE``` permission, for downloading the low res world.

See Android [issue 170734](https://code.google.com/p/android/issues/detail?id=170734): "DownloadManager does not work with implicit WRITE_EXTERNAL_STORAGE permission in version 19 and above".

**Comment by applantation** [comment]
I would suggest that we add this permission with a comment to make the
Samples app work.

**Comment by devemux86** [comment]
We have already the permission, but [implicitly](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/AndroidManifest.xml#L11-L13) declared.

You mean remove the ```android:maxSdkVersion="18"``` from it?

**Comment by devemux86** [comment]
I think the best approach for now is to remove the download process and simply notify the user for the need of ```world.map```, as we already do for the main map in Samples.

**Comment by ludwigb** [comment]
But the tile downloader works....maybe we should change to whatever
mechanism is used there.

**Comment by devemux86** [comment]
The main difference is:
- In tile download we (the app) are performing the download with plain http API and have the rights to write in storage.
- With ```DownloadManager``` we ask somehow an 'external' process to perform the task, i.e. access the user / app space which needs explicit permission.

**Comment by ludwigb** [comment]
Ok, I understand. I was wondering about the reason for the security
exception (so much about Google's recommendation to use Intents to work
with the new permission system ...).
I will have a look if we could just use plain http without much hassle.

**Comment by applantation** [comment]
Actually thinking about it, we should just explicitly add the permission,
as it solves the problem in the easiest fashion. With a comment added it
should be pretty clear to users and the Sample app is after all only a
Sample app (and if it uses another explicit permission is not really
tragedy).
What do you think?

Ludwig

**Comment by devemux86** [comment]
I agree with that.

e.g. I'm seeing now if we can fix the various crashes that can happen in our Samples if user does not have a main map file, or a second map in two maps example, or a tile store, etc.

I don't know if it's worth the effort, after all Samples is just code examples for users, not an app which has to be perfect in all possible ways.

**Comment by ludwigb** [comment]
Yes, not everything has to be perfect, but it would be better if it was a
bit clearer that the germany.map is actually just arbitrarily named.
We could do the same as with the world map, but download only the
berlin.map from our server (much smaller, I would not want to wait for a
1.4GB download).

With the tile store, maybe we could actually install this by default
somehow.

Ludwig

**Comment by devemux86** [comment]
For now I'm adding some more messages and moving the rest on buttons, as inside the examples they cannot be read due to activity finish.

**Comment by ludwigb** [comment]
+1, this should go into 0.6 as well as it does not affect the core
libraries, so the risk is small.

**Comment by devemux86** [comment]
I pushed the changes.

**Comment by devemux86** [comment]
I created #724 for keeping track of Samples improvements.

**Comment by devemux86** [comment]
@ludwigb so how should we handle this?
