### ISSUE TITLE
Question: where are label stored with the LabelLayer

### ISSUE THREAD

**Issue by demiantres** [mapsforge/mapsforge#726]
Hi,

This is  a question and not a bug report: With the current implementation labels such as road names are not drawn on the tiles but directly on a canvas (https://github.com/mapsforge/mapsforge/blob/master/docs/LabelLayer.md). If the tiles are cached in a file cache, where are the labels stored?  Or are labels always read from the the map file and never cached on disk?

**Comment by devemux86** [comment]
As seen in relevant [section](https://github.com/mapsforge/mapsforge/blob/master/docs/LabelLayer.md#the-new-approach): "The labels need to be redrawn for every redraw of the map".

BTW there is nothing mandatory in current implementation. You can use label layer or not.

For questions please use our mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev
