### ISSUE TITLE
Use several threads for parallel map tile rendering on multi-core CPUs

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#73]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 23, 2011 18:04:07_

As of today, (Android) smartphones have single core CPUs. But multi-core CPUs will be standard already in the near future. The LG Optimus 2x with its Nvidia Tegra 2 processor is one example, ready to be shipped in the next month.

To make better use of this additional CPU power, map rendering must be parallelised. The number of rendering threads should equal the number of available cores. Implementing this will probably be easy as the map rendering already works asynchronously and all critical data structures are synchronized. Doubling the number of worker threads will not speed up the rendering of a single map tile but double the output of map tiles per time unit.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=73_

**Comment by ludwigb** [comment]
This is work in progress in dev 29fd89a52ecd4b261

**Comment by devemux86** [comment]
I'm closing this, as the feature is considered implemented.

For problems see issue #591 or open a new one.
