### ISSUE TITLE
POI Search: SQLite wrapper

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#731]
- [x] SQLite R-tree wrapper
- [x] Native libraries (Android NDK)

**Comment by devemux86** [comment]
Related to #728.

**Comment by devemux86** [comment]
I'm reopening this to examine if we should provide the SQLite wrapper classes separately in its own module and not in `poi-android` like now.

**Comment by ludwigb** [comment]
I had actually been thinking about this today. My point of view is that we
should provide an implementation that works, but we should also make it
easy for users to supply their own sqlite implementation, e.g. if they
wanted to use spatialite. So swapping out the sqlite implementation should
be as easy as changing jars.

**Comment by devemux86** [comment]
I'll check it. Also see what can be done with the native libs.

**Comment by devemux86** [comment]
I put SQLite wrapper in its own module, for better handling it.

Though swapping SQLite implementations is not as simple as a jar change.
Each wrapper has usually different package, so an update in imports is often required.

**Comment by devemux86** [comment]
Move to SpatiaLite, see #807.
