### ISSUE TITLE
POI API connect with MapDataStore

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#742]
Connect POI API with `MapDataStore` for POI + Map interactivity.

**Comment by devemux86** [comment]
Related to #728.

**Comment by spyhunter99** [comment]
patiently waiting for this. I'd love to be able to query the database to find the closet town, city, landmark, etc

**Comment by devemux86** [comment]
We have already in `dev` the new [POI API](https://github.com/mapsforge/mapsforge/blob/dev/docs/POI.md).
