### ISSUE TITLE
POI Remove Code Duplication

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge#744]
The GeoCoordinate class is essentially a duplication of the LatLong class already present in mapsforge. My suggestion would be to replace the LatLong class with the poi GeoCoordinate class and adding whatever is missing from LatLong to it. The whole class would move into the mapsforge-core library. 

The rational for this is that first of all we do not want code duplication, plus using the same class will make adapting a poi store for the MapDataStore interface easier (plus no copying of data required).

**Comment by devemux86** [comment]
+1
(was already in my list)
Same goes for `WGS84` class too, i.e. all POI `core` components.

The rationale was that POI API was independent, but we need to connect it with Map API anyway.

**Comment by devemux86** [comment]
>My suggestion would be to replace the LatLong class with the poi GeoCoordinate

You mean merging their code, not changing the `LatLong` class name, as it's already in wide use.

**Comment by ludwigb** [comment]
Yes, the use of LatLong in user code that was my rationale for not changing
LatLong.

I am just refactoring this, unless you really want to do it.

Ludwig

**Comment by devemux86** [comment]
>I am just refactoring this, unless you really want to do it.

No, please go ahead!

**Comment by ludwigb** [comment]
ok, I will do it.

**Comment by ludwigb** [comment]
Stumbled over the ctor for GeoCoordinate(int, int), which assumes the input as E6 input, while GeoCoordinate(double, double) takes the input as is. 
So GeoCoordinate(1.0, 1.0) will produce a very different result from GeoCoordinate(1,1). 
I think this is asking for trouble and the (int, int) ctor should be removed.

**Comment by devemux86** [comment]
That's probably reminiscent from `Google Maps Android v1 API` which was followed those days:
```java
GeoPoint(int latitudeE6, int longitudeE6)
```
It'd be safe to remove it, since we don't use it anyway in Map API.

**Comment by ludwigb** [comment]
I made it a static method, it could actually be useful, LatLong::fromMicroDegrees(int, int)

**Comment by devemux86** [comment]
We have now degrees - microdegrees converters in both `LatLong` and `LatLongUtils`.
We should keep only one of them, presumably in `LatLongUtils` as it's already in use?

**Comment by devemux86** [comment]
I'm on it, to remove also some other duplicate methods in `LatLong` & `LatLongUtils`.

**Comment by ludwigb** [comment]
missed that, best to leave in LatLongUtils, in case someone already uses it.

**Comment by devemux86** [comment]
I pushed all the changes, moving also the static methods in `LatLongUtils`.
