### ISSUE TITLE
resizing maps view breaks displayed map (with HA)

### ISSUE THREAD

**Issue by nbxdevelop** [mapsforge/mapsforge#746]
mapsforge version: 0.6.0-rc1
Android target Version: 15
Android test devices: Samsung S2 (4.1.2) Samsung Galaxy XCover 2 (4.1.2) Samsung S3 (4.3)

*Setup*
We use a mapsforge offline map at the top of an activity. We put a button on top of the map to resize the whole map for a full screen view of the map. The button changes the layout weight of the view to increase and decrease the size of the view.

Here is a sample of the layout XML of the activity:
```xml
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingBottom="40dp"
        android:background="#f8f8f8"
        android:orientation="vertical">
        <RelativeLayout
            android:id="@+id/map_part"
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="0.4">
            <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/map_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="5dp">
            </FrameLayout>
            <ImageButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/btnMapSize"
                android:layout_marginRight="6dp"
                android:layout_marginTop="6dp"
                android:clickable="true"
                android:alpha="0.8"
                android:src="@drawable/map_fullscreen"
                android:theme="@android:style/Theme.Light"
                android:layout_alignParentBottom="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"/>
        </RelativeLayout>
        <ListView
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:id="@+id/entryListView"
            android:layout_weight="0.6"
            android:clickable="true" />

    </LinearLayout>
```
The activity adds a click listener on the image button that will find the *map_part* layout and increase the layout weight of it. The frame layout shows a simple layout containing the mapsforge map:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/mainView"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" >

    <org.mapsforge.map.android.view.MapView
        android:id="@+id/forgeMap"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:clickable="true"/>

    <ImageButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/mapCompas"
        android:layout_marginRight="6dp"
        android:layout_marginTop="6dp"
        android:clickable="true"
        android:alpha="0.8"
        android:src="@drawable/map_compas"
        android:theme="@android:style/Theme.Light"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"/>

</RelativeLayout>
```
The code of the fragment does not handle sizing of the map. Sizing and resizing is all done by default over the XML layout. We use the OSMARENDER theme for display.

*Issue*
When changing the size of the map over the button after the first or second resize the display of the loaded map changes and the map is displayed faulty. The map look like it is stretched and pushed to the rigth upper side. The map is still functioning and the map scale is not affected by this error. All drawn elements like markers, position marker and the map itself are affected.

I append a before and after image show the effect. 
![before](https://cloud.githubusercontent.com/assets/16191729/11629792/7f18c772-9cfa-11e5-8158-3fb0f2b9e2d7.png)
![after](https://cloud.githubusercontent.com/assets/16191729/11629794/82fad024-9cfa-11e5-938c-8eb2b348296b.png)

The effect does not disappear when we try to resize it again and again. It does not disappear when we try to change the display position or zoom level. A forced repaint does not help. 

The error is seen on the S2 and XCover 2 devices we use for testing. We can not see this ill effect on the S3. Maybe it is a concurency issue unlikely to happen on faster devices. On the S2 and XCover the error is seen all the time after 1 or 2 attempts to resize the map.

We tried to debug into the matter but all we found is that pivot is not the cause of the problem.

**Comment by ludwigb** [comment]
I think this is an issue related to Android 4.1.x.
I have seen something similar with emulators on that version only.

I have no explanation for it.

**Comment by devemux86** [comment]
Do you have hardware acceleration enabled?

Related to #440.

**Comment by nbxdevelop** [comment]
It was enabled by default not explicitly. Thank you! Disabling hardware acceleration in the activity fixed the issue. What it does to the performance we have to wait and see.

The official Android doc site mentions this problems too: http://developer.android.com/guide/topics/graphics/hardware-accel.html

**Comment by devemux86** [comment]
Currently we [recommend](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#hardware-acceleration) HA off with Mapsforge `MapView`.

I'm closing this as HA is monitored in #613.
