### ISSUE TITLE
POI: Case-insensitive matching of Unicode characters

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#747]
Official SQLite [docs](http://www.sqlite.org/lang_expr.html#like) and [FAQ](https://www.sqlite.org/faq.html#q18) state:

_SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range._

**Comment by ludwigb** [comment]
Is this a bug? I am not so sure it is, but I admit that this is an issue,
but not just limited to case-sensitive matching.

It also applies to many non-ascii characters, e.g. searching for "XYZ
Straße" (XYZ Street in German), many Germans would put "XYZ Strasse" (a
commonly used way to write the sharp-s without being a keyboard expert).
Same applies to accents in many languages (e.g. o != ó). English/American
English: Centre/Center etc pp

One way to deal with it is to "normalize" the spelling of words by
stripping out all accents/umlauts and store as lower case for searching
purposes, but retain the original name for display. Increases storage
required for names. Not sure how to work this for Center/Centre or
languages like Arabic.

Ludwig

**Comment by devemux86** [comment]
I changed the label because it's referred as 'bug' in SQLite [docs](http://www.sqlite.org/lang_expr.html#like). Do you think we should revert it?

I thought too about normalizing the names, but we have to consider also the multilingual POI (and categories) that would be probably implemented with many columns.

Another way is building the SQLite with proper unicode support. Though we have 2 platforms, Java for writer / reader and Android for reader.

**Comment by devemux86** [comment]
As it is not directly in our lib or breaking the feature, I put back the enhancement label.

**Comment by applantation** [comment]
+1, it is not our bug.

Dealing with it in a generic fashion is tricky and yes for multi-lingual
maps it gets even more difficult.

**Comment by devemux86** [comment]
See #1123.
