### ISSUE TITLE
POI: Database encyption

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#749]
We could handle POI built from proprietary data. Their providers may worry about how their data are used and exposed.

We can implement an optional SQLite encryption mechanism. This should be linked in both poi writer and reader.
https://www.sqlite.org/see/doc/trunk/www/readme.wiki

Related to #728.

**Comment by ludwigb** [comment]
+1 I am all for that, particularly as we do not really have to implement
anything apart from the hooking into sqlite provided services.

I do not see a link however how we would license a key for this. My
understanding is that we would need a key for development to make sure
everything works and then users would license their own key to encrypt
their data. Maybe, as we are not shipping a product, but having a open
source project we would get the development/test key for free or so.

Nice for playing, a good addition for serious users, not top priority.

**Comment by devemux86** [comment]
>I do not see a link however how we would license a key for this. My understanding is that we would need a key for development to make sure everything works and then users would license their own key to encrypt their data. Maybe, as we are not shipping a product, but having a open source project we would get the development/test key for free or so.

@ludwigb sorry I missed you here. I mean to provide a functionality to the users for encrypting / decrypting their DB. Apparently in both poi writer and reader (I updated issue description). If the DB has the module, then its use is up to the user for enabling it.

**Comment by ludwigb** [comment]
Yes, that is the way I understood it. But for testing we would need a key,
unless a dummy would just do.

**Comment by ksaihtam** [comment]
There is also a free implementation at https://github.com/rindeal/SQLite3-Encryption .
