### ISSUE TITLE
Allow for steplessly variable zoom level

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#75]
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 28, 2011 13:05:49_

Currently the map rendering works with fixed, discrete zoom levels (from 0 to 21). As we are rendering vectors, this should be improved by letting the user select an arbitrary zoom level at which the map is rendered and displayed.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=75_

**Comment by devemux86** [comment]
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.

**Comment by devemux86** [comment]
Fractional zoom in Mapsforge samples:

Zoom|Rotation + Zoom
-|-
<video src="https://github.com/cgeo/cgeo/assets/3484020/eac0c4d9-6891-44b4-a2b7-c30394f4f20f" width="50%"/>|<video src="https://github.com/cgeo/cgeo/assets/3484020/34e155ca-f5d6-4ea3-8ec5-51381a64afef" width="50%"/>
