### ISSUE TITLE
Multipolygons broken in latest Mapsforge

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#753]
As reported in [Atlas forum](https://groups.google.com/forum/#!topic/atlas-app/JMpKAAiXf7o) we have broken multipolygons in latest Mapsforge dev.
(screenshot by Christian)

I found that the issue arises at the change in closed way calculation from Euclidean distance to spherical distance (see [here](https://github.com/mapsforge/mapsforge/commit/f9b6059bb57ebe737eae32c3db4dc25a77338e66#diff-64dc68a7bd488ca2fd0f2124e1a5f8b8R126)).

@ludwigb can you explain why the change?
In a closed way the start and end points are extremely close (if not equal), so we can continue using the Pythagorean formula.

![multipolygons](https://cloud.githubusercontent.com/assets/3484020/11742260/149bf7b0-a007-11e5-8eb3-4b7b81ce2fb6.png)

**Comment by devemux86** [comment]
Actually the cause is quite different.
We make the closed way comparison in degrees, so we cannot use distance in meters for that.

I reinstated the Euclidean distance in degrees and changed the calculation fixing the issue.

**Comment by ludwigb** [comment]
There was no particular reason to change, it was just that the distance
method was not available in the GeoCoordinate class that became the LatLong
class.

I have not actually checked the data, so I do not know if in the OSM data
the points are identical and somehow there is a rounding problem making
them different. Declaring two points identical based on distance was and is
a hack.
