### ISSUE TITLE
reader: logged NPE in case of MapFileException

### ISSUE THREAD

**Issue by hgoebl** [mapsforge/mapsforge#754]
https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java#L302

When calling ctor of MapFile with non-existing mapFile, it tries to close the file.
In `closeFile()` there will always be a NPE which will be catched and logged 4 lines later.

An `if (this.databaseIndexCache != null)` before ~.destroy() would avoid that.

LOW PRIO!!

**Comment by ludwigb** [comment]
Thanks, fixed.

**Comment by devemux86** [comment]
@hgoebl thanks for the catch!
