### ISSUE TITLE
Persistent cache not draw tiles

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#764]
With the persistent cache enabled, there are cases after some working with the map, where areas appear empty without painted tiles.

**Comment by muZZkat** [comment]
I've seen this as wel, had a quick look but never got anything resolved

**Comment by ludwigb** [comment]
I have seen this too. But it is possible that empty tiles make it into the cache?

**Comment by devemux86** [comment]
I have not examined it further, possibly it's there from the start.

(Usually I don't use persistent cache as I find Mapsforge rendering fast enough)

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
