### ISSUE TITLE
MercatorProjection.longitudeToPixelX() enhance API

### ISSUE THREAD

**Issue by virus-warnning** [mapsforge/mapsforge#766]
MercatorProjection.longitudeToPixelX(double longitude, long mapSize) just support z=0, but
MercatorProjection.latitudeToPixelY(double latitude, byte zoomLevel, int tileSize) support any z value.

It makes me get pixel X like this:
```
double px = MercatorProjection.longitudeToPixelX(lng, 256) * Math.pow(2,z);
```

Hope these two methods have the same parameters.

**Comment by devemux86** [comment]
Valid request, I pushed the enhancement.

Note: you could use the `getMapSize(zoomLevel, tileSize)` method in the old API.

**Comment by ludwigb** [comment]
zoom level and tile size determine the map size, so the calculations are
available for all zoom levels. Why that particular method is missing I do
not know.

**Comment by devemux86** [comment]
I changed the title to better declare the change and closing this.

Thanks for the report.
