### ISSUE TITLE
How to display several MapsForge .map files?

### ISSUE THREAD

**Issue by 2ndGAB** [mapsforge/mapsforge#768]
Hello,

I'd like to display several MapsForge .map files with OSMDroid at the same time because France is cutted out in several regions.
I tried the code below. I don't know if it's the good way to it anyway, I have a problem with it.
When I zoom in and out, I briefly see all maps but I finally see only the last overlay because they are rendered with a with background instead of a transparent one.
So how to use several .map files?

And I also see that rendering such offline map seems to be slower than rendering online default one. Strange, why?

So my code is:

    boolean setMapsForgeTileProvider(){

        String path = Environment.getExternalStorageDirectory().getPath()+"/mapsforge/";
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();

        if (listOfFiles == null)
            return false;

        File mapFile = null;
        for (File file:listOfFiles){
            if (file.isFile() && file.getName().endsWith(".map")){
                mapFile = file;
                MapsForgeTileProvider mfProvider = new MapsForgeTileProvider(new SimpleRegisterReceiver(getActivity()), mapFile);
                final TilesOverlay tilesOverlay = new TilesOverlay(mfProvider, getActivity());
                tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
                mMapView.getOverlays().add(tilesOverlay);
            }
        }

        if (mapFile == null)
            return false;

        mMapView.setUseDataConnection(false);
        return true;
    }

Before my application calls ``setMapsForgeTileProvider()``, it calls ``setStdTileProvider()`` below:

    void setStdTileProvider(){
        if ((mMapView == null) || !(mMapView.getTileProvider() instanceof MapTileProviderBasic)){
            GenericMapView genericMap = (GenericMapView) rootView.findViewById(R.id.mapview);
            MapTileProviderBasic bitmapProvider = new MapTileProviderBasic(getActivity().getApplicationContext());
            genericMap.setTileProvider(bitmapProvider);
            mMapView = genericMap.getMapView();
            mMapView.setTileSource(TileSourceFactory.MAPQUESTOSM);
        }
    }

Regards,
Alain

**Comment by devemux86** [comment]
This code involves a mix of Mapsforge and Osmdroid.
Actually very old Mapsforge 0.3 API (we're over 0.6).

To use multiple maps now you can use MultiMapDataStore, see our [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/MapDataStore.md#multimapdatastore) and [Sample](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/MultiMapLowResWorld.java).

For questions please our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by 2ndGAB** [comment]
Hello devemux86,

After testing your Samples application, it seems that the problem is really existing.
I propose you to test it by downloading auvergne.map and rhone-alpes.map and naming these files germany.map and second.map and you will see this result:

http://i.imgur.com/E2qso89.png

So there is a problem with the white bacckground around the map region.

Regards,

**Comment by devemux86** [comment]
That's related to another more expensive [implementation](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/TwoMaps.java) using more than one renderer layers.
The reason for the lack of transparency is explained in #579 and has to do with the new maps / render themes construction.

(Above I mentioned a different newer way for playing with multiple maps)
