### ISSUE TITLE
ClusterMarker.onTap Toast

### ISSUE THREAD

**Issue by 2ndGAB** [mapsforge/mapsforge#771]
Hi,

in ``onTap()``, it should be interesting to add a test on ``ClusterManager.toast != null`` in case we are not interested to display a toast.

Alain

**Comment by devemux86** [comment]
You want to post any improvements you see with PR?

BTW current keeping of a `Toast` around (and a static one) is candidate for memory leaks with its (not weak) `Activity` reference. Would need a refactoring.
