### ISSUE TITLE
java.io.FileNotFoundException: mapsforge.map (Permission denied)

### ISSUE THREAD

**Issue by friedriich92** [mapsforge/mapsforge#773]
I am just trying to run the command "osmosis -v 10 --read-pbf /home/tecnic/albania-latest.osm.pbf --mapfile-writer /home/tecnic/test.map" from a Java Application running on my Tomcat. If I run on my terminal it finishes without errors, filling the mapsforge.map file. I don't know why it fills mapsforge.map because I am specificly telling I want test.map as the output. But well, when I run the command from my Java code it doesn't work, the error is this one:

SEVERE: error while writing file
java.io.FileNotFoundException: mapsforge.map (Permission denied)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
        at org.mapsforge.map.writer.MapFileWriter.writeFile(MapFileWriter.java:145)
        at org.mapsforge.map.writer.osmosis.MapFileWriterTask.complete(MapFileWriterTask.java:105)
        at crosby.binary.osmosis.OsmosisBinaryParser.complete(OsmosisBinaryParser.java:35)
        at crosby.binary.file.BlockInputStream.process(BlockInputStream.java:37)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:37)
        at java.lang.Thread.run(Thread.java:745)

jan 20, 2016 12:43:15 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFORMACIÓN: finished...
jan 20, 2016 12:43:15 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
DETAILED: total processed nodes: 113.298
jan 20, 2016 12:43:15 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
DETAILED: total processed ways: 20.658
jan 20, 2016 12:43:15 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
DETAILED: total processed relations: 31
jan 20, 2016 12:43:15 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFORMATION: estimated memory consumption: 80,45MB
jan 20, 2016 12:43:15 PM org.openstreetmap.osmosis.core.pipeline.common.PassiveTaskManager waitForCompletion
DETAILED: Task 2-mapfile-writer is passive, no completion wait required.
jan 20, 2016 12:43:15 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Pipeline complete.
ene 20, 2016 12:43:15 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Total execution time: 5306 milliseconds.

**Comment by devemux86** [comment]
See map writer [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md) for the proper syntax.
You need to set the output file via the `file=` option.

For questions please use the forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
