### ISSUE TITLE
Listener onTap() for Swing not exist

### ISSUE THREAD

**Issue by Radomiej** [mapsforge/mapsforge#774]
I'm checking source code and find that MouseEventListener don`t support onTap and onLongPress which work on android. 

I write own implementation MouseEventListener for swing based on Android Version(not tested in production)

```java

import org.mapsforge.core.model.LatLong;
import org.mapsforge.core.model.Point;
import org.mapsforge.map.awt.input.MouseEventListener;
import org.mapsforge.map.awt.view.MapView;
import org.mapsforge.map.layer.Layer;
import org.mapsforge.map.util.MapViewProjection;

public class MouseImprovedListener extends MouseEventListener{
	
	private final MapViewProjection projection;
	private final MapView mapView;
	
	public MouseImprovedListener(MapView mapView) {
		super(mapView.getModel().mapViewPosition);
		this.mapView = mapView;
		this.projection = new MapViewProjection(mapView);
	}
	
	public void mouseClicked(java.awt.event.MouseEvent e) {
		Point tapXY = new Point(e.getX(), e.getY());
		LatLong tapLatLong = projection.fromPixels(tapXY.x, tapXY.y);
		if (tapLatLong != null) {
			for (int i = this.mapView.getLayerManager().getLayers().size() - 1; i >= 0; --i) {
				Layer layer = this.mapView.getLayerManager().getLayers().get(i);
				Point layerXY = projection.toPixels(layer.getPosition());
				if (layer.onTap(tapLatLong, layerXY, tapXY)) {
					break;
				}
			}
		}
	};	
}

```

**Comment by devemux86** [comment]
I don't know if `long press` has an actual use in Java.

Your implementation appears fine. You can test it and post a PR.

Then we could include also a marker example in `SwingMapViewer` for the users.

**Comment by pgiu** [comment]
Thanks for the code ! I didn't realize there was no support for clicking on the map for the Swing version. 
I took your class and added a MouseListener to my current MapView instance. I know this is not the right way to use it, but thanks for the workaround.

`mapView.addMouseListener(new MouseImprovedListener(mapView));`

As @devemux86 said it may a good idea to include an example to show how to use it.

I replaced all the `Marker` instances in my project with `InfoMarker` objects as explained here: http://stackoverflow.com/questions/21582350/mapsforge-0-4-0-is-it-possible-to-implelment-a-marker-s-ontap-event

Hope this helps someone in a situation similar to mine.

**Comment by devemux86** [comment]
Yes `onTap` works in all layers (e.g. Marker) on both Android / Java platforms, albeit via different event origins.

**Comment by Radomiej** [comment]
I already rewrite orginal **MouseEventListener** class, but i must learn how send pull request:)


This is example how add support for tap event witch my external class  **MouseImproveListener**:

```java
private MapView createMapView() {
		MapView mapView = new MapView();
		mapView.getMapScaleBar().setVisible(true);
		if (SHOW_DEBUG_LAYERS) {
			mapView.getFpsCounter().setVisible(true);
		}
		// mapView.addComponentListener(new MapViewComponentListener(mapView));

		MouseEventListener mouseEventListener = new MouseImproveListener(mapView);
		mapView.addMouseListener(mouseEventListener);
		mapView.addMouseMotionListener(mouseEventListener);
		mapView.addMouseWheelListener(mouseEventListener);
		return mapView;
	}

```

and example how implement own logic in **Layer** extends class:

```java
TileDownloadLayer tileDownloadLayer = new TileDownloadLayer(tileCache, mapViewPosition, tileSource,
				GRAPHIC_FACTORY) {
			@Override
			public boolean onTap(LatLong tapLatLong, Point layerXY, Point tapXY) {
				System.out.println("OnTap: " + tapLatLong);				
				return true;
			}
		};
```

**Comment by devemux86** [comment]
I added the `onTap` listener for layers on Java, along with example in the Swing samples app.
