### ISSUE TITLE
How to make the sea appear?

### ISSUE THREAD

**Issue by 2ndGAB** [mapsforge/mapsforge#775]
Hello,

I see on your Application Samples, when go to the north of Germany, the sea is displayed in white instead of blue.

How to change it?

**Comment by devemux86** [comment]
That depends on what exactly map file (origin?) and render theme (Sample example?) is in use.

A render theme may not include the proper [tags](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md#render-theme) for displaying right a map.

Our integrated [Osmarender](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/resources/osmarender/osmarender.xml#L6-L12) theme and Samples [RenderThemeV4](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml#L144-L150) have these rules.

For questions please use our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
