### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#777]
It's a fact that night mode for map appearance can be done already by updating the render themes.

We could provide a more "quick" implementation regardless of render theme or tile layer type, by playing with color filtering of the map.

This apparently has to be workable differently in Android and Java platforms, but with common API.

Also in case of `LabelLayer` and its separate rendering, we need to take care the colors additionally for it.

**Comment by spyhunter99** [comment]
We have used a ColorFilter in osmdroid for the past few versions. It doesn't appear to affect performance and it works ok, but it's not really ideal. My 2 cents, a theme specific for night mode would be the best visually

**Comment by devemux86** [comment]
A 'night' theme is feasible and probably the intended solution. But there are so many theme variants out there, we cannot satisfy all needs by providing just a new one (like our two defaults).

What I'm thinking here is converting any theme in 'night' rendering. Initial tests in totally different Android / Java implementations show that we can play with the theme colors (albeit globally).

Important is starting from our common platform API and decide the processing hook, having in mind support for all our features.

**Comment by devemux86** [comment]
I pushed Android / Java implementations with the usual inverse color filtering per platform.

The night mode can be triggered via `DisplayModel.setColorInvert` and is performed live without modifying the cache.

I didn't change `LabelLayer` drawing. Do we want it too for a more common result?

**Comment by devemux86** [comment]
Some RenderThemeV4 screenshots in different coloring.

![day](https://cloud.githubusercontent.com/assets/3484020/12760291/60b34dcc-c9ee-11e5-83b3-0b49a30a8b1a.png)

![night](https://cloud.githubusercontent.com/assets/3484020/12760297/6558620e-c9ee-11e5-91c9-45ee6dad16fc.png)

**Comment by devemux86** [comment]
The new `LabelLayer` after filtering only the `TileRendererLayer`.

![labellayer](https://cloud.githubusercontent.com/assets/3484020/12760570/a83ff414-c9ef-11e5-8338-2037e01ba9c1.png)

**Comment by applantation** [comment]
+1

works very well just out of the box

**Comment by devemux86** [comment]
I have some second thoughts about the outcome, that's why the issue is still open.

It'll be good to have also the `LabelLayer` completely featuring this too, besides only the below tiles.

I'm looking at a different implementation, originating with color conversion during render theme reading.
That way we have better performance and the cache will host the modified colors.

But a number of changes are needed in elements API inheritance, still checking this..

**Comment by devemux86** [comment]
@ludwigb also is `DisplayModel` the appropriate place for hosting that option?

**Comment by devemux86** [comment]
Closing this in favor of the more generic #778.

**Comment by AlexKwakIT** [comment]
Thanks in advance!
