### ISSUE TITLE
Color filtering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#778]
Introduction of color filtering in map rendering.

Should be implemented in both platforms Android / Java.

Note: special care is needed for `LabelLayer` overlaying.

**Comment by devemux86** [comment]
I pushed an initial implementation of color filters in map rendering.

It's a more rational approach and we can proceed from here more easily.

**Comment by devemux86** [comment]
Apparently we can handle the filters in a more central location.

Above commit implements that - affecting all tile layers.
Plus `LabelLayer` now functions correctly.

**Comment by devemux86** [comment]
I pushed the annotations implementation of color filtering.
That fixes `LabelLayer` drawing in all levels.

Also added some new grayscale filters to play with.

**Comment by froux** [comment]
Great ! I was precisely looking at customizing theme for night mode rendering, I have tested this feature that you committed yesterday, it's perfect ! Exactly what I need and Filter color usage is elegant. I don't know if you see this side effect : i've sometimes to recenter the map in order to filter changes is made.

This features is great but I now embed a dependency to your #325 build jar with dependencies. Do you know when you plan to release the 6.1.0 ? 

Thanks for your wonderful framework, and thank you in advance for your response !

**Comment by devemux86** [comment]
The recommended way for night mode is always with a render theme. But for faster results we can play directly with the map colors.

>I don't know if you see this side effect : i've sometimes to recenter the map in order to filter changes is made.

Can you explain more what happens?
Also test the latest implementation and is it with `LabelLayer` or not?

>Do you know when you plan to release the 0.6.1 ? 

We don't have currently immediate plans for a release, we'll see in the future.
You can always use our latest features via [downloading](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md) jars or [JitPack](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md#jitpack).

*Note: Our Jenkins server has currently a building issue. To be resolved soon.*

**Comment by froux** [comment]
The symptoms : 
I invert colors
`this.mapView.getModel().displayModel.setFilter(nightMode ? Filter.INVERT : Filter.NONE);`

It seems that sometimes, if user don't interact with map, no changes occurs on screen (color not inverted). I have to call this in order that color changes is make immediately
`this.mapView.getModel().mapViewPosition.setCenter(this.mapView.getModel().mapViewPosition.getCenter()); `

I think I use the last implementation (yesterday build) and we don't use LabelLayer.

We plan to release our app for beginning of April, do you think with your experience that we can reasonably hope for a 6.1.0 (or 6.0.1) stable ?

Regards,

**Comment by devemux86** [comment]
Setting a color filter does not automatically refresh the existing map.
You can try the following and check the result:
```java
mapView.getLayerManager().redrawLayers();
```

I cannot foresee right now our next release, usually we expect the [changelog](https://github.com/mapsforge/mapsforge/blob/dev/docs/Changelog.md) to justify that enough.
But until then we always merge `dev` onto more stable `master` branch for the users.

**Comment by froux** [comment]
Thanks for refreshing tips. 

Nice changelog, POI search is a feature I'll look at the end of my project too :D

**Comment by devemux86** [comment]
Since none problem has been reported on this new feature, I'm closing it.

Note that we have now a ready infrastructure for playing with more color filters in the future.
