### ISSUE TITLE
PoiPersistenceManager.findNearPosition() Unable convert LatLong to PointOfInterest

### ISSUE THREAD

**Issue by chathura1** [mapsforge/mapsforge#779]
declaration here:
```
private static final String POI_FILE = "/storage/sdcard/" +  APPNAME +   "/berlin.poi"; 
private static final LatLong BRANDENBURG_GATE = new LatLong(52.516273, 13.377725); 
	
	
private PoiPersistenceManager pm;
private PoiCategoryManager cm;

```

meat of code:
```
pm = AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(POI_FILE, false);
cm = pm.getCategoryManager();

int distanceMeters = 2000;
int limit=100;
String searchpoi="Berlin Hauptbahnhof";
Collection<PointOfInterest> pois = pm.findNearPosition(BRANDENBURG_GATE, distanceMeters, null, searchpoi, limit);
pm.close();
```

There is bug in the findNearPosition where it is unable to convert LatLong type to PointOfInterest.

java.lang.ClassCastException: org.mapsforge.core.model.LatLong cannot be cast to org.mapsforge.poi.storage.PointOfInterest

Also there is no factory PoiPersistenceManagerFactory.java file in the poi folders.  I had to use the AndroidPoiPersistenceManagerFactory.java.   Also, please make code you write Java 1.6 compatible so can be used in any Android project.

**Comment by devemux86** [comment]
Have you checked our Sample [example](https://github.com/mapsforge/mapsforge/blob/dev/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/PoiSearchViewer.java)?

Note that POI API [consists](https://github.com/mapsforge/mapsforge/blob/dev/docs/Getting-Started-Developers.md#components) of platform unspecific and Android / Java specific modules.

About the exception, do you have a full log to help us understand the exception?

>Also, please make code you write Java 1.6 compatible so can be used in any Android project.

What do you mean here?
Android is now compatible up to Java 7.

**Comment by chathura1** [comment]
I found out I had to change PoiImpl.java file where Tag.KEY_VALUE_SEPERATOR is not visible.

```
	@Override
	public List<Tag> getTags() {
		List<Tag> tags = new ArrayList<>();
		if (this.data != null && this.data.trim().length() > 0) {
			String[] split = this.data.split("\r");
			for (String s : split) {
				if (s.indexOf(Tag.KEY_VALUE_SEPARATOR) > -1) {
					tags.add(new Tag(s));
				}
			}
		}
		return tags;
	}
```
To
```
public List<Tag> getTags() {
		List<Tag> tags = new ArrayList<Tag>();
		if (this.data != null && this.data.trim().length() > 0) {
			String[] split = this.data.split("\r");
			for (String s : split) {
				if (s.indexOf('=') > -1) {
					tags.add(new Tag(s));
				}
			}
		}
		return tags;
	}
``

In AbstractPoiPersistanceManager.java
I am getting <> Operator not allowed in source below 1.7
```
	protected AbstractPoiPersistenceManager() {
		this.ret = new ArrayList<>();
	}
```

```
	protected AbstractPoiPersistenceManager() {
		this.ret = new ArrayList<PointOfInterest>();
	}
```

I found out the error is in compiling AbstractPoiPersistenceManager.java

```
	/**
	 * {@inheritDoc}
	 */
	@Override
	public Collection<PointOfInterest> findNearPosition(LatLong point, int distance,
														PoiCategoryFilter filter, String pattern,
														int limit) {
		double minLat =  point.getLatitude() - LatLongUtils.latitudeDistance(distance);
		double minLon =  point.getLongitude() - LatLongUtils.longitudeDistance(distance, point.getLatitude());
		double maxLat = point.getLatitude() + LatLongUtils.latitudeDistance(distance);
		double maxLon = point.getLongitude() + LatLongUtils.longitudeDistance(distance, point.getLatitude());

		return findInRect(new BoundingBox(minLat, minLon, maxLat, maxLon), filter, pattern, limit);
	}
```

point.getLatitude() should be changed to point.latitude.

devemux86: thank you for pointing out the sample.

**Comment by devemux86** [comment]
I think you need to have a look at your classpath dependencies, as some modules depend on others.

The project is compiled fine and we actually mention the Samples `POI search` example in the docs related [section](https://github.com/mapsforge/mapsforge/blob/dev/docs/POI.md#example).

About Java, Android is now mostly compliant with 1.7, so that's the [required](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md#requirements) version to use.

**Comment by chathura1** [comment]
Hi, can you post a FULLY CONTAINED eclipse android project with all required .jar files and libraries with applications/android/samples/PoiSearchViewer.java?  I am wasting lot of time trying to get right libraries working with [offline .map file example](https://github.com/mapsforge/mapsforge/blob/dev/docs/Getting-Started-Android-App.md) .  This will help user community get up to speed and start using right away.

Much appreciated your feedback.

**Comment by devemux86** [comment]
Usually the recommended way is to use a build automation tool like Gradle or Maven.

Playing with jars, you can see the [wiki](https://github.com/mapsforge/mapsforge/blob/dev/docs/Getting-Started-Developers.md#components) for the needed modules per platform and third party libraries.
Our jars can be found in [downloads](https://github.com/mapsforge/mapsforge/blob/dev/docs/Downloads.md) section.

e.g. in Android Map+POI case you'll need from us:
mapsforge-core, mapsforge-map, mapsforge-map-reader, mapsforge-poi
mapsforge-map-android, mapsforge-poi-android, sqlite3-android

and third party libs:
[kXML2](http://www.kxml.org/), [androidsvg](http://bigbadaboom.github.io/androidsvg/)

**Comment by devemux86** [comment]
Any further questions can be handled in the forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
