### ISSUE TITLE
Out of memory org.mapsforge.map.android.graphics.AndroidGraphicFactory.createTileBitmap(AndroidGraphicFactory

### ISSUE THREAD

**Issue by chathura1** [mapsforge/mapsforge#783]
Here is my test code:
              mapView = (MapView)findViewById(R.id.mapView);
		
		mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);

		mapView.setClickable(true);

		tileCache = AndroidUtil.createTileCache(this, "mapcache",
				mapView.getModel().displayModel.getTileSize(), 1f, 
				mapView.getModel().frameBufferModel.getOverdrawFactor());

		mapView.getModel().mapViewPosition.setZoomLevel((byte) 15); //15
		mapView.getMapZoomControls().setZoomLevelMin((byte)15);
		mapView.getMapZoomControls().setZoomLevelMax((byte)20);

             // tile renderer layer using internal render theme
				tileRendererLayer = new TileRendererLayer(tileCache,
						mapView.getModel().mapViewPosition, false, AndroidGraphicFactory.INSTANCE);
				tileRendererLayer.setMapFile(mapFile);
				tileRendererLayer.setXmlRenderTheme(InternalRenderTheme.OSMARENDER);
				
				// only once a layer is associated with a mapView the rendering starts
				mapView.getLayerManager().getLayers().add(tileRendererLayer);
	
				mapView.setClickable(true); //true
				mapView.setBuiltInZoomControls(true);
				//mapView.setBuiltInZoomControls(false); //disable zoom bar when clicked
				mapView.getMapScaleBar().setVisible(true); //false
				mapView.repaint();
		

but It crashes with this output:
02-11 17:48:40.810: I/dalvikvm-heap(26684): Forcing collection of SoftReferences for 524304-byte allocation
02-11 17:48:40.920: D/dalvikvm(26684): GC_BEFORE_OOM freed 73K, 8% free 30228K/32552K, paused 109ms, total 109ms
02-11 17:48:40.920: E/dalvikvm-heap(26684): Out of memory on a 524304-byte allocation.
02-11 17:48:40.920: I/dalvikvm(26684): "MapWorker" prio=3 tid=17 RUNNABLE
02-11 17:48:40.920: I/dalvikvm(26684):   | group="main" sCount=0 dsCount=0 obj=0xb4856938 self=0xb8217d88
02-11 17:48:40.920: I/dalvikvm(26684):   | sysTid=26842 nice=13 sched=0/0 cgrp=apps/bg_non_interactive handle=-1206699768
02-11 17:48:40.930: I/dalvikvm(26684):   | state=R schedstat=( 14900000000 37480000000 9599 ) utm=1441 stm=48 core=0
02-11 17:48:40.930: I/dalvikvm(26684):   at android.graphics.Bitmap.nativeCreate(Native Method)
02-11 17:48:40.930: I/dalvikvm(26684):   at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
02-11 17:48:40.930: I/dalvikvm(26684):   at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
02-11 17:48:40.930: I/dalvikvm(26684):   at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.android.graphics.AndroidBitmap.createAndroidBitmap(AndroidBitmap.java:52)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.android.graphics.AndroidTileBitmap.<init>(AndroidTileBitmap.java:135)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.android.graphics.AndroidGraphicFactory.createTileBitmap(AndroidGraphicFactory.java:212)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:176)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:86)
02-11 17:48:40.930: I/dalvikvm(26684):   at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:63)
02-11 17:48:40.940: I/dalvikvm(26684):   at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
02-11 17:48:40.940: W/dalvikvm(26684): threadid=17: thread exiting with uncaught exception (group=0xb3aedb90)
02-11 17:48:40.940: E/AndroidRuntime(26684): FATAL EXCEPTION: MapWorker
02-11 17:48:40.940: E/AndroidRuntime(26684): Process: com.example.offlinemapsforgesample, PID: 26684
02-11 17:48:40.940: E/AndroidRuntime(26684): java.lang.OutOfMemoryError
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at android.graphics.Bitmap.nativeCreate(Native Method)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.android.graphics.AndroidBitmap.createAndroidBitmap(AndroidBitmap.java:52)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.android.graphics.AndroidTileBitmap.<init>(AndroidTileBitmap.java:135)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.android.graphics.AndroidGraphicFactory.createTileBitmap(AndroidGraphicFactory.java:212)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:176)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:86)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:63)
02-11 17:48:40.940: E/AndroidRuntime(26684): 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

I am not sure what is causing it to run out of memory.

**Comment by devemux86** [comment]
Android version (or device) ?

Also which Mapsforge version, because I see very old API, can you try latest release?

**Comment by chathura1** [comment]
This error was appearing in AVD.  It was a bug with AVD. I just deleted AVD and re-created it went away. I am using version 0.4.3 jars.
