### ISSUE TITLE
Multipolygon ignores layer information

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/mapsforge#784]
It seems that the layer information (-5 ... +5) is ignored for multipolygons. That is a problem in large cities where the (complex) undergroud infrastructure (eg. subway stations) is mappt. An example for this is Berlin Alexanderplatz.

That's what I expect (screenshot from OSM website):

![bildschirmfoto 2016-02-14 um 14 41 58](https://cloud.githubusercontent.com/assets/5493128/13055279/c24f4138-d40e-11e5-8500-be8ece13a445.jpg)

... and this is what mapsforge renders (screenshot from atlas 1.2.1, critical is the meadow area in the lower right corner, a multipolygon with layer=-1):

![bildschirmfoto 2016-02-15 um 17 44 13](https://cloud.githubusercontent.com/assets/5493128/13055312/f0c82fe8-d40e-11e5-9e34-ec989c069ccc.jpg)

Link to the (temporary) OSM test area: http://www.openstreetmap.org/#map=18/52.01350/7.48968

Regards Klaus

PS: And this is the tagging for the critical area:

landuse=meadow
layer   =-1
name=Multipolygon l=-1
type=multipolygon

**Comment by devemux86** [comment]
Which map file and render theme did you use?

**Comment by Klaus-Tockloth** [comment]
Map and theme are created by myself. In order to reproduce the effect I think it's the best if you create a default map by yourself and use your default theme. Link to the (small) geofabrik extract: http://download.geofabrik.de/europe/germany/nordrhein-westfalen/muenster-regbez.html

Regards Klaus

**Comment by Klaus-Tockloth** [comment]
Due to complex mapping (e.g. of railway stations) it's more and more important that mapwriter respects the layer information also for multipolygons. Could someone look into this issue?

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
