### ISSUE TITLE
OutOfMemoryError with new LabelLayer

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#785]
@Klaus-Tockloth reported OOM (in Cruiser with latest `dev`) and can provide the specific heavy area where the error is reproducible.
The device was a [Samsung Galaxy TabS 10.5](http://www.gsmarena.com/samsung_galaxy_tab_s_10_5-6438.php) with Android 5.
I copy here the relevant stack trace from developer console:

``` java
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 3GB until OOM
at org.mapsforge.map.layer.renderer.PolylineContainer.getCoordinatesAbsolute(PolylineContainer.java:83)
at org.mapsforge.map.layer.renderer.PolylineContainer.getCoordinatesRelativeToOrigin(PolylineContainer.java:98)
at org.mapsforge.map.layer.renderer.CanvasRasterer.drawShapePaintContainer(CanvasRasterer.java:158)
at org.mapsforge.map.layer.renderer.CanvasRasterer.drawWays(CanvasRasterer.java:63)
at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:101)
at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:121)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by Klaus-Tockloth** [comment]
The crash is reproducable by displaying the rhine-ruhr area (germany) in zoomlevel 10.

![screenshot_2016-02-16-17-15-50](https://cloud.githubusercontent.com/assets/5493128/13082609/a08ef552-d4d1-11e5-823d-eeeab418dd99.png)

Download links:
- map (302 MB): http://download.freizeitkarte-osm.de/android-1603-beta1/freizeitkarte_nordrhein-westfalen.map.zip
- theme (0.2 MB): http://download.freizeitkarte-osm.de/android-1603-beta1/freizeitkarte-v4.zip

Regards Klaus

**Comment by devemux86** [comment]
Those non deterministic errors.. Cannot reproduce it on Nexus 9 or emulator.
Is it with `LabelLayer` enabled?
Also what `zoom-interval-conf` did you use in map creation, the default?

**Comment by devemux86** [comment]
BTW it's indeed a heavy map / area, that's why I ask for its creation options.

**Comment by Klaus-Tockloth** [comment]
The crashes only occur with activated label layer. Concering the zoom-interval-conf I use the defaults.

**Comment by applantation** [comment]
Has almost certainly nothing to do with the PolylineContainer, it is just
the moment where OOM happens.

What is your LabelLayer setup?

LabelLayer will need more memory, particularly if you enable the return of
all ways, which is not a good idea.

Ludwig

**Comment by devemux86** [comment]
@ludwigb 
I included (in both apps) the new threaded LabelLayer with the hook returning all ways.

I wonder if there is difference between old and new LabelLayer in that case.

**Comment by ludwigb** [comment]
Most likely, we now return all data for all tiles visible and some more....
it is the same reason multi threading crashes. Too much data.
This will just not work.

**Comment by devemux86** [comment]
Ok with that, but filtering the rendered elements wouldn't fit what users expect either. They'll complain (it happened already) that the map does not work as intended.

**Comment by devemux86** [comment]
Related to #763.

**Comment by devemux86** [comment]
Playing with some of my custom maps I can see OOM even with having the hook returning only the default labeled ways.

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
