### ISSUE TITLE
Old LabelLayer not working

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#787]
I'm testing **old** `LabelLayer` and it doesn't seem to work after the changes in #763.

For example, trying to render a grid of symbols, they don't appear at tile boundaries.
That's an expected behavior in regular rendering, which somehow takes place here too.

![grid](https://cloud.githubusercontent.com/assets/3484020/13198558/cccebbde-d814-11e5-9a02-4b71bcc3ccf7.png)

**Comment by devemux86** [comment]
Situation seems confused. We have 3 rendering methods and only 1 works.
- Regular rendering (works)
- Old label layer (not work anymore). Actually uses regular rendering work flow - so what's its use case?
- New label layer (not work as users expect). So it'll be of little use for many.

**Comment by devemux86** [comment]
To test this at old "Separate LabelLayer using LabelStore" example you can omit the [addition](https://github.com/mapsforge/mapsforge/blob/dev/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/LabelLayerUsingLabelCacheMapViewer.java#L35) of the `LabelLayer` and still see the labels / symbols draw on the map.

**Comment by devemux86** [comment]
Ok I found where the malfunction takes place, I'm testing some alternatives.

Note that in old label layer right now we draw the elements 2 times, both in tiles and on label layer.

**Comment by devemux86** [comment]
I pushed the fix for old label layer drawing, now happens again correctly only on its own layer.

**Comment by ludwigb** [comment]
Fundamentally a mistake to make old cold still compile when new functionality is added. This should have triggered a compile error... I will remember this. Thanks.
