### ISSUE TITLE
Mapwriter 0.6 missing areas

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/mapsforge#788]
With mapwriter 0.6 I have the problem that sometime some areas are missing. It's not a general problem because mostly the areas are rendered. The problem doesn't occur with mapwriter 0.5. 

With mapwriter 0.6 (landuse=cemetery and leisure=sports_centre are missing):
![bildschirmfoto 2016-02-24 um 20 51 33](https://cloud.githubusercontent.com/assets/5493128/13298786/7bfe1944-db38-11e5-96dc-c2b4825205d4.jpg)

With mapwriter 0.5:
![bildschirmfoto 2016-02-24 um 20 50 44](https://cloud.githubusercontent.com/assets/5493128/13298795/875de0e4-db38-11e5-9cdf-ead8f6e2178d.jpg)

Link to OSM: https://www.openstreetmap.org/#map=16/51.9580/7.6075

Regards Klaus

**Comment by devemux86** [comment]
Simply the map-writer jar changes between the 2 procedures, nothing else?

**Comment by Klaus-Tockloth** [comment]
Yes, I only exchanged the mapwriter jar.

**Comment by applantation** [comment]
two possible culprits here:

https://github.com/mapsforge/mapsforge/commit/d10d3fab82ff6f1d61308efda85b589ddb2283c8

https://github.com/mapsforge/mapsforge/commit/c9ac9df22fdaace73a43c39f237721dbc8761491

I would not think that the multi-language features have anything to do with
it.

Anything special about that cemetery area in question?

Ludwig

**Comment by Klaus-Tockloth** [comment]
> Anything special about that cemetery area in question?

https://www.openstreetmap.org/way/11784438
barrier=fence
landuse=cemetery
name=Zentralfriedhof
website=http://www.zentralfriedhof-muenster.de/
wikipedia=de:Zentralfriedhof Münster

https://www.openstreetmap.org/way/40924122
barrier=fence
leisure=sports_centre
name=Sportpark Sentruper Höhe

https://www.openstreetmap.org/way/157045098
barrier=fence
landuse=cemetery
name=Friedhof Steglitz
wikipedia	de:Friedhof Steglitz

My first idea was, that the tag "barrier=fence" has something to do with the issue.
But on the hand side there are areas with the same tagging schema which are drawn correctly:

https://www.openstreetmap.org/way/151353918
barrier=fence
landuse=cemetery
name=Friedhof Eythstraße
wikipedia=de:Friedhof Eythstraße

https://www.openstreetmap.org/way/49038916
barrier=fence
denomination=catholic
landuse=cemetery
name=St. Matthias-Friedhof
religion=christian

The result of an overpass-turbo request (landuse=cemetery && barrier=fence):

![bildschirmfoto 2016-02-25 um 07 01 56](https://cloud.githubusercontent.com/assets/5493128/13311342/09223da0-db8e-11e5-9510-d2a346e3c7b8.jpg)

![bildschirmfoto 2016-02-25 um 07 00 02](https://cloud.githubusercontent.com/assets/5493128/13311346/0eeeb1a0-db8e-11e5-8e3d-d17bdbdf885f.jpg)

Regards Klaus

**Comment by devemux86** [comment]
I also don't think that multilingual feature influence that.

BTW which exact map-writer 0.5 is that?
As there several 0.5.X versions and to check the intermediate changes, we'd need that information.

**Comment by Klaus-Tockloth** [comment]
That's the output during the build process:
INFO: mapfile-writer version: mapsforge-map-writer-0.5.0

You can download the jar I use here (eg. for further investigation):
https://dl.dropboxusercontent.com/u/1677057/mapsforge-map-writer-0.5.0.jar

Regards Klaus

**Comment by devemux86** [comment]
Can you try with the other 0.5.X and `dev` versions from the [downloads](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md) section?

**Comment by Klaus-Tockloth** [comment]
Same problem (missing areas) with version 0.5.1 (and also with 0.5.2).

INFO: mapfile-writer version: mapsforge-map-writer-0.5.1

![mapwriter-5 1 0](https://cloud.githubusercontent.com/assets/5493128/13328116/3919cb54-dbed-11e5-978b-5e3cf509b59e.jpg)

Regards Klaus

**Comment by ludwigb** [comment]
These are the changes affecting the map writer, they are connected to our
heuristics on what is a polygon and what just a line:

git diff  9815cc5a1cd21264ac3c280450ce4666579c477f..aa7649fe3f28fe53f7
mapsforge-map-writer/src/main/

**Comment by devemux86** [comment]
Ok now that the changes have been narrowed down, a good first step would be to check the actual geometry of those areas.

**Comment by lincomatic** [comment]
Interesting, it renders with 0.5.1 for me with corrupted polygon like in #795 

![image](https://cloud.githubusercontent.com/assets/1422186/13855293/dfa5e756-ec2c-11e5-997c-ce1fc59a55cf.png)

**Comment by devemux86** [comment]
After some testing #797 from @lincomatic seems to fix the issue.
@Klaus-Tockloth can you confirm it?

**Comment by Klaus-Tockloth** [comment]
Where can I find the latest mapwriter jar with the correction?

**Comment by devemux86** [comment]
In the downloads section at [dev builds](https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md#latest-development-build-downloads).

**Comment by Klaus-Tockloth** [comment]
Looks good for me at the first glance ... the missing areas (eg. cemetery) are now visible.

Mar 18, 2016 6:43:51 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile-writer version: mapsforge-map-writer-dev-SNAPSHOT

![bildschirmfoto 2016-03-18 um 18 50 47](https://cloud.githubusercontent.com/assets/5493128/13887174/a23c84c4-ed3a-11e5-9071-e477873af9a3.jpg)

I will run further tests with Berlin.

**Comment by Klaus-Tockloth** [comment]
Berlin looks also good:

![bildschirmfoto 2016-03-18 um 19 35 30](https://cloud.githubusercontent.com/assets/5493128/13888244/b70583be-ed40-11e5-9bb6-72960d0e0c67.jpg)
