### ISSUE TITLE
fix memory handling to enable usage of multiple maps at the same time

### ISSUE THREAD

**Issue by nbxdevelop** [mapsforge/mapsforge#790]
This issue comes from #789 

The memory handling of mapsforge maps has to be fixed for use cases where two or more maps are used independently. For example:

1. activity A contains a map view
2. activity B opens activity B
3. activity B contains a map view
4. activity B is closed
5. activity A is shown again

In this app design 2 map views exists at the same time. This works already. There might be issues when both maps show different offline maps (for example A shows map file X, B shows map file Z) but this can be handled by different map caches. 
The issue we found comes from calling 
`MapView.destroyAll().` 
This is supposed to cleanup the used memory and space of the map view. Since it calls 
`AndroidGraphicFactory.clearResourceMemoryCache();` 
all allocated bitmaps of all active map views is cleared. clearResourceMemoryCache() is a static method that accesses a static 
`Map<Integer, Pair<Bitmap, Integer>> RESOURCE_BITMAPS`
that is used by all map view instances at the same time. So it is not possible to clear only the memory of a single map view. 

The next issue described in #789 is that the recycle calls of bitmaps causes an illegal memory access in the still active map views when scrolling and zooming. It causes a potential crash when destroyAll is called during the life time of a map view. Interestingly there is no crash when you close a map and start a new map. Unfortunateley this behaviour has some impact on the overall design of an app since there is no easy way to use two or more maps in different opened activities or fragments.

Please enable the usage of multiple map views at the same time.

**Comment by devemux86** [comment]
Multiple map views work already. Take a look at the various examples in the Samples.

Regarding the `destroyAll` call, it can be used safely on exit.
In intermediate cases its internal calls can be used (we did that in old versions) and have the `AndroidGraphicFactory.clearResourceMemoryCache()` for the exit.

Of course a simpler API would help here to not confuse the users.

**Comment by devemux86** [comment]
Related to #620.

**Comment by nbxdevelop** [comment]
I don't know if a simpler API would solve the problem completely. 

As I see it there is **one** map that caches **all** bitmaps at the moment. There is no way to clear that resources by map view at the moment. Take this example

- activity A shows the map file London.map
- activity B shows the map file Paris.map

If you close B you will compromise the cached bitmaps of A too since clearResourceMemoryCache() recycles all stored bitmaps of both maps. If you partially destroy the map view of B there is no quaranty that all or any bitmaps of B are cleared. When I tested it the app consumed more and faster memory when I did not call AndroidGraphicFactory.clearResourceMemoryCache() when I destroyed a map view. When I used destroyAll() all the time the memory footprint was smaller. Keep that in mind when you redesign the API.

**Comment by devemux86** [comment]
Keep in mind that we're talking here about resource bitmaps - not tiles - so they can be used by all open maps.

Clearing the resources memory cache when it's not needed is the best scenario.
Now it's just common among the maps, so it has to be done at the end of all.

**Comment by devemux86** [comment]
I removed the "clear resource memory cache" from `MapView` destroy calls.
So it can be shared and called once finally at the application exit.
