### ISSUE TITLE
Max Zoom ignored on Double Tap or Gesture

### ISSUE THREAD

**Issue by ksaihtam** [mapsforge/mapsforge#791]
Max zoom is ignored on Double Tap or Gesture and works only with zoom controls.

**Comment by devemux86** [comment]
Did you limit map zooming?
```java
mapView.getModel().mapViewPosition.setZoomLevelMin
mapView.getModel().mapViewPosition.setZoomLevelMax
```

**Comment by ksaihtam** [comment]
Yes of course, i also set the max./min.-Zoom level for the zoom control. My version is the dev branch.

mapView.getModel().mapViewPosition.setZoomLevelMin
mapView.getModel().mapViewPosition.setZoomLevelMax
mapView.getMapZoomControls().setZoomLevelMin
mapView.getMapZoomControls().setZoomLevelMax

**Comment by devemux86** [comment]
At max zoom the double tap or zoom gesture does not go any further, that's the expected behavior.
Do you see something different?

**Comment by ksaihtam** [comment]
Yes, i'm able to zoom above the max. zoom level and the map disappear. But this happens only with gestures.
I will debug the zoom problem and give some feedback.

**Comment by ksaihtam** [comment]
The problem was a missing getZoomLevelMax overload function. Every time the MapViewerTemplate function was used and reset the max. zoom level to 24.

**Comment by devemux86** [comment]
Thanks for the report.

It helped fixing the raster map examples in Samples.
