### ISSUE TITLE
I would like to use Mapsforge in a commercial app.

### ISSUE THREAD

**Issue by gianlucamoretti** [mapsforge/mapsforge#793]
There are any chance for using mapsforge in a commercial app without distribute the app source code?

**Comment by devemux86** [comment]
Mapsforge is free and open source, licensed under the [LGPL3 license](https://github.com/mapsforge/mapsforge/blob/master/LICENSE).

Please use the forum for questions:
https://groups.google.com/forum/#!forum/mapsforge-dev
