### ISSUE TITLE
Polygon Corruption

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#795]
Cemetary polygons in the Berlin map below are corrupted. I have traced back using old map writers, and v0.4.0 and earlier render them correctly, while v0.5.1 and newer cause the error. Some change to the polygon processing code of the map writer in between those versions created the bug.

![47a1f5b2-d59d-11e5-8ca2-12036177ea89](https://cloud.githubusercontent.com/assets/1422186/13832092/f3ca673a-eb95-11e5-9c22-789bde32b49c.jpg)

**Comment by applantation** [comment]
Can you identify the OSM object that does cause this? We have to see what
is strange about it.

**Comment by lincomatic** [comment]
http://www.openstreetmap.org/way/5096178
and
http://www.openstreetmap.org/way/137041447

**Comment by lincomatic** [comment]
Narrowed it down .. 0.5.0 is OK, so the bug creeped in between 0.5.0 and 0.5.1. How do I figure out which changes happened in this range?

**Comment by lincomatic** [comment]
I reverted the JTSUtils.java portion of this commit, and the problem goes away:

https://github.com/mapsforge/mapsforge/commit/7bda373c862b8b8c8b013a12ae33cc36bfe36ef6

**Comment by lincomatic** [comment]
While reverting the commit seems to fix the problem, the underlying issue seems to occur elsewhere, possibly in the code that cuts the polygons. I will research this some more and report back.

**Comment by devemux86** [comment]
Probably related to #788.

**Comment by lincomatic** [comment]
OK, I found the cause, now we need to find a good solution. The commit [7bda373](https://github.com/mapsforge/mapsforge/commit/7bda373c862b8b8c8b013a12ae33cc36bfe36ef6) relies on the shape of TDWay to be accurately determined in this line:

`if (way.getShape() != TDWay.LINE || innerWays != null && innerWays.size() > 0) {`

The problem is that the underlying code doesn't properly categorize TDWay, because OSMUtils.isArea() doesn't properly flag cemeteries as polygons. I added this code to isArea():

```
                if ("landuse".equals(key)) {
                    return true;
                }
```

and the error goes away. So the underlying problem goes back to what the commit was trying to fix. We don't have a foolproof way of determining whether or not a way is a polygon or not. isArea() is hard to fix .. adding my landuse clause is only a band aid, because there probably other tags that we missed.

One idea that might work is to check to see if a way is clockwise or counterclockwise ... only counterclockwise ways are polygons ... but I'm afraid this might be computationally too expensive and will slow down the writer too much.

**Comment by devemux86** [comment]
Additionally we don't want to fill the code with fixed tags.
Writing and reading should be able to play well with any data source (i.e. arbitrary tags).

**Comment by lincomatic** [comment]
+1

**Comment by lincomatic** [comment]
+1
> Additionally we don't want to fill the code with fixed tags.
Writing and reading should be able to play well with any data source (i.e. arbitrary tags).

**Comment by lincomatic** [comment]
Reading the wiki makes things even more confusing:

http://wiki.openstreetmap.org/wiki/Area

implies that direction is not a reliable method of area detection:

> In the past it was necessary to draw boundaries around areas in a particular direction (clockwise or anticlockwise) to ensure that the information was rendered properly - that is no longer necessary.

In any case, isArea() should include all of the tags discussed in the wiki entry:

http://wiki.openstreetmap.org/wiki/Key:area

**Comment by devemux86** [comment]
The default values should probably be ok.

Eventually we should come up with a way to validate properly the geometries.
Mapsforge is a versatile project, used in many custom maps.

**Comment by lincomatic** [comment]
I submitted a PR to add the tags from the wiki https://github.com/mapsforge/mapsforge/pull/797/commits/c419168a19cc84448f7e26033bd5d775eff6476b

For most flexibility, in the future, it is best to control which tags correspond to polygons in tag_mapping.xml.

**Comment by ludwigb** [comment]
I agree there is probably a point to somehow add this to a configuration
file, but short of that the proposed fix might work. There is just no good
solution.

(This failure to differentiate between lines and areas is one of my OSM pet
hates, I had a heated discussion with Steve Coast in a London pub ten years
ago about this. Not supporting proper geometries has caused endless grief
.... and hacks, like this.)

**Comment by devemux86** [comment]
After some testing #797 from @lincomatic seems to fix the issue.
