### ISSUE TITLE
Label layer - permanent high cpu load

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/mapsforge#803]
If a map has no data at it margins, Cruiser consumes a permanent high cpu load. The problem occurs only with activated label layer.

![bildschirmfoto 2016-03-20 um 21 00 04](https://cloud.githubusercontent.com/assets/5493128/13907218/969684ca-eee9-11e5-9731-435070af015d.jpg)

The area in north (above the border) has no data. Tested on OS X (2 cores) with Cruiser 1.2.3.

Regards Klaus

**Comment by devemux86** [comment]
(discussion [here](https://groups.google.com/forum/#!topic/atlas-app/QxnVGzoF8v8))

The high cpu load occurs if with `LabelLayer` enabled we go to the edges of the map bbox, viewing also the outside map area.

Something continues to work at the background in that case loading the cpu.
I remember in the past fixing some `LabelLayer` draw issues, will need a review.

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
