### ISSUE TITLE
Scale render theme values per zoom level

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#814]
Currently we scale only `stroke-width` (and `dy`) per zoom level in rendering (for zoom >12).

We can extend that to other directives, making it optional too.

**Comment by devemux86** [comment]
I pushed a new `scale` option with values `all, none, stroke` (default is `stroke`).

See [examples](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-samples-android/assets/renderthemes/rendertheme-v5.xml#L703-L710) in render theme v5 sample for highway=footway and highway=path, where the dash array is also scaled by zoom.

**Comment by Klaus-Tockloth** [comment]
That sounds promising. As soon as a new version of Cruiser or Atlas is available (including the feature) I will start testing.

Klaus

**Comment by Klaus-Tockloth** [comment]
I think the new scale options (all, none, stroke) are very useful. But the behavior of the "all" option differs from the others. It seems that the length of a dashed line (or gap) is not calculated with the same algorithm as for the options "none or stroke". This breaks compatibility. Here is an example:

line stroke="#bd6500" stroke-width="0.6" stroke-dasharray="8,4" stroke-linecap="butt"
![bildschirmfoto 2016-04-02 um 09 25 18](https://cloud.githubusercontent.com/assets/5493128/14225174/798f4266-f8b9-11e5-8e91-9ad1690769ab.jpg)

line stroke="#bd6500" stroke-width="0.6" stroke-dasharray="8,4" stroke-linecap="butt" scale="all"
![bildschirmfoto 2016-04-02 um 09 26 44](https://cloud.githubusercontent.com/assets/5493128/14225179/840fd08e-f8b9-11e5-8137-978cc79b6d25.jpg)

And here some screenshot of the scaling result I got with Atlas. The feature requires some fine tuning in the theme, but basically looks good for me (first impression):

line stroke="#bd6500" stroke-width="0.6" stroke-dasharray="3,1.5" stroke-linecap="butt" scale="all"
![bildschirmfoto 2016-04-02 um 09 28 57](https://cloud.githubusercontent.com/assets/5493128/14225189/e9b54130-f8b9-11e5-8c2e-956b8304a027.jpg)

![bildschirmfoto 2016-04-02 um 09 29 26](https://cloud.githubusercontent.com/assets/5493128/14225191/efad4b5a-f8b9-11e5-8acc-6d74c4681298.jpg)

![bildschirmfoto 2016-04-02 um 09 30 12](https://cloud.githubusercontent.com/assets/5493128/14225192/f54bc51e-f8b9-11e5-8fbe-d6fd2514d8db.jpg)

![bildschirmfoto 2016-04-02 um 09 30 29](https://cloud.githubusercontent.com/assets/5493128/14225193/fb9265f4-f8b9-11e5-824f-f8da0762b18c.jpg)

Klaus

**Comment by devemux86** [comment]
Thanks for the feedback. Let me explain better the new `scale` options:
- `stroke` (default): as before only the `stroke-width` (and `dy`) is scaled.
- `none`: nothing is scaled per zoom level.
- `all`:additional rule numerics are scaled too (same manner as `stroke-width`).

The scale factor is `Math.pow(1.5, zoomLevel - 12)`. Also:
- `all` option works currently in `line` for its additional `stroke-dasharray` directive.
- I didn't add the `scale` to `circle` rule, since there is already the `scale-radius` doing the same.

**Comment by Klaus-Tockloth** [comment]
Could you explain the compability issue a bit? Or isn't it an issue?

Zoomlevel 14: The dashed line is without scale="all" (first occurence):
![798f4266-f8b9-11e5-8e91-9ad1690769ab](https://cloud.githubusercontent.com/assets/5493128/14225796/cde4410c-f8cf-11e5-90cc-08b96bd268d0.jpg)

Zoomlevel 14: The dashed line with scale="all" (first occurence):
![840fd08e-f8b9-11e5-8137-978cc79b6d25](https://cloud.githubusercontent.com/assets/5493128/14225797/d65d08aa-f8cf-11e5-87e1-32755b4fc3b5.jpg)

With scale="all" the dashes (and gaps) are significant longer (same zoomlevel).

Klaus

**Comment by devemux86** [comment]
The scaling starts from zoom level >12, so in the example the scale factor is `1.5 ^ (14 - 12) = 2.25`.

In 1st picture we have only `stroke-width` scaling. The `stroke-dasharray` dashes and gaps remain always the same. So by zooming only their width increases.

In 2nd picture there is also scaling on `stroke-dasharray`, i.e. its numerics are multiplied by the scale factor. So we have increase at both widths and dashes / gaps simultaneously.

Isn't that the intended behavior or am I missing something?

**Comment by Klaus-Tockloth** [comment]
OK, with the formula (and the example) it's now clear what to do and how to calculate the "new" line parameters. After some experiments I came to excellent results. I'm sure that I will use this feature in the future. But before that I have to wait till the (main) apps have integrated the (upcoming) mapsforge lib with the new feature.

Thanks for implementing this - Klaus.
