### ISSUE TITLE
Cache initialization state

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#819]
Have a way to be notified about (file) cache initialization status (like an observer).

This might be helpful for slow file systems and persistent file cache.

**Comment by ludwigb** [comment]
What is the actual problem?
Maybe we just need some sort of barrier so the cache cannot be used until
fully initialized?

**Comment by devemux86** [comment]
In the case of persistent tile cache, during the initialization the filled cache directory is read asynchronously.
So a notification about the end of the process could be useful.

**Comment by ludwigb** [comment]
But would it in this case not simply be better that any read attempts are
blocked until the cache has been entirely read in?

That is much easier than having an observer, that calls back into the app,
where the cache reader would have to poll or block on the observer.

**Comment by devemux86** [comment]
I don't disagree.
Also what happens already in map view during the period of cache directory asynchronous read, doesn't it already wait and then get filled with data afterwards?

Or developer needs a notification, e.g. for displaying a message to users?

**Comment by ksaihtam** [comment]
Blocking the redraw for one layer is not really a solution. Currently with a online tile cache the redraw process re-download the tiles because the file cache is not ready. 
There should be at least a notification if the tile cache is ready and usable.
