### ISSUE TITLE
Android zoom button visibility is inconsistent

### ISSUE THREAD

**Issue by mvglasow** [mapsforge/mapsforge#827]
On 0.4.3, the zoom buttons were initially hidden and would only show upon tapping the display, panning or zooming. Some 2 seconds after the operation they would disappear again.

After moving from 0.4.3 to 454c97b (post-0.6.0), I notice the zoom buttons are initially visible and will only disappear after a tap/pan/zoom.

Is this behavior intentional, or is that a bug?

**Comment by devemux86** [comment]
The behavior should be the same, so something changed that, as we had several zoom controls [improvements](https://github.com/mapsforge/mapsforge/blob/dev/docs/Changelog.md) since then.

**Comment by devemux86** [comment]
A quick check reveals that this behavior started due to #700 changes.

**Comment by devemux86** [comment]
I pushed a fix, can you confirm that it works as intended?

**Comment by mvglasow** [comment]
Yes, now zoom button behavior is like it was before.
