### ISSUE TITLE
Sharing map data between apps

### ISSUE THREAD

**Issue by mvglasow** [mapsforge/mapsforge#832]
When multiple Mapsforge-based apps are installed on a device, it makes sense to place map files in shared storage and point all apps to that same path. I've tried this in the past and it didn't seem to cause any conflicts.

What we lack is a convention for the path to use, and possibly some logic that "encourages" adopting this convention. For example, the path could be something like `<shared_storage>/mapsforge` or `<shared_storage>/org.mapsforge/maps` on Android; for desktop Java we'd need to come up with a suitable equivalent for `<shared_storage>`.

One could then have `MapFile` constructors accept relative paths (interpreted as being relative to that default path), and/or `MultiMapDataStore` default to all map files found in that path (and possibly its subdirs).

Similar considerations would apply for `TileStore`. Tile caches are a bit more tricky: downloaded tiles are probably OK to share, while locally rendered tiles may differ (different rendering styles, possibly also differences between Mapsforge versions). Here it's probably preferable to have the app dev choose between a shared vs. private cache, and describe the consequences of that choice in the API docs.

**Comment by devemux86** [comment]
Interesting thought. And certainly more applicable to map files than tile cache.
Which depends of far too many options, e.g. device dpi, text scale, map language, render theme, style, overlays, etc.

Another thing to consider is that two of the largest MF integrators (Locus, Orux) have their own directory structures, hosting MF maps in specific location.

**Comment by ludwigb** [comment]
I have a bit a doubt that any such proposal will gain much traction.

What would be useful is a file filter for Android etc that searches for
.map files that also have our magic bytes at the beginning. Computationally
more expensive, but does not depend on any convention.

**Comment by devemux86** [comment]
>I have a bit a doubt that any such proposal will gain much traction.

I agree, each app developer has his own preference for such an organization.
That's why most of them have default paths, but with app option for users to change them.

Regarding filter, we have two active map versions, 3 and 4 (readable from 0.6), another thing to consider.

**Comment by mvglasow** [comment]
> I have a bit a doubt that any such proposal will gain much traction.

I guess I should provide some background here – this came out of a feature request I got for my own app: https://github.com/mvglasow/satstat/issues/65 – not only provide offline maps, but also use the same map path as another app – Radiobeacon, whose maintainer I'm occasionally in touch with (and since he's also a user of both apps, he'd benefit from that as well).

I can't speak for other app devs – but if Mapsforge defaults to a shared path unless explicitly requested otherwise, I suspect this will speed up adoption.

> What would be useful is a file filter for Android etc that searches for .map files that also have our magic bytes at the beginning

Fair enough, as long as there is an easy way to tell Mapsforge "just grab all the map files on the device, unless they're explicitly declared to be private".

> [...] tile cache. Which depends of far too many options, e.g. device dpi, text scale, map language, render theme, style, overlays, etc.

Sure, map files are the higher priority here. A few thoughts on caches, though:

Device DPI is constant across apps, thus it shouldn't be an obstacle to sharing caches on the same device.

Text scale, map language, render theme and style are relevant only for tiles rendered locally but not for downloaded tiles – hence my statement that a shared cache would work well for downloaded tiles but less so for locally rendered tiles.

Overlays – do they get cached at all? Together with the "base" tiles or separately? In any case, I'd treat tiles with overlay data in the same way as locally rendered tiles.

**Comment by devemux86** [comment]
All that appear to me more related to the app side than the library.

Isn't the MF API already usable for such cases? The `MapFile` takes as argument a file.
Developer can scan the file system, get the map files he wishes, present a choice to users or even make a multi map data store to show them all.

>Overlays – do they get cached at all?

I was referring to style overlays in render themes, (not map overlays).

**Comment by gdt** [comment]
Yes, it probably can be done by the app.  I think the point is to declare a standard place, and have the normal library usage use that standard place.    This is probably uncontroversial, as it seems obviously good to make mapsforge work in all apps once a map has been loaded for one of them.  So Ithink it's just about norms and defaults.

**Comment by axd1967** [comment]
It seems to me that the proper way to share the data would be via a content provider.

**Comment by mvglasow** [comment]
@axd1967 Having a content provider would eliminate the need for a well-defined directory on Android. However, it would open up a bunch of questions: if there are multiple Mapsforge apps (each with its own content provider, which would presumably be part of the Mapsforge library), how would we decide whose content provider would get used? What if one of the apps has a buggy content provider?

More important, since Mapsforge is available not only Android but also on JRE, we'd still need to find a solution for JRE. On the other hand, two apps accessing the same set of files is no issue (the maps are read-only, after all), and agreeing on a default path is definitely less work.

**Comment by axd1967** [comment]
That would not be part of Mapsforge apps, but a separate Mapsforge Android **app** (eg "MapsforgeProvider", similar to `mapsforge-map-android` and `mapsforge-map-android-extras`).

This component would have to be installed separately by the end user, with the clear argument that it will save loads of memory, and Mapsforge apps could trivially check for the presence of the component and direct the user to install it if it is missing. Such a component would also provide the user a minimal interface to manage maps, which would also relieve client apps from this kind of management.

In fact, such a component could be written by extending the file approach; apps that use the component will no longer need the file, and JRE can continue with the file approach.

And, by the way, a typical behaviour of a content provider that provides blobs is to store those blobs ... on the filesystem. But in a much more controlled fashion.
* http://stackoverflow.com/questions/3883211/how-to-store-large-blobs-in-an-android-content-provider
* https://developer.android.com/guide/topics/providers/content-provider-basics.html#DataTypes
* http://www.grokkingandroid.com/handling-binary-data-with-contentproviders/

**Comment by devemux86** [comment]
Closing this, as it's questionable if it involves core library or applications (which each wants and has its own UI guidelines).

The best place for potential feature discussions is foremost our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
