### ISSUE TITLE
Default zoom control style

### ISSUE THREAD

**Issue by mvglasow** [mapsforge/mapsforge#835]
The `MapZoomControls` class relies on Android's `ZoomControls`, which Google seems to have abandoned somewhere between Honeycomb and ICS. As a result, the design doesn't look particularly nice on current versions of Android.

Is there any way to bundle Android resources into Mapsforge and supply custom default images for the buttons? In that case I'd donate the set of SVGs I've created for my own app (based on the Samples buttons, which unfortunately are HDPI only). You can take a look at them at https://github.com/mvglasow/satstat/commit/2c623d3133abb00aa7b1c33a75e950af32563eeb (unfortunately Github won't let me attach them here).

**Comment by devemux86** [comment]
That's already supported from `0.6.0`, see #700 about customization of internal zoom controls with Android resources.

Of course it's always possible to use external zoom buttons for more control.

**Comment by mvglasow** [comment]
I'm aware of the possibility to add custom drawables, which the samples demonstrate nicely.

I was talking about bundling these drawables with the Mapsforge library. However, your comment on #695 (which #700 references) answers my question: bundling drawables and other resources would require making Mapsforge an Android library project, which is more complex to integrate than a jar that can simply be dropped into a folder, and you want to keep that kind of complexity away from Mapsforge. Valid point. The `CustomZoomControls` approach you suggested there sounds interesting – if I get around to it, I might implement something and submit a pull request.

**Comment by devemux86** [comment]
Precisely, moving to `aar` is not in our plans. That helps also the many developers who prefer jars or Maven or Eclipse or... We try to be as generic as possible.

Implementing custom zoom controls is not difficult. I show it in [RotateMapViewer](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/RotateMapViewer.java) example in Samples. An `Observer` can be added too for listening to map zoom changes.
