### ISSUE TITLE
Maven build module: mapsforge-map-android-extras - dependency compatibility-v4 not exist

### ISSUE THREAD

**Issue by sytolk** [mapsforge/mapsforge#838]
Here its have dependency to compatibility-v4:23.2.1
https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android-extras/pom.xml
But its not exist in Maven central. I have use this project to import SDK libraries to my local maven repo https://github.com/simpligility/maven-android-sdk-deployer
but now compatibility modules are commented in maven-android-sdk-deployer
```
<!--  none of the compatibility modules are in the SDK anymore for me (2016-05)-->
<!--                 <module>compatibility-v4</module> -->
<!--                 <module>compatibility-v7-gridlayout</module> -->
<!--                 <module>compatibility-v7-appcompat</module> -->
```
They not exist in my SDK too. Check this in yours?
Im not sure if this is better solution but I have this fix in my project
```xml
      <dependency>
            <groupId>org.mapsforge</groupId>
            <artifactId>mapsforge-map-android-extras</artifactId>
            <version>0.6.1-rc2</version>
            <exclusions>
                <exclusion>
                    <groupId>android.support</groupId>
                    <artifactId>compatibility-v4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

       <dependency>
            <groupId>com.android.support</groupId>
            <artifactId>support-v4</artifactId>
            <version>23.4.0</version>
            <type>aar</type>
        </dependency>
```

**Comment by devemux86** [comment]
Android libraries do not exist in Maven central, that's why the `Maven Android SDK Deployer` tool is needed to publish them in user's local repository and use them from there.
Unfortunately recently this procedure was broken..

Regarding Mapsforge Maven support see also the related [forum topic](https://groups.google.com/d/msg/mapsforge-dev/Dx0mULA0K74/E7ZA38fqDAAJ).
We avoided `aar` dependencies in the past for compatibility reasons, e.g. how does Eclipse handle them now?

**Comment by sytolk** [comment]
Thanks for the link. Why its have dependency to android.support.compatibility-v4 instead of com.android.support.support-v4 ? only to have jar dependency instead of aar?
I dont use Eclipse sorry my IDE is Intellij IDEA and I dont have any issues with AAR.

**Comment by devemux86** [comment]
Yes to avoid `aar` for above reasons. Also that's the artifact id that Deployer publishes as `jar` in local repository.

Of course now we may need to review the whole procedure..
See also [here](https://github.com/simpligility/maven-android-sdk-deployer/issues/295).

**Comment by sytolk** [comment]
I will copy the whole ANDROID_HOME directory before to run SDK Manager update :)

**Comment by devemux86** [comment]
The proposed solution can work for applications using Mapsforge.

We still have issues with internal Maven build, so closing in favor of #852.
