### ISSUE TITLE
please use semantic versioning

### ISSUE THREAD

**Issue by Bananeweizen** [mapsforge/mapsforge#839]
I just tried upgrading from 0.6.0 to 0.6.1. Afterwards I was greated by a compile error in cgeo (TileRendererLayer has a new constructor parameter). Please increase at least the "y" of your x.y.z version number, when doing API changes. People consuming your artifacts probably expect that the version number follows [semantic versioning](http://semver.org/), and that scheme requires backwards compatible changes when only the z part increases.

Thanks.

**Comment by devemux86** [comment]
Sorry for the inconvenience. See also the simplified tile layer creation in #833 (mentioned in [changelog](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md)).

Thanks for the versioning suggestion.
AFAIK Mapsforge wasn't following such a principle, though it's a valid one.

I'm closing this, we can continue such discussions in the forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
