### ISSUE TITLE
Getting-Started-Android-App needs germany.map

### ISSUE THREAD

**Issue by axd1967** [mapsforge/mapsforge#840]
please add in 

https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md

that this map file should be created or put or whatever,

so that people that want to try the app are not facing a useless warning... they will already have passed quite some time in dealing with the JDK 7 issue.

**Comment by devemux86** [comment]
We specifically declare in a code comment the name of the map file in the external storage.

You mean to write also in the documentation?

**Comment by axd1967** [comment]
Of course! 

Put yourself in the place of an Android dev: (s)he will clone, import in AS, and then press the Run button... *Nobody* is ever going to read the example source code first.

**Comment by devemux86** [comment]
To clarify things, we're talking about Getting-Started-Android-App guide which needs copy/paste the code to run.

The full Samples app is independent module and in there the warnings are for such purposes.

**Comment by axd1967** [comment]
And where can we find that file?

**Comment by axd1967** [comment]
BTW - you don't need to copy-paste any code.

It's as simple as

1. clone
1. import
1. run

that's it.

**Comment by devemux86** [comment]
> And where can we find that file?

In [front page](https://github.com/mapsforge/mapsforge) we have link to [download server](http://download.mapsforge.org/).

**Comment by devemux86** [comment]
> BTW - you don't need to copy-paste any code.

You ran the [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) code text without putting it in a project?

**Comment by axd1967** [comment]
* may I suggest to add the link directly in the doc page? that's why hypertext was invented, right?
* but yes, building the demo app in AS was a breeze (after fixing the JDK7/8 issue):
![device-2016-06-14-195924](https://cloud.githubusercontent.com/assets/3529789/16053832/aa22c30e-326a-11e6-92e4-41e4cd30567e.png)
