### ISSUE TITLE
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference while cleaning

### ISSUE THREAD

**Issue by deiauk** [mapsforge/mapsforge#843]
I'm having this problem. When I navigate to next window of my app I get null pointer exception
       @Override
        public void onDestroy() {
	mapView.destroyAll();
	AndroidResourceBitmap.clearResourceBitmaps();
	AndroidSvgBitmapStore.clear();
	AndroidGraphicFactory.clearResourceFileCache();
}

**Comment by devemux86** [comment]
With `destroyAll` you don't need to call all these clear methods.
```java
this.mapView.destroyAll();
AndroidGraphicFactory.clearResourceMemoryCache();
```

See the [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) guide for proper implementation.

**Comment by devemux86** [comment]
I think we can close this.
