### ISSUE TITLE
Rendering is not smooth in 0.6.1 version

### ISSUE THREAD

**Issue by deiauk** [mapsforge/mapsforge#844]
I have an app where I display lots of plygons on lake (polygons overlap each other and so on). Now when I zoom in everything is laggy and that's only because 0.6.1 version. When I was using 0.6.0 everything was working fine. Why is that? Here's how I initiate TileRendererLayer
```
 tileRendererLayer = new TileRendererLayer(tileCache, mapDataStore,
                mapView.getModel().mapViewPosition, false, false, false, AndroidGraphicFactory.INSTANCE);
```

**Comment by devemux86** [comment]
We need to understand exactly what is the problem.

Can you provide more details about the implementation (a small example perhaps)?
Does it happens only on zoom or also during the map scroll?
Are the polygons overlays on top of a map or polygons built inside a map file?
And what "laggy" means, slow rendering or something else?

BTW you can try the alternative simplified `TileRendererLayer` constructor.

**Comment by deiauk** [comment]
I will add more code. Here's how I create Polygon
```
public MyPolygon createPolygon(ArrayList<LatLong> latLongs, int polygonId, int color){
        Paint paintStroke = AndroidGraphicFactory.INSTANCE.createPaint();
        paintStroke.setStyle(Style.FILL);
        paintStroke.setColor(color);
        paintStroke.setStrokeWidth(1);

        MyPolygon polygon = new MyPolygon(latLongs, polygonId, paintStroke, paintStroke, AndroidGraphicFactory.INSTANCE);

        return polygon;
    }

```

And here's method from MyPolygon class

```
public class MyPolygon extends Layer {
...
@Override
    public void draw(BoundingBox boundingBox, byte zoomLevel, Canvas canvas, Point topLeftPoint) {
        if (this.latLongs.size() < 2 || (this.paintStroke == null && this.paintFill == null)) {
            return;
        }

        Iterator<LatLong> iterator = this.latLongs.iterator();

        Path path = this.graphicFactory.createPath();
        LatLong latLong = iterator.next();

        long mapSize = MercatorProjection.getMapSize(zoomLevel, displayModel.getTileSize());
        float x = (float) (MercatorProjection.longitudeToPixelX(latLong.longitude, mapSize) - topLeftPoint.x);
        float y = (float) (MercatorProjection.latitudeToPixelY(latLong.latitude, mapSize) - topLeftPoint.y);
        path.moveTo(x, y);

        while (iterator.hasNext()) {
            latLong = iterator.next();
            float x1 = (float) (MercatorProjection.longitudeToPixelX(latLong.longitude, mapSize) - topLeftPoint.x);
            float y1 = (float) (MercatorProjection.latitudeToPixelY(latLong.latitude, mapSize) - topLeftPoint.y);
            path.lineTo(x1, y1);
        }

        if (this.paintStroke != null) {
            canvas.drawPath(path, this.paintStroke);
        }
        if (this.paintFill != null) {
            canvas.drawPath(path, this.paintFill);
        }
    }
}
```

And this code worked perfectly on Maspforge 0.6.0 version. But on 0.6.1 for example when I zoom everything scrolling is not smooth.

**Comment by devemux86** [comment]
I can confirm such behavior with Samples overlay example, if add e.g. 10K polygon overlays.
The map rendering then starts to delay and the tiles refresh is very slow.

**Comment by deiauk** [comment]
Well but for me 0.6.0 version works perfectly

**Comment by devemux86** [comment]
I tested it also with 0.6.0 with same result.
Loading map with too many overlays leads to cpu intensive slow tiles rendering.

How many overlays you added?

**Comment by devemux86** [comment]
Closing as too many overlays can slow the map rendering in all versions.
