### ISSUE TITLE
 Memory leak due to LayerManager's reference to MapView

### ISSUE THREAD

**Issue by kalabalik** [mapsforge/mapsforge#845]
When using the LeakCanary library, it gives me the following chain of references causing a leak:

LayerManager.<Java Local>
|
references LayerManager.mapView
|
references MapView.mContext
|
leaks MainActivity.instance

The reason seems to be that `mapView.destroyAll()` (located in a fragment's `onDestroy()` method) does not destroy the `LayerManager` which holds a reference to `MapView` which in turn holds a reference to the activity. A solution would be to destroy `LayerManager` in `mapView.destroyAll()`.

**Comment by devemux86** [comment]
>A solution would be to destroy LayerManager in mapView.destroyAll().

Do you mean like nullify `LayerManager` in mapView's destroy?

Also something like removing activity references could work.

**Comment by kalabalik** [comment]
Yes, nullification of |LayerManager| is what I was thinking of.
Possibly, nullifying the mContext attribute would do, too. However, I am
not sure whose attribute it actually is and whether you have access to
it or not.

Cordially,
CK

Am 28.06.2016 um 14:14 schrieb Emux:

**Comment by devemux86** [comment]
If you can play with Mapsforge source, can you try it and report back?

Also a pull request if you find the solution would be fine!

**Comment by kalabalik** [comment]
Okay, I will try - either Thursday or next week.

Am 28.06.2016 um 23:35 schrieb Emux:

**Comment by devemux86** [comment]
I pushed the nullification of `LayerManager` in `destroy`.

@kalabalik can you retest your case?

**Comment by kalabalik** [comment]
Sorry, I was away for so long. I had to publish the app I was working on and managed to solve the issue by using `MapView mapView = new MapView(activity.getApplicationContext());` as you suggested on the mapsforge-dev list.

However, I am still trying to help if I can. I tested the patch you supplied in the master branch and it did not work. For some reason the code in `MapView`s `onDestroy()` is never executed. In order to fiddle around with the mapsforge code _as I use it in my app_ I would like to be able to manipulate a local copy of mapsforge while it is used as a library. However, I failed to set it up properly. The [Jitpack](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#jitpack) variant didn't work (not write access), this [variant](http://stackoverflow.com/questions/30344053/how-do-you-edit-a-dependency-external-library-in-android-studio) didn't work either. Can you point me to a guide to a working configuration? Thanks so much!

**Comment by devemux86** [comment]
You can use latest Mapsforge master via jars, published in our [server](http://ci.mapsforge.org/job/master/).

But the best way to play with the code is by cloning the repository, open it in Android Studio and run `gradle install` to install the master artifacts in your local Maven repository (`.m2` folder under your profile).
Then you can use them like the release ones. You just need to include `mavenLocal()` in your application's repositories.

**Comment by devemux86** [comment]
BTW Jitpack is for using master via GitHub, not local clones.

**Comment by acorn371** [comment]
I'm using latest release 0.8.0 and the memory leak is still there.
LayerManager is destroyed in MapView.destroy(), anyway MapView isn't destroyed on Activity/Fragment destruction. 
I tested it on mapsforge-samples-android app from 0.8.0 release, opening and closing "Simplest Map View" activity several times.
The same in my own app.
I tested it with  AndroidStudio hprof / "Deteck Leaked Activities" tool.

**Comment by easdue** [comment]
The problem here is that the LayoutManager Thread is simply not successfully interrupted after calling LayoutManager.interrupt() (eg. afterRun() is never called). I've seen this in my own apps background job handling as well. Sometimes if you call Thread.interrupt() this simply does not result in Thread.isInterrupted() returning true.

I solved this problem in my app by not using isCancelled() but by setting and testing a volatile boolean variable to break out of the background job's work loop.

**Comment by puneethreddy-3186** [comment]
The memory leak happens on the sample project too!! See the snapshot from the eclipse MAT. Seems like the LayerManagerController and MapViewController are registered as observers to the mapViewPosition and mapViewDimension model objects, but they are never unregistered from them.
The same is confirmed by the MAT, See the pic below
<img width="618" alt="untitled" src="https://user-images.githubusercontent.com/35573402/35111258-21e77c78-fc7b-11e7-8cc8-1a95ef50a1c9.png">

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
