### ISSUE TITLE
Allow resources without location prefixes in render themes

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#847]
We could allow resources without location prefixes (`file:`, `assets:`, `jar:`) in render themes.

The location awareness can be handled in code with the above order.
That would make themes simpler to write and more usable / movable.

Of course there will be backwards compatibility with older render themes having location prefixes.

**Comment by ludwigb** [comment]
I think an emphasis on deprecation is important here, so the old themes
will continue to work as before. Only if there is no prefix, the search
order is somewhere done in code.

**Comment by devemux86** [comment]
(I changed the description)
If a resource has a location prefix then it will be used, otherwise the algorithm will search the resource in the above order.

I pushed the implementation in `issue_847` branch. If all are ok, I will merge it in master soon.

**Comment by devemux86** [comment]
I merged the implementation in `master` branch.
