### ISSUE TITLE
Deprecate Maven build

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#852]
Android Support jars have been removed from SDK and stopped working with maven-android-sdk-deployer.
See https://github.com/simpligility/maven-android-sdk-deployer/issues/295

As a consequence Mapsforge now fails to build with Maven.

**Comment by sytolk** [comment]
@devemux86 Gradle buld with Java 8 failed https://github.com/mapsforge/mapsforge/issues/540

**Comment by devemux86** [comment]
#540 is about Maven, is that you mean?

Also Java 8 doclint should be handled in #851.

**Comment by sytolk** [comment]
https://github.com/mapsforge/mapsforge/issues/540#issuecomment-62258226 look at the bottom of the issue. Do you have success if you disable doclint and try to build project with Java 8 ?

**Comment by devemux86** [comment]
This issue is about Maven, you're referring to Gradle?

Note that current build tools version 23.X support Java 7.
With new Android version will see what happens with Java 8.

**Comment by devemux86** [comment]
For Gradle with Java 8 see fix in #853.

**Comment by devemux86** [comment]
We decided to deprecate Mapsforge Maven build and focus our resources on Gradle.
