### ISSUE TITLE
Map writer label-position option inconsistency

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#859]
[In documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#advanced-options-only-use-when-you-know-what-you-are-doing) it is stated that the default for `label-position` is `true` but [in code](https://github.com/mapsforge/mapsforge/blob/03c750a58f744bb4387b95a48e95c094a05fab00/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/osmosis/MapFileWriterFactory.java#L63) it is `false`.

**Comment by devemux86** [comment]
Indeed and I wonder which one should be actually the default and needs change.

**Comment by devemux86** [comment]
I pushed the code change.
