### ISSUE TITLE
CopyOnWriteArrayList for Layers

### ISSUE THREAD

**Issue by kalvish** [mapsforge/mapsforge#865]
It seems that layers use CopyOnWriteArrayList.

mapsforge-map/src/main/java/org/mapsforge/map/layer/Layers.java 

```java
this.layersList = new CopyOnWriteArrayList<>();
```

It seems that this type of array list create a copy whenever we add an item to the Layers list. [Java Doc on CopyOnWriteArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) Does that mean if we iterate over list of POIs and add markers to a 'Layers' list will create copy of layers list each time we add a POI?

For example;

```java
Layers layers = mapView.getLayerManager().getLayers();
        Marker marker = createMarker(tapLatLong, R.drawable.ic_gps_fixed_black_24dp);
        if (marker != null)
        {
            if(layers.size()>1){
                layers.remove(1);
                layers.add(1,marker);
            }
 }
```

Will this code create copy of list twice?

**Comment by devemux86** [comment]
For questions please use our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
