### ISSUE TITLE
invalid tileX number on zoom level 32: 2147483647

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#866]
(with #572 fixed)
New max zoom level limit now appears to be 31, again because of integer overflow.

**Comment by devemux86** [comment]
Is there need for supporting such large zooms >31, e.g. for indoor maps?
Also how extended can be such move from `integer` to `long`...
@ludwigb your thoughts?

**Comment by devemux86** [comment]
Older similar report in #500.

**Comment by ludwigb** [comment]
I cannot quite remember what the value is, but I think zoom 31 is already
in the sub-mm area, so I do not think this makes sense for indoor maps.

**Comment by devemux86** [comment]
No purpose to go beyond zoom 31.
