### ISSUE TITLE
Still getting error of `Task type mapfile-write doesn't exist.`

### ISSUE THREAD

**Issue by quang-ha** [mapsforge/mapsforge#867]
Right I have been struggling with this for hours, here is the situation.

I have placed the plugins under:

```
quang_ha@daedalus: pwd
/home/quang_ha/.openstreetmap/osmosis/plugins
quang_ha@daedalus: ls
mapsforge-map-writer-0.6.1-jar-with-dependencies.jar
```

and also `osmosis` under:

```
quang_ha@daedalus: pwd
/home/quang_ha/osmosis-new
quang_ha@daedalus: ls
bin  changes.txt  config  copying.txt  lib  package.iml  readme.txt  script
```

But when I run:

```
bin/osmosis --rb file=~/Downloads/us-pacific-latest.osm.pbf --mapfile-write file=~/Downloads/us-pacific-latest.map
```

it renders the following issue:

```
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Task type mapfile-write doesn't exist.
```

Now interestingly, when I put the plugin under `osmosis-new/lib/default/`, this is what I get instead:

```
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Task type "mapfile-writer" already exists.
```

Now if I go and delete either the plugin in the `lib/default` or `~/.openstreetmap/osmosis/plugins`, it can't find the plugin again.

Any help?

**Comment by devemux86** [comment]
Your command line has a typo, it's `--mapfile-writer`.

For questions please use our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
