### ISSUE TITLE
Offline germany.map some blank tiles for zoomlevel 5-7 

### ISSUE THREAD

**Issue by k3b** [mapsforge/mapsforge#868]
Since i updated mapsforge-clientapp-c:geo to a newer version the rendering of the offlinemap **germany.map** has some issues with **zoomlevel 5-7**: map west of Regensburg/north of Stuttgart is not rendered any more. This issue can be reproduced with  **mapsforge-samples-android**, too.

![device-2016-08-29-235025](https://cloud.githubusercontent.com/assets/1374583/18069043/d67d7276-6e44-11e6-8002-db9561ab49ff.png)

I am using android-4.4.2. 

Note: with zoom-level-8 and up the lib and the demo works as expected.

With older c:geoclient (using mapsforge < 6.0) using the same germany.map file this issue didn-t exist.

I just updated germany.map to current august-2016 file but the result is still the same.

How to reproduce

* i am using android-4.4.2 (api-19)
* place germany.map from http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/europe/ to /mnt/sdcard/
* start mapsforge-samples-android
* select DiagnosticsMapViewer
* zoom out until zoomlevel 5 is shown

The problem can be reproduced with mapsforge-samples-android/DiagnosticsMapViewer
mapsforge-0.6.0  and mapsforge-0.6.1

**Comment by devemux86** [comment]
Any exceptions in the log?

>Note:to make mapsforge-samples-android runnable on android 4.4.2 i had to add the missing
<uses-permission android:name="android.permission.PACKAGE_USAGE_STATS" /> to the manifest

Mapsforge always worked fine without the need of such a special permission.

**Comment by k3b** [comment]
i added wrong map-s folder "/mnt/extsd/osmdroid/" and got this:

08-29 19:38:43.391 1739-1761/? D/asset: AssetManager-->addDefaultAssets CIP path not exsit!
08-29 19:38:43.397 1739-1755/? W/System.err: java.lang.SecurityException: Neither user 10003 nor current process has android.permission.PACKAGE_USAGE_STATS.
08-29 19:38:43.398 1739-1755/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1781)
08-29 19:38:43.398 1739-1755/? W/System.err:     at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1810)
08-29 19:38:43.399 1739-1755/? W/System.err:     at com.android.server.am.UsageStatsService.getAllPkgUsageStats(UsageStatsService.java:862)
08-29 19:38:43.399 1739-1755/? W/System.err:     at com.android.internal.app.IUsageStats$Stub.onTransact(IUsageStats.java:113)
08-29 19:38:43.399 1739-1755/? W/System.err:     at android.os.Binder.execTransact(Binder.java:404)
08-29 19:38:43.400 1739-1755/? W/System.err:     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-29 19:38:43.400 1739-1755/? W/System.err:     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
08-29 19:38:43.400 1739-1755/? W/System.err:     at android.os.Binder.execTransact(Native Method)
08-29 19:38:43.401 1739-1755/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
08-29 19:38:43.403 2531-2543/? W/AppsProvider.ApplicationsProvider: Could not fetch usage stats
                                                                    java.lang.SecurityException: Neither user 10003 nor current process has android.permission.PACKAGE_USAGE_STATS.
                                                                        at android.os.Parcel.readException(Parcel.java:1465)
                                                                        at android.os.Parcel.readException(Parcel.java:1419)
                                                                        at com.android.internal.app.IUsageStats$Stub$Proxy.getAllPkgUsageStats(IUsageStats.java:237)
                                                                        at android.app.ActivityManager.getAllPackageUsageStats(ActivityManager.java:2224)
                                                                        at com.android.providers.applications.ApplicationsProvider.fetchUsageStats(ApplicationsProvider.java:714)
                                                                        at com.android.providers.applications.ApplicationsProvider.updateApplicationsList(ApplicationsProvider.java:548)
                                                                        at com.android.providers.applications.ApplicationsProvider.access$400(ApplicationsProvider.java:72)
                                                                        at com.android.providers.applications.ApplicationsProvider$UpdateHandler.handleMessage(ApplicationsProvider.java:232)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                        at android.os.Looper.loop(Looper.java:193)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

the path should have been "/mnt/sdcard/osmdroid/"

**Comment by devemux86** [comment]
What device?
`Environment.getExternalStorageDirectory()` usually returns whatever is set as "external storage" in the device environment: in some the external sd card, on other the internal storage.

**Comment by k3b** [comment]
on my other android device (android-4.2 tablet) has 2 extrernal storages

* Environment.getExternalStorageDirectory() = /mnt/sdcard/osmdroid/ (900 MB free, not enought for 1.5 gb germany.map)
* /mnt/extsd/osmdroid/ . (20gb free)

**Comment by devemux86** [comment]
The 1st is the internal storage and the 2nd the external sd card?

**Comment by k3b** [comment]
unfortunately Environment.getExternalStorageDirectory() is not SD-Card

**Comment by k3b** [comment]
with the android-4.4.2 Environment.getExternalStorageDirectory()  is ok (external sd-card) but i need subdir "osmdroid"

**Comment by k3b** [comment]
sorry i closed the wrong ticket

**Comment by devemux86** [comment]
That's what I thought, unfortunately it seems that goes with the device.

Base class `MapViewerTemplate` already has methods like `getMapFileDirectory()`, `getMapFileName()`, `getMapFile()` to be overridden by Samples classes declaring their own paths.

BTW you can try the more convenient way of Java `mapsforge-samples-awt` to check the map rendering on desktop. It accepts map file paths as command line arguments.

**Comment by k3b** [comment]
Is this the same as #806 ?

**Comment by devemux86** [comment]
#806 involves multi-threading rendering (which by default is not enabled) and should be fixed in `master`.

Can you post a screenshot with the problem showing also the diagnostics tile grid / coordinates for us to check?

**Comment by k3b** [comment]
i have added a screenshot to ticket-intro

**Comment by devemux86** [comment]
After debugging, the log shows:
`MapFile: current block size too large: 3326540`

So the issue is due to read buffer limit, see #619.
We had made the limit adjustable for users to select what they need.
e.g. on desktop where memory is less restrictive we [have](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-awt/src/main/java/org/mapsforge/samples/awt/Samples.java#L73):
```java
ReadBuffer.setMaximumBufferSize(6500000);
```

**Comment by k3b** [comment]
Thanks for fast help.

I will try this tonight.

**Comment by k3b** [comment]
with 

    ReadBuffer.setMaximumBufferSize(6500000);

the problems are gone :-)
