### ISSUE TITLE
AndroidMatrix not accessible

### ISSUE THREAD

**Issue by DrMarkEy** [mapsforge/mapsforge#870]
I try to draw a Bitmap as MapOverlay with a transformation matrix. Unfortunately there seems to be a problem with the accessibility of some of the drawing classes, espacially with the AndroidMatrix class. Therefore it is currently impossible to use the method Canvas.drawBitmap(Bitmap bitmap, Matrix matrix).

**Comment by devemux86** [comment]
Are you trying to mix an Android Canvas with a Mapforge Matrix?

Mapsforge interfaces & their Android / Java classes are meant to be used within their environment:
```java
AndroidGraphicFactory.createGraphicContext(android.graphics.Canvas).drawBitmap(Bitmap, Matrix);
```

**Comment by DrMarkEy** [comment]
Thank You, I wasn't trying to mix mapsforge and android classes but rather couldn't find a method to construct a mapsforge matrix for the mapsforge.core.graphics.Canvas.drawBitmap((Bitmap bitmap, Matrix matrix) method, because Matrix is only an interface and the implementation AndroidMatrix is not accessible from the outside. Thanks to your answer I've just found the AndroidGraphicFactory.INSTANCE.createMatrix() method, which solves my problem. Nevertheless I think it is a bit confusing how this has to be done.

**Comment by devemux86** [comment]
Mapsforge from the `rewrite` era was rebuilt that way in order to support multiple platforms.
There are the common interfaces called in the core and their implementations per platform.
The `...GraphicFactory` classes are the best start points for handling all these.
