### ISSUE TITLE
Osmarender - Making a line invisible

### ISSUE THREAD

**Issue by dsehrawat** [mapsforge/mapsforge#874]
Hi Everyone,

I am struggling to make a section of "footway" disappear (indoor section). I want it to be there in nodes and ways but don't want it to be visible on mapsforge during rendering (via osmarender). I tried playing around with osmarender.xml; following section:

                    <rule e="way" k="highway" v="footway">
                        <line stroke="#e5e02" stroke-width="0.45" />
                        <rule e="way" k="*" v="*" zoom-min="20">
                            <pathText k="name" font-style="bold" font-size="10" stroke="#e5e0c2"
                                stroke-width="2.0"/>
                        </rule>

Tried making stroke-width to 0; it didn't work. Tried adding stroke-opaque field but looks like it's not supported.

Can anyone please help me?

**Comment by devemux86** [comment]
For questions please use our forum:
https://groups.google.com/forum/#!forum/mapsforge-dev
