### ISSUE TITLE
[vtm - enhacement req] Generalization of BucketRenderer

### ISSUE THREAD

**Issue by nebular** [mapsforge/mapsforge#875]
I am working in a layer to render 3d models around the map. My initial solution was creating a new layer extending `Layer`. But now I realize that the best approach is probably to create a custom `BucketRenderer` so I get lots of features for free: visibility test, texture atlas, VBO/IBO rendering ...

At the moment the bucket renderer has 4 or 5 bucket types hardcoded, but seems very easy to generalize so developers can create new Bucket Renderers.

In other words, turn this:

```
BucktRenderer.java 130

for (RenderBucket b = buckets.get(); b != null; ) {
            switch (b.type) {
                case POLYGON:
                    b = PolygonBucket.Renderer.draw(b, v, 1, true); break;
                case LINE:
                    b = LineBucket.Renderer.draw(b, v, div, buckets); break;
                case TEXLINE:

```                     
into something like

```
for (RenderBucket b = buckets.get(); b != null; ) {
    
          b = BucketRendererProvider.get(b.type).render(b,v,buckets);
    

```

Do you think it is a good idea?
Thanks in advance

**Comment by devemux86** [comment]
As this is Mapsforge issues list, can you create it in [VTM issue list](https://github.com/mapsforge/vtm/issues), explaining also in more detail the change benefits?
