### ISSUE TITLE
Do TileCache.put() in another Thread

### ISSUE THREAD

**Issue by virus-warnning** [mapsforge/mapsforge#878]
In MapWorkerPool.java, line 155~163

``` java
bitmap = MapWorkerPool.this.databaseRenderer.executeJob(rendererJob);
if (inShutdown) {
    return;
}

if (!rendererJob.labelsOnly && bitmap != null) {
    MapWorkerPool.this.tileCache.put(rendererJob, bitmap);
    MapWorkerPool.this.databaseRenderer.removeTileInProgress(rendererJob.tile);
}
```

Before render a tile, it's necessary to wait previous tile putting into cache.
If the cache instance is FileSystemTileCache, and the file system is in SD card,
it cost a lot of time to wait tileCache.put().

Hope tileCache.put() run in another thread, and schedule them by queue.
With non-blocking design, the performance of rendering is better.

For some Android phones, it's not a good idea to use InMemoryTileCache.
I have got some OOM from several phones, especially Samsung Note and S series.

**Comment by devemux86** [comment]
Following the API calls you can see how the whole cache system works.
Also you can try enabling multithreaded rendering via `MapWorkerPool.DEFAULT_NUMBER_OF_THREADS` (default 1, see $591 #806).

With the Mapsforge `rewrite` I thought we forgot OOM. :smile: 
Only in extreme situations we might see them now.

But the exceptions log and how you create the tile layer would be helpful.
And you can choose what caches to use (memory, file, both).

**Comment by virus-warnning** [comment]
I got OOM after using AndroidUtil.createTileCache(...).
Two level cache is not stable for Android.

**Comment by devemux86** [comment]
>Two level cache is not stable for Android.

That's a 1st time to hear that.. we never had such issue so far.

Please test Mapsforge [Samples](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) to see its behavior.

Also provide details regarding how you build the map and any logs, without them the issues cannot be examined.

**Comment by virus-warnning** [comment]
Thanks, I found another approach to improve performance.
I'll make a PR later, which contain a MapView for Android.
The new MapView is ParallelMapView.
ParallelMapView render tiles by SurfaceView at another Thread, not in ViewGroup.
