### ISSUE TITLE
Blurry or aliased bitmap markers

### ISSUE THREAD

**Issue by TheChimeric** [mapsforge/mapsforge#881]
Hello, first I would like to thank all the people who work everyday to make mapsforge better.
In my mapsforge based app, i use markers overlays to indicate locations and other things. I use bitmaps for that, and for visibility reasons they are 50px x50px of dimension.The problem is that at that size, the bitmaps of my marker look very aliased or blurry. In other words, they seem ugly compared to the map. My question is: is here a trick to improve the appearance of my bitmap markers? Does mapsforge support svg vector overlays (as vectors are well known to have looseless quality)
I hope you can help me, forgive me for my poor english. Thanks.

**Comment by devemux86** [comment]
Mapsforge needs a `org.mapsforge.core.graphics.Bitmap` for the `Marker`.
Having high quality drawables per density in `drawable-X` folders, you can create bitmaps with `AndroidGraphicFactory.convertToBitmap(drawable)`.
See Samples [OverlayMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/OverlayMapViewer.java) for a complete example.

**Comment by TheChimeric** [comment]
I followed your instructions and my markers look much better. Instead of loading low res bitmaps as i did before, i used hi res bitamps and rescaled them to the suitable size before displaying them as markers. The result is very good. Thank you for the quick answer

**Comment by devemux86** [comment]
Forgot to mention that we now support (#858) loading of SVG also outside themes.
e.g. check `AndroidSvgBitmap.getResourceBitmap`
