### ISSUE TITLE
High CPU Load at LayerManager in emulator with nothing to do.

### ISSUE THREAD

**Issue by mikes222** [mapsforge/mapsforge#882]
Just opening a view with Mapsforge in android emulator and doing nothing. The Taskmanager shows 20% cpu. The android Monitor reports that doWork() in LayerManager is constantly executing. Seems `redrawNeeded`is always true. 

Any suggestions how to fix this? 

btw. A workaround would be to let us change the `MILLISECONDS_PER_FRAME` variable in layermanager. 

This is how the mapView is instantiated:

```
    mapView = new MapView(getActivity());

    mapView.setClickable(true);
    mapView.getMapScaleBar().setVisible(false);
    mapView.setBuiltInZoomControls(false);
    mapView.getMapZoomControls().setZoomLevelMin(ZOOMLEVEL_MIN);
    mapView.getMapZoomControls().setZoomLevelMax(ZOOMLEVEL_MAX);
    mapView.getModel().mapViewPosition.setZoomLevelMin(ZOOMLEVEL_MIN);
    mapView.getModel().mapViewPosition.setZoomLevelMax(ZOOMLEVEL_MAX);
    mapView.getModel().mapViewPosition.setCenter(new LatLong(0, 0));
    mapView.getModel().mapViewPosition.setZoomLevel(ZOOMLEVEL_MIN);

    TileRendererLayer tileRendererLayer = MapMgr.get().getTileRendererLayer(mapView.getModel());
    mapView.getLayerManager().getLayers().add(tileRendererLayer);

    LabelLayer labelLayer = new LabelLayer(AndroidGraphicFactory.INSTANCE, tileRendererLayer.getLabelStore());

    mapView.getLayerManager().getLayers().add(labelLayer);

    // prevent flickering on some hardware
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)
        mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);

    zoomObserver = new ZoomObserver();
    markerObserver = new MarkerObserver();
    mapView.getModel().mapViewPosition.addObserver(zoomObserver);
    mapView.getModel().mapViewPosition.addObserver(markerObserver);
```

Later on a bunch of layers are added. This might be the reason why the cpu-load is so obious to me.

**Comment by devemux86** [comment]
Layer redraw can happen continuously with a location layer, where each location update triggers a redraw.

Here I see you use a `LabelLayer` which indeed uses much more CPU.
Have you tried without it?

And are the map edges visible during the event?
See also #803.

**Comment by mikes222** [comment]
I do not have a location layer and I do not change the location in the android emulator. 

Issue #803 seems not suitable to my problem. See screenshot below. 

![untitled](https://cloud.githubusercontent.com/assets/2129663/19220940/744b2746-8e39-11e6-92d5-3f2be14a5f66.png)

I found out: If I zoom in or change the `ZOOMLEVEL_MIN` from 6 to 7 the cpu usage falls down to zero. My first guess is that pow(2, 6) is not exactly 64.0(double) in `MapViewPosition.animationInProgress()`. 

Althought setting the starting zoom level to 7 instead of 6 is not a big deal I cannot guarantee that this behavior is not occuring at other zoom levels too therefore I would like to find the root cause for that issue.

**Comment by devemux86** [comment]
Zoom levels 6-7 are small enough for the edges to be near visible view depending on map area and screen size.
And considering that the default frame buffer is square (largest side), I'm not sure if above map is completely covers it.

**Comment by mikes222** [comment]
`redrawLayers()` in `LayerManager` is called by `MapWorkerPool.this.layer.requestRedraw();` in `MapWorkerPool`. 
The jobs are added by `retrieveLabelsOnly()` in `TileRendererLayer` and feed by `LayerManager` line 95 (`layer.draw(boundingBox, mapPosition.zoomLevel, this.drawingCanvas, topLeftPoint);`

So seems we have a circular call here. No clue how to solve this. 

(I am sure now that this issue is similar to #803)

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
