### ISSUE TITLE
Rendered result only displays big cities names and no streets/roads

### ISSUE THREAD

**Issue by androidseb** [mapsforge/mapsforge#885]
First, allow me to thank you for your amazing work!

I spotted this issue, not sure what the source of the problem is, but in the hope that it will be helpful to you, here are the steps to reproduce it:
- Download the full mapsforge project from github (from October 14th, 2016)
- Download the "brazil.map" http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/south-america/brazil.map the version says "2016-10-15 02:56 628M"
- Rename the "brazil.map" to "germany.map" at the root of the sd card
- Open the mapsforge project with Android studio
- Launch the sample app on a real physical device running Android 6.0.1 (LG G5 in my case)
- open the "rendertheme V4" activity

=> when zooming on any city, the streets/roads to not display

**Comment by devemux86** [comment]
A sufficient zoom is needed so that labels can "fit" in their line segments (see screenshot), specially if there are curved roads.

That area certainly needs improvements (related to #644).

![streets](https://cloud.githubusercontent.com/assets/3484020/19410335/1278ed38-92f2-11e6-9dce-9beb83c60c09.png)

**Comment by b3nn0** [comment]
I'm currently working on a way to enable better pathText rendering. The result already looks quite promising. Basically, pathText can do up to a 45° angle and renderes around curves. It already somewhat works for both, Android and AWT:
![grafik](https://user-images.githubusercontent.com/1858945/55186709-7f599680-5197-11e9-907e-4432490b10bc.png)
I'm still fighting some issues - would a patch with something like that be accepted?
It will also need some renderTheme tweaks. The current render theme will now draw far too many labels, and has some display="always" in there that will result in overlapping labels.

Also, some overlapping issues that I don't understand yet:
![grafik](https://user-images.githubusercontent.com/1858945/55186946-0d358180-5198-11e9-93b9-838457077d5e.png)

**Comment by devemux86** [comment]
> It already somewhat works for both, Android and AWT

That is essential to be implemented so that will work in all platforms.

> I'm still fighting some issues - would a patch with something like that be accepted?

If there is a working solution, we can review it.

**Comment by devemux86** [comment]
> It already somewhat works for both, Android and AWT

It's essential that every implementation works on all platforms.

> I'm still fighting some issues - would a patch with something like that be accepted?

If there is a working solution, we can review it.

> is it acceptable to include an apache-licensed code file from a different project?

That license is compatible and can include such classes if they are self-contained.

**Comment by devemux86** [comment]
Implemented via #1112.
