### ISSUE TITLE
Updates for Europe offline maps

### ISSUE THREAD

**Issue by arbie65** [mapsforge/mapsforge#887]
Hiya,

How often are the  offline maps which are available here (1) updated?  It looks like most of the world gets updates except for Europe where only Germany gets updates recent. Everything else is at least 6 months old if not older.

**Comment by devemux86** [comment]
For questions please use our forum:
https://groups.google.com/group/mapsforge-dev

Also you can find there a recent [answer](https://groups.google.com/forum/#!topic/mapsforge-dev/IbNv_TU7SY8) to this.
