### ISSUE TITLE
Customize mapView animation speed and interpolation

### ISSUE THREAD

**Issue by bruneric** [mapsforge/mapsforge#889]
Sometimes i use animateTo() method to animate the mapView to a specified position, and it works very well. Unfortunately i am not able to customize the animation speed(or duration), and i can't find a way to change the default interpolation of the mapView animation. My question is: is it possible to customize speed and/or interpolation of mapView's animateTo() method?

**Comment by devemux86** [comment]
`MapViewPosition.animateTo` uses some predefined constants for the animation calculation.
We could add another method with these as variables or even come with a better implementation. :slightly_smiling_face:
