### ISSUE TITLE
Problem with line patterns

### ISSUE THREAD

**Issue by jolly47roger** [mapsforge/mapsforge#894]
I am trying to render a Mapsforge map that I have created.
I have a line pattern for an embankment and I want this pattern to follow the bank of the river, curving where necessary and making a continuous line.

This happens with Vectorial Map but Cruiser and Mobile Atlas Creator clip the pattern to the width of the stroke but do not rotate it or curve it. I am using XSD v5

<rule e="way" k="barrier" v="retaining_wall">
  <line  src="file:/patterns/embankment.png" stroke-width="4.0" />
</rule>

Which of these results is the correct one? I want to use MOBAC for rendering but cannot find a way to get it to do what I want. (lineSymbol plats copies of the pattern along the line but they are neither continuous nor curved)
![embankment](https://cloud.githubusercontent.com/assets/6407871/20015584/eae8ca1e-a2b3-11e6-8d93-e33cb1115aac.png)

**Comment by devemux86** [comment]
Do you have a sample map and theme to test?
Or coordinates at an existing map and the change in default theme?

**Comment by devemux86** [comment]
BTW why don't you use a `line` with `stroke-dasharray`?

**Comment by jolly47roger** [comment]
Thanks,

www.the-thorns.org.uk/topostyle.zip  contains the map and the style sheets.

Everything is else works well - apart from bridges which suffer in the same
way as the embankment and I still have to get the elevations onto the
contours.

Best wishes,

John

**Comment by jolly47roger** [comment]
For that pattern, I could use a dasharray but there are other line patterns
- such as cliffs - that are assymetric for which I will need a solution

John

**Comment by devemux86** [comment]
If you check also internal theme line patterns, they're created for expansion in all directions.
Apparently implementation works like area patterns, filling all available space.

**Comment by jolly47roger** [comment]
Sorry, I don't understand what I need to do.

**Comment by devemux86** [comment]
I meant to check [line patterns](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-themes/src/main/resources/osmarender/osmarender.xml#L757-L762) of internal theme [here](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-themes/src/main/resources/osmarender/patterns).
Current implementation works by using them like area patterns.

**Comment by jolly47roger** [comment]
With those patterns it doesn't matter whether they rotate or not.

What I am looking for is something like this : https://tilemill-project.
github.io/tilemill/docs/guides/styling-lines/

I have been trying with SVG patterns but they behave in the same way as
PNG.

John
