### ISSUE TITLE
Documentation Write-Access POI Persistance Manager 

### ISSUE THREAD

**Issue by wish7code** [mapsforge/mapsforge#897]
Minor improvement suggestion for https://github.com/mapsforge/mapsforge/blob/master/docs/POI.md 

It says:

> With everything set up you can check the 'POI search' example in Samples for:
>     How a database is opened for read-**write** access.

I think, that in fact the 'POI search' sample just shows the **read** access..
We might add a explaining sentence here like 

> In order to get write access, call getPoiPersistenceManager(filename, false)

**Comment by devemux86** [comment]
Thanks!
