### ISSUE TITLE
Area not correctly filled

### ISSUE THREAD

**Issue by mikes222** [mapsforge/mapsforge#908]
I have a closed way (first and last nodeId is the same) with 580 nodes. Tags are as follows: 

tag k="boundary" v="administrative"/>
tag k="city:left" v="Gela"/>
tag k="region:left" v="Sicilia"/>
tag k="province:left" v="Caltanissetta"/>
tag k="natural" v="nosea"/>
tag k="layer" v="-5"/>

The rendering in the map however is not correct. See the following image made with sample app:
![grafik](https://cloud.githubusercontent.com/assets/2129663/21017861/124d2b5a-bd6b-11e6-8634-993a85658e86.png)

Any clue how to fix this?

This is a very simplified file providing only sizilia.

[map_simpl_sizilia.zip](https://github.com/mapsforge/mapsforge/files/640046/map_simpl_sizilia.zip)

I have created the file with 

`call osmosis\bin\osmosis.bat --read-xml file=map_simpl_sizilia.osm --mapfile-writer file=map_simpl_sizilia.map type=hd zoom-interval-conf=8,5,11 simplification-factor=0`

**Comment by devemux86** [comment]
We don't prefer OSM coastline (being line), but land polygons from [OpenStreetMap Data](http://openstreetmapdata.com/).
See also the map creation [guide](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md) for details.

With them the result is like the screenshot:
![land](https://cloud.githubusercontent.com/assets/3484020/21024854/be85ec54-bd8e-11e6-8b82-eb42082ee617.png)

Closing as for questions please use our forum:
https://groups.google.com/group/mapsforge-dev
