### ISSUE TITLE
Fling on "Map Rotation" sample goes to wrong direction

### ISSUE THREAD

**Issue by pauminku** [mapsforge/mapsforge#910]
When you fling the map on the "Map Rotation" sample with map rotated, the fling direction is not rotated, so it moves to wrong direction.
The problem is that rotateTouchEvent in RotateView only rotates the last position, not historical positions. 
Historical positions can't be modified on MotionEvent's, so I thing the only possible solution without refactoring a lot of code is to get the rotated event with: 
`MotionEvent rotatedEvent = MotionEvent.obtainNoHistory(ev);`
At least when `mapOrientation != 0`

**Comment by devemux86** [comment]
Thanks for the report!

We can use newer Android API for the rotated event's transformation.
I pushed a different implementation, can you check it?

**Comment by pauminku** [comment]
Yes, it works perfectly. Better than just use obtainNoHistory because fling keep working always.
