### ISSUE TITLE
Multiple Maps with different zoom levels

### ISSUE THREAD

**Issue by mikes222** [mapsforge/mapsforge#911]
I have a MultiMapDataStore with different maps. 

- One map is created with configuration parameter zoom-interval-conf=8,5,11
- Another map (or a bunch of other maps) is/are created with zoom-interval-conf=15,12,18

Since `public boolean supportsTile(Tile tile)` do not take the zoomLevel into account the system tries to query the detailed maps even if it should display zoomLevel 5 which lead to OutOfMemoryError because the detailed maps tries to collect several 100.000 ways for `MapReadResult`. 

**Some additional infos:**

`MapFile.processBlocks` is called with the following QueryParameters:

QueryParameters{fromBaseTileX=0, fromBaseTileY=0, fromBlockX=0, fromBlockY=0, queryTileBitmask=0, queryZoomLevel=12, toBaseTileX=32767, toBaseTileY=32767, toBlockX=1365, toBlockY=2272, useTileBitmask=false}

This call never returns...

**How to solve that issue?**
- take zoomLevel into account at `supportsTile()`, how?
- do not return ways/pois if no zoomlevel is defined in the current map?
- some code in MultiMapDataStore to have a fallback?

Any help is appreciated. 
Regards, Mike

**Comment by mikes222** [comment]
addendum: setting `public void restrictToZoomRange(byte minZoom, byte maxZoom)` to 12, 18 does not help.

**Comment by devemux86** [comment]
For questions please use our forum:
https://groups.google.com/group/mapsforge-dev

**Comment by devemux86** [comment]
I enabled the `MapFile.restrictToZoomRange(minZoom, maxZoom)` in a more correct way.

`MultiMapLowResWorld` sample demonstrates the two ways for restricting zoom range:
- Use `MapFile.restrictToZoomRange(minZoom, maxZoom)`
- Override the `MapDataStore.supportsTile(tile)`

**Comment by devemux86** [comment]
@mikes222 can you check if it works for you?

**Comment by mikes222** [comment]
Hi @devemux86, yes it works! 
I just want to note here that one can retrieve the default zoom levels of this map from `MapFile.getMapFileInfo().zoomLevelMin` and `MapFile.getMapFileInfo().zoomLevelMax`. This values can then be filled into `MapFile.restrictToZoomRange(minZoom, maxZoom)`.
