### ISSUE TITLE
AndroidUtil.createExternalStorageTileCache uses Context.getExternalCacheDir()

### ISSUE THREAD

**Issue by easdue** [mapsforge/mapsforge#913]
Context.getExternalCacheDir() will allways return emulated external storage on API23 and up. 
Wouldn't it be better to let the application decide the storage location for caching tiles?

If not Context.getExternalCacheDirs() should be used to determine the real external storage location
Index 0 on API23 and up will always be emulated external storage (at least on emulators)
Index > 0 will be real external storage.

**Comment by devemux86** [comment]
Good remark!

Though `Context.getExternalCacheDirs()` requires API level 19 and we shouldn't load Mapsforge with Android Support dependency.

So best if the API provide as parameter the cache directory, selectable by the user from outside.

**Comment by devemux86** [comment]
I added in `AndroidUtil` extra methods with the tile cache folder as parameter.
