### ISSUE TITLE
AndroidSvgBitmapStore uses Context.openFileOutput

### ISSUE THREAD

**Issue by easdue** [mapsforge/mapsforge#914]
This results in svg's being cached in the applications getFilesDir(). Wouldn't it be better to
a: let the application decide where to cache svg's (internal or external cache dirs)
b: use internal or external cache dir

**Comment by devemux86** [comment]
Not a bad idea!

The `AndroidSvgBitmapStore` is an internally used class, so we need to find a way to pass the svg cache directory.

**Comment by devemux86** [comment]
I added the `AndroidGraphicFactory.setSvgCacheDir` method for setting the SVG cache folder.
