### ISSUE TITLE
memory leak from TileDownloadThread

### ISSUE THREAD

**Issue by Bananeweizen** [mapsforge/mapsforge#918]
Since upgrading to mapsforge 0.7 I see a memory leak in the LeakCanary reports, with pointers going from the TileDownloadThread to the Activity containing the MapView.

* cgeo.geocaching.maps.mapsforge.v6.NewMap has leaked:
* GC ROOT org.mapsforge.map.layer.download.TileDownloadThread.<Java Local>
* references org.mapsforge.map.layer.queue.JobQueue.mapViewPosition
* references org.mapsforge.map.model.MapViewPosition.observers
* references java.util.concurrent.CopyOnWriteArrayList.elements
* references array java.lang.Object[].[2]
* references cgeo.geocaching.maps.mapsforge.v6.MfMapView.mContext
* leaks cgeo.geocaching.maps.mapsforge.v6.NewMap instance

That leak is seeminly reported every time when leaving a map activity.

I have been solving similar issues in cgeo code itself by only having weak references when storing activities, views etc. So from my point of view the CopyOnWriteArrayList in the observer seems most suspicious since I would expect some kind of weak reference collection there instead. However, I'm not sure of that, since I don't really know your architecture and implementation.

The reported leakage is just some KB, so this probably only leads to real problems like crashes over some extended time of usage, I guess.

**Comment by devemux86** [comment]
Thanks for the report.

- Are you sure it's not related to app implementation but it's a library issue?
- Can you see such behavior also with Mapsforge [Samples](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) examples?

**Comment by devemux86** [comment]
For reference there is another for memory leak in #845.

**Comment by puneethreddy-3186** [comment]
The memory leak happens on the sample project too!! See the snapshot from the eclipse MAT. Seems like the LayerManagerController and MapViewController are registered as observers to the mapViewPosition and mapViewDimension model objects, but they are never unregistered from them.
The same is confirmed by the MAT, See the pic below
<img width="618" alt="untitled" src="https://user-images.githubusercontent.com/35573402/35111258-21e77c78-fc7b-11e7-8cc8-1a95ef50a1c9.png">

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
