### ISSUE TITLE
Missing Admin Boundaries

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#925]
Parts of administrative boundaries are missing. Here is an example at the western border of Massachusetts and New York states:

![image](https://cloud.githubusercontent.com/assets/1422186/23322246/e6fb6182-fa97-11e6-9b2b-d765ee9d3923.png)

The problem is that the map writer doesn't seem to handle relations correctly.

The missing way is 

```
  <way id="29307896" version="12" timestamp="2013-08-23T15:14:31Z" uid="113450" user="nfgusedautoparts" changeset="17471305">
    <nd ref="75427679"/>
    <nd ref="2429256059"/>
  </way>
```

which is part of

```
 <relation id="61315" version="106" timestamp="2016-11-08T18:41:20Z" uid="1943392" user="LogicalViolinist" changeset="43495289">
    <tag k="ref" v="MA"/>
    <tag k="name" v="Massachusetts"/>
    <tag k="type" v="boundary"/>
     <tag k="boundary" v="administrative"/>
    <tag k="admin_level" v="4"/>

```
If I add boundary=administrative and admin_level=4 to way 29307896 like so:

```
  <way id="29307896" version="12" timestamp="2013-08-23T15:14:31Z" uid="113450" user="nfgusedautoparts" changeset="17471305">
    <nd ref="75427679"/>
    <nd ref="2429256059"/>
    <tag k="boundary" v="administrative"/>
    <tag k="admin_level" v="4"/>
  </way>
```

Then the missing way gets put into the map:

![image](https://cloud.githubusercontent.com/assets/1422186/23322447/d75cb982-fa98-11e6-9986-ba60e263a607.png)

**Comment by devemux86** [comment]
Is this somehow related to #586 and use of `force-polygon-line` in administrative boundaries?

**Comment by lincomatic** [comment]
No, I looked further into the map writer, and the problem is that it doesn't handle relations at all, except for multipolygons. I am working on a fix. Also, I need to open another issue. There are a lot of bugs in the clipping of large polygons.

**Comment by devemux86** [comment]
> the problem is that it doesn't handle relations at all, except for multipolygons.

Indeed that's an old issue (#245).

**Comment by lincomatic** [comment]
OK, sorry, I didn't know about #245. I have modified the map writer to handle boundary relations, and it's working perfectly now. My fix only supports RamTileBasedDataProcessor, not HDTileBasedDataProcessor.. unfortunately, I'm swamped with other work, and don't have time to write code that supports the HDTileBasedDataProcessor. Also, I am working with a snapshot of the code from a year ago. As such, I don't think I should submit a pull request, but I can share the code with you if you would like to take a look

**Comment by ludwigb** [comment]
If you share the code I might have a look. There have been not too many
changes in the writer, so integration should not be too difficult ... but
testing it is another matter....

**Comment by devemux86** [comment]
@lincomatic @ludwigb 
:+1:

**Comment by lincomatic** [comment]
I i'm still tweaking it a bit. Will post here when I'm done testing my planet map
