### ISSUE TITLE
Error rendering forest polygons

### ISSUE THREAD

**Issue by pbmorton** [mapsforge/mapsforge#926]
I've seen this issue with mapsforge 0.5.0, 0.5.1 and now 0.7.0. I'm using the render theme in mapsforge 0.7.0 mapsforge-themes\src\main\resources\assets\mapsforge\default.xml with the following modification to make my error more visible (i.e. I'm colouring the forests red):

    <rule e="way" k="natural|landuse" v="forest|wood">
        <area fill="#A50000" />

    </rule>

When rendering the forests the map incorrectly shows white areas amongst the forest as shown in the attached screenshot. I doubt the openstreetmap raw data is faulty as these forest areas show up correctly when viewing the map via http://www.openstreetmap.org. Also note that when I generate the maps I'm using the mapsforge 0.7.0 mapsforge-map-writer\src\main\config\tag-mapping.xml.

Can anyone suggest what the problem is here? Also if you'd rather I move this "issue report" instead to stackoverflow just say so and close it here.

![screenshot_2017-02-28-01-46-23](https://cloud.githubusercontent.com/assets/8908488/23388748/06cad3ee-fd9f-11e6-9cba-31019539edcc.png)

**Comment by devemux86** [comment]
Can you point us the map file from the [download server](http://download.mapsforge.org/maps/) and the coordinates to check that area?
(or an OpenStreetMap link)

**Comment by pbmorton** [comment]
This is the link. Let me know if you need some info.
http://www.openstreetmap.org/#map=10/-34.0390/115.7176

**Comment by devemux86** [comment]
Maybe the [simplification](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#advanced-options-only-use-when-you-know-what-you-are-doing) happening in zoom levels <12 plays a role, as the issue in zoom 12 "mostly" disappears.

We see the same map appearance with OpenAndroMaps too:
![oam](https://cloud.githubusercontent.com/assets/3484020/23401281/cb7c8308-fdaf-11e6-9e29-d341e06c78f2.png)

**Comment by applantation** [comment]
In the original data is this actually a single polygon? or is it several
polygons that in the original data cover the entire area?
To me it looks like several polygons that are then separately simplified,
resulting in these empty spaces?

**Comment by devemux86** [comment]
@ludwigb is right, that's usually the first thing to check in such cases.

**Comment by ludwigb** [comment]
It is what I expected: the forest is composed out of zillions of individual
(non-rectangular) polygons. In the process of simplification, these
polygons are individually simplified, as the simplification process does
not know that these polygons actually make up a contiguous area. The result
of the simplification is that individual points eliminated to straighten
lines, the resulting areas so do not match up, making the back-ground show
through.

I think this is actually a data error: this is a contiguous forest area,
not a collection of individual forest areas that happen to make up a
contiguous forest.

I think the only solution would be to turn the simplification off
altogether, but this will result in polygons with many more points and
increased map size. Increase map size also means increased reading and
rendering time.

There are some options on the mapbuilding process for this, might be worth
seeing what the impact of changing the simplification factor is: does it
eliminate the problem? impact on map size? impact on rendering time?

Ludwig

**Comment by devemux86** [comment]
> I think this is actually a data error: this is a contiguous forest area, not a collection of individual forest areas that happen to make up a contiguous forest.

:+1: 

Turning simplification off for small zoom levels would hurt performance.
And the problem does not disappear completely. Can be checked already in zoom 12 where we don't have simplification.
The multiple polygons are not designed to fit perfectly each other, so some voids still exist.

If the OpenStreetMap data are not correctly made, probably fix them?

**Comment by pbmorton** [comment]
I can confirm the OSM data for the contiguous forest area is made up of many smaller  polygons and the white areas do show up on the polygon boundaries due to simplification when zoomed out. As you've said, the proper way to fix this is to fix the OSM data. Perhaps polygons that are for identical "areas" that have exactly shared boundaries should be merged in the OSM data? I cannot see a way of doing this (easily or not so easily) as an OSM contributor. What are the options?

**Comment by devemux86** [comment]
Learning how to map, there are a couple of good resources out there, e.g. [learnOSM](http://learnosm.org/en/).

**Comment by pbmorton** [comment]
I'm willing to use JOSM to merge some of the land use areas to remove this problem for the map I need. Manually fixing this worldwide for all land use is impractical. I think it should be automated.

The map area I must fix is very large - the limitations of JOSM (or whatever) mean I must work on several smaller areas separately. I have a couple of questions I'd really appreciate you answer.  

Using JOSM I'm doing these steps:
- downloading a map areas
- Edit menu -> Search. I search "natural=wood"
- Tools menu -> Join Overlapping Areas.
- I then see a warning. When I select "yes" I see another warning. The 2 warnings are attached.
![merge_warning](https://cloud.githubusercontent.com/assets/8908488/23584193/dc364902-0194-11e7-9f7f-739d3e2b357d.jpg)
![merge_warning2](https://cloud.githubusercontent.com/assets/8908488/23584194/df8b90bc-0194-11e7-806e-2ac9dafeb753.jpg)

The warnings advise me to "please abort if you are not sure". Well, I'm not sure. Can you please tell me if it is safe to ignore these warnings in my use case? If it's unsafe can you suggest a different tool or procedure for merging land use areas?

**Comment by pbmorton** [comment]
You labelled this issue as invalid. There is nonetheless an underlying problem where OSM data and the way it is typically simplified for mapsforge results in mapping artefacts. Are you suggesting we do nothing about this other than manually fixing the map data to merge a huge number of small polygons?

**Comment by devemux86** [comment]
Invalid as it's not tied strictly with something need be done in Mapsforge code.
The reader does not modify the input data - besides simplification which is by default enabled until zoom 12, but can be [changed](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#advanced-options-only-use-when-you-know-what-you-are-doing) on map creation.

Like mentioned, this area's polygons are split and also not even perfectly connected each other.
So the logical step would be to correct or report those data in OpenStreetMap?

**Comment by applantation** [comment]
It is really an error in the data: the forest areas are really contiguous
and not composed of individual patches of forest.

However, there is probably a way that would make this effect disappear.
Just to recap: the problem is that certain points on lines are eliminated
because the angle between the lines is close to 180deg. If you were to
preprocess the data first to align all points on a grid (let's say 50cm
apart, in real life this makes little difference as most OSM data is not so
accurate) then this effect would probably not be visible as lines were
either straight or the angle so large as to not allow simplification.

This alignment on a grid could be achieved by simply rounding the OSM
coordinates to a grid, by truncating the last few digits in the OSM coords.
As this would happen in the map writer there is no performance overhead and
perhaps the map would get smaller as we then store less accurate
coordinates.

If this is really an issue to you, I would suggest you try this in the
mapwriter somewhere.

**Comment by devemux86** [comment]
@ludwigb still the original data have voids among them, so eventually there would be voids in the map too.

**Comment by devemux86** [comment]
I remove the label until issue is well defined.
