### ISSUE TITLE
mapsforge and JavaFX

### ISSUE THREAD

**Issue by blackbirdsr71br** [mapsforge/mapsforge#928]
Is there any way to integrate mapsforge with JAVAFX

Thank you.

**Comment by devemux86** [comment]
Mapsforge is a multi-module vector map library with clearly separated core (backend) and platform (frontend) modules.

We have already the `mapsforge-map-android` for Android and `mapsforge-map-awt` for AWT / Swing platforms.

There could be needed a `mapsforge-map-javafx` module hooking Mapsforge API with JavaFX ecosystem.
([mapsforge-map-awt](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map-awt) would be a nice guide for that)
