### ISSUE TITLE
Multiline text can be drawn overlapped

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#929]
Sometimes, text is drawn overlapped, if the string gets broken up into multiple lines.
This is caused by a bug in the calculation of text height in AwtPaint.java.

```
	public int getTextHeight(String text) {
		Graphics2D graphics2d = bufferedImage.createGraphics();
		FontMetrics fontMetrics = graphics2d.getFontMetrics(this.font);
		graphics2d.dispose();
		return (int) this.font.createGlyphVector(fontMetrics.getFontRenderContext(), text).getVisualBounds().getHeight();
	}
```

The calculation does not take into account the fact that the string will be drawn on multiple lines.

**Comment by devemux86** [comment]
Do you mean overlapped with text of another element, like when using the [display="always"](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#display) directive which permits overlaps?

Could post an example screenshot?

**Comment by lincomatic** [comment]
It's not related to display="always." It's something more fundamental. Here is an example:

![image](https://cloud.githubusercontent.com/assets/1422186/23527604/88c16edc-ff4b-11e6-888b-da082915157d.png)

Note that Sahwari Democratic Republic overlaps with Mauritania. This is because when the bounding box for the text is computed, it doesn't know that the text will be broken up into multiple lines. So in DatabaseRenderer, the code that looks for clashes uses the wrong bounding rectangle.

**Comment by lincomatic** [comment]
Hmm. Sorry, I just looked into AwtPointTextContainer::computeBoundary(), and it actually does try to compensate for multiple lines:

```
		if (lines > 1) {
			// a crude approximation of the size of the text box
			boxWidth = maxTextWidth;
			boxHeight = this.textHeight * lines;
		}
```

but I guess the crude approximation is not good enough.

**Comment by lincomatic** [comment]
The approximation only takes into account total number of characters, and ignores spaces, so it will often compute too few lines

**Comment by devemux86** [comment]
Could you proved an example with a map from the [download server](http://download.mapsforge.org/)?
Our world map does not have labels, so it's difficult to reproduce the issue.

**Comment by lincomatic** [comment]
I have a deadline right now, it will take me some more time to find an example using one of your maps. But in the process, I found a couple of different issues, using the current map Africa map from the download server. This is using Atlas 1.2.3.

1) note the improper line break below

![image](https://cloud.githubusercontent.com/assets/1422186/23594855/2c308e8a-01d2-11e7-8ac0-cd634f17049b.png)

2) overlapping and cut off text:

![image](https://cloud.githubusercontent.com/assets/1422186/23594997/3e815cf8-01d3-11e7-9567-e044043b8973.png)

3) overlapping text

![image](https://cloud.githubusercontent.com/assets/1422186/23595045/94c65730-01d3-11e7-95f3-2ffe1145ca14.png)


It is harder to reproduce text errors with Cruiser desktop, since it uses oversized tiles. Is there a way to reduce the size of tiles in Cruiser?

**Comment by devemux86** [comment]
>It is harder to reproduce text errors with Cruiser desktop, since it uses oversized tiles. Is there a way to reduce the size of tiles in Cruiser?

For latest Desktop Cruiser I opted for using 512px tile size on vector maps for better rendering.

BTW you can also use [mapsforge-samples-awt](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-awt) for the tests, where you can change the tile size and use the latest reader at the same time.
