### ISSUE TITLE
map-writer: infinite loop with polylabel algorithm

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/mapsforge#930]
In order to improve the positioning of labels like this ...

![bildschirmfoto 2017-03-03 um 19 34 05](https://cloud.githubusercontent.com/assets/5493128/23563888/f5662930-0048-11e7-8a22-2aa8754124ca.jpg)

... I have activated the map-writer option "label-position=true". The result is a lot of warning output and the process runs into an infinite loop and has to be killed.

```
Mar 03, 2017 6:53:51 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.43.1
Mar 03, 2017 6:53:51 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Mar 03, 2017 6:53:51 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile-writer version: mapsforge-map-writer-0.7.0
...
Mar 03, 2017 6:54:26 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 100% of sub file for zoom interval 1 (5,0,7)
Mar 03, 2017 6:54:27 PM org.mapsforge.map.writer.util.PolyLabel get
WARNING: Failed to get label for geometry: MULTILINESTRING ((7.073865 51.483592, 7.073792 51.483496, 7.073848 51.483453, ...
...
Mar 03, 2017 6:54:27 PM org.mapsforge.map.writer.util.PolyLabel get
WARNING: Failed to get label for geometry: MULTILINESTRING ((7.365507 52.29322, 7.364424 52.291585, 7.363985 52.290906, ...
...
```

See also issue #886

**Comment by devemux86** [comment]
From the old days, map writer's label position option is not used in Mapsforge map reader.

That work was initiated from https://github.com/mapsforge/vtm/issues/80 for improved polygon labels and was implemented only in VTM client (not Mapsforge).

cc @andreynovikov

**Comment by devemux86** [comment]
Isn't more safe to use instead the `label-position` in tag-mapping for the needed polygons?
e.g. see default tag-mapping.xml which has it for polygon [buildings](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml#L312)

**Comment by Klaus-Tockloth** [comment]
Conclusion ... the "label-position=true" feature:
- is not applicable to mapforge (only vtm)
- results in (very) high cpu usage
- can only set for a small set of objects (due to high cpu usage)

Currently it doesn't make sense for me to use the feature.

**Comment by Klaus-Tockloth** [comment]
The primary problem is clarified. So I will close this issue. Thanks for looking into it and the helpful responses from devemux86.

**Comment by devemux86** [comment]
@Klaus-Tockloth let's leave it open, as eventually we need to see what happens.

BTW what map did you build and saw that behavior?

**Comment by Klaus-Tockloth** [comment]
Some remarks ...

Test area was this map from geofabrik (97 MB pbf):
http://download.geofabrik.de/europe/germany/nordrhein-westfalen/muenster-regbez.html

Normal build process (without any "label-position=true" setting):
76 sec (map size 76.3 MB)

Build process with "label-position=true" for all buildings (customized in tag_mapping.xml):
1920 sec (map size 79.7 MB)

Build process with "label-position=true" for all map objects (customized as mapwriter option):
process killed after approx. one hour (see first post; maybe to early)

**Comment by devemux86** [comment]
@Klaus-Tockloth thanks for the details!

@ludwigb I wonder if the `label-position="true"` in [buildings](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml#L312) is the reason for the late map build problems at the server.
Could you try the next build process without that tag?

**Comment by devemux86** [comment]
In #972 I reverted tag-mapping via 846f74a60473c4022b594fb859173f29aed7d381 to previous default configuration without `label-position` in buildings until this improves better.

**Comment by devemux86** [comment]
- In #1061 I changed the option `label-position` to use the JTS [interior point](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/InteriorPointArea.html) algorithm (minimal performance overhead) for calculating polygon centroids inside their interior.
If want to use instead the Mapbox [polylabe](https://github.com/mapbox/polylabel)l algorithm, can use the `polylabel=true` option.

- In #1064 I implemented the read & render of polygon [label/symbol position](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md#way-properties) from map files also in Mapsforge client.

This issue remains open for the "polylabel" algorithm infinite loop problems.
