### ISSUE TITLE
 Black screen in offline maps

### ISSUE THREAD

**Issue by blackbirdsr71br** [mapsforge/mapsforge#931]
Good afternoon.

Mapsforge is an excellent library, and I'm starting to use it, the problem I have is that when I use offline maps and follow the basic Android app example, and run it on my device, the application runs correctly but the map looks black in the screen.
![blackscr](https://cloud.githubusercontent.com/assets/24237848/23594186/9b0cbc38-01dd-11e7-8892-9dc03a9e526a.png)

Could you tell me what I'm doing wrong, attach my code

Thank you

package com.example.alex.sicmain;

import android.content.Context;
import android.location.Criteria;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.Environment;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.app.FragmentManager;
import android.view.View;
import android.support.design.widget.NavigationView;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.WindowManager;
import com.example.alex.sicmain.helpers.ExceptionsHelper;
import com.example.alex.sicmain.context.DataBase;
import com.google.android.gms.maps.model.LatLng;
import android.support.v4.content.ContextCompat;
import android.content.pm.PackageManager;
import android.widget.Spinner;
import android.view.View.OnClickListener;

import org.mapsforge.core.model.LatLong;
import org.mapsforge.map.android.graphics.AndroidGraphicFactory;
import org.mapsforge.map.android.util.AndroidUtil;
import org.mapsforge.map.android.view.MapView;
import org.mapsforge.map.datastore.MapDataStore;
import org.mapsforge.map.layer.cache.TileCache;
import org.mapsforge.map.layer.overlay.Marker;
import org.mapsforge.map.layer.renderer.TileRendererLayer;
import org.mapsforge.map.reader.MapFile;
import org.mapsforge.map.rendertheme.InternalRenderTheme;
import java.io.File;

@SuppressWarnings("ALL")
public class SICSystem extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener, LocationListener, OnClickListener {

    //** Variables Publicas
    public double latitude, longitude;
    public boolean first=true;
    public Context context;
    public LocationManager locationManager;
    public FragmentManager fragmentManager;
    public LatLng cameraLatLng;
    public float cameraZoom;
    public static String devicereg;

    private static final String MAP_FILE = "mexico.map";

    private MapView mapView;
    private final Marker marker=new Marker(null, null,  0, 0);;

    //** Variables Privadas

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        inicializaBD();
        AndroidGraphicFactory.createInstance(this.getApplication());

        this.mapView = new MapView(this);
        setContentView(this.mapView);

        this.mapView.setClickable(true);
        this.mapView.getMapScaleBar().setVisible(true);
        this.mapView.setBuiltInZoomControls(true);
        this.mapView.setZoomLevelMin((byte) 10);
        this.mapView.setZoomLevelMax((byte) 20);

        // create a tile cache of suitable size
        TileCache tileCache = AndroidUtil.createTileCache(this, "mapcache",mapView.getModel().displayModel.getTileSize(), 1f,
                                                          this.mapView.getModel().frameBufferModel.getOverdrawFactor());

        // tile renderer layer using internal render theme
        MapDataStore mapDataStore = new MapFile(new File(Environment.getExternalStorageDirectory(), MAP_FILE));
        TileRendererLayer tileRendererLayer = new TileRendererLayer(tileCache, mapDataStore,
                this.mapView.getModel().mapViewPosition, AndroidGraphicFactory.INSTANCE);
        tileRendererLayer.setXmlRenderTheme(InternalRenderTheme.OSMARENDER);
        mapView.setLayerType(View.LAYER_TYPE_HARDWARE, null);

        // only once a layer is associated with a mapView the rendering starts
        this.mapView.getLayerManager().getLayers().add(tileRendererLayer);

        this.mapView.setCenter(new LatLong(19.28414896480929,-99.51395778696823));
        this.mapView.setZoomLevel((byte) 15);

        PreparaControl();
        GPSActivate();

    }

    @Override
    public void onClick(View v){
        switch (v.getId())
        {
            //handle multiple view click events
        }
    }

**Comment by devemux86** [comment]
In what path did you put the map in the device / emulator?
Also can you post the logcat while running the app to check any exceptions?

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
