### ISSUE TITLE
Black Screen displayed

### ISSUE THREAD

**Issue by powellbird** [mapsforge/mapsforge#932]
Good afternoon

I'm trying to use Mapsforge library, I used the basic example provided in github, I have my own layout with a mapview and a spinner, but when assigning the layout to my application, the map does not only see a black screen, the Map is placed in the device at the root of the system. You could tell me that I'm doing wrong.

Image and Codido Attachment

Thank you.

![black](https://cloud.githubusercontent.com/assets/3671297/23631322/af17ee4a-0283-11e7-9870-5415b2529279.png)

[activityxml.txt](https://github.com/mapsforge/mapsforge/files/822615/activityxml.txt)
[mainActivity.txt](https://github.com/mapsforge/mapsforge/files/822616/mainActivity.txt)

**Comment by devemux86** [comment]
As mentioned already in #931:

In what path did you put the map in the device / emulator?
Also can you post the logcat while running the app to check any exceptions?

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
