### ISSUE TITLE
How to implement my own layout?

### ISSUE THREAD

**Issue by blackbirdsr71br** [mapsforge/mapsforge#933]
Good afternoon

My question is the following:

I have my layout where I add the mapView mapforge control, in addition to this I add controls like floatingactionbutton, and spiners. The application works and runs on my device but the map puts it on black screen, all other controls are seen.

I would like to know if there is any way to implement my own layout in my application.

Greetings and thanks.
My Logcat
03-06 20:40:15.985 5345-5345/com.example.alex.sicmain I/InstantRun: Starting Instant Run Server for com.example.alex.sicmain
03-06 20:40:16.172 5345-5345/com.example.alex.sicmain W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-06 20:40:16.725 5345-5345/com.example.alex.sicmain I/System.out: ID:---------------------------- /storage/emulated/0
03-06 20:40:16.741 5345-5345/com.example.alex.sicmain I/System.out: /storage/emulated/0/SicSystem/Datos/
03-06 20:40:17.056 5345-5345/com.example.alex.sicmain D/Check:...............: 355478065590415
03-06 20:40:17.090 5345-5345/com.example.alex.sicmain I/AndroidUtil: TILECACHE INMEMORY SIZE: 16
03-06 20:40:17.096 5345-5345/com.example.alex.sicmain I/AndroidUtil: TILECACHE FILE SIZE: 2000
03-06 20:40:17.324 5345-5345/com.example.alex.sicmain I/System.out: LatLong 0.0 ,  0.0
03-06 20:40:17.340 5345-5718/com.example.alex.sicmain D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-06 20:40:17.464 5345-5718/com.example.alex.sicmain I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I14a17c7611)
                                                                    OpenGL ES Shader Compiler Version: XE031.06.00.02
                                                                    Build Date: 12/04/15 Fri
                                                                    Local Branch: workspace
                                                                    Remote Branch: 
                                                                    Local Patches: 
                                                                    Reconstruct Branch: 
03-06 20:40:17.471 5345-5718/com.example.alex.sicmain I/OpenGLRenderer: Initialized EGL, version 1.4
03-06 20:40:17.981 5345-5345/com.example.alex.sicmain W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView

Annex application code and XML Layout
[activityxml.txt](https://github.com/mapsforge/mapsforge/files/822680/activityxml.txt)
[mainActivity.txt](https://github.com/mapsforge/mapsforge/files/822681/mainActivity.txt)

**Comment by devemux86** [comment]
As mentioned already in #931:

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
