### ISSUE TITLE
Infowindows on tap or click markers

### ISSUE THREAD

**Issue by blackbirdsr71br** [mapsforge/mapsforge#937]
Good morning, I'm using the library and this is excellent, is there any way to add an infowindow to a marker like google maps does ?, thank you very much.

**Comment by devemux86** [comment]
You can have a look in [mapsforge-samples-android](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) which has many examples, like [BubbleOverlay](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/BubbleOverlay.java) or [ViewOverlayViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/ViewOverlayViewer.java).

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
