### ISSUE TITLE
Infowindows on tap or click markers

### ISSUE THREAD

**Issue by blackbirdsr71br** [mapsforge/mapsforge#938]
Thanks a lot for the answer about bubleoverlay and viewoverlayviewer, but what I want to do is something like the image I attached below:

Infowindows with Images, Tables and Fonts.
![infowindow](https://cloud.githubusercontent.com/assets/24237848/23919455/7d04268c-08bc-11e7-9ff9-897c552d4434.png)

Thank you so much

**Comment by devemux86** [comment]
Like noted (#937) already many times..
..please avoid opening issues in repository and use the [forum](https://groups.google.com/group/mapsforge-dev).

Issues list is not for questions or discussion.
