### ISSUE TITLE
POI: PersistenceManager "order by" enhancement

### ISSUE THREAD

**Issue by womisa** [mapsforge/mapsforge#939]
Enhancement to the POI Persistence Manager to insert an order by clause?

 #[Forum](https://groups.google.com/forum/#!topic/mapsforge-dev/zAyB9TurEdA)

SELECT column-list FROM table_name [WHERE condition] 
====>>> [ORDER BY column1, column2, .. columnN] [ASC | DESC]; <<<====

e.g. adding String[] and boolean[] parameters for columns and order direction

**Comment by devemux86** [comment]
Don't know if that's feasible to include an 'order by' clause, since `poi_data` table includes only one `data` field which contains merged together all POI tags.
So a more convenient sorting per name, distance etc. could be done via code on the result POI collection.
