### ISSUE TITLE
POI: only one category possible per POI

### ISSUE THREAD

**Issue by eartrumpet** [mapsforge/mapsforge#940]
There are several POIs in OSM which have not just one defining tag, but two or more.
E.g. http://www.openstreetmap.org/way/91920694#map=19/47.64615/11.93511 has amenity=restaurant and tourism=alpine_hut

Depending on the source of the POIs (mapsforge or OAM), it is only contained in either one or the other category if I select the category in Cruiser or OruxMaps. So not every amenity=restaurant or tourism=alpine_hut is listed, which would be the expected behaviour. E.g. in bayern.poi from OAM, I only get a few alpine_hut (those who don't have amenity=restaurant), the majority isn't shown, probably because all are categorized in amenity=restaurant.

Only if I use the free text search with alpine_hut or restaurant, I get the expected result.

**Comment by devemux86** [comment]
I'm happy that OruxMaps supports Mapsforge POIs! :slightly_smiling_face:

**Comment by devemux86** [comment]
Regarding current POI implementation:

Categories form an [R-tree](https://en.wikipedia.org/wiki/R-tree) for spatial access (with children subtrees and leaf nodes).
POIs belong to their parent category, to their grandparent, all the way to top (seen in [poi-mapping.xml](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi-writer/src/main/config/poi-mapping.xml)).
Searching for a category, can retrieve the POIs also for children categories, all the way to bottom.

A POI can be defined by multiple tags, e.g. [Ice cream shops](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi-writer/src/main/config/poi-mapping.xml#L38-L41).
Also worth checking the SQL [statements](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi/src/main/java/org/mapsforge/poi/storage/DbConstants.java) to understand the DB schema.

What you suggest for category:POI relationship is going from one-to-many `1:n` to many-to-many `m:n`?

**Comment by eartrumpet** [comment]
I'm not so sure if I understand the structure. 

The problem is, if one POI already exists in one category, like the example above, it's not possible to find it in the other category. Both categories are defined in poi-mapping.xml, and one would suspect that if a POI fits a category, it would be contained, but only one category you can select in the UI ("restaurant" OR "alpine_hut") gets the POI as result.

One could work around by moving tags which are often combined in child categories, but this works only in a few cases.

**Comment by devemux86** [comment]
Probably in [PoiWriter.processEntity](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi-writer/src/main/java/org/mapsforge/poi/writer/PoiWriter.java#L348) we use indeed only one of POI's tags to resolve the matching categories and store.

**Comment by eartrumpet** [comment]
Sound like the reason. Is there any possibility to change this? E.g. are more categories per POI possible (preferable), or could a POI be added several times if several categories match? It would be nice if an option for PoiWriter would resolve this.

**Comment by devemux86** [comment]
> could a POI be added several times if several categories match?

This may appear easier to implement, but would load DB with same content. i.e. a POI will be stored in multiple records with same data and just different category ids.

> are more categories per POI possible

To get things done correctly would need many-to-many relationship among Categories and POIs, i.e. changes in DB schema and API.
This seems the appropriate solution?

> It would be nice if an option for PoiWriter would resolve this.

I think that by default we should change this with a new POI version, as the expected behavior is to include all categories?

**Comment by eartrumpet** [comment]
You're right, of course this would be the best thing to do, I was just trying to think of all possibilities. As mapsforge POIs are not so widespread yet (I know only of Cruiser and OruxMaps Beta), changing DB schema and API hasn't so many consequences.

**Comment by devemux86** [comment]
For now I pushed the 1st solution, i.e. add POI several times per category.

More formal solution with many-to-many relationship among Categories and POIs will be implemented in #950.

**Comment by eartrumpet** [comment]
Thanks Emux!

**Comment by devemux86** [comment]
Reopening as additional fix is needed (see [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/ax0kgedZ4n4)).
