### ISSUE TITLE
jp2 and .xml support

### ISSUE THREAD

**Issue by pinvisible** [mapsforge/mapsforge#941]
Hello There, 

I need to use offline maps in Android app. I have .jp2 and .xml files.
Can i use mapsforge library with this?

**Comment by devemux86** [comment]
`.jp2` as JPEG2000 map tiles, what do you mean with `.xml`?

Mapsforge besides its own offline vector [map file format](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md) supports also raster maps ([online](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadCustomLayerViewer.java) or [offline](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/TileStoreLayerViewer.java)).

Using JPEG2000 map tiles could need the proper reader, depending also on the platform.

**Comment by pinvisible** [comment]
Thank you friend. I need your help once again.

We need to show some offline maps of Australia inside Android app. This is our concept. 
I found that, this library can be used to show offline maps.

But i want to know, how we can develop offline maps? Can you please help me?

Thanks
Punit

**Comment by pinvisible** [comment]
Thank you friend. I need your help once again.

We need to show some offline maps of Australia inside Android app. This is
our concept.
I found that, this library can be used to show offline maps.

But i want to know, how we can develop offline maps? Can you please help me?

Thanks
Punit

**Comment by devemux86** [comment]
For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
