### ISSUE TITLE
MyLocationOverlay problem 'int org.mapsforge.map.model.DisplayModel.getTileSize()' on a null object reference

### ISSUE THREAD

**Issue by jahongir9779** [mapsforge/mapsforge#942]
was trying to show my location, got this error - getTileSize()' on a null object reference
 pls help
my permissions
```
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> 
```

**Comment by devemux86** [comment]
Need to provide details for the implementation, have a look also at [LocationOverlayMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LocationOverlayMapViewer.java) working example.

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
