### ISSUE TITLE
FixedPixelCircle implementation is inconsistent

### ISSUE THREAD

**Issue by cpt1gl0** [mapsforge/mapsforge#944]
FixedPixelCircle does density adaption for the raw pixel radius inside getRadiusInPixels(). The radius returned by this function is used for drawing. In contrast, the contains() method uses the raw non density adapted radius. As a result, the contains() method checks if some point is contained in a circle whose radius differs from the circle which is actually drawn.

As a solution I would suggest to remove density adaption from getRadiusInPixels() and just return the raw pixel radius from this function.

**Comment by devemux86** [comment]
Nice remark!

Or better use scale factor in `contains`, can you check the commit I pushed?

**Comment by cpt1gl0** [comment]
Okay, I think this should do. Personally I'd prefer a non density adapted pixel radius, mainly because the used device scaling factor is no accurate scale factor but determined by Android's display metrics density, which is "used to scale the size of the overall UI in steps based on gross changes in the display dpi". If FixedPixelCircle would use unadapted pixels also users desiring an accurate density adaption could use the class and do the display density adaption theirselves.

**Comment by devemux86** [comment]
We could enhance the `FixedPixelCircle` API with e.g. a boolean scale parameter, so allowing also unscaled radius?

**Comment by cpt1gl0** [comment]
I would highly appreciate something in that direction!

**Comment by devemux86** [comment]
See latest commit with the new `setScaleRadius` method.

**Comment by cpt1gl0** [comment]
Perfect!
