### ISSUE TITLE
POI: many-to-many relationship among Categories and POIs

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#950]
Implement many-to-many relationship among Categories and POIs to properly fix #940.

**Comment by devemux86** [comment]
That requires a new POI specification v2.

POI specification v1 is published, used by apps and offered by e.g. [Mapsforge](http://download.mapsforge.org/) and [OpenAndroMaps](http://www.openandromaps.org/en/).

So need to support both `.poi` file versions for not breaking suddenly any backwards compatibility.
POI writer can advance totally to v2, anyone can use older jar for building v1 `.poi` - which will be deprecated by time.

But POI readers better to be able to work with both v1 and v2 versions for now.
In `metadata` table we store already the specification version, can read it at `.poi` open and follow the separate path in code.

Also let's have distinct DB statements / methods / ... with `v1` and `v2` suffixes for easy reference.

**Comment by Gustl22** [comment]
In my upcoming commit #991 there's an imperceptive difference. The concerned methods have a third parameter with `version` number to avoid extra methods for each version. Often only a few lines differ from the other version, so there's no need of nearly duplicate them.

While the underlying concept is different (in new v1 and v2), but does not take effect on the queried results, and is more modular, like the following:
The DB is fragmented in:
- `metadata`, which has an exceptional position
- poi-location (`poi_index`)
- poi-tags (`poi_data`)
- `poi_categories`
- M to N relationship between POI and categories in v2 (`poi_cmap`)

Depending on the requests in `findInRect`, more tables are joined:
v1: join `poi_data`, if necessary for categories and tags
v2: join `poi_data` for tags, and `poi_cmap` for categories

Second step is the creation of POIs from the results. Only for the specific results the tags and categories are requested afterwards, to complete missing categories (v2) and tags.

The `metadata`-table must be prepared and requested before all the other statements to change them based on the poi-version. For that, this is handled in `updatePoiFileInfo`, that you cannot forget initializing its statement. This is an abstract method in `AbstractPoiPersistenceManager`, too, so `getPoiFileInfo()` could be implemented and used in that Manager.

I'm happy for some feedback... thx ;D

**Comment by devemux86** [comment]
Closed via #991.
