### ISSUE TITLE
RenderTheme element <caption position="center" ... /> not work

### ISSUE THREAD

**Issue by virus-warnning** [mapsforge/mapsforge#952]
I'd like to display number of subway entrance over symbol image, but position="center" is invalid.

```xml
    <!-- 捷運出入口 -->
    <rule e="node" k="railway" v="subway_entrance" zoom-min="15">
    	<rule e="node" k="ref" v="*">
    		<symbol id="entrance_bg" src="file:symbols/entrance_bg.svg" symbol-percent="100" />
    		<caption symbol-id="entrance_bg" k="ref" position="center" font-size="11" font-style="bold" fill="#333333" stroke="#e7e0d0" stroke-width="3.0" />
    	</rule>
    </rule>
```

The yellow triangle is "entrance_bg.svg".

![2017-04-18 5 40 28](https://cloud.githubusercontent.com/assets/5044734/25124395/2a5c3312-245e-11e7-8e9d-6109f4e2304b.png)

After changing position="above", all refs appeared.

![2017-04-18 5 46 46](https://cloud.githubusercontent.com/assets/5044734/25124686/10d019f8-245f-11e7-87b8-e58401e0500f.png)

**Comment by devemux86** [comment]
Probably collision detection, can you try the [display](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#display) directive?

**Comment by virus-warnning** [comment]
With display="always".

![2017-04-18 5 55 26](https://cloud.githubusercontent.com/assets/5044734/25125101/4105c392-2460-11e7-9ef8-0aaa773e1cc9.png)

**Comment by devemux86** [comment]
Could add [priority](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#priorities) too, with labels higher.
Do you use `LabelLayer` in rendering?

**Comment by applantation** [comment]
If you do not have the symbol, the number caption displays?

**Comment by virus-warnning** [comment]
It works after adding priority. No LabelLayer here.

```xml
    <!-- 捷運出入口 -->
    <rule e="node" k="railway" v="subway_entrance" zoom-min="15">
    	<rule e="node" k="ref" v="*">
    		<symbol id="entrance_bg" priority="1" src="file:symbols/entrance_bg.svg" symbol-percent="100" />
    		<caption symbol-id="entrance_bg" priority="2" k="ref" position="center" display="always" font-size="11" font-style="bold" fill="#333333" stroke="#e7e0d0" stroke-width="3.0" />
    	</rule>
    </rule>
```

![2017-04-18 6 06 40](https://cloud.githubusercontent.com/assets/5044734/25125592/f9b77fc4-2461-11e7-8698-4801275638d8.png)

**Comment by ludwigb** [comment]
Looks that it actually works as it should:

   - The display="always" turns off the collision detection
   - The setting of a lower priority assures that the numbers are printed
   after the high-priority symbols are printed. (I do not think this was the
   original intention, but stacking order can be important as we see in this
   example.)
