### ISSUE TITLE
Changing the int to double for precision in LatLongUtils.java

### ISSUE THREAD

**Issue by akarsh** [mapsforge/mapsforge#954]
From the [google groups discussion](https://groups.google.com/d/msg/mapsforge-dev/530Kktm0lv4/INqHNwrpDAAJ) I found the issue with usage of int instead of double in the class [LatLongUtils line number 100 ](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/LatLongUtils.java#L100).

So, changing this will correct the precision problem  ?

**Comment by devemux86** [comment]
[Mapsforge map file specification](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md) defines that coordinates are stored in microdegrees (degrees × 1E6) INT.

And `LatLontUtils.degreesToMicrodegrees` is the common way to perform conversion from degrees to microdegrees, it's not the cause, just used in the process.

**Comment by akarsh** [comment]
@devemux86 
I did not find any instructions on building the plugin from [source](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map-writer) in [Getting-Started-Map-Writer](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md).

Is it possible for you to add documentation of steps to build from source ?

**Comment by devemux86** [comment]
You can clone Mapsforge repository and open it with Android Studio.
Then running `./gradlew install` or via UI will publish the artifacts to your local `.m2` Maven repository.

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
