### ISSUE TITLE
soft hyphen (  &#173; ) support

### ISSUE THREAD

**Issue by mbe57** [mapsforge/mapsforge#955]
Mapsforge or whatever component does not insert a hyphen when forcing a line break. And most importantly: the line break is in wrong position of the word, as you can expect. Depending on the theme and scaling you would see

Möncheng
ladbach

Mönchengladbac
h

I have seen the weirdest stuff.

This is exactly why soft hyphens have been introduced ...

Quote from: https://en.wikipedia.org/wiki/Soft_hyphen

In this context, the soft hyphen may also be called a discretionary hyphen or optional hyphen. It serves as an invisible marker used to specify a place in text where a hyphenated break is allowed without forcing a line break in an inconvenient place if the text is re-flowed.

Can you pls. support the proper interpretation of  &#173;
I.e. ignore this soft hyphen if there is no line break needed. If a line break is needed, use the position of and show the soft hyphen as "-" at line end.

TXs and cheers
Michael

Result of discussion: https://groups.google.com/forum/#!topic/mapsforge-dev/alZDa3jqoZU

**Comment by mbe57** [comment]
I found that different Androids show different behaviour. One did split at the soft hypen, but did not show the hyphen :-(
So, a safe way forward would be to check if a line break would happen, if yes, convert the respective soft hyphen and discard all other soft hypens.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
