### ISSUE TITLE
Changing RenderTheme with persistence enabled

### ISSUE THREAD

**Issue by jeffbordon** [mapsforge/mapsforge#956]
When I turn persistence on in the settings of the samples and run the `RenderThemeChanger` sample I get a mixture of both renderthemes used (`rendertheme-v4.xml` and `onlybuildings.xml` in my case). See attached screenshot.

I experimented a bit with `tileCaches.get(0).purge()` instead of `tileCaches.get(0).destroy()` and also with `AndroidGraphicFactory.clearResourceMemoryCache()` / `AndroidGraphicFactory.clearResourceFileCache()` but nothing worked as expected.

Is there any way to make the on-the-fly change of RenderThemes possible when persistence enabled?

![screenshot_20170501-131115 1](https://cloud.githubusercontent.com/assets/10179133/25578538/0471472a-2e70-11e7-8657-73a6815f03ae.png)

**Comment by devemux86** [comment]
I pushed some improvements in `RenderThemeChanger` sample using the needed tile cache purge.

Though `RenderThemeChanger` does not work correctly even with tile cache persistence off.
The similar `TileSizeChanger` seems to work fine.

**Comment by devemux86** [comment]
I pushed a fix (irrelevant of cache persistence), using alpha in tile renderer layer creation, needed only for themes like `onlybuildings.xml` with transparent map background.

**Comment by jeffbordon** [comment]
Thanks, works like charm!
