### ISSUE TITLE
Wrong file for Mapsforge Reader test "with_data"

### ISSUE THREAD

**Issue by charlenni** [mapsforge/mapsforge#961]
Could it be, that the map file for the reader test "with_data" has only one tag for Pois and Ways and not more than one, like it should have (see in the XML file)?

**Comment by devemux86** [comment]
If you mean how to process the input osm tags during map creation, that can be done via a custom tag-mapping.xml in map-writer (see [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md)).

More arbitrary tag transforms can be applied to OSM data as a preprocessing step before using map-writer with [TagTransform](http://wiki.openstreetmap.org/wiki/Osmosis/TagTransform) plugin for Osmosis.

**Comment by charlenni** [comment]
No, that's not my problem. The problem is, that there is only one tag (one key-value-pair) is inside the output.map file. If you use a hex editor you could check this.

**Comment by devemux86** [comment]
In map files there are [default](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java#L118-L133) tags which are stored and parsed like (`ele`, `addr:housenumber`, `name`, `ref`) and the various mentioned in [tag-mapping](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml).

Opening the sample map with a render theme, we can see the road rendered via `highway=motorway` along with its `name` and `ref`, all of them coming from map file:

![with_data](https://cloud.githubusercontent.com/assets/3484020/26522456/b8f8e452-4309-11e7-9f04-6fe9096102f6.png)

**Comment by devemux86** [comment]
Regarding map file internals you can also check its [specification](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md) docs.

**Comment by charlenni** [comment]
Sorry for any inconvenience. The problem was on my side. I had problems with my BoundingBox, so that the POI wasn't inside and so there are any Tags added. You are right, the file is correct.

Thank you for your help.
