### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by stephensworld** [mapsforge/mapsforge#962]
https://github.com/mapsforge/mapsforge/blob/master/docs/Downloads.md

Maybe somebody could reupload it.

Thanks

**Comment by devemux86** [comment]
That was an obsolete page (I remove it) having very old versions.

You can check the [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md) for how to use Mapsforge latest release or snapshot version.
