### ISSUE TITLE
Can mapsforge support geoTiff in the MapView?  it can zoom in and zoom out?

### ISSUE THREAD

**Issue by QDPeng** [mapsforge/mapsforge#963]

**Comment by devemux86** [comment]
Mapsforge supports raster image tiles, either via an online server ([DownloadCustomLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadCustomLayerViewer.java) sample) or offline tile storage ([TileStoreLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/TileStoreLayerViewer.java) sample).
Essentially that needs to cut the image in tiles.

**Comment by QDPeng** [comment]
I have tested the TileStoreLayerViewer, it need prepare many *.png image for each zoom level,and .tiff file can't be shown in mapview. I have only one tiff file,I want show it in the mapview and can zoom in and out.Do you have any other ideas? Thank you very much.

**Comment by devemux86** [comment]
You need to produce tiles from the georeferenced image.
Can do that with many tools like [GDAL](http://gdal.org/), [MapTiler](http://www.maptiler.com/), etc.

For further questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
