### ISSUE TITLE
Closest or cut LatLong from two polyline

### ISSUE THREAD

**Issue by jsimarro103** [mapsforge/mapsforge#966]
I think am trying something imposible.
I have two polyline, or Array of LatLong and wanna the closest point or the cut point of both.
How can I travel throught a polyline and get multiple LatLong to compare distances?
I tried dividing the polyline but i cant get the bearing between two LatLong to walk throught the line.

**Comment by devemux86** [comment]
From a `Polyline` you can get its coordinates list via `getLatLongs()`.
Then can check `LatLongUtils` which has several useful utilities.
Also can see [here](http://www.movable-type.co.uk/scripts/latlong.html) for a variety of calculations for lati­tude/longi­tude points.

For further questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
