### ISSUE TITLE
[mapfile-writer] Missing Features at the boundary of the input data

### ISSUE THREAD

**Issue by DrMarkEy** [mapsforge/mapsforge#967]
This is related to #295, however it is not solved by the discussion there. In my app I am using the following workflow: 
1.) Extract the raw data for a desired polygon boundary with osmosis from a bigger file.
2.) Use mapfile-writer to generate the corresponding .map file.

With this method I have so far tried two possibilities to handle the Multipolygons / ways that cross the boundary:
a) let osmosis polygon-clipping cut them of at the boundary
b) use completeWays=yes and completeRelations=yes and keep them

However with method a) the mapfile-writer gets ways with missing nodes and discards them completely, which makes them disappear even inside the wanted region.
Method b) on the other hand writes them completely into the .map-file, even outside the desired region, which may be not too bad for a ordinary street, but can be rather disturbing if a long running hiking trail or interstate crosses the area. I had occassions where a hiking trail severeal hundret miles away was still included in the data due to completeRelations=yes.

A possible solution could be to process also ways/polygons with missing nodes in mapfile-writer as good as possible, instead of discarding them. Any ideas?

The following images demonstrate the problem (the raw osm-data is clipped with osmosis at the brown administrative boundary):

![keepways_no](https://user-images.githubusercontent.com/21967688/27253658-ddcff20a-5378-11e7-885b-fd8f32b114eb.png)

a) With completeWays=no and completeRelations=no, the road and the forest are clipped at the boundary. As both ways are incomplete after this transformation, they are discarded in mapfile-writer and thus not rendered in mapsforge.

![keepways_yes](https://user-images.githubusercontent.com/21967688/27253656-d7433f6e-5378-11e7-975d-bb892efebe49.png)

b) With completeWays=yes and completeRelations=yes, both features are completely included in the .map-file and thus rendered even outside the cutting region. This is espacially problematic if long relations (e.g. hiking trails) occur, that go way outside the cutting region.

**Comment by devemux86** [comment]
If having proper input data then produced map should contain all polygons clipped to map boundaries.
For example like the neighboring countries in Italy map:

![countries](https://user-images.githubusercontent.com/3484020/27253259-d40d618e-5379-11e7-8845-cceecc935785.png)

**Comment by devemux86** [comment]
See also https://github.com/mapsforge/mapsforge-mapcreator/issues/14.

Seems more an Osmosis process decision, i.e. use Osmosis `--bounding-box` or `--bounding-polygon` with `completeWays=yes completeRelations=yes` so input data to map-writer be complete.

Then map-writer with [bbox](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#basic-options) option will cut those complete input data at the exact map bounds.
