### ISSUE TITLE
Android Studio 3.0 (Canary Channel) won't build - FlavorDimensions missing

### ISSUE THREAD

**Issue by hawalter** [mapsforge/mapsforge#968]
The build fails with the message:
/Users/howard/Desktop/Temp/mapsforge-master/mapsforge-samples-android/build.gradle
Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

**Comment by devemux86** [comment]
I added flavor dimensions in Gradle build, how is it now?

Note that Mapsforge usually supports the stable editions of Gradle, Android plugin, Android Studio, etc.

**Comment by hawalter** [comment]
Your mod fixed the problem and it now builds. Thanks for the quick response.
