### ISSUE TITLE
MapWriter "hangs up" when using sachsen-anhalt extract from Geofabrik

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge#972]
When I run the following:
```
wget http://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf
../osmosis/bin/osmosis --rb file=sachsen-anhalt-latest.osm.pbf --mapfile-writer file=sachsen-anhalt.map
```

The process "hangs up" after this log:
`Jul 06, 2017 11:52:41 AM org.mapsforge.map.writer.MapFileWriter writeSubfile`

When looking at the CPU utilization all my CPUs are at 100% and my RAM (as far as I allowed it with xmx) is filled.

The process works for other extracts from Geofabrik including Germany, Berlin, and others. Any idea what could happen here?

I use the latest mapwriter. I also tried setting `type=hd`.
Osmosis Version 0.45

**Comment by boldtrn** [comment]
BTW: I have seen the same behavior for Sachsen-Anhalt that I extracted myself from the latest planet export. Maybe this indicates an issue of my setup?

I installed the latest stable osmosis and followed your guide.

**Comment by devemux86** [comment]
Haven't debugged what happens, but the simplest test is always the Geofabrik pbf, those should normally always work. :slightly_smiling_face:

**Comment by boldtrn** [comment]
Thanks, as I said, both don't work for me. The writer hangs up with the GeoFabrik extract and an extract that I created myself.

**Comment by devemux86** [comment]
And you try a plain Osmosis zip with just the latest snapshot map-writer?
(no complex map-creator configurations)

**Comment by boldtrn** [comment]
Well I ran the following:

```
wget http://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf
../osmosis/bin/osmosis --rb file=sachsen-anhalt-latest.osm.pbf --mapfile-writer file=sachsen-anhalt.map
``` 

Which does not work. Is there a simpler way?

**Comment by devemux86** [comment]
That's the simplest build.
(I meant to use the latest fresh [Osmosis zip](http://wiki.openstreetmap.org/wiki/Osmosis#Latest_stable_version) and not an older or modified distribution)

**Comment by boldtrn** [comment]
Ah, well I used this Osmosis version: `wget http://bretth.dev.openstreetmap.org/osmosis-build/osmosis-latest.tgz`. I downloaded it less than one month ago. I think there hasn't been a new version for quite some time.

**Comment by devemux86** [comment]
@ludwigb any idea on this or what happens with that area on server?

**Comment by boldtrn** [comment]
Can you confirm the bug or might this be an issue of my configuration or setup?

**Comment by devemux86** [comment]
Can confirm the long build, though my test with `-Xmx8g` had OOM. :slightly_frowning_face: 
But the map exists in server, so should be built somehow.

**Comment by Advialance** [comment]
I can confirm this Issue with an even smaller Extract.
The OSM Extract is valid and has the bbox: 50.756836,6.811523 to 50.888672,7.294922
I'm using the latest Snapshot Build of the Writer Plugin and the Latest osmosis Version.
I can confirm the Problem with the latest stable Writer Plugin, too.  
  
`osmosis --rbf map_files/63240172.osm.pbf --mw file=map_files/63240172.map bbox=50.756836,6.811523,50.888672,7.294922 preferred-languages=de,en label-position=true && rm $file  
Aug 01, 2017 2:10:46 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.45  
Aug 01, 2017 2:10:46 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.  
Aug 01, 2017 2:10:46 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile-writer version: mapsforge-map-writer-0.8.0  
Aug 01, 2017 2:10:46 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile format specification version: 4  
Aug 01, 2017 2:10:46 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.  
Aug 01, 2017 2:10:46 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.  
Aug 01, 2017 2:10:46 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask process
INFO: start reading data...  
Aug 01, 2017 2:10:51 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: completing read...  
Aug 01, 2017 2:10:57 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: start writing file...  
Aug 01, 2017 2:10:57 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: overwriting file /ssd/home/mapsforge/map_files/63240172.map
Aug 01, 2017 2:10:59 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 100% of sub file for zoom interval 1 (5,0,7)
Aug 01, 2017 2:11:03 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 100% of sub file for zoom interval 2 (10,8,11)
Aug 01, 2017 2:11:09 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 10% of sub file for zoom interval 3 (14,12,21)
Aug 01, 2017 2:11:13 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 20% of sub file for zoom interval 3 (14,12,21)
Aug 01, 2017 2:11:16 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 30% of sub file for zoom interval 3 (14,12,21)
Aug 01, 2017 2:11:18 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 40% of sub file for zoom interval 3 (14,12,21)
Aug 01, 2017 2:11:23 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 50% of sub file for zoom interval 3 (14,12,21)`  
  
It runs upto the last Zoom-Interval at 50% then it hangs for at least an hour. Consuming 100% of all CPUs and eventually aborts with OOM after that.  
  
I tried that giving osmosis 17GB of Ram and with 8 GB of Ram.  
With type=hd and without. 
With the latest SNAPSHOT and with the latest stable.  
  
Results stay the same in all combinations. It happened to me with other extracts, too.

**Comment by boldtrn** [comment]
I just saw the same issue with Hessen. This seems to be new for Hessen.

**Comment by devemux86** [comment]
Apparently something (new) in the osm data plays a role in this map-writer behavior.

**Comment by devemux86** [comment]
The issue is due to #884 where we put in tag-mapping.xml the `label-position="true"` for the buildings.
Removing those calculations, the builds run again smoothly.

So we should revert to the older default situation for Mapsforge and improve it further in #930.

**Comment by boldtrn** [comment]
Thanks a lot for investigating this :).
