### ISSUE TITLE
Use XmlPullParserFactory instead direct constructor of kxml2

### ISSUE THREAD

**Issue by MarcelHeckel** [mapsforge/mapsforge#974]
Hi,

in "org.mapsforge.map.rendertheme.rule.RenderThemeHandler" you directly call the "org.kxml2.io.KXmlParser" constructor the create a "org.xmlpull.v1.XmlPullParser" instance.

But there are different implementation of the org.xmlpull.v1.XmlPullParser (like xpp3). That's why the interface defines a "org.xmlpull.v1.XmlPullParserFactory" so that the implementing library could be exchanged. 

But as you use the direct constructor, one is forced also to included kxml2 even if I like to use xpp3.

Please replace the line 63 in org.mapsforge.map.rendertheme.rule.RenderThemeHandler

` XmlPullParser pullParser = new KXmlParser();`

with 

`XmlPullParser pullParser = org.xmlpull.v1.XmlPullParserFactory.newInstance().newPullParser()`

**Comment by devemux86** [comment]
Then how someone could use explicitly the kXML2 parser, like now?
Or should we make possible to have the XML pull parser as option?

**Comment by MarcelHeckel** [comment]
_XmlPullParserFactory.newInstance()_ reads _/META-INF/services/org.xmlpull.v1.XmlPullParserFactory_ to search for implementation classes. So if there is only the kxml2 jar in the classpath, it will be used (see kxml2-2.3.0.jar). If more than one implementations are present, its undetermined, which will be used.

P:S:
For performance reasons it would also be better to have a static Factrory instance:
```
    private static XmlPullParserFactory xmlPullParserFactory;
    public static XmlPullParserFactory getXmlPullParserFactory() throws XmlPullParserException
    {
        if (xmlPullParserFactory != null)
            xmlPullParserFactory = XmlPullParserFactory.newInstance();
        return xmlPullParserFactory;
    } 
```

And than
`XmlPullParser pullParser = getXmlPullParserFactory().newPullParser();`

P.P.S:
The factory could also be created with a specific implementation
e.g.
`XmlPullParserFactory.newInstance("org.kxml2.io.KXmlParser,org.kxml2.io.KXmlSerializer",null);`
So if you really want the user the change the implementation, you may add a setter for the factory.
```
 public static void setXmlPullParserFactory(XmlPullParserFactory xmlPullParserFactory)
    {
        RenderThemeHandler.xmlPullParserFactory = xmlPullParserFactory;
    }
```

**Comment by devemux86** [comment]
That could work, need to make some tests first in all supported platforms.

**Comment by devemux86** [comment]
`mapsforge-map` module is platform agnostic, not tied to Android or Desktop specific API.
So if remove the kXML2 dependency, there isn't a `XmlPullParser` available.

**Comment by MarcelHeckel** [comment]
Sorry, you should better read what I am writing: I just wanted that you change some lines of your implementation. You may keep the dependency to kmxl2, so that there is an implementation as default. But when your code is agnostic to the implementation of the parser, one can explicitly exclude the dependency to kxm2l and use another implementation! That's why there is the XmlPullParserFactory!

**Comment by devemux86** [comment]
Where is the `XmlPullParserFactory` located, in which API, Android or Java?

**Comment by devemux86** [comment]
With kXML2 as dependency, we can use its API and allow different implementations of `XmlPullParserFactory`.
I pushed the changes, @MarcelHeckel please see if all are ok.

**Comment by MarcelHeckel** [comment]
Looks good. Thank you!
