### ISSUE TITLE
Bug, wrong cast in Hillshading.java

### ISSUE THREAD

**Issue by oruxman** [mapsforge/mapsforge#975]
Hello,

Hillshading.java class, lines 76-77; not working with maptileLeftLng negative values.

for (**int shadingLeftLng = (int) maptileLeftLng**; shadingLeftLng <= maptileRightLng; shadingLeftLng += shadingLngStep) {
for (**int shadingBottomLat = (int) maptileBottomLat**; shadingBottomLat <= maptileTopLat; shadingBottomLat += shadingLatStep) {

I think it should be (for example):
int shadingLeftLng = (int)Math.floor(maptileLeftLng);
for (; shadingLeftLng <= maptileRightLng; shadingLeftLng += shadingLngStep) {
            int shadingBottomLat = (int)Math.floor(maptileBottomLat);
            for (; shadingBottomLat <= maptileTopLat; shadingBottomLat += shadingLatStep) {

[patch.txt](https://github.com/mapsforge/mapsforge/files/1155315/patch.txt)

**Comment by devemux86** [comment]
Do you mean hillshading does not work in areas with negative longitude?

**Comment by oruxman** [comment]
It does not work in negative longitude areas.

If we want render a shadow, from maptileLeftLng=-3.66 to  maptileRightLng=-3.25 then 
int shadingLeftLng = (int) maptileLeftLng = -3 and we want it to be -4, because if not, the code inside the for loop is not executed.

**Comment by devemux86** [comment]
Do you want to create a pull request with the change?

**Comment by devemux86** [comment]
Thanks, I merged your patch.
