### ISSUE TITLE
Updated from 0.6.1 to 0.8.0, what happened to InternalRenderTheme?

### ISSUE THREAD

**Issue by spyhunter99** [mapsforge/mapsforge#980]
I believe the full package name was `org.mapsforge.map.rendertheme.InternalRenderTheme` but it appears to have been removed at some point. Is there a replace for this or recommended mechanism that i can use to update our code? (osmdroid's mapforge adapter)

**Comment by devemux86** [comment]
Themes now exist in their own mapsforge-themes 
<https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md> 
module.

compile 'org.mapsforge:mapsforge-themes:0.8.0'

-- 
Emux <https://devemux86.github.io>

**Comment by devemux86** [comment]
Themes now exist in their own [mapsforge-themes](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md) module:

```gradle
compile 'org.mapsforge:mapsforge-themes:0.8.0'
```

**Comment by devemux86** [comment]
For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
