### ISSUE TITLE
Copyshops are not displayed on the map

### ISSUE THREAD

**Issue by Margaret1824** [mapsforge/mapsforge#983]
Hello! I was converted osm file to map file with osmosis and mapsforge mapfile-writer 0.8.0 and I have problems with copyshops. I use mapsforge libraries for android and I not see copyshops and other organizations (shop-pastry, small conver, greengrocer, etc.) on my map when I am testing my android app. But when I am opening this map in JOSM or openstreetmap.org this shops are displaying. What is the problem?

**Comment by devemux86** [comment]
Everything to be displayed on map needs first to be included in map files with map-writer.
If default [tag-mapping](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#defining-a-custom-tag-mapping-via-xml) does not contain those tags, then can use a custom tag-mapping.
Afterwards need to use a [render theme](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md) to define how these tags are to be displayed.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by Margaret1824** [comment]
Thanks for the advice. We are doing very necessary things. Good luck to you.
