### ISSUE TITLE
java.lang.NoClassDefFoundError: org.mapsforge.map.model.DisplayModel

### ISSUE THREAD

**Issue by farhad-kargaran** [mapsforge/mapsforge#984]
I can not run my app on Samsung S3 (android 4.3) and HTC desire 516 (android 4.3) facing this error:
java.lang.NoClassDefFoundError: org.mapsforge.map.model.DisplayModel
at this line of my code:
`AndroidGraphicFactory.createInstance(mInstance);`
my app runs fine on these phones I have tested:
LG G4 , Huawei P8 lite, Samsung S7, Lenovo Tab3, Samsubg Note 4

(I tried mapsforge 0.6.1 and 0.8.0, but same error in both versions on Samsung S3 and HTC Desire 516, I think android 4.3 is the problem )
this is the screen shot in android studio](http://imgh.us/2017-08-08_8-43-42.png)

**Comment by devemux86** [comment]
For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).

Cannot know your implementation or classpath, so try either a simple project like [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) or [mapsforge-samples-android](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android).
