### ISSUE TITLE
Distorted map view

### ISSUE THREAD

**Issue by BetsaValerij** [mapsforge/mapsforge#987]
I used your code from the sample to load a map from a file. I'm having trouble displaying the map, it somehow displays at an angle. This happens when the map is only loaded and when I try or change the zoom or move around the map. Download this map from this link http://download.mapsforge.org/maps/europe/ Why is this happening?
Here is the screen
![screenshot_2017-08-14-16-39-57](https://user-images.githubusercontent.com/27415709/29274228-c8127d60-810f-11e7-919e-933d928a73fb.png)

**Comment by devemux86** [comment]
Do you use latest Mapsforge and on what device and Android?

There were earlier reports for distorted map: #440 and #770.

**Comment by BetsaValerij** [comment]
My device is 4.1.2. Project on Android Studio. In the project I use the library mapsforge-map-android-0.8.0.jar. Hardware acceleration is disabled in the settings of the device

**Comment by devemux86** [comment]
Have disabled hardware acceleration on the device, why?

Latest Mapsforge supports hardware acceleration, so can try with that on.
